### ISSUE TITLE
Additional "var usage" option for Unity default types in formatter

### ISSUE THREAD

**Issue by lambdor** [JetBrains/resharper-unity#100]
For Code Style -> C# -> Code Style -> 'var' usage in declaration add an additional option for Unity default types such as Vector to define whether explicit type or var should be used.

**Comment by citizenmatt** [comment]
Unfortunately, this can't be extended. The analysis to handle `var` usage isn't extensible, and categorises usage into "built in", "simple" (no generics) and "other" (generics). There isn't a way to add another category, and adding a separate analysis would conflict with the existing one. The best workaround would be to change the severity of the existing inspection to either "Do not show" or "hint".
