### ISSUE TITLE
Unity Plugin no longer working anymore

### ISSUE THREAD

**Issue by zhuchun** [JetBrains/resharper-unity#1005]
Hi, my Rider is not working with Unity on one of my PC these days, no usage hint, no code template, the worst thing is that I can't right click on any folder that already has any cs file inside, no context menu popped up. 

![NoUsage](https://imgur.com/download/gEG40jQ)

![NoAutoComplete](https://imgur.com/download/wX7Y1lr)

Tried reinstalled Unity and Rider but no luck. Disabling the Unity Support plugin makes everything work properly. Is there any way to fix this?

Environment
Rider: 2018.3.1
Unity: 2018.3.2f1
Windows 10

**Comment by van800** [comment]
Please attach all logs from folder, which opens by Help->Show log in Explorer.
(If you want to attach it privately, start a new issue in https://youtrack.jetbrains.com/issues, it allows to set visibility for attachment)

**Comment by van800** [comment]
Thanks! This issue is known and fixed for 2018.3.2, which should appear shortly.
The problem is that for some users Unity installations contains Unity.exe, which is packed differently. And we fail on reading version information from it.

**Comment by zhuchun** [comment]
Thank you @van800 
It's weird that the latest beta version of Unity 2019 is not affected by this bug :\
