### ISSUE TITLE
Display project name in list of debuggable Unity processes

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#1009]
When attaching to a Unity process, the dialog will list all players found on the network, as well as any local Unity editor instances. If there is more than one instance of the editor running, it's very difficult to tell them apart - it would be very useful to list the project name next to the process name.

Unfortunately, the project name isn't easily available, and there isn't an API to fetch it. Our plugin could write the project name to a file with exe name and pid to a shared location (somewhere under the user's profile) and delete it on exit. The dialog could read this and show the project name.

And/or, we could use the currently open project's `Library/ProjectInstance.json` to at least mark the current project's Unity editor instance.

**Comment by van800** [comment]
Unity team mentioned that they have it on a backlog for 2019.3. "Add more information to the multi-cast messages for Unity."

**Comment by van800** [comment]
@citizenmatt I guess, you have some info from Rareș about this, right?

**Comment by citizenmatt** [comment]
Yep. Will implement today, hopefully. Although this will be Unity 2019.2 only

**Comment by citizenmatt** [comment]
Currently, the list of debuggable process will show the project name for players built with Unity 2019.2. It doesn't yet show project name for editor instances. This will come as a separate PR, after speaking with Unity next week.
