### ISSUE TITLE
Removing default initializers fails when building for Windows Store platform

### ISSUE THREAD

**Issue by lambdor** [JetBrains/resharper-unity#101]
We had a method which looked similar to this:
```
public static bool foo()
{
	bool ret = false;
	...
	return ret;
}
```

Inspector suggested to "remove redundant initialization" which makes sense, but fails when building for Windows Store platform.

**Comment by citizenmatt** [comment]
Does that method have and `#if` statements in it? As far as I can see, ReSharper/Rider doesn't do different assignment analysis for different platforms.

**Comment by lambdor** [comment]
Yes it does and it gets assigned there which explains the error. Sorry for the wrong report, I'll close the issue.
