### ISSUE TITLE
Automatic Attach to Unity when solution is opened with project

### ISSUE THREAD

**Issue by oxysoft** [JetBrains/resharper-unity#1011]
This could be a toggleable feature, but I know I would love to have Rider attach itself automatically for me and not have to think about pressing F5 before I need to debug some code.

**Comment by van800** [comment]
Apps under debug run a lot slower. For case of Unity it might also be more unstable. It may lag during attach. I don't think we would ever implement this.

**Comment by oxysoft** [comment]
I see, in that case you're definitely right. I've personally never noticed any difference on my machine but I will take your word for it.

**Comment by oxysoft** [comment]
I don't know if this was an old feature but I noticed in 2019.1 EAP I can click the debug button in the debugger panel to start Unity with debugging, which addresses this issue perfectly and is a better compromise!

**Comment by van800** [comment]
Starting Unity with debug button is a new feature in 2019.1 EAP. Thanks to @krasnotsvetov
