### ISSUE TITLE
Allow SerializeField on properties' backing fields

### ISSUE THREAD

**Issue by kroltan** [JetBrains/resharper-unity#1016]
The following code correctly serializes a value:
```csharp
[field: SerializeField]
public SomethingSerializable Foo { get; private set; }
```
It should not be considered "Attribute is redundant when applied to this declaration type", since it's being applied to the _backing field_ of the property. Sure, the name that Unity shows for such variables in the editor is ugly (but fixably so), but serialization itself works perfectly fine.

**Comment by roboryantron** [comment]
@kroltan Thanks for getting this reported (and then fixed!) I am excited to start using this rather than the extra code going the non-auto-property route. 
You mentioned: 
> Sure, the name that Unity shows for such variables in the editor is ugly (but fixably so)

Could you share how it is fixable? I can not find anything outside of a custom inspector or property drawer that lets you change the display name of one of these fields.

**Comment by kroltan** [comment]
@roboryantron For the sake of this issue, I meant with a custom inspector.

But I have also solved this in the past by injecting code into Unity's `displayName` handling using [Harmony](https://github.com/pardeike/Harmony/). Of course it's a bit brittle conceptually but worked just fine for me.

```csharp
using System.Reflection;
using System.Text.RegularExpressions;
using Harmony;
using UnityEditor;

namespace Hacks
{
	[InitializeOnLoad]
	public class AutoNameInjection
	{
		private static readonly Regex BackingFieldRegex = new Regex(@"^<(.+)>");

		static AutoNameInjection()
		{
			var harmony = HarmonyInstance.Create("some_cool_unique_identifier");
			harmony.PatchAll(Assembly.GetExecutingAssembly());
		}

		[HarmonyPatch(
			typeof(SerializedProperty),
			nameof(SerializedProperty.displayName),
			MethodType.Getter
		)]
		class SerializedPropertyDisplayNamePatch
		{
			static string Postfix(string __result)
			{
			
				var matches = BackingFieldRegex.Matches(__result);
				var clean = matches.Count > 0
					? matches[0].Groups[1].Value
					: __result;

				return clean;
			}
		}
	}
}
```

(This was my first use of Harmony, so sorry for any non-idiomatic-ness of the code)

**Comment by roboryantron** [comment]
Thanks so much for the fast reply and all these details! I may do an attribute based property drawer for the rename like [DisplayNameOverride("NewName")] but I am super excited to learn about this Harmony tool. I think I will be using this all the time now.....

**Comment by kroltan** [comment]
I have to advise you not to use it for runtime code if you can, since it can deoptimize some code, as well as break with code stripping. But it is just fine for editor scripts and patching some of Unity's idiosincrasies.
