### ISSUE TITLE
Consider #if in inspector suggestions

### ISSUE THREAD

**Issue by lambdor** [JetBrains/resharper-unity#102]
We have a function similar to the following. The inspector was making the suggestion "Value assignment is not used in any execution path" which is not the case if certain define symbols are changed. This is especially the case in Unity where #if are all over the place for certain platforms.

```
public static void foo( int bar )
{
	int ret = 0;
	if( bar == 0 )
	{
		ret = 0
	}
	else if( bar == 1 )
	{
		ret = 1
	}
#if UNITY_EDITOR	
	else
	{
		ret = -1
	}
#endif

	return ret;	
}
```

**Comment by citizenmatt** [comment]
ReSharper has no way of doing this, as there is no right answer - the warning is both valid and invalid, depending on the current context. If `UNITY_EDITOR` is defined, the warning is invalid and it shouldn't be shown. But if it's not, then it is a valid warning, and it should be displayed. What should ReSharper do in this case?

ReSharper can only work with the current context, which usually means the `#define` symbols for the current build configuration - Debug/Release. Switching the context will change the `#define` symbols and cause the inspections to be re-run, and any results updated.

(An exception to this is projects that have multiple target frameworks, such as shared projects and .net core projects. If Solution Wide Analysis is enabled, ReSharper will perform multiple analysis passes, one for each framework. This will pick up errors, with "Include warnings" as an option. However, it does not handle multiple build configurations per target framework - that could easily explode to a lot more analysis)

Any change here would have to come from ReSharper itself. There are several issues in the backlog ([here's a quick and dirty search](https://youtrack.jetbrains.com/issues/RSRP?q=preprocessor%20%23unresolved) that includes unrelated issues) about this, but no plan yet on how this could be successfully addressed.
