### ISSUE TITLE
Release for Resharper 2018.3.2

### ISSUE THREAD

**Issue by sorencoder** [JetBrains/resharper-unity#1021]
New bug-fix update of resharper released two days ago.
Can you give us an ETA of this plugin for the new version of resharper?

**Comment by citizenmatt** [comment]
There was a new version uploaded last week that corresponds to Rider 2018.3.2. Here are the [release notes](https://github.com/JetBrains/resharper-unity/releases/tag/183-eap12-rtm).

Note that there won't be a ReSharper release that corresponds to Rider 2018.3.3, as this only had a couple of fixes, and they were all Rider specific.
