### ISSUE TITLE
Allow SerializeField on a non-Unity derived class

### ISSUE THREAD

**Issue by karolwieczorek** [JetBrains/resharper-unity#1022]
`[SerializeField]` attribute in example below is not redundant. The very opposite is true.

```
public class SerializationTest
{
    [SerializeField] string serializedValue;

    public SerializationTest(string serializedValue)
    {
        this.serializedValue = serializedValue;
    }
}

var json = JsonUtility.ToJson(new SerializationTest("woho"));
Debug.Log(json);
```

Even when it's not class deriving from `UnityEngine.Object` it's still part of unity serialization system. 

The documentation has same error:
https://github.com/JetBrains/resharper-unity/wiki/Redundant-SerializeField-attribute
> isn't serialised, such as a field in a non-Unity derived class

**Comment by karolwieczorek** [comment]
@bddckr Thanks You are right. I was mislead by that [Redundant SerializeField attribute](https://github.com/JetBrains/resharper-unity/wiki/Redundant-SerializeField-attribute)
 doc and the fact that it actually worked without `System.Serializable attribute`...
Anyway it would be nice to have that second condition for plain class in this doc.

**Comment by citizenmatt** [comment]
I've [expanded the wiki page](https://github.com/JetBrains/resharper-unity/wiki/Redundant-SerializeField-attribute) to include details about this. 

Upshot is, explicit serialisation does not require the `[Serializable]` attribute, but we can't easily recognise this as the only usage, so the warning is really optimised to the use case of implicit serialisation as a field in a `MonoBehaviour`, and that DOES require the `[Serializable]` attribute. The workaround is to use the <kbd>Alt</kbd>+<kbd>Enter</kbd> quick fix to add the `[Serializable]` attribute, and that will shut Rider/ReSharper up.

Let me know if you think it could be clearer.
