### ISSUE TITLE
Rider 2018.3.2/Unity 2018.3.4f1 Failed to get RiderPath via .channel.settings.json and ArgumentNullException

### ISSUE THREAD

**Issue by jwvanderbeck** [JetBrains/resharper-unity#1023]
The Unity log is constantly being spammed with two messages, one a warning, the other an error.

Failed to get RiderPath via .channel.settings.json
UnityEditor.SyncRiderProject:PathCallback()
UnityEditorInternal.ScriptEditorUtility:GetFoundScriptEditorPaths(RuntimePlatform) (at C:/buildslave/unity/build/Editor/Mono/ScriptEditorUtility.cs:146)
UnityEditor.SettingsService:OpenUserPreferenceWindow()

ArgumentNullException: Value cannot be null.
Parameter name: source
System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <1b13ba6391c74847bbc3eddc86df7eee>:0)
UnityEditor.RiderPathLocator+<CollectPathsFromToolbox>c__AnonStorey3.<>m__0 (System.String a) (at C:/buildslave/unity/build/Editor/Mono/SyncRiderProject.cs:198)
UnityEditor.SyncRiderProject:PathCallback()
UnityEditorInternal.ScriptEditorUtility:GetFoundScriptEditorPaths(RuntimePlatform) (at C:/buildslave/unity/build/Editor/Mono/ScriptEditorUtility.cs:146)
UnityEditor.SettingsService:OpenUserPreferenceWindow()

**Comment by van800** [comment]
Workaround: https://youtrack.jetbrains.com/issue/RIDER-23678#focus=streamItem-27-3267904-0-0
Real fix should come with Unity update at some point.
