### ISSUE TITLE
2018.03: Having "Editor" and "Scripts" folder, Rider loses it necessary references

### ISSUE THREAD

**Issue by MohsenneChaverdie** [JetBrains/resharper-unity#1026]
Make a project with Unity 2018.03.03. Creates two folder in "Assets" folder: "Editor" and "Scripts". Then create one sample script in each of them. Open Rider with them. Rider issues a Warning and the script in Editor folder loses its references to the project.

Rider Warning: 
`Project 'Assembly-CSharp-Editor' load finished with warnings: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin" directory. at (1657:5)`

**Comment by van800** [comment]
It must be an issue in MSBuild installation. Either try to fix it based on the comments in https://developercommunity.visualstudio.com/content/problem/137779/the-getreferencenearesttargetframeworktask-task-wa.html
or use **JetBrains MSBuild** https://download.jetbrains.com/resharper/JetMSBuild.zip
More information here https://blog.jetbrains.com/dotnet/2018/04/13/introducing-jetbrains-redistributable-msbuild/
