### ISSUE TITLE
Can't install in visual studio

### ISSUE THREAD

**Issue by Woody4618** [JetBrains/resharper-unity#103]
Hey, i dont see the plugin in the resharper extension manager. 
Am i missing something?

**Comment by citizenmatt** [comment]
What version of ReSharper are you using? Do you see other extensions listed?

**Comment by Woody4618** [comment]
9.2 Yes i see others. But the Unity plugin does not appear at all.

**Comment by Woody4618** [comment]
shall i update to 2016.3.2?

**Comment by citizenmatt** [comment]
You should be able to see it in 9.2 - I'm not sure why you don't. I've given the server a little kick, and while I don't have 9.2 to test properly, I think it's in the feed now. However, the version for 9.2 is way back at 1.0, doesn't have a lot of features (here are the [release notes](https://github.com/JetBrains/resharper-unity/releases/tag/v1.0.0)), and won't be updated. Moving to 2016.3 will give you the latest version.

**Comment by Woody4618** [comment]
Now i see Version 1.0.0. Thanks 
I will install the new resharper version and try again

**Comment by Woody4618** [comment]
That worked. Thank you again :)
