### ISSUE TITLE
Add custom attribute to mark method as expensive

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#1030]
Add a new `JetBrains.Annotations` attribute to mark a method as expensive. Any usage of this method inside a performance critical context would be highlighted as usage of an expensive method, in the same was as `GetComponent`, `Find`, etc. are currently handled.

This would be useful for third party assemblies that indirectly call the known Unity APIs that are expensive (e.g. `Camera.main` calls `FindObjectWithTag` internally) and could be included as external annotations, or compiled directly into the code. We should add features to make it easy to create or add a reference/package to use the attribute.

Another option is to ship a public attribute in the plugin, or as a package. We can mark it as `[Conditional]` to prevent a binary dependency, or maybe `[Conditional("UNITY_EDITOR")]` so the dependency is only there for the editor, which would help if the project was being distributed on the Asset Store or as a package.

We should also think carefully about choosing a name - expensive might not be expressive enough. Maybe something like "performance sensitive"? And it would be worth co-ordinating with R# team to see if it could be shared, or just something with a Unity specific name.

**Comment by citizenmatt** [comment]
See also [RIDER-22807](https://youtrack.jetbrains.com/issue/RIDER-22807)

**Comment by Domonion** [comment]
Implemented, from now you can add `// ReSharper enable Unity.ExpensiveCode` above your `IFunctionDeclaration` and you would get this function marked as expensive

**Comment by Domonion** [comment]
Here is an example of avaiable features:   
![java_TyLQx58N8w](https://user-images.githubusercontent.com/12771085/96574014-9317a100-12d7-11eb-8aa0-59c1cba19c11.png)

And of course, they do affect the analysis transitively.

**Comment by limdingwen** [comment]
![image](https://user-images.githubusercontent.com/1744967/152645822-752719c9-b1b8-449f-a63d-08a74376745a.png)

Hi, this does not seem to work for me. JetBrains Rider 2021.3.2
