### ISSUE TITLE
Coroutine breakpoints inconsistently don't work

### ISSUE THREAD

**Issue by aaronhoogstraten** [JetBrains/resharper-unity#1040]
Rider version: 2018.3.3
Unity version: 5.6.3p3
```
12:06:03.631 |V| DebugSessionFrontend          | Debugger worker MTA main thread:3 | Breakpoint added C:/Users/Aaron Hoogstraten/Documents/repos/***/File.cs, line 243
12:06:03.632 |V| DebugSessionFrontend          | Debugger worker MTA main thread:3 | Breakpoint C:\Users\Aaron Hoogstraten\Documents\repos\***\File.cs, line 244 status changed: NotBound Not found associated module for breakpoint File.cs:244,9
12:06:03.647 |V| DebugSessionFrontend          | Debugger worker MTA main thread:3 | Breakpoint C:\Users\Aaron Hoogstraten\Documents\repos\***\File.cs, line 244 status changed: NotBound Unable to resolve method at position
```
This error appears while trying to place a breakpoint in various coroutines. However, it is inconsistent and in some files it works while in others it doesn't. To workaround this I can move the exact same coroutine method to a different file which I know works for debugging coroutines - breakpoints can successfully resolve the method in that file, but not in the original file.

**Comment by citizenmatt** [comment]
While it's inconsistent across the project, is it consistently failing in the same files?

**Comment by aaronhoogstraten** [comment]
Hi Matt, yes it consistently fails in the same files. So all coroutines in FileA.cs won't work, but all coroutines in FileB.cs are debuggable. The files are both in the same assembly as well, not sure if that matters.

**Comment by van800** [comment]
Closed in favor of https://youtrack.jetbrains.com/issue/RIDER-24652
Debugging is Rider core functionality it would be planned and fixed in YT.
