### ISSUE TITLE
Rider "Save On Frame Switching" causes Unity to sometimes throw a warning of missing .cs file

### ISSUE THREAD

**Issue by rob8861** [JetBrains/resharper-unity#1041]
If I make changes to a script file and switch over to Unity (without invoking the save command within Rider), Unity will throw this error

` A meta data file (.meta) exists but its asset 'Assets/Scripts/Actors/Enemy.cs' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.`

this however, never happens if I save the file in Rider which then triggers the Unity recompile. I can't tell for sure but from the Unity warning message it looks like Rider is deleting the script file, then creating it again.

**Comment by citizenmatt** [comment]
What OS is this? Forward slashes makes me think it's Mac"

**Comment by rob8861** [comment]
it is actually a PC. 
Unity's error and warning messages have always been in Mac format :)

**Comment by citizenmatt** [comment]
I think this is hitting a race condition. By default, Rider is set to use "safe write" when saving files. This writes to a temporary files, renames the old file, renames the new file and then deletes the old file. This is a safety measure to handle e.g. unexpected power loss. But Unity might be a bit quick off the mark and looking for changes before the process is finished.

I'm not sure what we can do about this. You can try to uncheck the "Use 'safe write'" option in the _Preferences | Appearance & Behavior | System Settings_ page. This will update the file in-place. There's a small chance of data loss in the case of power failure at exactly the wrong time, but it should be small enough to work with - [Local History](https://www.jetbrains.com/help/rider/local_history.html) could help a lot if things go wrong (the chances are tiny).

Does it happen each time, or only occasionally?

**Comment by rob8861** [comment]
> Does it happen each time, or only occasionally?
very occasionally.  I would say it happens once every 20 compilations, give or take. So I think you could be right. It does feel like a race condition especially since you confirmed Rider does all sorts of file manipulations.
I guess it is just a side effect we could live with.

**Comment by citizenmatt** [comment]
Closing this, mainly because I don't think there's anything we can do from the plugin.
