### ISSUE TITLE
C# Language Version "latest" not allowing 7.1 or greater features with Unity 2019.1

### ISSUE THREAD

**Issue by Hyp-X** [JetBrains/resharper-unity#1043]
This issue is sort of back:
[C# Language Version "latest" not allowing 7.x features](https://github.com/JetBrains/resharper-unity/issues/956)

Except this is now with Rider 2018.3.3 and Unity 2019.1.0b3 and only features for C# language version >=7.1 are affected.
This works correctly with the same Rider version and Unity 2018.3

The code compiles successfully in Rider but it is full of red underlines in the source editor.

I see new tags in the project file generated by Unity 2019.1:
```xml
    <CscToolPath>C:\Program Files\Unity\Hub\Editor\2019.1.0b3\Editor\Data\Tools\RoslynScripts</CscToolPath>
    <CscToolExe>unity_csc.bat</CscToolExe>
```
Maybe this is where the analyzer went wrong.

**Comment by citizenmatt** [comment]
Can you check that the project file contains `<LangVersion>latest</LangVersion>` and not `<LangVersion>default</LangVersion>` or something else?

**Comment by Hyp-X** [comment]
Yes I checked, it contains `<LangVersion>latest</LangVersion>`
Also the workaround from the original issue works. (Forcing the language version from Unity/Preferences/Rider)

**Comment by van800** [comment]
Doesn't reproduce for me mac/windows. @Hyp-X what do you have in Unity-Project Settings?
![image](https://user-images.githubusercontent.com/1482681/52859324-af3f6400-312c-11e9-89ef-e1f61f2683ab.png)

**Comment by van800** [comment]
Reproduced.

```
			int binaryNotation = 0b_0001_1110_1000_0100_1000_0000; // 2 million
			Debug.Log(binaryNotation);
```
for latest it show error, for 7.3 it is good.

**Comment by van800** [comment]
[SimpleUnityProject.zip](https://github.com/JetBrains/resharper-unity/files/2875629/SimpleUnityProject.zip)

**Comment by van800** [comment]
I am closing the issue here, issue is going to be fixed on Re# side. https://youtrack.jetbrains.com/issue/RSRP-473506
