### ISSUE TITLE
Exception Breakpoints 'Just my code' not working as expected

### ISSUE THREAD

**Issue by oxysoft** [JetBrains/resharper-unity#1046]
![image](https://user-images.githubusercontent.com/3945277/52907237-72a66200-322b-11e9-9af7-92fc156560f7.png)

As you can see in this screenshot, Rider has paused execution on an exception and directed me to some decompiled code. I have this exception set to "Just my code":

![image](https://user-images.githubusercontent.com/3945277/52907246-9d90b600-322b-11e9-9f22-b823edfca9d6.png)

**Comment by van800** [comment]
Closed in favor of https://youtrack.jetbrains.com/issue/RIDER-24651
Debugging is Rider core functionality it has better chances to be planned and fixed in YT.

**Comment by oxysoft** [comment]
Wasn't sure myself, thanks!
