### ISSUE TITLE
Find and Find-in-path to select word under the caret automatically.

### ISSUE THREAD

**Issue by chrisk414** [JetBrains/resharper-unity#1064]
Hi, the default behavior for Find and Find-in-path should be that the word under the caret is automatically selected word. 

It works like that in VS but not in Rider and it's really annoying when searching a word.

Could you please support the feature? Thanks.

**Comment by citizenmatt** [comment]
Hi. This repo is just for the Unity specific functionality of Rider. Please can you make feature requests and bugs for default Rider features in [the public bug tracker](https://youtrack.jetbrains.com/newIssue?project=RIDER), and we can make it sure it gets seen by the correct people?
