### ISSUE TITLE
Caret sometimes disappears when doing unsplit. 

### ISSUE THREAD

**Issue by chrisk414** [JetBrains/resharper-unity#1065]
Doing split/unsplit a window sometimes make the caret to disappears and I must click on a window to bring it back.

**Comment by citizenmatt** [comment]
Hi. This repo is just for the Unity specific functionality of Rider. Please can you make feature requests and bugs for default Rider features in [the public bug tracker](https://youtrack.jetbrains.com/newIssue?project=RIDER), and we can make it sure it gets seen by the correct people?
