### ISSUE TITLE
Show active window more obvious

### ISSUE THREAD

**Issue by chrisk414** [JetBrains/resharper-unity#1066]
When you split the window, it's hard to tell which window is active. 
Making the caret line highlight to show more vivid on the active window than non-active window but they look the same right now.
Thanks.

**Comment by citizenmatt** [comment]
Hi. This repo is just for the Unity specific functionality of Rider. Please can you make feature requests and bugs for default Rider features in [the public bug tracker](https://youtrack.jetbrains.com/newIssue?project=RIDER), and we can make it sure it gets seen by the correct people?

**Comment by citizenmatt** [comment]
You can change the colour of the caret line highlight in the _Preferences | Editor | Color Scheme | General_ page, select _Editor | Caret row_ and modify the background colour.
