### ISSUE TITLE
Maximze text editor.

### ISSUE THREAD

**Issue by chrisk414** [JetBrains/resharper-unity#1067]
When there are many windows on the screen, the text editing area is quite limited. It's sometimes desired to have the text editor maximized but there doesn't seem way to maximize the text editor window.

**Comment by citizenmatt** [comment]
Hi. This repo is just for the Unity specific functionality of Rider. Please can you make feature requests and bugs for default Rider features in [the public bug tracker](https://youtrack.jetbrains.com/newIssue?project=RIDER), and we can make it sure it gets seen by the correct people?

**Comment by citizenmatt** [comment]
You can double click the tab to hide all tool windows and maximise the current editor. If you go to the Keymap preferences page, you can search for "Hide All Tool Windows", and that will show you what the keyboard shortcut is (it depends on what keymap you have active).
