### ISSUE TITLE
Make moving around split window easier.

### ISSUE THREAD

**Issue by chrisk414** [JetBrains/resharper-unity#1068]
There are options to "Goto next splitter" and "Goto previous splitter" but when you split the window with many horizontal/vertical, moving around is hard. What I would like is to move around the split windows using arrow keys. Please make the command (move to splitter window, right, left, up, down) available and I'll figure out the hotkeys somehow. Thanks.

**Comment by citizenmatt** [comment]
Hi. This repo is just for the Unity specific functionality of Rider. Please can you make feature requests and bugs for default Rider features in [the public bug tracker](https://youtrack.jetbrains.com/newIssue?project=RIDER), and we can make it sure it gets seen by the correct people?

**Comment by citizenmatt** [comment]
If you go to the _Keymap_ options page and search for "Goto next splitter" and "Goto previous splitter", you'll find the keyboard shortcuts, and can modify them if you want to.
