### ISSUE TITLE
More search options are needed

### ISSUE THREAD

**Issue by chrisk414** [JetBrains/resharper-unity#1069]
I think the consolidated search tool is really the most awesome feature and I wish Rider takes it to the next level. FYI, I use Entrian Search tool on VS and I'll really miss it if I move to Rider. It probably is the best search tool as it supports full indexing based on Elasticsearch engine. Basically, I would like a search option for multiple words; word1 OR word2, word1 AND word2.  I know there is regex search options but search word1 and word2 on regex is not so easy. Anyway, please take a look Entrian Search if you haven't looked at it. It will give you many good ideas.

**Comment by citizenmatt** [comment]
Hi. This repo is just for the Unity specific functionality of Rider. Please can you make feature requests and bugs for default Rider features in [the public bug tracker](https://youtrack.jetbrains.com/newIssue?project=RIDER), and we can make it sure it gets seen by the correct people?
