### ISSUE TITLE
Warn about unsaved scenes before commit

### ISSUE THREAD

**Issue by bartlomiej-dawidow** [JetBrains/resharper-unity#1077]
To reproduce:
1. Make some changes to a Unity scene, e.g. rename a GameObject.
2. Edit a script in Rider.
3. Commit changes to git.

If you do not save the changes done in Unity, they will not be included in the commit. I routinely find myself forgetting to do this.

A suggested solution would be to add a prominent warning message somewhere in the Commit Changes dialog if there are any unsaved changes in Unity.

**Comment by van800** [comment]
I wonder if there is any api to check unsaved scenes in UnityEditor.

**Comment by citizenmatt** [comment]
Yes, you can call `Scene.isDirty` to see if it's modified in memory, and use something like `EditorSceneManger.GetSceneAt` to iterate over all open scenes. I need something similar for the YAML stuff (don't want to rename something referenced in an unsaved scene), so I can look into this as part of that.

**Comment by van800** [comment]
```
for (var i = 0; i < SceneManager.sceneCount; ++i)
    if (SceneManager.GetSceneAt(i).isDirty) ...
```

**Comment by krasnotsvetov** [comment]
We have already do same check for Find Usages in scenes, so it is possible. But the connection should be established for this feature

**Comment by van800** [comment]
closed in favor of https://youtrack.jetbrains.com/issue/RIDER-60824
