### ISSUE TITLE
NoNullPropagation spelled wrong as NoNullPropogation

### ISSUE THREAD

**Issue by Dravere** [JetBrains/resharper-unity#1083]
There seems to be a spelling error for the warning `Unity.NoNullPropagation`. The warning is actually named `NoNullPropogation`. When you want to disable it once with a comment in Rider, it will then display a warning because of the wrong spelling.

https://github.com/JetBrains/resharper-unity/blob/1edad4e83421d388524f612f1929969af8579198/resharper/resharper-unity/src/CSharp/Daemon/Errors/CSharpErrors.xml#L504

**Comment by citizenmatt** [comment]
Doh! This is awkward, because if we fix it, then Rider won't recognise an existing (incorrectly spelt) comment and highlight it as a warning again...

**Comment by Dravere** [comment]
But in the long run it probably is better? Or do you support a way to have two names for it and support both and thus have backwards compatibility?
