### ISSUE TITLE
get_unityVersion is not allowed to be called while application is terminating.

### ISSUE THREAD

**Issue by QuentinBrun2** [JetBrains/resharper-unity#1084]
Using Unity for magic leap version 2018.1.9f2-MLTP10 is unable to launch "zero iteration mode" when rider plugin is installed (in version 2018.3.0.135) 

For information, Magic leap add a menu to relaunch unity in a specific mode. But as unity crash while closing, it is not able to launch again.
Here is the log inside unity editor: 
get_unityVersion is not allowed to be called while application is terminating.

As soon as I remove the rider plugin, the "get_unittyVersion" issue does not appear and unity relaunch well.

Tell me if you need anything else

**Comment by van800** [comment]
I believe this is already fixed in Rider 2019.1 upcoming EAP.
https://github.com/JetBrains/resharper-unity/pull/979
It should become public this week.

**Comment by QuentinBrun2** [comment]
Thank you!
