### ISSUE TITLE
Shader compiler bug in Unity prompts urgent need for shader schema as 1st class

### ISSUE THREAD

**Issue by bradzoob** [JetBrains/resharper-unity#1088]
I know this is an old request from users, and an old promise from JetBrains, but our joyful indifference at the lack of progress must unfortunately come to an end

Fully realised shader language (HLSL/GLSL) editing is a must have feature in the Rider IDE.

Despite shaders being an essential part of Unity development and indeed for development in general  (compute/opencl) there's still no first class representation of them in Rider, the shader editor remains ostensibly as UX mature as notepad.exe, but to increase pressure there's also currently an issue with Unity 2018.X regarding shader compilation, it's causing peoples projects to take a ridiculous amount of time compiling shaders, so now more than ever we need proper Shader syntax parsing/"intellisense" etc to avoid superfluous re-compiles which are taking 15-300 minutes whenever you modify a shader, so as you'd expect that means bracket matching/structure panel/method traversal/ctrl-space/ctrl-b functionality, basically all the stuff we've been waiting on for years to appear in Rider for editing shaders with Unity, which is now fairly critical.  The sad thing is, Visual Studio HAS a solution for this, but it's Visual Studio, so although i'd rather eat my own spine than use VS again, this shader issue is devastating for iteration/testing/achieving production ready applications so at this time persevering with Rider is ostensibly worse than the prospect of switching back to VS.

If you're unable to do this, understandable you have priorities and shader schemas probably aren't high on that list, are you able to expose documentation relating to building our own language schema for Rider? and if not documentation then at least exposure/reference to a lib/API so I can figure it out myself? I did try approaching this a month or so ago but couldn't find what I needed, which is basically any docs / refs available for building a new language into Rider, ie; hlsl. Not just basic syntax highlighting, as I did find some references for that, but full IDE language parsing / integration capabilities, the equivalent of any other language in IntelliJ. Though I suspect this would be time consuming it would be worth it if the end result was a proper shader editor and being able to continue using Rider.

Thanks!

**Comment by van800** [comment]
We can invite you to plugin devs slack channel. I would need your email.

**Comment by bradzoob** [comment]
Wasn't sure the best way to send you my email and wasn't keen on the idea of publishing my IntelliJ license ID so I guess I'll just dump it here; bradley.higgs@zoob.net :) thanks for your time Ivan.

**Comment by van800** [comment]
You may delete the email now, I have got it. Please expect the invite in a couple of days.

**Comment by bradzoob** [comment]
Thanks! :)

**Comment by van800** [comment]
I believe, you should have got an invitation by now.
