### ISSUE TITLE
Unity Explorer disappeared

### ISSUE THREAD

**Issue by Temka193** [JetBrains/resharper-unity#1095]
![image](https://user-images.githubusercontent.com/11135702/54824011-ae18ce00-4cba-11e9-9324-bcad4d326d1b.png)
Where item "Unity" ?

Version 2019.1.0.17

**Comment by van800** [comment]
Probably one of the conditions wasn't met.
https://github.com/JetBrains/resharper-unity/blob/3f55e9348b743f1f6106b0a46da73bbe9f6383a9/rider/src/main/kotlin/com/jetbrains/rider/UnityProjectDiscoverer.kt#L27

**Comment by van800** [comment]
Rider 2019.1EAP2? OS? Reproduces for any project or only one? Only UnityExplorer is missing or all Unity support plugin functionality? Please add full screenshot or logs (Help->Compress Logs and Show).
Unity support plugin itself is present, right?
![image](https://user-images.githubusercontent.com/1482681/54825031-dac5e900-4cac-11e9-987d-19f1526672ae.png)

**Comment by Temka193** [comment]
Yes, "Unity Support" installed.
Rider 2019.1 EAP2, OS Windows 10

**Comment by van800** [comment]
Please check conditions mentioned in https://github.com/JetBrains/resharper-unity/issues/1095#issuecomment-475614368
If it is not the case, I would need logs.

**Comment by Temka193** [comment]
Assets and ProjectSettings exist
![image](https://user-images.githubusercontent.com/11135702/54827574-664a7480-4cc3-11e9-89a9-b79824f573e3.png)

**Comment by van800** [comment]
And `ProjectVersion.txt` file inside ProjectSettings?

**Comment by van800** [comment]
Ok, could you share logs (https://rider-support.jetbrains.com/hc/en-us/articles/360001079770-How-to-collect-Rider-logs-) and full screenshot?

**Comment by Temka193** [comment]
I would not want to do my logs to public

**Comment by Temka193** [comment]
@van800 how can I send logs only to you?

**Comment by van800** [comment]
Please send to Ivan.Shakhov at jetbrains.com

**Comment by Temka193** [comment]
> Please send to Ivan.Shakhov at jetbrains.com

this email address?

**Comment by Temka193** [comment]
@van800 I sent you logs

**Comment by van800** [comment]
@Temka193 Change " at " into "@" and send.

**Comment by van800** [comment]
I think reason for not showing UnityExplorer is this error in the logs
ERROR | ExtensionPointImpl             | Illegal char <:> at index 74
I will show it to corresponding devs. Thanks

**Comment by citizenmatt** [comment]
Fix should be available in EAP 3
