### ISSUE TITLE
Exception if open Preferences in Unity

### ISSUE THREAD

**Issue by Temka193** [JetBrains/resharper-unity#1097]
Unity 2018.3.9f1 
Rider 2019.1 EAP2

ArgumentNullException: Value cannot be null.
Parameter name: source
System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <1b13ba6391c74847bbc3eddc86df7eee>:0)
UnityEditor.RiderPathLocator+<CollectPathsFromToolbox>c__AnonStorey3.<>m__0 (System.String a) (at C:/buildslave/unity/build/Editor/Mono/SyncRiderProject.cs:198)
UnityEditor.SyncRiderProject:PathCallback()
UnityEditorInternal.ScriptEditorUtility:GetFoundScriptEditorPaths(RuntimePlatform) (at C:/buildslave/unity/build/Editor/Mono/ScriptEditorUtility.cs:154)
UnityEditor.SettingsService:OpenUserPreferenceWindow()

**Comment by van800** [comment]
https://youtrack.jetbrains.com/issue/RIDER-23678
