### ISSUE TITLE
Improve keyboard UX of LogView, including stacktrace navigation

### ISSUE THREAD

**Issue by oxysoft** [JetBrains/resharper-unity#1101]
I think it would be a pretty big usability win if the stacktrace was presented as a list instead of text, like the stacktrace in the debugger. Up/Down keys could be used to select and enter to navigate to the relevant file and line of code.

**Comment by van800** [comment]
Currently log is presented in a same way as "Stacktrace explorer" feature.

**Comment by oxysoft** [comment]
I see, so should I instead create a ticket on youtrack for the Stacktrace explorer to have this feature?

**Comment by van800** [comment]
I am just giving you more context. Could you please add more context to your request. What is your use-case? How do you use LogView? In current presentation, you can click to almost any place in the stacktrace and it will open file and navigate to line. Why it is not enough?

**Comment by oxysoft** [comment]
* I am mostly a keyboard only user, I try to avoid the mouse at all cost, mostly because I am more comfortable with my hands resting on the keyboard. Some time when I am debugging a tough bug, I will slowly navigate the stacktrace with my hands resting at the keyboard and arrow keys. I would like to be able to use the same workflow for debugging errors printed out in Unity.

* I have a lot of horizontal space on my monitor and I try to keep vertical space as minimal as possible for code, so I like to place tool windows on the side instead of at the bottom. 

   ![image](https://user-images.githubusercontent.com/3945277/54884545-e3532680-4e48-11e9-8f51-f1255ab54646.png)

   Unfortunately I have to scroll horizontally a lot to see the lines. I can enable soft-wrap but it makes it really hard and uneven to read. With a list of items, it would be easy to navigate and keep track of if it were soft-wrapped.

* The output from Unity is simply too hard to read and I some formatting and cleaning could be done if it were made into a dedicated GUI item. Something like the debugger stacktrace:

   ![image](https://user-images.githubusercontent.com/3945277/54884663-19dd7100-4e4a-11e9-8093-2bbf382114c3.png)

**Comment by van800** [comment]
Thanks for the thoughtful explanation!

**Comment by van800** [comment]
What currently is already available.
First Tab focuses filter box, second tab focuses stacktrace view.
Ctrl+Alt+Arrow in stacktrace view allows navigating.

I understand there is a need of some UI tweak to reduce space occupied by text in each line.

**Comment by oxysoft** [comment]
Thank a lot for informing that this existed. I have no idea whether Ctrl+Alt+Up/Down is new or I replaced the mapping for this shortcut long ago, but I just mapped the 'Previous/Next Occurence' actions again to Ctrl+Page Up/Down and this works perfectly for my workflow. The Unity tool window or Stacktrace explorer doesn't need to have focus which is even better.

**Comment by van800** [comment]
related issue https://youtrack.jetbrains.com/issue/RIDER-14610

**Comment by van800** [comment]
I am closing this issue in favor of those 2 requests above.
