### ISSUE TITLE
Hold Ctrl+S for a minute causes huge perf problem for Unity pre-2018.1

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#1106]
Because csproj on disk gets recreated many times with different content.

**Comment by van800** [comment]
Hm, Doesn't reproduce for me on my windows machine.

**Comment by krasnotsvetov** [comment]
This problem affects only 2017 LTS

**Comment by van800** [comment]
No idea, what could be done here. Closing, since problem is solved in new Unity versions.

**Comment by citizenmatt** [comment]
Is this due to Unity rebuilding on file writes, or us telling Unity to refresh on every save request? We could throttle the calls to refresh so we don't do it more than e.g. once a second. This might be a good idea even if Unity 2018+ handles this better.

**Comment by van800** [comment]
@citizenmatt We checked the logs. Rewriting csproj is happening ~ once per 2 seconds, but the problem is that Unity writes their version of csproj to disk, our Editor plugin reads it, edits and saves back.
Those 2 versions have differences, which cause SWEA reanalyze.

**Comment by citizenmatt** [comment]
Are we causing the rewriting by refreshing too often?
