### ISSUE TITLE
batchmode postprocessor crash on OSX

### ISSUE THREAD

**Issue by bhallionOhbibi** [JetBrains/resharper-unity#1125]
I get the following error when building unity player on mac osx:
The only solution was to remote the plugin from my project

GetManagerFromContext: pointer to object of manager 'PlayerSettings' is NULL (table index 0)
UnityEditor.PlayerSettings:GetApiCompatibilityLevel(BuildTargetGroup)
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
System.Reflection.MethodBase:Invoke(Object, Object[]) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
JetBrains.Rider.Unity.Editor.AssetPostprocessors.CsprojAssetPostprocessor:GetApiCompatibilityLevel()
JetBrains.Rider.Unity.Editor.AssetPostprocessors.CsprojAssetPostprocessor:.cctor()
System.Reflection.MonoCMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoCMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:513)
System.Reflection.MonoCMethod:Invoke(BindingFlags, Binder, Object[], CultureInfo) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:528)
System.Reflection.ConstructorInfo:Invoke(Object[]) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/ConstructorInfo.cs:77)
System.Activator:CreateInstance(Type, Boolean) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Activator.cs:372)
System.Activator:CreateInstance(Type) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Activator.cs:254)
UnityEditor.AssetPostprocessingInternal:InitPostprocessors(String) (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:117)

[/Users/builduser/buildslave/unity/build/Runtime/BaseClasses/ManagerContext.cpp line 91] 
(Filename: /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs Line: 222)

Fatal Error! GetManagerFromContext: pointer to object of manager 'PlayerSettings' is NULL (table index 0)
System.Reflection.MethodBase:Invoke(Object, Object[])
JetBrains.Rider.Unity.Editor.AssetPostprocessors.CsprojAssetPostprocessor:GetApiCompatibilityLevel()
JetBrains.Rider.Unity.Editor.AssetPostprocessors.CsprojAssetPostprocessor:.cctor()
UnityEditor.AssetPostprocessingInternal:InitPostprocessors(String)

UnityEditor.PlayerSettings:GetApiCompatibilityLevel(BuildTargetGroup)
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
System.Reflection.MethodBase:Invoke(Object, Object[]) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
JetBrains.Rider.Unity.Editor.AssetPostprocessors.CsprojAssetPostprocessor:GetApiCompatibilityLevel()
JetBrains.Rider.Unity.Editor.AssetPostprocessors.CsprojAssetPostprocessor:.cctor()
System.Reflection.MonoCMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoCMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:513)
System.Reflection.MonoCMethod:Invoke(BindingFlags, Binder, Object[], CultureInfo) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:528)
System.Reflection.ConstructorInfo:Invoke(Object[]) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/ConstructorInfo.cs:77)
System.Activator:CreateInstance(Type, Boolean) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Activator.cs:372)
System.Activator:CreateInstance(Type) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Activator.cs:254)
UnityEditor.AssetPostprocessingInternal:InitPostprocessors(String) (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:117)

[/Users/builduser/buildslave/unity/build/Runtime/Utilities/Argv.cpp line 226] 
(Filename: /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs Line: 222)

Aborting batchmode due to failure:
Fatal Error! GetManagerFromContext: pointer to object of manager 'PlayerSettings' is NULL (table index 0)
System.Reflection.MethodBase:Invoke(Object, Object[])
JetBrains.Rider.Unity.Editor.AssetPostprocessors.CsprojAssetPostprocessor:GetApiCompatibilityLevel()
JetBrains.Rider.Unity.Editor.AssetPostprocessors.CsprojAssetPostprocessor:.cctor()
UnityEditor.AssetPostprocessingInternal:InitPostprocessors(String)

**Comment by van800** [comment]
Could you please try 2019.1 EAP?
It is expected to be already fixed. https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FRIDER-24358
