### ISSUE TITLE
Index out of range exception when clicking on a folder in project window

### ISSUE THREAD

**Issue by sorencoder** [JetBrains/resharper-unity#1128]
When I click on a folder in project view, Rider prints this message in the unity console:
```
Exception thrown while invoking [OnOpenAssetAttribute] method 'JetBrains.Rider.Unity.Editor.PluginEntryPoint:OnOpenedAsset (int,int)' : ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
System.String.Substring (System.Int32 startIndex, System.Int32 length) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.String.Substring (System.Int32 startIndex) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
JetBrains.Rider.Unity.Editor.OnOpenAssetHandler.OnOpenedAsset (System.Int32 instanceID, System.Int32 line, System.Int32 column) (at <95768797cee0464e99db51d00d374980>:0)
JetBrains.Rider.Unity.Editor.PluginEntryPoint.OnOpenedAsset (System.Int32 instanceID, System.Int32 line) (at <95768797cee0464e99db51d00d374980>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

I've switched the logging to verbose and have attached the log.

Thank you!
[2019-04-05T-22-40-46.log](https://github.com/JetBrains/resharper-unity/files/3049147/2019-04-05T-22-40-46.log)

**Comment by van800** [comment]
What is your Unity version? And Rider version? Thanks!

**Comment by van800** [comment]
What behavior would you expect? Either do nothing or open in Rider?

**Comment by sorencoder** [comment]
Unity 2018.3.11, Rider 2019.1 EAP 4
I have reproduced it with older versions too.

The expected behavior is to do nothing. 
I've never double clicked on a folder with intention of opening it in external code editor.

**Comment by van800** [comment]
I can't reproduce it, probably I am clicking in the wrong place. Could you please make a screenshot and mark a place to click?

**Comment by sorencoder** [comment]
I use one column project layout. 

To switch to one column project layout, you need to click on the button with three bars that is at top right of the project window and select "One Column Layout".

**Comment by van800** [comment]
I am confused - still no repro. However I added a probable fix, so I will notify you, when build is available.

**Comment by sorencoder** [comment]
![1](https://user-images.githubusercontent.com/30625116/55681892-321cb800-5941-11e9-9169-5d3752c9364d.png)
![2](https://user-images.githubusercontent.com/30625116/55681895-3648d580-5941-11e9-88f6-9d1b79d3af84.png)
![3](https://user-images.githubusercontent.com/30625116/55681896-39dc5c80-5941-11e9-81ee-249ff9dbbd7a.png)

Once you switched to One Column Layout (Your project folders are like the last picture), double click on a folder.

**Comment by sorencoder** [comment]
Just to be more clear, you need to double click on this area:
![4](https://user-images.githubusercontent.com/30625116/55685845-dcabcf80-596f-11e9-9281-69725d548ad5.png)
