### ISSUE TITLE
Generate run-configuration for the application build by Unity

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#1132]
Approach 1:
Find compiled application via `UnityEditor.EditorUserBuildSettings.GetBuildLocation` and generate `Unity executable` run-configuration for it. It would help to start profiling.
Approach 2:
Use something like `UnityEditor.BuildPlayerWindow.BuildPlayerAndRun` to build/rebuild application and take Approach 1 to generate/update run-configuration.

**Comment by citizenmatt** [comment]
Fixed in #1708
