### ISSUE TITLE
Using Rider as diff tool when collaboration feature is enabled

### ISSUE THREAD

**Issue by marpe** [JetBrains/resharper-unity#1136]
How do I set Rider as t he default merge/diff tool when using Unitys collaboration feature?

**Comment by van800** [comment]
Will this work? 
https://www.jetbrains.com/help/rider/Command_Line_Differences_Viewer.html

**Comment by marpe** [comment]
Would maybe work if Unity allowed me to enter a custom tool, but it doesn't when hte collaboration feature is on. I realized that this is probably a question more suitable for the Unity forums.
