### ISSUE TITLE
No marks on IEnumerator Start() method

### ISSUE THREAD

**Issue by WeslomPo** [JetBrains/resharper-unity#114]
Unity have also feature that Start method can be a IEnumerator and start coroutine method "Start" immediately before first frame. Plugin did not mark them as ok now.
This is regular start method:
```
private void Start() {}
```
This is ~~smokers~~ also normal start method:
```
private IEnumerator Start() {
	yield return new WaitForSeconds(1);
}
```

[Unity Coroutine docs with example](https://docs.unity3d.com/ScriptReference/MonoBehaviour.StartCoroutine.html)

**Comment by CAD97** [comment]
See #52
