### ISSUE TITLE
Unity Fails To Open When Rider has Solution Open

### ISSUE THREAD

**Issue by Alex-Gilbert** [JetBrains/resharper-unity#1141]
using unity 2019.2.0a11

When opening a Unity project when Rider has the project's .sln file open, Unity will crash and fail to start.

**Comment by Alex-Gilbert** [comment]
Unity project opens fine when Rider is closed.

**Comment by van800** [comment]
When Unity crashes there should be a crash log, could you please provide it?
What is you OS and Rider version?

**Comment by Alex-Gilbert** [comment]
Hello Ivan,

Unfortunately I don't receive any logs from unity. It just sits at the splash screen. Task manager reports unity as "Not Responding". It remains in this state until I end the process through task manager. 

Using Rider 2018.3.4 on Windows 10

This happened again to me this morning. Unity would not open the project until I removed all the Rider Plugins from my asset folder.

**Comment by Alex-Gilbert** [comment]
I'm unsure of what is causing the issue exactly.

Unity will refuse to open until I either,
a) Close Rider
--- Sometimes this isn't enough so ----
b) Delete all the Rider plugin files from my asset folder. 

Unity now has no issue opening my project

**Comment by van800** [comment]
Unfortunately it is not easy to reproduce the case, but there are couple of things may help us understand the problem.
Next time when Unity hangs, please collect:
1. Editor log https://docs.unity3d.com/Manual/LogFiles.html
2. Rider logs from Help->Compress logs and show in Explorer
3. Install this nuget package https://www.nuget.org/packages/UnityCaptureTraces.x64/
(nuget.exe install UnityCaptureTraces.x64 in some place)
4. Run debug_process.bat process_id
where process_id is process id of hanged Unity.exe.
5. Collect log file from newly created folder

**Comment by van800** [comment]
I am closing this. Please reopen or just comment, when if strikes again.
