### ISSUE TITLE
missing quick doc info for attributes like ExecuteInEditMode

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#115]
[ExecuteInEditMode]
https://docs.unity3d.com/ScriptReference/ExecuteInEditMode.html

**Comment by citizenmatt** [comment]
Hmm. Looks like a ReSharper bug. This attribute has XML doc, but only on the class. When used in code, ReSharper treats `[ExecuteInEditMode]` as a reference to the constructor, and there isn't a doc for the constructor, so ReSharper shows nothing. It also doesn't show in this case:

```csharp
/// <summary>
/// Bananas
/// </summary>
public class FooAttribute : Attribute { }

[Foo]
public class Bar { }
```

But if VS is providing the tooltip, it shows correctly. I'll raise an issue against ReSharper.

**Comment by citizenmatt** [comment]
https://youtrack.jetbrains.com/issue/RSRP-463453

**Comment by MrJul** [comment]
Also see https://github.com/MrJul/ReSharper.EnhancedTooltip/issues/23 - Enhanced Tooltip displays documentation for the class rather than the constructor for attribute usages by default.

(Sorry for the self promotion, but this solves this very specific issue :smile:)

**Comment by citizenmatt** [comment]
I thought it might :) I didn't test, in this instance, because it also needs to work in Rider...
