### ISSUE TITLE
ReSharper 2019.1 - Not appearing in extension list.

### ISSUE THREAD

**Issue by LurchUSA** [JetBrains/resharper-unity#1157]
It appears that this extension is NOT compatible with 2019.1, as it is not showing up in the extension list. Please provide 2019.1 support.

**Comment by citizenmatt** [comment]
It's just been uploaded to the repository. Should be available in the Extension Manager now.

**Comment by LurchUSA** [comment]
Are you sure you are talking about the ReSharper Ultimate Extensions dialog?

Because the attached image is what I'm seeing.

![2019-04-30_11-16-11](https://user-images.githubusercontent.com/21182290/56976844-7c0c4e80-6b39-11e9-80ce-197d240f9fc5.png)

**Comment by citizenmatt** [comment]
Yeah, something's gone wrong server side. Let me follow up.

**Comment by citizenmatt** [comment]
It's available in the Extension Manager now. Apologies for the delay!

**Comment by LurchUSA** [comment]
No worries, all good. Thanks for getting back to me.
