### ISSUE TITLE
How to install on Mac OS?

### ISSUE THREAD

**Issue by kapyar** [JetBrains/resharper-unity#116]

**Comment by citizenmatt** [comment]
Can you provide some more details, please? If you mean Rider, just install it via the Plugins page in Preferences.

**Comment by kapyar** [comment]
Yeap, can't find this repository in plugins 
![screen shot 2017-03-01 at 7 55 53 pm](https://cloud.githubusercontent.com/assets/6231331/23473519/2838ee2e-feb9-11e6-95ce-1692aa3169af.png)

**Comment by citizenmatt** [comment]
Looks like it's already installed - this plugin is "Unity Support" in Rider, the second item in your list. If you open a Unity project, do you see any Unity icons in the text editor gutter, or any Unity items in the Generate menu (<kbd>Alt</kbd>+<kbd>Insert</kbd>)?

**Comment by kapyar** [comment]
Oh yes (facepalm) thanks, sorry for disturbing you.
