### ISSUE TITLE
Consider stopping {package_root}/Scripts acting as a namespace provider

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#1161]
Rider (and ReSharper) currently prevents the `Assets` and `Assets/Scripts` folders acting as "namespace provider", so Rider won't suggest adding `Assets` or `Assets.Scripts` as part of the namespace.

Rider doesn't do anything similar for packages. So if a package root folder has a `Scripts` folder, Rider will suggest adding `Scripts` into the namespace.

To fix this, when loading each project, look for a `.asmdef` file - the location of this file marks the root folder of the package's project (a package can hold multiple projects). We can then use this path to stop `Scripts` being flagged as a namespace provider.

Big question is: is this a scenario likely to be encountered by a large number of users? Will most users set up a folder structure with `Scripts` in the root folder of a package project?

**Comment by StephenHodgson** [comment]
Personally, I don't typically use `Scripts` as a root folder but I like to separate the code out into unity packages that then get imported via UPM (Unity package manager).

I definitely like the search for `.asmdef` and would like to see this be the root, or starting point for namespace name suggestions, with the name of the assembly being part of that name.

**Comment by StephenHodgson** [comment]
Also, I noticed that for my embedded upm scripts the namespace suggestions take the `Packages` folder into consideration. I think this will also fix that issue as well.

**Comment by StephenHodgson** [comment]
Personally, I don't typically use `Scripts` as a root folder but I like to separate the code out into unity packages that then get imported via UPM (Unity package manager).

I definitely like the search for `.asmdef` and would like to see this be the root, or starting point for namespace name suggestions, with the name of the assembly being part of that name.

**Comment by citizenmatt** [comment]
Where are the `.asmdef` files in the embedded packages?

**Comment by StephenHodgson** [comment]
Typically the assembly definitions could live anywhere.

In embedded packages it might be better to just search for the `package.json` that defines them. They're always at the root folder.

**Comment by StephenHodgson** [comment]
Embedded packages are local files that live in the `Packages` folder which is a sibling to `Assets`

**Comment by Stuv42** [comment]
Just going to throw in my support for this, slowly migrating my modules to separate packages and namespaces are probably my only issue with them so far in Rider.

For reference this is the structure unity suggests: https://docs.unity3d.com/Manual/cus-layout.html

Ideally I think the namespaces should be:
YourPackageName and YourPackageName.Editor

So assuming the .asmdefs are named YourPackageName and YourPackageName.Editor (The assembly name, not the file name) , I think working off the .asmdef location as you mention is ideal as you can simply make sure the name is what ever you want the root to be.

Just something I noticed when first trying packages, somehow Rider was giving me the option to change the properties on the packages root and my package, thus I could change if it was a namespace provider. The option seemed to go away after a restart sadly, but I was hopeful it was a workaround.

**Comment by syscrusher1709** [comment]
> Personally, I don't typically use `Scripts` as a root folder but I like to separate the code out into unity packages that then get imported via UPM (Unity package manager).
> 
> I definitely like the search for `.asmdef` and would like to see this be the root, or starting point for namespace name suggestions, with the name of the assembly being part of that name.

I agree. Whether or not I use Scripts as a top-level folder depends on a number of factors, for instance joining an existing project -- especially for an external customer -- that already has a large folder structure and namespaces established.

The suggested solution of examining the .asmdef files seems a very project-neutral way of allowing fine-grained control to developers who need it while not breaking a simple default behavior for small sandbox projects or novices.

I would add that having "Scripts" or "scripts" as a default namespace in the latter situation would, IMO, be a really bad idea, so I'm glad that is not the default now! If it's desired to have Rider suggest a default, the Product Name (sanitized to fit C# syntax) from the Unity project settings (under "Player") might be a good choice.
