### ISSUE TITLE
Error on Plugin Load. Unable to resolve reference 'nunit.framework'

### ISSUE THREAD

**Issue by OmegaRogue** [JetBrains/resharper-unity#1166]
When loading the plugin in the unity editor (Unity 2019.2.0a14) this error is thrown:
```
Assembly 'Assets/Plugins/Editor/JetBrains/JetBrains.Rider.Unity.Editor.Plugin.Repacked.dll' will not be loaded due to errors:
Unable to resolve reference 'nunit.framework'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
```

**Comment by van800** [comment]
There is currently a workaround to add the following package:
`"com.unity.ext.nunit": "1.0.0"`

**Comment by van800** [comment]
Fixed in com.unity.ide.rider package ver. 1.0.7.
Would be available in staging in one-two days.
To access staging packages add the following:
`"registry": "https://staging-packages.unity.com",` to manifest.json
