### ISSUE TITLE
Why is Rider reporting errors in Unity scenes?

### ISSUE THREAD

**Issue by Spartanace1024** [JetBrains/resharper-unity#1188]
I have a scene named CharacterSelectCanvasController.unity and rider for some reason is reporting errors in the scene. Specifically it's telling me that the method name is unresolved, despite it being just fine in the scene. See images below for details.

![image](https://user-images.githubusercontent.com/2967721/57876580-86ca1300-77ca-11e9-90bb-5fd1f547536a.png)

![image](https://user-images.githubusercontent.com/2967721/57876675-cbee4500-77ca-11e9-8dff-717ea11e4e99.png)

**Comment by Spartanace1024** [comment]
After further investigation it looks like every scene that has a OnClick gui handler is reporting an error in the scene file stating it can't find the method. Strange part is that if I Ctrl + hover / click the method name in the scene file it finds it just fine.

**Comment by krasnotsvetov** [comment]
Thanks for your feedback!
Looks like we have already fixed it in the upcoming bugfix, but to be sure could you please try to install the latest Rider version from toolbox (download https://www.jetbrains.com/toolbox/app/ and choose Rider 2019.1 Nightly from a dropdown)?

**Comment by Spartanace1024** [comment]
Yup i'll go ahead and check that out. Also can you clarify that this is a new feature for Rider? 

Does it check the scene files to ensure you have the function you say you do in the inspector events? If so can you point me to the docs that elaborate on this.

Thanks in advance!

**Comment by Spartanace1024** [comment]
Just updated to the latest nightly and it seams to resolve the issue 👍
