### ISSUE TITLE
GetComponent(string) should check the symbol in text argument ...

### ISSUE THREAD

**Issue by CAD97** [JetBrains/resharper-unity#119]
... or at least warn against using `GetComponent(string)` and suggest using the generic verison `GetComponent<Type>` instead.

[`AddComponent`](https://docs.unity3d.com/ScriptReference/GameObject.AddComponent.html),  [`GetComponent`](https://docs.unity3d.com/ScriptReference/GameObject.GetComponent.html), and [`CreateInstance`](https://docs.unity3d.com/ScriptReference/ScriptableObject.CreateInstance.html) all offer a form taking a `string`. This should be interpreted as a type.

However, the generic forms of these methods, rather than the form taking a `Type`, should be preferred. Other methods which have a generic form and a form taking a type:  [`GetComponentInChildren`](https://docs.unity3d.com/ScriptReference/GameObject.GetComponentInChildren.html), [`GetComponentInParent`](https://docs.unity3d.com/ScriptReference/GameObject.GetComponentInParent.html), [`GetComponents`](https://docs.unity3d.com/ScriptReference/GameObject.GetComponents.html), [`GetComponentsInChildren`](https://docs.unity3d.com/ScriptReference/GameObject.GetComponentsInChildren.html), [`GetComponentsInParent`](https://docs.unity3d.com/ScriptReference/GameObject.GetComponentsInParent.html). These do not have an overload taking a string, however.

The ideal case would be that this plugin would resolve and add a reference to the string argument as if it were a type for the string overload of these methods, and if the string or type argument form are used, raise a warning with a quick-fix to use the generic version instead.

**Comment by citizenmatt** [comment]
This has been addressed as part of #835, among others. String literal arguments to these methods are now treated as references, meaning errors if they don't resolve, code completion (if completing with namespaces), ctrl+click navigation, find usages + rename. Other commits have added inspections to use the generic version instead of the string literals.
