### ISSUE TITLE
This plugin slow down unity's run

### ISSUE THREAD

**Issue by epluguo** [JetBrains/resharper-unity#1194]
Hi,I use rider to develop unity game. It is a great IDE.But I found it add a plugin to unity automatically. I know it is a bridge of rider and unity. But it is really slow when run the game in editor.

I found the `PluginEntryPoint` class use the  `[InitializeOnLoad]` attribute.
When I run the game in editor, It cost 490ms time.

![image](https://user-images.githubusercontent.com/6416516/57963439-ce7da580-7956-11e9-868b-ca3dddc71398.png)

![image](https://user-images.githubusercontent.com/6416516/57963466-10a6e700-7957-11e9-915b-8d6c6fb22a95.png)

**Comment by van800** [comment]
Duplicates https://github.com/JetBrains/resharper-unity/issues/728

**Comment by van800** [comment]
Please list Rider version, Unity version, OS.

**Comment by epluguo** [comment]
Unity 2017.4.3f1
windows7 sp1
Rider 2018.1

thx

**Comment by van800** [comment]
Please update Rider to recent version. I have improved initialization time
to 200 ms somewhere in 2018.3.x.
