### ISSUE TITLE
AssertionException chunk.Ptr > 0 with Rider 2019.1.1 and Unity

### ISSUE THREAD

**Issue by Dravere** [JetBrains/resharper-unity#1198]
I'm getting an AssertionException in the Unity console:

```
AssertionException: chunk.Ptr > 0
JetBrains.Diagnostics.Assertion.Fail (System.String message) (at <1d3a65e106e7443f8372eb6ad5d9c33d>:0)
JetBrains.Diagnostics.Assertion.Assert (System.Boolean condition, System.String message) (at <1d3a65e106e7443f8372eb6ad5d9c33d>:0)
JetBrains.Threading.ByteBufferAsyncProcessor.ThreadProc () (at <1d3a65e106e7443f8372eb6ad5d9c33d>:0)
JetBrains.Threading.ByteBufferAsyncProcessor.ThreadProcCatchAbort () (at <1d3a65e106e7443f8372eb6ad5d9c33d>:0)
System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Threading.ThreadHelper.ThreadStart () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
UnityEngine.UnhandledExceptionHandler:<RegisterUECatcher>m__0(Object, UnhandledExceptionEventArgs)
```

I'm working with Rider 2019.1.1. Initially used Unity 2018.3.2f1 and then upgraded to 2019.1.3f1. It happened in both Unity versions. Operating system is Ubuntu 18.04.2.

Not exactly sure what the problem is. Also can't really see any obvious problems. The only noticeable change with latest Rider since I got that error is the performance. It got painfully slow. But not sure if this is related?

**Comment by van800** [comment]
We had some problem on linux (https://github.com/JetBrains/resharper-unity/pull/1171), which degraded performance on linux.
Nightly Builds with fix are available in https://www.jetbrains.com/toolbox/app/

Exception `chunk.Ptr > 0` doesn't really affect anything, and is fixed in Rider 2019.2 https://youtrack.jetbrains.com/issue/RIDER-27320

**Comment by Dravere** [comment]
Thanks for the quick answer! Is it normal to also have Rider-Unity bugs tracked on JetBrains YouTrack? Didn't search there as I was expecting those bugs to be tracked here.

**Comment by van800** [comment]
Sometimes it is hard to distinguish. If you get exception, which can be automatically submitted to YT, it is completely fine to submit it.
