### ISSUE TITLE
Didn't show a compile error when string replace use the char is empty char like ''

### ISSUE THREAD

**Issue by id55503** [JetBrains/resharper-unity#1204]
If I write `"".Replace('a','');` rider did not show a compile error but it will show  **"Empty character literal"** error in unity3d edit console.

**Comment by van800** [comment]
Is there a stacktrace in the Console?

**Comment by id55503** [comment]
![image](https://user-images.githubusercontent.com/5811830/58446722-57a19300-8134-11e9-82d2-f7ed7628a66d.png)
There is a screenshot.

**Comment by citizenmatt** [comment]
Looks like an issue in the underlying ReSharper engine - [RSRP-474929](https://youtrack.jetbrains.com/issue/RSRP-474929). Rider will pick this up when that issue is fixed.
