### ISSUE TITLE
Rider Plugin Adding up to 30s Assembly Reload time

### ISSUE THREAD

**Issue by kwasak** [JetBrains/resharper-unity#1208]
HTML Created from Unity Profiler frame.

In my project, the Rider-Unity plugin is taking a whopping 30s to refresh code changes in Unity, during which time, I can't use Unity, as Unity becomes unresponsive.

[profiler.html.zip](https://github.com/JetBrains/resharper-unity/files/3237948/profiler.html.zip)

Disabling the plugin seems to solve the problem, however, this crucial Unity features.

Unity 2018.3.0f2
Rider 2019.1.1

**Comment by van800** [comment]
Please update Rider at least to 19.1.1.

**Comment by kwasak** [comment]
Sorry, I'm using Rider 2019.1.1 (May 1st build). The post has been edited to reflect that.

**Comment by van800** [comment]
Unity Editor.log may also be helpful. What OS is it?
How many projects do you have? I don't understand why SolutionSynchronizer.SyncProject() is called 102 times. There is a small amount of our code in the call-stack. We invoke `SyncVS.SyncSolution()` once and them it takes enormous amount of time.

**Comment by kwasak** [comment]
It seems Unity creates a separate C# project for every assembly definition.
In my project, I have 102 assembly definitions, resulting in `SyncProject()` being called 102 times.

I created an empty project in Unity 2018.3.0f2, with 5 assembly definitions, and as suspected, `SyncProject()` was called 5 times.

![AssemblyDefinitionComparison](https://user-images.githubusercontent.com/1744202/58730109-28e81e80-83b9-11e9-8638-433ec47faf82.png)

[UnityRiderPluginTest.zip](https://github.com/JetBrains/resharper-unity/files/3242646/UnityRiderPluginTest.zip)

**Comment by van800** [comment]
Still it seems weird that it takes so long. Maybe it was optimized in new Unity versions? As a workaround you can disable just Refresh from Rider in Rider settings. (Search for word refresh)

**Comment by van800** [comment]
I actually recall some conversation about such problem. I am almost sure it was fixed on Unity side.

**Comment by van800** [comment]
I have raised a question in our private communication channel with Unity team, this issue would be addressed.

**Comment by van800** [comment]
As a workaround you can disable just Refresh from Rider in Rider settings. (Search for word refresh)

**Comment by van800** [comment]
@kwasak Recently I was involved in ProjectGeneration speed improvements.
It was targeting Unity 2019.2+, where ProjectGeneration is moved to package.
Package version with improvements would 1.1.0, not yet published, but available as source
https://github.com/van800/com.unity.ide.rider
Please let me know if you want to try and have any questions.

**Comment by kwasak** [comment]
Thanks for keeping me in the loop! It's good to hear the issue will be addressed.
I'd like to try, speed improvements are welcomed. 

I'm currently away from my computer. From what I can see, I only need to copy the contents of the package folder, with the exclusion of the manifest file, is that correct?
I haven't seen a package installed this way in Unity before.

**Comment by SugoiDev** [comment]
You can clone the repository, switch to the tag you want to test (in that case, 1.1.0-perf), then use the package manager to add it as a local package.
![image](https://user-images.githubusercontent.com/7355630/59529218-cf064f00-8eb6-11e9-8d1e-a554a713c5fd.png)

Now you point to the package folder `Packages/com.unity.ide.rider/` and select the manifest.
The package manager will add it to your project.
To go back to using the registry version, just remove the package you added by click the "remove" button.

---

If you don't want to use the package manager, you can remove the com.unity.rider package using the package manager, then drop the folder `Packages/com.unity.ide.rider/Rider` into your project and it should work.
