### ISSUE TITLE
Incorrect Unreachable Code Inspection in Coroutine with yield

### ISSUE THREAD

**Issue by gjh33** [JetBrains/resharper-unity#1219]
The following snippet of code incorrectly identifies a section as unreachable, greying out the text in an annoying way. Disabling project wide is not a viable solution. Adding comments specific to rider in a project where not everyone is using it is also not a viable solution. Therefore requires fix.

```csharp
IEnumerator SomeCoroutine()
{
  bool toggleVar = false;
  while(true)
  {
    yield return new WaitForFixedUpdate();
    if (!toggleVar && SomeFunctionThatChangesOnFixedUpdate())
    {
      toggleVar = true;
    }
    if (toggleVar && !SomeFunctionThatChangesOnFixedUpdate())
    {
      // Unreachable Code According To Inspection
    }
  }
}
```

In the above example, it's unaware that a yield statement allows the value of SomeFunctionThatChangesOnFixedUpdate() to change. Therefore it assumes the only time toggleVar is true, is when SomeFunctionThatChangesOnFixedUpdate() is true. Therefore the second if statement will always be false, since either toggleVar is false OR SomeFunctionThatChangesOnFixedUpdate() is true, therefore it's negation is false. This is incorrect behaviour and greys out a large portion of code.

**Comment by krasnotsvetov** [comment]
Thank you for your feedback. What is your Rider version?
I could not reproduce it in 2019.1.2

**Comment by gjh33** [comment]
Hey, It seems to be happening somewhat at random. In one MonoBehaviour this broke as described, but I just pasted it into another and it worked. I'll see if I can narrow down exactly what's causing that and follow up.

**Comment by gjh33** [comment]
This example seems to work consistently:

```csharp
    IEnumerator SomeCoroutine()
    {
        WaitForFixedUpdate _waitForFixedUpdate = new WaitForFixedUpdate();
        bool toggleVar = false;
        while (true)
        {
            yield return _waitForFixedUpdate;
            if (!toggleVar && testBool is bool)
            {
                toggleVar = true;
            }

            if (toggleVar && !(testBool is bool))
            {
                toggleVar = false;
            }
        }
    }

    public object testBool { get; private set; }
```

**Comment by krasnotsvetov** [comment]
There is a bug in ReSharper engine. I have created issue : https://youtrack.jetbrains.com/issue/RSRP-475190
