### ISSUE TITLE
Show play/pause state of editor in IDE status bar

### ISSUE THREAD

**Issue by oxysoft** [JetBrains/resharper-unity#1227]
The resharper-unity plugin offers an action to switch between play/pause mode in the Editor and it is displayed as a toggle in the Search Everywhere Action popup (CTRL-SHIFT-A).

A common manipulation when I am debugging and hit a breakpoint is to pause the editor from within Rider, that way the game does not immediately resume when I resume execution in Rider, allowing me to inspect the state of the game or more carefully step through the next few frames.

However, the pause/play state is only shown in the Search Everywhere popup (as far as I can tell), which makes it less efficient to use, especially when mapping the action to a keyboard shortcut. A nice little indicator in the IDE status bar would be appreciated. Cheers!

**Comment by van800** [comment]
There is already one. In the right bottom part

**Comment by oxysoft** [comment]
Are you talking about this icon?

![image](https://user-images.githubusercontent.com/3945277/59460630-93538280-8ded-11e9-8a4c-b9d790886607.png)

It does reflect whether the editor is in edit or play mode which is good, but it doesn't seem to reflect pausing.

**Comment by van800** [comment]
Yes, it doesn't.
Would it be enough, if we add pausing state to it?

**Comment by oxysoft** [comment]
That'd be perfect, thanks.

**Comment by citizenmatt** [comment]
What about the play/pause icons in the toolbar at the top of the window?

<img width="459" alt="Screenshot 2019-06-17 at 12 33 08" src="https://user-images.githubusercontent.com/222659/59601527-25b09a80-90fc-11e9-971e-c5453f9aa2e0.png">

**Comment by van800** [comment]
Yeah, they are actually reflecting the state. @oxysoft do they work for you?

**Comment by oxysoft** [comment]
Hmm I'm guessing they must be working, however I have the toolbar disabled to save space since I don't really use it.

**Comment by oxysoft** [comment]
OK so just to confirm, the toolbar buttons do work fine. For now I will map the toolbar to a quickly accessible shortcut so that I can see the play/pause state at a glance when needed. In any case, alternating the inner 'play icon' of the status bar Unity indicator with pause as well would be a nice subtle addition too. 

In reality I also normally keep the status bar off and toggle it with a shortcut, so it comes out mostly the same regardless. I generally prefer the status bar over the toolbar since it provides me with a variety of potentially useful information, whereas the toolbar is simply an agglomeration of buttons that I either never use or access exclusively through the keyboard.

**Comment by citizenmatt** [comment]
Request for icon: [RIDER-31725](https://youtrack.jetbrains.com/issue/RIDER-31725)

**Comment by citizenmatt** [comment]
Fixed with #1301
