### ISSUE TITLE
[BUG] - UI Event Handlers are not detected when inside a prefab

### ISSUE THREAD

**Issue by rob8861** [JetBrains/resharper-unity#1229]
Rider seems to have an issue detecting event handlers when they are used inside a prefab. It works fine if the UI element is directly inside a scene, but if the event handler is used inside a prefab, Rider is unable to detect it, even if the prefab is used in a scene.

not sure if that's a known issue/limitation, but it would be nice if this can be added/fixed so event handlers can be detected in prefabs that are actively placed in a scene.

**Comment by krasnotsvetov** [comment]
Fixed in upcoming 2019.2 EAP

**Comment by rob8861** [comment]
@krasnotsvetov do you know if animation events not being detected by Rider will also be fixed in 2019.2? This is a similar issue where animation events (c# methods that are hooked to an animation event in the editor) are grayed out in Rider. It would be nice if Rider can scan the ymal file or whatever and detect if the animation event function is used/referenced.

thanks,
