### ISSUE TITLE
Unity looking for Rider installation in wrong location

### ISSUE THREAD

**Issue by myxibrium** [JetBrains/resharper-unity#1230]
I am getting the following log in Unity's console:

```
Unable to find Rider EditorPlugin C:\Program Files\JetBrains\JetBrains Rider 2018.1.2\plugins\rider-unity\EditorPlugin\JetBrains.Rider.Unity.Editor.Plugin.Full.Repacked.dll for Unity 
UnityEngine.Debug:Log(Object)
Packages.Rider.Editor.RiderInitializer:Initialize(String) (at Library/PackageCache/com.unity.ide.rider@1.0.8/Rider/Editor/RiderInitializer.cs:43)
Packages.Rider.Editor.RiderScriptEditor:.cctor() (at Library/PackageCache/com.unity.ide.rider@1.0.8/Rider/Editor/RiderScriptEditor.cs:26)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[])
```

I do NOT have 2018.1.2 install, instead I have 2019.1.2 (the latest version) so it appears as though it's looking in the wrong place for the installation. So the DLLs are not getting installed correctly.

So then I tried installing the DLLs myself manually, and got this error instead:

```
Please delete D:\GameDev\Transcendence\Assets\Plugins\Editor\JetBrains.Rider.Unity.Editor.Plugin.Full.Repacked.dll. Unity 2019.2+ loads it directly from Rider installation.
UnityEngine.Debug:LogError(Object)
Packages.Rider.Editor.RiderInitializer:Initialize(String) (at Library/PackageCache/com.unity.ide.rider@1.0.8/Rider/Editor/RiderInitializer.cs:15)
Packages.Rider.Editor.RiderScriptEditor:.cctor() (at Library/PackageCache/com.unity.ide.rider@1.0.8/Rider/Editor/RiderScriptEditor.cs:26)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[])
```

A frustrating user experience.

I'm using Unity 2019.3.0a5 on Windows 10 with Rider Editor 1.0.8

**Comment by van800** [comment]
Please check, what do you have in Unity Preferences - External Editor
![image](https://user-images.githubusercontent.com/1482681/59554851-e2dead80-8fa9-11e9-8e49-a8933dc16ff5.png)

**Comment by myxibrium** [comment]
I see what you're getting at and fixed the issue. Is it possible to have the plugin automatically check the next Rider installation if one is missing/uninstalled? Having it auto-remove from the dropdown would be nice too. I have a feeling that many developers will be upgrading their versions of Rider (especially after getting the "Please delete" error) and encounter this same confusing situation.

**Comment by van800** [comment]
Do I understand correctly that folder  C:\Program Files\JetBrains\JetBrains Rider 2018.1.2 doesn't exist on your environment?

**Comment by van800** [comment]
Issue addressed in Rider package. Hopefully would be out in version 1.1.0.

**Comment by van800** [comment]
You can try the fix, if you like from this branch https://github.com/van800/com.unity.ide.rider/tree/1.1.0-perf
Please follow instructions from this comment https://github.com/JetBrains/resharper-unity/issues/1208#issuecomment-502211659
