### ISSUE TITLE
Rider Inop in 2019.2b6?

### ISSUE THREAD

**Issue by jwvanderbeck** [JetBrains/resharper-unity#1233]
Rider version is latest as installed by Toolbox. 

JetBrains Rider 2019.1.2
Build #RD-191.7141.355, built on June 4, 2019

Apologies if this has been reported, but I scanned the first few pages of issues and didn't see it which kind of surprised me.

I installed Unity 2019.2b6 from the Unity Hub, and created a new project from the HDRP template.  When I go to Preferences -> External Tools or Preferences -> Rider, the preferences pane is blank and the log is spammed with Rider errors.

Manually loading the project in Rider, which in the past would auto install the Rider plugin also does not seem to do so anymore. 

There are a lot of console errors and they dont' stop, so I'm not sure which ones are the right ones to post and which are knock ons. 

```
NullReferenceException: Object reference not set to an instance of an object
Packages.Rider.Editor.EditorPluginInterop.InitEntryPoint () (at <072369e179f6469db1efdb207452957c>:0)
Packages.Rider.Editor.RiderInitializer.Initialize (System.String editorPath) (at <072369e179f6469db1efdb207452957c>:0)
Packages.Rider.Editor.RiderScriptEditor..cctor () (at <072369e179f6469db1efdb207452957c>:0)
Rethrow as TypeInitializationException: The type initializer for 'Packages.Rider.Editor.RiderScriptEditor' threw an exception.
Packages.Rider.Editor.PluginSettings+<>c.<RiderPreferencesItem>b__35_0 (System.String searchContext) (at <072369e179f6469db1efdb207452957c>:0)
UnityEditor.SettingsProvider.OnGUI (System.String searchContext) (at C:/buildslave/unity/build/Editor/Mono/Settings/SettingsProvider.cs:103)
UnityEditor.SettingsWindow.DrawControls () (at C:/buildslave/unity/build/Editor/Mono/Settings/SettingsWindow.cs:322)
UnityEditor.SettingsWindow.DrawSettingsPanel () (at C:/buildslave/unity/build/Editor/Mono/Settings/SettingsWindow.cs:313)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:281)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Comment by van800** [comment]
1. Update Rider package to last available version
![image](https://user-images.githubusercontent.com/1482681/59900506-d5398580-93f8-11e9-920a-a0cde9c26cce.png)
2. Set Rider 2019.1.2 as External Editor in Unity.
![image](https://user-images.githubusercontent.com/1482681/59900648-34979580-93f9-11e9-9973-996816f4bb66.png)

If it would not help:
 - either wait for the next version would be 1.1.0, just last small things are currently preventing it from shipping. Should be out in couple of days.
 - or get package as source from my public mirror https://github.com/van800/com.unity.ide.rider/tree/1.1.0, use branch 1.1.0.

**Comment by van800** [comment]
For Unity 2019.1.2+ we now do not auto-install EditorPlugin. It is loaded by the package instead directly from Rider installation.

**Comment by jwvanderbeck** [comment]
As it was a freshly created project, all the packages are expected to be up to date.  

I verified this one just now to be sure though and it is indeed up to date.

**Comment by jwvanderbeck** [comment]
1.10 package from that repo works.  Thanks.  FYI on it though it still shows as version 1.0.8 in the json.

**Comment by Arakade** [comment]
Just installed Unity 2019.2.0f1 and am getting this same(?) error (below) on a newly created Unity 2D project.  I haven't even tried opening Rider.

When I open the project with Rider (2018.3.4 = latest non-beta from Toolbox AFAIK) it installs the plugin.  I then no longer see the errors but am instead told to delete the plugin!

Delete the plugin and the errors come back again!

```
NullReferenceException: Object reference not set to an instance of an object
Packages.Rider.Editor.EditorPluginInterop.InitEntryPoint () (at Library/PackageCache/com.unity.ide.rider@1.0.8/Rider/Editor/EditorPluginInterop.cs:88)
Packages.Rider.Editor.RiderInitializer.Initialize (System.String editorPath) (at Library/PackageCache/com.unity.ide.rider@1.0.8/Rider/Editor/RiderInitializer.cs:39)
Packages.Rider.Editor.RiderScriptEditor..cctor () (at Library/PackageCache/com.unity.ide.rider@1.0.8/Rider/Editor/RiderScriptEditor.cs:26)
Rethrow as TypeInitializationException: The type initializer for 'Packages.Rider.Editor.RiderScriptEditor' threw an exception.
UnityEditor.CodeEditorProjectSync.PostprocessSyncProject (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at C:/buildslave/unity/build/Editor/Mono/CodeEditor/CodeEditorProjectSync.cs:35)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:154)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Comment by van800** [comment]
2018.3.4 is far not the last release on toolbox. Package 1.1.0 is very close to being published. It is a shame that Unity released 2019.2 without it. I did many PRs to the package, but releasing the package is up to Unity team.

**Comment by Arakade** [comment]
> 2018.3.4 is far not the last release on toolbox. 

Um, are you saying 2018.3.4 isn't the latest non-beta version?

![Rider-2018-3-4](https://user-images.githubusercontent.com/1194266/62166091-cad3ab00-b317-11e9-89ad-17237975aeeb.png)

**Comment by Ennaxor** [comment]
Hey! 
I updated Rider to the 2018.3.5 version but it still doesn't work! Did you solve the issue?

**Comment by van800** [comment]
@Ennaxor Please use 2019.1.3 release or 2019.2 EAP.

**Comment by Ennaxor** [comment]
@van800 Updated Rider to 2019.1.3 and still not working.

![image](https://user-images.githubusercontent.com/7715594/62197163-a8757800-b37f-11e9-8584-109a2b05a3cd.png)

**Comment by van800** [comment]
@Ennaxor switch the external script editor in Unity.

**Comment by van800** [comment]
1. Open Packages\manifest.json and change `"com.unity.ide.rider": "1.0.8"` into `"com.unity.ide.rider": "1.0.2"`. 
2. Set Rider 2019.1.3 as External Editor
3. Change `manifest.json` back.

**Comment by Ennaxor** [comment]
Thanks a lot @van800  :D That fixed it!

**Comment by Arakade** [comment]
ditto.  Thx

**Comment by SiggiG** [comment]
Thanks that worked! :)

**Comment by van800** [comment]
Package v.1.1.0 is available. Solves the issue completely.
![image](https://user-images.githubusercontent.com/1482681/62518396-c46a9500-b829-11e9-8316-51a6a70c00e7.png)

**Comment by marnel-estrada** [comment]
Is it just me? I don't see 1.1.0 version in my Package Manager. We're using Unity 2019.2.

**Comment by van800** [comment]
@marnel-estrada Try to press "see all versions"? I tried even with new project 1.1.0 is still there.

**Comment by marnel-estrada** [comment]
Still can't see it.
![image](https://user-images.githubusercontent.com/10250284/62940101-63345a00-be05-11e9-85be-8ba3749f85b9.png)

**Comment by van800** [comment]
@marnel-estrada I can check on your OS and Unity version, please share those. Is it consistent on new empty project? You may also share manifest.json.

**Comment by marnel-estrada** [comment]
OS: Windows 10
Unity: 2019.2.0f1

Here's my manifest.json:
[manifest.zip](https://github.com/JetBrains/resharper-unity/files/3497779/manifest.zip)

**Comment by jwvanderbeck** [comment]
What happens if you just update your manifest by hand to point to 1.1.0?

**Comment by van800** [comment]
You are using staging packages gallery.

**Comment by van800** [comment]
Workaround would be either manually setting version to 1.1.0 in manifest.json or removing `"registry": "https://staging-packages.unity.com",` from manifest.json, installing v. 1.1.0 and adding registry back, if you need it.

**Comment by van800** [comment]
I  have got a comment from Unity team that staging gallery is deprecated and is going to be completely removed.

**Comment by marnel-estrada** [comment]
What should I use then? "https://packages.unity.com"?

**Comment by marnel-estrada** [comment]
> a

It says this:
![image](https://user-images.githubusercontent.com/10250284/63027882-4fa9f180-bee0-11e9-8be0-467b8d668a78.png)

**Comment by marnel-estrada** [comment]
Thanks for the help. I used "https://packages.unity.com" and it works now.

**Comment by van800** [comment]
Removing the line should be better.
