### ISSUE TITLE
Exception load projects

### ISSUE THREAD

**Issue by ijotus** [JetBrains/resharper-unity#1234]
Hi
Unity 2018.3.8
all projects loading fail
Project 'Assembly-CSharp-Editor-firstpass' load failed: Длина параметра "name" не может быть равна нулю.
Project 'Assembly-CSharp-Editor' load failed: Длина параметра "name" не может быть равна нулю.
...
etc

**Comment by van800** [comment]
Could you please show csproj content related to the error? Does it reproduce for any project or just one? Your OS?

**Comment by van800** [comment]
Solved in https://youtrack.jetbrains.com/issue/RIDER-29135
