### ISSUE TITLE
nowarn in csc.rsp doesn't work

### ISSUE THREAD

**Issue by sebas77** [JetBrains/resharper-unity#1239]
Rider should support the csc.rsp, but it's not working as shown in attachment, hence I may not have configured it correctly. Please advise.

Note: several  asmdefs are used 

![Capture](https://user-images.githubusercontent.com/945379/60360693-37cfea00-99d4-11e9-8b43-1c3ccdf1f262.PNG)

**Comment by van800** [comment]
1. NoWarn was never supported in Rider EditorPlugin
https://github.com/JetBrains/resharper-unity/blob/192/unity/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs#L305

2. And as far as I know is not supported in Unity project generation
https://github.com/van800/com.unity.ide.rider/blob/1.1.0/Packages/com.unity.ide.rider/Rider/Editor/ProjectGeneration.cs#L752

**Comment by sebas77** [comment]
Unity supports it in the sense that the warning disappears from the unity console.
sometime is useful to build with rider for convenience.

**Comment by van800** [comment]
This issue should be fixed in Unity `com.unity.ide.rider` package.
https://github.cds.internal.unity3d.com/unity/com.unity.ide.rider/issues/24
This link is here for reference, unfortunately the repo is currently not shown to external users.

**Comment by van800** [comment]
@sebas77 You may try to apply those changes manually on your package to see if it works in your case 
https://github.com/van800/com.unity.ide.rider/commit/1ae27bf11693c7fd2885160ff7f8e1850792d83e

**Comment by JurjenBiewenga** [comment]
It would be good to support extra analyzers and additional files as well. There's a whole bunch of arguments that you can use in the csc.rsp file, see [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/listed-by-category)

**Comment by van800** [comment]
Package 1.1.1 with fix gone public.

**Comment by van800** [comment]
@JurjenBiewenga I have added a request about `analyser` to Rider package in Unity. (https://github.cds.internal.unity3d.com/unity/com.unity.ide.rider/issues/48 I know it is unavailbale without permissions, but it will help tracking for me.)
Do I understand correctly, that instead of doing magic like https://github.com/vad710/UnityEngineAnalyzer/issues/27#issuecomment-399764272
We can support `analyser` in csc.rsp and that would be more predictable less hacky way? 
And it should provide similar results in both Unity and Rider?

**Comment by JurjenBiewenga** [comment]
Yes, if you implement it in the same way as [nowarn](https://github.com/van800/com.unity.ide.rider/blob/1ae27bf11693c7fd2885160ff7f8e1850792d83e/Packages/com.unity.ide.rider/Rider/Editor/ProjectGeneration.cs) then you wouldn't need your own postprocessor anymore that fixes the csproject. I'd be willing to make a proposal for which arguments to support.

**Comment by van800** [comment]
@JurjenBiewenga 
Yes, I am willing to do it the same way as nowarn.
But I am not satisfied with idea to put dll-s with analysers to the project and commit binaries to git. It is a shame we can't use nuget directly in Unity projects.  I try to think of some workaround for that. If you have any idea - share it with me.

**Comment by JurjenBiewenga** [comment]
It is less than ideal however I'm not sure there is a better solution, there is a nuget format that stores the included references in a separate file from the csproject. However that format is the old way of supporting nuget.
