### ISSUE TITLE
Error opening file *.cs___jb_tmp___

### ISSUE THREAD

**Issue by MeikelLP** [JetBrains/resharper-unity#1241]
In most cases when I save a `.cs` file Rider creates a `.cs___jb_tmp___` file (probably for backup / caching).

The problem here is that Unity tries to import this file and gives an error `The process cannot access the file because it is being used by another process`. 

This is not a breaking bug it it is very annoying because I always have to go to Unity and close this window so Unity can continue to compile my files.

![grafik](https://user-images.githubusercontent.com/11669846/60644226-b940d580-9e35-11e9-8e97-45b18a435fca.png)

This might be a windows specific problem.

**System**
* JetBrains Rider 2019.1.2 (#RD-191.7141.355)
* Windows 10 10.0
* Unity Support Plugin v2019.1.0.110
* Unity 2019.1.3f1

**Comment by citizenmatt** [comment]
When does this dialog show? Are you switching from Rider to Unity at the time?

One thing to try is unchecking the "use safe write" option in Preferences -> System Settings. This will save over the existing file, without making a temporary backup first. 

<img width="576" alt="Screenshot 2019-07-04 at 14 00 04" src="https://user-images.githubusercontent.com/222659/60668581-397e2f80-9e64-11e9-9102-c2601a7c781b.png">

**Comment by MeikelLP** [comment]
Doesn't matter "when" I go back to unity. As soon as I hit "Save" (CTRL + S) Unity makes this popup (if not already).

The workaround to disable "safe write" seems to work. What are the down sides here?

**Comment by citizenmatt** [comment]
I wouldn't expect Unity to refresh the asset database in the background while we're saving. @van800 could this be something to do with the refresh assets plugin action? Perhaps we're notifying before save is complete?

The "safe write" will save, delete the original and then rename - less chance of losing data in the event of a badly timed power cut. On the plus side, Rider's Local History takes frequent snapshots of files, so it's possible to restore previous versions (I once managed to destroy a folder I thought was in git and Local History saved the day)

**Comment by MeikelLP** [comment]
At least that sounds like my problem.

Thank you for clarification. I think I stay with the unsafe saving (at least until the issue is resolved).

**Comment by dogukankse** [comment]
Same error here but a little bit different.

This error occurs when I saved a script and switch back to Unity window.

**Comment by MeikelLP** [comment]
@dogukankse How is that different? At least I think that's the issue I described :D If not then this is exactly the issue I have.

**Comment by dogukankse** [comment]
@MeikelLP As I understand, when you saved your script Unity gives this error to you. 

In my case, this error only occurs when I back to Unity.

If you meant that is that same error, yes it is, as I understand but it occurs differently. If not, I'm sorry for the misunderstanding.

**Comment by MeikelLP** [comment]
Then I think your explanation is more clear. It happens when I save a script and switch back to unity.

**Comment by van800** [comment]
So far I was able to reproduce it on 19.1.3, but it doesn't reproduce on 19.2 EAP4.
@MeikelLP @dogukankse Could you please try one of 19.2 EAP builds?

**Comment by MeikelLP** [comment]
@van800 Not reproducible for me in EAP4.

**Comment by van800** [comment]
Thank you for following up.
