### ISSUE TITLE
Suppressed Performance Critical method still marked as Performance Critical

### ISSUE THREAD

**Issue by StefanJanssen95** [JetBrains/resharper-unity#1248]
When a certain method is marked as PerformanceCritical all functions calling that are also marked PerformanceCritical. during debugging I want to log information so I made a method that can do that for me. Unfortunately if I suppress the warning on that method, methods which call the suppressed method _are_ marked as PerformanceCritical.
This hides possible other PerformanceCritical parts since every method in my class will call the the PerformanceCritical method. 

I have the following piece of code
```CS
[SuppressMessage("ReSharper", "Unity.PerformanceCriticalCodeInvocation")]
private void LogInfo(string val)
{
    if (enableDebugLog)
        Debug.Log(val);
}
```

This seems to me like unwanted behavior since suppressing the warning should actually suppress the warning on the method itself.

**Comment by Domonion** [comment]
Hello @StefanJanssen95! From the next EAP, you will be able to add `// ReSharper disable Unity.PerformanceAnalysis`. This is available as QuickFix at any marked invocation, as code vision item, and Context Action at method declaration!
