### ISSUE TITLE
Focus Rider window when game hits breakpoint

### ISSUE THREAD

**Issue by sorencoder** [JetBrains/resharper-unity#1257]
Currently when the game hits a break point, everything suddenly stops and you have to manually switch to rider window.
It would be nice if rider window got focus automatically (Like the behavior of Visual Studio).

**Comment by van800** [comment]
Does Rider window blink in tray instead of focusing?

**Comment by sorencoder** [comment]
No. Rider icon in the taskbar doesn't blink. 
I notice that I have hit the breakpoint when editor freezes. There are no other signs.

**Comment by van800** [comment]
That's shame.
This must be this issue https://youtrack.jetbrains.com/issue/IDEA-198293 Please comment/vote it.
I can't say what is the origin. At my machine it blinks.
Unfortunately this can't be addressed in this plugin scope, so I am closing this request here.
