### ISSUE TITLE
Generating Unity methods like Start shouldn't clear IEnumerator

### ISSUE THREAD

**Issue by Baste-RainGames** [JetBrains/resharper-unity#1258]
If I write "IEnumerator Start", and then use Rider's completion to generate the Start method, it gets turned into a void method:

![image](https://user-images.githubusercontent.com/12800067/61869758-c30da400-aedc-11e9-9dd8-120b7e8f01b7.png)

Hit enter:

![image](https://user-images.githubusercontent.com/12800067/61869784-d02a9300-aedc-11e9-9a13-0cc72081ff2b.png)

Preferably, the generator would check the return type written, and keep it if it's a valid return type for the Start method.

**Comment by citizenmatt** [comment]
See also [RIDER-33453](https://youtrack.jetbrains.com/issue/RIDER-33453)
