### ISSUE TITLE
[UnitTest][DOTCOVER] Autostart unit tests don't target unity pipeline

### ISSUE THREAD

**Issue by Sylmerria** [JetBrains/resharper-unity#1261]
When I run Foo test manually, no problem
But when it's dotcover which run it, I have security exception.

For rider 19.1.3, dotcover 19.1.3 and unity 19.1.9f1
 
![Capture](https://user-images.githubusercontent.com/43926946/62007996-b5625380-b154-11e9-99de-74d530e1df4d.PNG)

**Comment by van800** [comment]
Please vote: https://youtrack.jetbrains.com/issue/DTRC-26262

**Comment by van800** [comment]
related https://youtrack.jetbrains.com/issue/PROF-760

**Comment by van800** [comment]
Please vote: https://youtrack.jetbrains.com/issue/RIDER-21064
