### ISSUE TITLE
Multi-line texts are not parsed correctly for prefab instances

### ISSUE THREAD

**Issue by Ciziu** [JetBrains/resharper-unity#1269]
Rider fails to properly parse Unity scenes and reports "Unexpected content" errors when parsing prefab instances, that contain multi-line text overrides.

Tested on Unity 2018.3.9 and Rider 2019.2 EAP6

![obraz](https://user-images.githubusercontent.com/2765921/62533809-db1fe480-b847-11e9-98e5-2a220266aee1.png)

Steps to reproduce:
1. Create a new scene.
2. Add a Text component (the UI one) to any GameObject.
3. Make this GameObject a prefab.
4. Change the value of the text for the instance on the scene, to a multi-line one.
5. Save the scene.
6. Rider should now report an error while parsing this scene.

I'll try to confirm soon, if the problem persists on Unity 2019.2.0.

**Comment by Ciziu** [comment]
I can confirm that problem occurs with Unity 2019.2.0, with the very same steps to reproduce.

**Comment by krasnotsvetov** [comment]
Hi!
This has been already fixed in 19.2 release which will be available soon
