### ISSUE TITLE
Pause the game instead of freezing the whole Unity Editor when rider hits breakpoint

### ISSUE THREAD

**Issue by mnarimani** [JetBrains/resharper-unity#1272]
I don't know the reasoning behind freezing the whole unity. But it's counter productive for me. 
When Rider hits the breakpoint, I cannot use the inspector to see the state of different objects. Which is very important in debugging.

My suggestion is that Rider should pause the game when it hits a breakpoint. This way I can still use the editor to evaluate the situation.

**Comment by SugoiDev** [comment]
I don't know if that's trivial to do because it's the same process. Moreover, you might be debugging editor code so you need to halt the editor to actually do any debugging/stepping.

I use it a lot when creating custom editors and inspectors, and when debugging Unity engine issues.

**Comment by mnarimani** [comment]
I think the correct way to solve this is to provide an option in `Languages & Frameworks/Unity Engine` section in settings to opt-in or opt-out this feature. 
Something like a checkbox that says `Pause the thread when a breakpoint is hit`. When the checkbox is checked, Rider should freeze the unity editor completely and when it's not checked, Rider should pause the game.

**Comment by van800** [comment]
This is not technically possible. 
Unfortunately debugger protocol doesn't allow to execute code like `EditorApplication.isPaused = true`.
You may only add it to your scripts  manually.

cc: @joncham

**Comment by mnarimani** [comment]
It's unfortunate that this is not possible.
Can Rider communicate to Rider plugin dll inside unity and call `EditorApplication.isPaused = true` through the plugin?

**Comment by van800** [comment]
When execution is stopped on brakepoint, we can't Pause.
If we just send async Pause signal without stopping the execution, it will be only applied later in future.

**Comment by mnarimani** [comment]
Alright. I will close this issue as it's not technically possible to pause the editor.
