### ISSUE TITLE
Rider does not recognize and compile new files

### ISSUE THREAD

**Issue by RealMSHB** [JetBrains/resharper-unity#1274]
When I create new files and open them in rider, it does not compile the code and does not suggest any thing when coding.

I searched for this problem and already done the solution that is suggested here:
https://github.com/JetBrains/resharper-unity/issues/799
The solution fixed the problem for the files that I made before. But I still have same problem for new files.

I'm using Unity 2019.2.0f1 and Rider 2019.1.3 on windows 10.

**Comment by van800** [comment]
Please check the Rider package version in Unity package manager. Try to update it to 1.1.0.
Make sure that External Editor in Unity points to your desired version of Rider.

**Comment by RealMSHB** [comment]
I didn't have Rider Editor package installed in package manager.
Installing it fixed the problem.

Thank you

**Comment by B4ttleCat** [comment]
Thanks, @van800. Worked perfectly for my imported project that wasn't created with Rider.
