### ISSUE TITLE
Support for Resharper 2019.2 

### ISSUE THREAD

**Issue by StephenHodgson** [JetBrains/resharper-unity#1277]
Release was yesterday, and now I'm missing one of my favorite tools <3

**Comment by brogan89** [comment]
Is this a stunt to make me use Rider? Because if it is, its probably going to work 😅

**Comment by SharlatanY** [comment]
I would really appreciate if JetBrains could line up their releases of R# and the extensions better (or work on extensions needing an update less frequently to work with new version of R#).
Or at least a rough time frame when we can expect one of their official extensions to work with the new version. I know, it often doesn't take long but sometimes it takes a few weeks and it would just be nice and highly appreciated to know when one can roughly expect the update :)

**Comment by citizenmatt** [comment]
It's being tested right now. Hopefully later today, or tomorrow.

**Comment by citizenmatt** [comment]
I've just uploaded it to the ReSharper plugin gallery, so it should be available as of now (give or take 10 or 20 minutes of caching). Check out the [release notes](https://github.com/JetBrains/resharper-unity/releases/tag/192-eap7-rtm-2019.2.0) for all changes (including Rider changes, as they're built from the same commit).

**Comment by StephenHodgson** [comment]
@citizenmatt you rock my socks off!

**Comment by SharlatanY** [comment]
@citizenmatt Thank you very much! :)

**Comment by brogan89** [comment]
Does anyone else have it yet? I still can't see it as an extension 😕 
![image](https://user-images.githubusercontent.com/8637789/63051879-27e37980-bf32-11e9-89bf-7abe5f63fe0f.png)

**Comment by brogan89** [comment]
works now :) thank you! 
![image](https://user-images.githubusercontent.com/8637789/63072813-ea0a4380-bf79-11e9-9cb2-4430378d0ab1.png)

**Comment by citizenmatt** [comment]
I thought caching was only supposed to be 10 minutes per layer. I didn't think we had that many layers :) 

But I'm glad it's working now, don't know why it took so long, it should have been much quicker than that.
