### ISSUE TITLE
Clear on Play doesn't work

### ISSUE THREAD

**Issue by robertocaldas** [JetBrains/resharper-unity#1281]
Hello @van800 
The feature to clear the log when entering play mode doesn't seem to be working.
Related to https://github.com/JetBrains/resharper-unity/issues/393
I'm using Rider 2019.2, Unity 2017.4.24 and macOS 10.14.6.

**Comment by van800** [comment]
Thank you for reporting, I will look into this.

**Comment by robertocaldas** [comment]
Hey, I'm just curious, what's the branch `net193`? Do things on it get into the next release? (I'm assuming no since the milestone for this is 2019.3, but its the default branch so it got me thinking)

**Comment by van800** [comment]
@robertocaldas This fix is already in 2019.3 EAP builds.
`net193` is release `2019.3`
