### ISSUE TITLE
Add Debug Usb Android To Rider IDE

### ISSUE THREAD

**Issue by AlbertMontagutCasero** [JetBrains/resharper-unity#1287]
Add to Attach to Run > Attach to unity Process... The game running process in android or ios device attached by USB, same as in Visual studio.

![imagen](https://user-images.githubusercontent.com/23361386/63047457-c7721f00-bed4-11e9-9aba-5c21f1349177.png)

![imagen](https://user-images.githubusercontent.com/23361386/63047509-e2dd2a00-bed4-11e9-94f4-e0e917a8620f.png)

**Comment by friuns2** [comment]
its possible if enter 127.0.0.1: and copy port from visual studio

**Comment by friuns2** [comment]
or you can get port number by typing in cmd adb forward --list

**Comment by literakl** [comment]
I need to debug Oculus Go app designed in Unity. I miss this feature in Rider.

**Comment by AlbertMontagutCasero** [comment]
> I need to debug Oculus Go app designed in Unity. I miss this feature in Rider.

I think that can be another issue.

**Comment by citizenmatt** [comment]
AIUI, Oculus Go is an Android app as far as Unity is concerned, right? So if Rider supports Android USB debugging, it should support Oculus Go. Is this correct?

**Comment by literakl** [comment]
Yes, it is Android based and Unity generates APK

st 8. 1. 2020 v 16:30 odesílatel Matt Ellis <notifications@github.com>
napsal:

**Comment by AlbertMontagutCasero** [comment]
Rider supports android USB debugging? My android device is plugged on to my computer. I Just generated an APK using unity with the Development Build, Script Debugging and Wait For Managed Debugger checkbox enabled as you can see.

![image](https://user-images.githubusercontent.com/23361386/71992710-25155800-3236-11ea-8a22-97a7e01db254.png)

I am currently working with rider 2019 3.1

As you can see my device is plugged on.
![image](https://user-images.githubusercontent.com/23361386/71992822-5726ba00-3236-11ea-8890-c14b3b89d0e3.png)

But when I go to the `Run → Attach to Unity Process...` only the editor is shown in the pop up.

![image](https://user-images.githubusercontent.com/23361386/71992957-96550b00-3236-11ea-9a24-21e047235d64.png)

My android device (Wi-Fi) is connected to the same network as it is the computer(wired)

What I am missing if Rider supports android USB debugging, same as Visual Studio?

**Comment by literakl** [comment]
https://youtrack.jetbrains.com/issue/RIDER-35382

**Comment by citizenmatt** [comment]
Rider currently only supports wifi debugging. The target device must be visible on the same network as the machine running Rider. USB debugging is not yet supported.

**Comment by AlbertMontagutCasero** [comment]
Ahhh, sorry I had misunderstood you! We will wait for the implementation! Really nice work!

**Comment by HnngKoos** [comment]
How's the feature coming along?

**Comment by citizenmatt** [comment]
It's in progress, and it should be part of Rider 2023.1

**Comment by fedek1324** [comment]
Install Android SDK to VS

**Comment by gerwalk** [comment]
@citizenmatt I'm using Rider 2023.3 (`Build #RD-232.10203.29, built on November 1, 2023`) and can't figure out how to debug Android via USB. Since this was marked completed back in February of this year for 2023.1, I should have access to this new capability, right? Is there documentation?

**Comment by citizenmatt** [comment]
@gerwalk Yes, you should have USB debugging support. There is some [documentation in the web help](https://www.jetbrains.com/help/rider/Debugging_Unity_Applications.html#debug_usb), but essentially, you should just have to connect your Android device, and use the _Attach to Unity Process_ action to show a dialog with all the different processes you can attach to. Rider will use the `adb` that you have configured in Unity to list running processes on connected devices, and it should list them in this dialog. You can select and double click, and it should attach and start debugging. If this isn't working, the best thing to do would be to use Help -> Submit a bug in Rider, which will create a bug report with attached logs, and I can take a look from that side of things.

**Comment by citizenmatt** [comment]
The text probably should be updated to include something about Android USB. I think this one needs to look at logs, please, so submitting a bug report would be the best option. It's possible it's ARM related, as I personally haven't tested it on Apple Silicon. Also, I'm assuming you have the Android build support modules installed into your Unity installation.
