### ISSUE TITLE
[Feature Request] Unity asserts support

### ISSUE THREAD

**Issue by Silentor** [JetBrains/resharper-unity#129]
Hello!

Unity engine lib has a couple of a poor-man Assert methods, see 
https://docs.unity3d.com/ScriptReference/Assertions.Assert.html
but Resharper doesnt know about it, and warns about code guarded by Unity asserts:

```
UnityEngine.Assertions.Assert.IsTrue(a != null);
a.SomeMethod();    // <- Possible null ref warning
```

Can you add support for Unity assertions? Sometimes I use them for very small projects, instead of 
`System.Diagnostics.Debug.Assert()` :)

**Comment by citizenmatt** [comment]
Oh, how did I miss those?! Good call, thanks.

**Comment by citizenmatt** [comment]
This is live in [1.7 release](https://github.com/JetBrains/resharper-unity/releases/tag/v1.7.0).
