### ISSUE TITLE
"Unable to do OpenFile to Rider from dll" warning when opening C# project in Unity

### ISSUE THREAD

**Issue by chmodseven** [JetBrains/resharper-unity#1290]
In Unity 2019.2.0f1 I have got Rider 192.5895.1069 as my External Script Editor in Preferences.  The "Rider Editor" package in Unity Package Manager is also present by default.  However when I go to Open C# Project from the Unity menu, I get the following warning in the console:

```
Unable to do OpenFile to Rider from dll, fallback to com.unity.ide.rider implementation.
UnityEngine.Debug:Log(Object)
Packages.Rider.Editor.EditorPluginInterop:OpenFileDllImplementation(String, Int32, Int32) (at Library/PackageCache/com.unity.ide.rider@1.0.8/Rider/Editor/EditorPluginInterop.cs:59)
Packages.Rider.Editor.RiderScriptEditor:OpenProject(String, Int32, Int32) (at Library/PackageCache/com.unity.ide.rider@1.0.8/Rider/Editor/RiderScriptEditor.cs:70)
UnityEditor.CodeEditorProjectSync:SyncAndOpenSolution()
```

The warning doesn't seem to cause any issues with using Rider once it opens, at least.

In case it helps: in older versions, I remember it used to create a Rider plugin under Plugins, but that doesn't seem to be happening any more.  Not sure if that's part of the issue or a change in the integration.

**Comment by van800** [comment]
Try to update Rider package in Unity to 1.1.0 or newer available version.

**Comment by chmodseven** [comment]
Ok thanks, that fixed it.  I was on the verified 1.0.8 before, and didn't see there was a later hidden 1.1.0 one under the foldout that wasn't being presented for update.
