### ISSUE TITLE
How to force Rider to copy its dlls in Plugins folder Unity 2019.2+

### ISSUE THREAD

**Issue by mnarimani** [JetBrains/resharper-unity#1295]
Recently Unity's Rider plugin that installs through Package Manager broke everything.
Unity doesn't open rider when I double click on a script.
I don't know why we can't have a nice development day with Unity anymore.
Is this possible to turn this new "feature" off and just copy dlls into Assets folder?

**Comment by van800** [comment]
Try to update Rider package to version 1.1.0.

**Comment by mnarimani** [comment]
I updated to 1.1.0 and it still doesn't work. It doesn't open rider for the first time.

**Comment by van800** [comment]
Is Rider specified as external editor in Unity?
![image](https://user-images.githubusercontent.com/1482681/63500065-701e1100-c4c9-11e9-838a-694125766bef.png)

If it is, could you please attach Editor.log from Unity?

**Comment by mnarimani** [comment]
Yes. Rider is specified as external editor.
[Editor.log](https://github.com/JetBrains/resharper-unity/files/3529586/Editor.log)

**Comment by van800** [comment]
There is an error in the log saying 
`Please delete Assets\Plugins\Jetbrains\Editor\JetBrains.Rider.Unity.Editor.Plugin.Repacked.dll. Unity 2019.2+ loads it directly from Rider installation.`
Have you done that?
We are aware it can be hard to spot it, we are thinking of a better approach on that. cc: @krasnotsvetov

**Comment by mnarimani** [comment]
Yes. I have done that. And it doesn't work with or without the dlls.

**Comment by van800** [comment]
I am sorry for the inconvenience.
Could you please set Rider EditorPlugin Verbose log, reproduce the issue and attach here?
![image](https://user-images.githubusercontent.com/1482681/63511900-b59b0800-c4e2-11e9-83c2-dd02a79f85e0.png)

**Comment by mnarimani** [comment]
I set the Logging Level to verbose. I tried to use the Open Log button and it didn't work. Also the plugin version is 0.0.0.0 in this window.
![Annotation 2019-08-22 180029](https://user-images.githubusercontent.com/30625116/63519202-c4e07c80-c507-11e9-8a1e-b1edd9cd2bc3.png)
But I found the log file anyway:
[2019-08-22T-18-04-16.log](https://github.com/JetBrains/resharper-unity/files/3530361/2019-08-22T-18-04-16.log)

**Comment by van800** [comment]
Do you see this icon in the status bar in Rider? 
![image](https://user-images.githubusercontent.com/1482681/63521399-a2923300-c4f6-11e9-9263-8a5100d4ecda.png)

You may also verify that Unity plugin in Rider is enabled
![image](https://user-images.githubusercontent.com/1482681/63521485-d2413b00-c4f6-11e9-82f4-09f6b53f634f.png)

**Comment by mnarimani** [comment]
Yes. I see that icon. And it's connected.

Please note that when Rider is already open, It doesn't have a problem with Unity. Unity only cannot open Rider for the first time.

I have Rider 2019.2.1. But I had this problem in 2019.2.0 too.

**Comment by van800** [comment]
Now I understand the scope of the problem, however I can't reproduce it. According to the log the following commandline is started
`"C:\Program Files\JetBrains\JetBrains Rider 2019.2.1\bin\rider64.exe" "C:\Dev\Unity\Fearow\Fearow.sln" --line -1 "C:\Dev\Unity\Fearow\Assets\DataContainer.cs"`
Does all the listed paths exist? Also what can break startup is invisible Rider process hanging in the background.

**Comment by mnarimani** [comment]
All the paths exist. How can I check if there is an invisible Rider process in the background?

**Comment by van800** [comment]
You may use ProcessExplorer or just reboot and try again.

**Comment by van800** [comment]
Normally executing this line from console should open Rider with solution and file. Does it happen?

**Comment by van800** [comment]
@mnarimani any update on this?

**Comment by mnarimani** [comment]
I took the brutal way to fix this problem and it worked for me. 
I uninstalled every Unity and Rider version (Including Unity Hub), then deleted every cache or setting file that Rider and Unity had (in User's home folder, ProgramData and AppData). I also deleted Library folder of the project. Then reinstalled everything again. 
I will close this. If somebody else has this problem reopen it again.

**Comment by van800** [comment]
Oh, wow, so sorry for that, but glad that works now.
