### ISSUE TITLE
OnGUI method marked as unused and named inconsistently

### ISSUE THREAD

**Issue by StefanoFiumara** [JetBrains/resharper-unity#13]
In Unity, ```OnGUI``` is a function that is called by the editor to render a user interface, either in game or (more importantly) when writing editor extensions.

Resharper marks this method has having inconsistent naming as the suggested name is ```OnGui```, obviously this would break the functionality of the method. Resharper should recognize it as a built in Unity function and ignore the naming inconsistencies.

Resharper also marks this method as unused when leaving out the ```[UsedImplicitly]``` attribute, even though it is being called by the engine.

![unity on gui](https://cloud.githubusercontent.com/assets/2746784/11755753/26cd3d5a-a01a-11e5-8ee3-33836fbd4a36.PNG)

Thank you for your continued support on this extension, it has helped me tremendously!

**Comment by citizenmatt** [comment]
What version are you using? The latest is 1.2.0, which has support for disabling naming inspections on `MonoBehaviour` classes, and it does understand about `OnGUI`, too. Go to ReSharper &rarr; Extension Manager and look for updates.

**Comment by StefanoFiumara** [comment]
I am on the latest version:
![unity on gui](https://cloud.githubusercontent.com/assets/2746784/11756749/d4250b34-a021-11e5-975b-abaafa304190.PNG)

I think the issue here is that this script is an extension I'm writing for the editor of type ```EditorWindow``` which inherits from ```ScriptableObject```, not ```MonoBehavior```

**Comment by citizenmatt** [comment]
Yep, that's the reason. We currently only handle `MonoBehaviour` classes. Do you know if there's a list of the classes you can derive from, and the messages they can receive? So there's `EditorWindow`, but I don't know what else there is...

**Comment by StefanoFiumara** [comment]
well this is my first time doing editor scripting so I'm not too familiar with all that is available.

[EditorWindow](http://docs.unity3d.com/ScriptReference/ScriptableObject.html) has several events you can capture, and [ScriptableObject](http://docs.unity3d.com/ScriptReference/ScriptableObject.html) has a couple as well.

Property Drawers are something I've not messed with just yet, but they also fire OnGUI events, if I'm not mistaken.

**Comment by TarasOsiris** [comment]
Yes, exactly EditorWindow and ScriptableObject should be included. As well as [ScriptableWizard](http://docs.unity3d.com/412/Documentation/ScriptReference/ScriptableWizard.html) - also has several specific methods (check link in "Messages Sent" section). Will write more if come across anything else.

**Comment by citizenmatt** [comment]
Fixed in bd67def92fdc0bf9f302e31e5a0efcae1cadaed4
