### ISSUE TITLE
Create serialized field option shown when the missing symbol represents a method

### ISSUE THREAD

**Issue by SirIntruder** [JetBrains/resharper-unity#130]
I would often start writing something like:
`var foo = SomeNewMethod(x, y)`
and then use resharper to create that new method. Now, "Create serialized field" is default action for SomeNewMethod, and it is pretty annoying when I accidentally create weird serialized fields like that.
Problem could be solved if such method symbols can be detected (and hide this option for them), or if at least this option is no longer the default one.

**Comment by citizenmatt** [comment]
Yep, agreed. This has already been fixed with #124. Please update to 1.6.2 of the plugin, it should fix this.

**Comment by SirIntruder** [comment]
Thanks Matt, greatly appreciated! Sorry for the nudge, will update now
