### ISSUE TITLE
Feature Request: Packages Assembly Symbols

### ISSUE THREAD

**Issue by bklooster** [JetBrains/resharper-unity#1305]
Maybe I missed this functionality, but would it be possible to do type/symbol resolution of the assemblies that are located in the package manager rather than going through the decompiler? 

When I do a command-click (Go to definition) it will open the decompiled version of the assembly for code that resides in the packages folder in libraries. I'd love to be able to have it go to the source code in the packages folder (Library/PackageCache) if possible so that we can see comments/implementation?  

Thanks!

**Comment by citizenmatt** [comment]
Make sure you have the "Use sources from symbol files" option checked in _Preferences | Tools | External Symbols_. Packages are compiled in to assemblies, but we can use the source information in the .pdb files to navigate to the actual source code.

**Comment by bklooster** [comment]
Interesting, I had that option checked, but it was still preferring to decompile the assembly. I tested it again though and it appears to be working. I'll close this request. Thanks!
