### ISSUE TITLE
Force Text Serialization warning despite already being set

### ISSUE THREAD

**Issue by Flavelius** [JetBrains/resharper-unity#1310]
As the title says, the warning to force text serialization in unity comes up even though it is already set to "Force Text", Unity 2019.2.3f1, Rider 2019.2.1, Unity plugin 2019.2.0.87 .

**Comment by van800** [comment]
Please switch it back and forth, it helps.
Unity sometimes doesn't respect its own setting and some asset files are still binary serialized. https://fogbugz.unity3d.com/default.asp?1181735_4pg49et6735pprql
