### ISSUE TITLE
Unity Usages seems to not work reliably

### ISSUE THREAD

**Issue by JashanChittesh** [JetBrains/resharper-unity#1313]
One of the really cool features in Rider is that it shows Unity usages in scenes and prefabs. In our project, this feature has already worked, and sometimes still works (or it did fairly recently), but it hasn't been very reliable. When it doesn't work, I double check that project wide analysis is active and has completed, and also navigate into the code from an active Unity scene - but the relevant public fields and methods simply show "No asset usages", and "Find Unity usages" also comes up empty, even though the properties are overridden / the methods used (e.g. in event handlers).

This is in Unity 2019.1.14f1 (could also be one of the minor Unity updates broke this - it definitely worked with one of the earlier 2019.1 versions but even then, not always).

<img width="390" alt="Capture_UnityRiderAllLooksGood" src="https://user-images.githubusercontent.com/986684/64528739-87526080-d309-11e9-9dbc-65643dc7f9fd.PNG">

**Comment by krasnotsvetov** [comment]
Hi!
Does it happen with all files? Or the problem only with a specific script?

**Comment by JashanChittesh** [comment]
When it happens, it seems to not work for any files (= doesn't work for all files).

**Comment by JashanChittesh** [comment]
Turns out for some reason, I've had **_Settings / Languages & Frameworks / Unity Engine / Parse Text Based Assets ..._** disabled. After re-enabling it, it worked again. Thanks @krasnotsvetov for helping with that.

I also noticed that this could probably break when disabling the Unity related metrics in **_Editor / Code Vision_**.
