### ISSUE TITLE
Does not seem to work at all in VS 2015 & ReSharper 2016.1.

### ISSUE THREAD

**Issue by gazialankus** [JetBrains/resharper-unity#132]
Hello, 

I have: 
Visual Studio Community 2015 (14.0.25425.01 Update 3) 
ReSharper Ultimate 2016.1.2

I installed ReSharper Unity Support:
![image](https://cloud.githubusercontent.com/assets/412997/24752431/75050948-1ad6-11e7-8f2e-17e43999fbd3.png)

However, I don't see any of the features listed in the [readme](https://github.com/JetBrains/resharper-unity/blob/master/readme.md) here.

For example, no color underlining: 
![image](https://cloud.githubusercontent.com/assets/412997/24752471/9d441e30-1ad6-11e7-82c3-ae426585c085.png)

It's like I never installed Resharper Unity Support, really. 

How can I start troubleshooting this situation?

**Comment by citizenmatt** [comment]
That's an old version - 1.2.1, which doesn't support all of the features. 1.2.1 is the last version that supports ReSharper 2016.1. You'll need to update your ReSharper to get the latest features, which you can do as long as you have a valid subscription.

**Comment by gazialankus** [comment]
Yes, upgrading ReSharper underlined that UnityEngine.Color.red. Thank you:)
