### ISSUE TITLE
Code Inspections for Physics2D.LinecastAll will not work, and corresponding method may be not correct.

### ISSUE THREAD

**Issue by RyotaMurohoshi** [JetBrains/resharper-unity#1324]
According to [Avoid using allocating versions of Physics Raycast functions](https://github.com/JetBrains/resharper-unity/wiki/Avoid-using-allocating-versions-of-Physics-Raycast-functions), there are some `code inspections` for Physics and Physics2D.
For example, the `code inspections` suggests converting from `Physics2D.BoxCastAll` to `Physics2D.BoxCastNonAlloc`.

According to [Avoid using allocating versions of Physics Raycast functions](https://github.com/JetBrains/resharper-unity/wiki/Avoid-using-allocating-versions-of-Physics-Raycast-functions), there is a code inspections from `Physics2D.LinecastAl` to `Physics2D.CapsuleCastNonAlloc`
But this code inspections will not work.

And, at https://docs.unity3d.com/ScriptReference/Physics2D.LinecastAll.html , `Physics2D.LinecastAll` corresponds to `Physics2D.LinecastNonAlloc` not `Physics2D.CapsuleCastNonAlloc`.

At the code https://github.com/JetBrains/resharper-unity/blob/c39fc2ef84fbfe8d81e95e7f720da154be240638/resharper/resharper-unity/src/CSharp/Daemon/Stages/Analysis/PreferNonAllocApiAnalyzer.cs#L32, `LinecastAll` is corresponding to `CapsuleCastNonAlloc`
I expect this method mapping may be wrong.
This mismatch may be cause of `Physics2D.LinecastAll` will not work. There is arguments check in code.

**Comment by citizenmatt** [comment]
See also [RIDER-33443](https://youtrack.jetbrains.com/issue/RIDER-33443)

**Comment by RyotaMurohoshi** [comment]
https://youtrack.jetbrains.com/issue/RIDER-33443#focus=streamItem-27-3793110.0-0

> The issue is fixed and fix will be available in EAP5

Thank you! 👍

**Comment by RyotaMurohoshi** [comment]
related : https://github.com/JetBrains/resharper-unity/commit/a760939b96828c7dc7b3227bd7aec934a2c7e8a9
