### ISSUE TITLE
Avoid to automatically attach to Unity.exe, started in background for importing Assets

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#1328]
Upcoming feature in Unity that spawns instances of the Unity Editor in the background with some special command line arguments to ensure it imports files in the background. We're having some issues with the Debuggers as they attempt to attach to any of the Unity.exe instances that we spawn, and usually the debuggers connect to the wrong executable and we can't debug via automatically attaching.
Filtering out any Unity.exe process who is spawned by another Unity.exe is the way to go with this, such that when auto-connecting a managed Debugger would result in it connecting to the right process instead of a child process. However, it would still be good to show these processes when Manually attaching to an instance, so code on those instances can be debugged, and perhaps tagging them so they can be easily identified (i.e this is a subprocess).

https://unity.slack.com/archives/C9BJY3RM2/p1569401790017900
https://jetbrains.slack.com/archives/G4EUFJYDB/p1569308749009000

**Comment by citizenmatt** [comment]
Also ensure that child processes are correctly identified in _Attach to (local) process_
