### ISSUE TITLE
Rider doesn't detect usage in a scene

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#1331]
In the attached project script is attached to a prefab and prefab is used in OnClick of Button gameobject. In such case Rider doesn't detect the usage of method.
![image](https://user-images.githubusercontent.com/1482681/65662171-d1d71b00-e033-11e9-9193-9e4bace2f15c.png)

[New Unity Project (1).zip](https://github.com/JetBrains/resharper-unity/files/3656137/New.Unity.Project.1.zip)

**Comment by nick-morhun** [comment]
It also doesn't seem to work with nested prefabs

**Comment by krasnotsvetov** [comment]
>It also doesn't seem to work with nested prefabs
Nested prefabs are not related to this task, but it is not supported yet. We have plans to support them in the 2020 release
