### ISSUE TITLE
can't update to 1.1.1

### ISSUE THREAD

**Issue by sebas77** [JetBrains/resharper-unity#1336]
I get this error:

![image](https://user-images.githubusercontent.com/945379/65866321-8e9ae600-e36c-11e9-8e36-24bf108488f2.png)

**Comment by van800** [comment]
You should have the following:
```
“com.unity.test-framework”: “1.1.2",
“com.unity.ide.rider”: “1.1.1",
```
in `manifest.json`

**Comment by van800** [comment]
Package has a dependency in place https://github.com/van800/com.unity.ide.rider/blob/next/master/Packages/com.unity.ide.rider/package.json#L9
But Package Manager doesn't enforce it. It is a bug in Package Manager.
