### ISSUE TITLE
Check validity of virtual input mapings

### ISSUE THREAD

**Issue by CAD97** [JetBrains/resharper-unity#134]
This requires reading `InputManager.asset`, which could be binary or YAML. At the very least, we should scrape it when it's serialized as text. Any `m_Name` line is a valid virtual button/axis (duplicates may (and likely will) occur). I don't know the semantics of reading a Button as an Axis or visa versa, but I think it's valid.

All of these methods take a string which should match a virtual axis/button defined in the InputManager. Bonus points if it works with constants as well as literals: my current project has a `MagicConstants` class which holds all of the Unity bridge magic constants.

- [`GetAxis`](https://docs.unity3d.com/ScriptReference/Input.GetAxis.html)
- [`GetAxisRaw`](https://docs.unity3d.com/ScriptReference/Input.GetAxisRaw.html)
- [`GetButton`](https://docs.unity3d.com/ScriptReference/Input.GetButton.html)
- [`GetButtonDown`](https://docs.unity3d.com/ScriptReference/Input.GetButtonDown.html)
- [`GetButtonUp`](https://docs.unity3d.com/ScriptReference/Input.GetButtonUp.html)

Sister Issue: #123 for physical keys.

**Comment by citizenmatt** [comment]
Implemented as part of #1158
