### ISSUE TITLE
Errors in TestsCallback.cs on update to 1.1.1 (Unity 2019.2.7f2)

### ISSUE THREAD

**Issue by FWCorey** [JetBrains/resharper-unity#1345]
The plugin throws the following compile errors when it is updated to 1.1.1 from 1.1.0 in Unity 2019.2.7f2
![Rider Plugin Errors](https://user-images.githubusercontent.com/3747871/66279904-b99eb000-e8ff-11e9-8be3-5d8b50639222.jpg)

Library\PackageCache\com.unity.ide.rider@1.1.1\Rider\Editor\UnitTesting\TestsCallback.cs:
CS0122: 'ICallbacks' is inaccessible due to its protection level
CS0122: 'ITestResultAdaptor' is inaccessible due to its protection level
CS0122: 'ITestAdaptor' is inaccessible due to its protection level
CS0122: 'ITestResultAdaptor' is inaccessible due to its protection level
CS0122: 'TestStatus' is inaccessible due to its protection level

**Comment by van800** [comment]
Please update Test Framework package to 1.1.1+.

**Comment by van800** [comment]
The problem was also workarounded in Rider package 1.1.2, but it is not yet released.

**Comment by keH1** [comment]
> The problem was also workarounded in Rider package 1.1.2, but it is not yet released.

When will the package 1.1.2 release be? Becouse Test Framework package 1.1.1 not released yet too(

**Comment by van800** [comment]
@keH1 Do you mean `verified`? Why do you need `verified`? I see multiple releases of Test Framework 1.1.1, 1.1.2, 1.1.3, .. 1.1.5. Any of the would work.

There is also Rider package 1.1.3-preview, which doesn't require Test Framework at all.

Releasing package is totally under Unity control, we can't do much about it, unfortunately.
