### ISSUE TITLE
No EditorConfig properties for the Unity inspections?

### ISSUE THREAD

**Issue by DmitriyYukhanov** [JetBrains/resharper-unity#1353]
Hey,

Thank you for the great work on Unity integration!

Though it seems there are no properties for the .editorconfig specified anywhere for the corresponding unity-specific inspections.

Regular Rider \ Resharper inspections all have properties listed [here](https://www.jetbrains.com/help/rider/Reference__Code_Inspections_CSHARP.html#CodeStyleIssues), but I can't find similar list for the Unity-specific inspections.

It would be really nice to be able to override them from the editorconfig as well ^^

**Comment by citizenmatt** [comment]
It's not documented, but the names for the Unity inspections can be inferred. If you have a warning in code, alt+enter and suppress by comment. You'll get something like:

```
// ReSharper disable once Unity.ExplicitTagComparison
```

Take the `Unity.ExplicitTagComparison` and make it all lowercase, split at word breaks with `_` and replace `.` with `_` too. Then prepend `resharper_` and append `_highlighting`. You can then add this to the `.editorconfig` file:

```
resharper_unity_explicit_tag_comparison=hint
```

The value can be `error`, `warning`, `suggestion`, `hint` or `do_no_show`.

I'll get it documented as part of the wiki.

**Comment by DmitriyYukhanov** [comment]
Wow, so glad to hear it's possible!
Thank you @citizenmatt ^^
