### ISSUE TITLE
All of a sudden Rider is trying to install the old plugin

### ISSUE THREAD

**Issue by jwvanderbeck** [JetBrains/resharper-unity#1358]
I'm confused by this.  I've changed nothing.  Same version of Rider and same version of Unity that I've been using in this new project for several weeks, but all of a sudden when the project is opened in Rider, Rider installs the old plugin that used to be used before Unity added first party support in the package.  Which then causes errors because I have that package installed.

Actually come to think of it, I did recently update that Unity Package might that be related?

Rider 2019.2.2 and Unity 2019.2.6f1.  "Rider Editor" package version 1.1.2

**Comment by jwvanderbeck** [comment]
After removing the plugin manually and turning off the option to auto-add the plugin (which I didn't need to turn off before, which is the point of the ticket) I noticed an oddity.

My Editor code that contains Unit tests is no longer being properly parsed by Rider.  It was when the plugin was installed by Rider, but once I removed it, now it has only SOME syntax coloring and the method calls don't seem connected to the rest of my source.

**Comment by van800** [comment]
There is a known issue with detecting version of `preview` Rider package.
Fix backported to upcoming bugfix release 2019.2.3. Due around next week.
Give me more info about the UnitTesting issue. Could you please share a screenshot?
If you want to share it privately - use youtrack.jetbrains.com. Reference new issue here.
Thank you!

**Comment by jwvanderbeck** [comment]
Strangely once I started editing the unit test file, the coloring re-appeared so **shrug**

**Comment by van800** [comment]
Let us know if it reproduce.
