### ISSUE TITLE
ReSharper: Pressing `Attach to Unity` shows an empty select instance window

### ISSUE THREAD

**Issue by JurjenBiewenga** [JetBrains/resharper-unity#1360]
Attaching to Unity while the project in question is not open in Unity shows an empty `Select Unity instance` Windows. 
See https://i.imgur.com/JzpMxoZ.png

**Comment by van800** [comment]
Doesn't reproduce for me on Windows with Rider 2019.2.2.
Any special conditions for it to happen?

**Comment by JurjenBiewenga** [comment]
Oh sorry, this is happening with R#

**Comment by van800** [comment]
What behavior would you expect?

**Comment by JurjenBiewenga** [comment]
I would expect it to show the open Unity project, similar to what happens when you press attach debugger

**Comment by van800** [comment]
I think in VS Attaching debugger is VSTU functionality not Re#.
