### ISSUE TITLE
Navigate to GameObject connected to the log-message

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#1369]
Second parameter in Debug.Log() can be used to connect message with game-object.
Need to investigate, if it is passed further to EditorPlugin and to Rider and finally use it to navigate from log-message to that GameObject.

https://twitter.com/febucci/status/1184075446771695616

**Comment by citizenmatt** [comment]
Is this related to #1368?

**Comment by van800** [comment]
No.

**Comment by van800** [comment]
closed in favor of https://youtrack.jetbrains.com/issue/RIDER-48685
