### ISSUE TITLE
"Move to folder" refactoring doesn't move meta files

### ISSUE THREAD

**Issue by mnarimani** [JetBrains/resharper-unity#1370]
Moving classes using Rider's "Move to folder" refactoring option doesn't move meta file of that class.
That causes "missing script" error on game objects.

**Comment by van800** [comment]
Rider version? Unity version? Os?

**Comment by mnarimani** [comment]
Rider 2019.2.3
Unity 2019.2.3f1
Rider Plugin 1.1.0
Windows 10

**Comment by van800** [comment]
Unrelated to request, just want to let you know that
Rider Plugin 1.1.0 is not a good one.
Use at least 1.1.1 with `Test Framework` package 1.1.1.
Or 1.1.2-preview / 1.1.3-preview, both don't have requirement to have `Test Framework`.

I will try to reproduce the `Move to folder` request. Thank you.

**Comment by van800** [comment]
This issue doesn't reproduce for me. There must be something special in your case. Does it reproduce in simple boiler-plate project?

**Comment by van800** [comment]
Please provide more information.

**Comment by mnarimani** [comment]
Sorry I totally forgot about this.
I still can reproduce it in an empty project. Here is a video of this bug:
https://youtu.be/Zx5tGSNfhHY

**Comment by van800** [comment]
Reproduced. Thank you!
