### ISSUE TITLE
Everytime resharper self update I need to setup it again manually in unity

### ISSUE THREAD

**Issue by sebas77** [JetBrains/resharper-unity#1374]
I have to go to preferences -> external tools and copy and paste the new folder manually. Used to not do this, but it did with the last 2 updates.

**Comment by van800** [comment]
Unity version?

**Comment by sebas77** [comment]
2019.2.10 but I'd say the problem happens with all the 2019.2 cycle at
least

**Comment by van800** [comment]
It is expected to be fixed in Rider package 1.1.3.
It is available in preview package.
