### ISSUE TITLE
Default symbols and mistyping

### ISSUE THREAD

**Issue by dimmduh** [JetBrains/resharper-unity#1377]
I mistyped and spent 20 minutes to find logical bug.
Maybe you have aby idea how to prevent this, maybe highlighting wrong typing default symbols.

![image](https://user-images.githubusercontent.com/446814/67613957-db949f80-f7e6-11e9-976b-090ff2a685e2.png)

**Comment by van800** [comment]
This is something about general Rider functionality, not Unity plugin. So please resubmit it to https://youtrack.jetbrains.com.
Please correct me, if I got it wrong.
