### ISSUE TITLE
Do not suggest using foreach in Burst compiled jobs

### ISSUE THREAD

**Issue by UnknownSoldier1** [JetBrains/resharper-unity#1378]
Hello,

I've been having this issue that Rider keeps suggesting me to use features in Burst-compiled jobs that are unsupported. The best example is the suggestion to replace a for loop with foreach, which is unsupported by Burst. Another example would be the usage of Linq, which is also unsupported.

So far I've been dealing with this issue by simply adding the Resharper disable comments, but this is something that I think should not be necessary.

Cheers

**Comment by Lattyware** [comment]
Yeah. Ideally full support would include showing errors in burst compiled code where such features are used. Other examples:

* Showing errors when using `try/catch` or `using`.
* Showing errors when using instances of managed types.
* Showing errors when writing to static fields.

The full restrictions can be found at https://docs.unity3d.com/Packages/com.unity.burst@1.2/manual/index.html#cnet-language-support.

**Comment by krasnotsvetov** [comment]
Thank you for your feedback. We have big internal task to support Burst compiler

Please share any feature requst for Burst support here :)

**Comment by Domonion** [comment]
Hello @Lattyware and @UnknownSoldier1!
Thank you for your feedback, as you might have already seen we have added some support for the Burst compiler.  From the next EAP, there will be code vision that will show if the function is in the Burst context or not. 

Here is an example:
![java_CwdOZoSEyS](https://user-images.githubusercontent.com/12771085/96591681-2f4da200-12f0-11eb-8b6b-a6839a8f96bd.png)

Also, there is context action and quick fix to place the `BurstDiscard `attribute.
![burstCodeVision](https://user-images.githubusercontent.com/12771085/96591965-88b5d100-12f0-11eb-866e-6eb183ce6c60.png)
![burstQuickFix](https://user-images.githubusercontent.com/12771085/96591967-894e6780-12f0-11eb-8244-8098c5e0b9ed.png)

If you have further suggestions on what to support at Burst - feel free to post it at [YouTrack](https://youtrack.jetbrains.com/) or add here at repo as an issue.

**Comment by Domonion** [comment]
@Lattyware I created issues based on your suggestions, it would be great you would provide a code example to support for each suggestion. #1900 #1901

**Comment by Domonion** [comment]
https://github.com/JetBrains/resharper-unity/issues/2015 from now foreach is allowed in burst compiled code, closing issue
