### ISSUE TITLE
Avoid suggesting C# 8 language features

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#1379]
When Rider build tool is MSBuild 16, Rider starts to treat Unity projects as LangVersion =8.

**Comment by StephenHodgson** [comment]
I think it's okay to suggest whatever the Lang feature is targeted at.

**Comment by StephenHodgson** [comment]
I am curious to know when unity will support c#8

I believe there is an experimental upm package for it.

**Comment by van800** [comment]
https://forum.unity.com/threads/would-the-roslyn-compiler-compile-c-8-0-preview.598069/#post-3998851

**Comment by SugoiDev** [comment]
Did this fix land in EAP 2? I just noticed Rider suggesting the new switch syntax today on a Unity project.

**Comment by van800** [comment]
Main piece of it landed in EAP2, however it was not applied to Packages
projects.
In EAP3 with this fix
https://github.com/JetBrains/resharper-unity/pull/1389/files#diff-41377c16a04d119c03b8f64d54700e88R34
it should work also for packages.
