### ISSUE TITLE
Shaderlab support?

### ISSUE THREAD

**Issue by sebas77** [JetBrains/resharper-unity#1386]
hello,

I can see that shader labe higlight is supported, but I wonder if there could be something more, like at least being able to fetch the documentation of each hlsl method and, even more useful, the code where unity shader lab macros are declared.

**Comment by citizenmatt** [comment]
Not at the moment. ShaderLab support is really only for the ShaderLab format inside `.shader` files, and doesn't include good HLSL support. We are very much aware of this, and we do have a plan in progress to address this and improve/introduce proper HLSL support.
