### ISSUE TITLE
Unity crashes while viewing variable values in Rider debugger

### ISSUE THREAD

**Issue by dimmduh** [JetBrains/resharper-unity#1388]
It happens all time with me.
When stops on breakpoint and check unity components variable value, for example animator.

**Comment by van800** [comment]
I am sorry this is something, which we can't address in Unity plugin scope.
Please join this request. https://youtrack.jetbrains.com/issue/RIDER-34683
It would help if you provide an accurate steps to reproduce and mention Unity version, Rider version, OS.
Thank you!
