### ISSUE TITLE
Do not suggest null-coalescing compound assignment in Unity projects

### ISSUE THREAD

**Issue by callumtw** [JetBrains/resharper-unity#1391]
Hi, just updated to 2019.2 and was impressed by the suggestion to use null-coalescing compound assignments, which can simplify lazy-loaded properties in the following way:

`public Foo SomeProperty => _backingField ?? (_backingField = CreateBackingField());`

becomes

`public Foo SomeProperty => _backingField ??= CreateBackingField();`

However, recompilation in Unity will fail, with the following error being thrown:
error CS1525: Invalid expression term '='

I assume Unity's mono version doesn't understand this? 2019.2 .Net 4.x Mono backend.

It would be useful if Rider did not offer this suggestion in Unity projects.

**Comment by van800** [comment]
This is expected to be fixed in 2019.3 eap https://github.com/JetBrains/resharper-unity/issues/1379
