### ISSUE TITLE
Don't suggest null propagation

### ISSUE THREAD

**Issue by derkork** [JetBrains/resharper-unity#14]
![image](https://cloud.githubusercontent.com/assets/327257/11895520/c0c07516-a57f-11e5-9e9b-6f26b9f7cbe9.png)

Resharper suggested null propagation for an if statement, however this language construct is not supported by Unity.

**Comment by citizenmatt** [comment]
What version are you using? This should be fixed - 1.2 will spot a Unity project and set the language level to C# 5. Is this a Unity project, or a supporting project?

**Comment by derkork** [comment]
I am using 1.0. The extension manager doesn't seem to know about a version 1.2 being available.

![image](https://cloud.githubusercontent.com/assets/327257/11895836/0fe78e48-a582-11e5-930d-0a54b67a76dd.png)

**Comment by citizenmatt** [comment]
Ah, 1.1 and higher are for ReSharper 10 only, I'm afraid.

**Comment by derkork** [comment]
Ok, updating to Resharper 10.

**Comment by citizenmatt** [comment]
Closing. Please reopen if it's still an issue.
