### ISSUE TITLE
After completing the statement, the cursor should be ready to write new expression

### ISSUE THREAD

**Issue by furkankurt1** [JetBrains/resharper-unity#1400]
![1](https://user-images.githubusercontent.com/54959713/68675290-a028fd80-0568-11ea-8513-8c7db9bcae7a.png)
![2](https://user-images.githubusercontent.com/54959713/68675291-a028fd80-0568-11ea-93f4-d157934facd2.PNG)

There are two pictures attached. After being complete the statement automatically, the cursor should be ready to write a new expression. but cursor sticks between"d" the letter and ] symbol.
Therefore we use the right arrow key on the keyboard,
that's one small step for man one giant leap for mankind :)

**Comment by oxysoft** [comment]
This would be _very_ annoying if the user wishes to add more attributes. What you can do is create a live template which creates this attribute for you along with the brackets. If you make the token short enough you can invoke it very quickly, for example `sf<TAB>`.

**Comment by krasnotsvetov** [comment]
It is designed behaviour. @oxysoft is right here :)
