### ISSUE TITLE
Add support for .asmref files

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#1406]
Unity 2019.2 added `.asmref` files - Assembly Definition References Files. 

From the [release notes to 2019.2.0a6](https://unity3d.com/unity/alpha/2019.2.0a6):

> Scripting: Added support for Assembly Definition Reference Files (asmref). These allow for adding additional source code directories to an existing Assembly Definition File (asmdef).

There doesn't seem to be [much documentation](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html):

> You can use Assembly Definition Reference Assets to add additional folders to an existing Assembly Definition asset.

Add support, e.g. syntax highlighting, JSON schema, and whatever else is needed. Also look at how this affects showing the project name in the Unity Explorer tree view (#1398)

**Comment by SugoiDev** [comment]
As requested, this is a sample asmref file. For now, they are incredibly simple:
Here's the editor
![image](https://user-images.githubusercontent.com/7355630/68825688-c68a8e00-0679-11ea-807b-7554ded4163f.png)

There file content is the following

1. When not using GUID
```
{
    "reference": "Vendor"
}
```


2. When using GUID
```
{
    "reference": "GUID:679b1ad5ea99ee144828e78799109596"
}
```

**Comment by CanBaycay** [comment]
I would really love to see .asmref support happening in Rider.

Unity.Mathematics library is full of partial classes that makes it really easy to be extensible just by putting an Assembly Definition Reference inside an external folder. Seems like Unity is happy with that approach but Rider goes crazy with asmref being around and does not even see the symbols in original asmdef for some reason.

For starters, at least just a basic support to prevent these errors would be great.

Here is a simple example project:

https://gitlab.com/canbaycay/RiderAsmrefSupportExample

**Comment by SugoiDev** [comment]
Oh? I thought it worked fine with asmrefs, just didn't have proper support to create them, but it seems it's not working properly when being used with packages?

I use them extensively on my current project, and never noticed anything strange in Rider. But, I only use them for "Editor" folders. Never used them to extend a package. That's super neat and I hadn't thought about it at all. (thanks!)

**Comment by SugoiDev** [comment]
Or maybe Rider breaks when used with partial classes in particular?
I mean, the actual projects should have no knowledge of the "asmref" itself. They'll behave as if the files were included in them normally, from what I know.

Did you have trouble with using an asmref but not using a partial class? Just doing something with something "internal" on a package, for example.

I'll see if I can make time to do a quick test on this.

**Comment by van800** [comment]
@CanBaycay Sorry for delay. I have just downloaded your example, open with Unity 2019.3.0f5 with Rider package 1.2.1 and Rider 2019.3.3 and it is all green. You may try to build your solution in Rider, and if it builds, but Rider is still showing errors - then try the last resort `File`->`Invalidate caches and Restart`.

**Comment by diomich** [comment]
@van800 I have the same issue with both my project and sample project mentioned above. Rider just does not see the original assembly. Anyway, Unity3d can compile this code without errors. Tried both build the solution and "invalidate caches and restart" Didn't help. 

Unity3d version: `2019.4.26f1`
Rider version: `2020.2.5`

**Comment by van800** [comment]
@diomich try to update Rider package to latest (3.0.7)

**Comment by citizenmatt** [comment]
I'm going to reopen this. We don't need to do anything to support projects that contain `.asmref` - the project files are correctly generated, etc. But we also don't provide syntax highlighting or any support for the `references` node (completion, navigation, find usages, etc.)

**Comment by citizenmatt** [comment]
We should also look at what happens with non-user code in projects generated from `.asmref` files. For example, if I want to extend `Unity.Mathematics` with a `.asmref`, then the generated project will include my user code, and also the non-user code from the Unity Mathematics package. This non-user code should be treated as read only, not analysed, etc.

**Comment by citizenmatt** [comment]
Closing this. #2252 adds support for `.asmref` files - syntax highlighting, JSON schema validation + completion, completion for the `reference` node, ctrl+click navigation and Find Usages support for the reference, GUID reference tooltip and inlay, and the reference will be updated when an assembly definition is renamed.
