### ISSUE TITLE
loss of precision for `Equals(object)`

### ISSUE THREAD

**Issue by StephenHodgson** [JetBrains/resharper-unity#1429]
I noticed I get a warning about the [possible loss of precision with floating point numbers](https://www.jetbrains.com/help/resharper/2019.2/CompareOfFloatsByEqualityOperator.html) for the `==` operator but not for `.Equals(object)`. Should the warning be raised for both?

**Comment by StephenHodgson** [comment]
bumpo

**Comment by citizenmatt** [comment]
Hey. This issue has slipped through the cracks, sorry. I suspect that yes, the warning should apply to both the equals operator `==` and `.Equals()`. This isn't something that the Unity plugin can fix, so I've raised an issue for the underlying ReSharper engine that provides the original inspection - [RSRP-479655](https://youtrack.jetbrains.com/issue/RSRP-479655)
