### ISSUE TITLE
Inspection for method signatures for InitializeOnLoad attributes

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#143]
Add inspections for:

* `[InitializeOnLoadMethod]` should be applied to a static void method with no arguments.
* `[InitializeOnLoad]` requires a static constructor.
* `[RuntimeInitializeOnLoadMethod]` requires a static method with no arguments.

**Comment by aybe** [comment]
Same as #19, it is incorrectly seen as unused:

![devenv_2020-06-16_16-33-01](https://user-images.githubusercontent.com/1537591/84788131-0f7b3a00-afef-11ea-9bf8-10b5728d53f2.png)

**Comment by citizenmatt** [comment]
Thanks. I've created a new issue to track this split. It's going to affect a bunch of things which are currently keyed off `UnityEditor`, but now live in `UnityEditor.CoreModules.dll`. These "unused method" examples will be fixed by updating the external annotations xml files, but if you see any others, can you add a comment to #1699, please?

**Comment by aybe** [comment]
OK
