### ISSUE TITLE
Cannot attach to Unity directly with F5 in 2019.3 EAP

### ISSUE THREAD

**Issue by oxysoft** [JetBrains/resharper-unity#1440]
Not sure if this should go on youtrack or if this is at all a bug or simple a configuration that I lost in the transition to 2019.3 EAP. I remember before in 2019.2, I could press F5 to attach to Unity without any popup. Now, it simply opens up the 'Debug...' menu. Now I have to take the long way with CTRL-SHIFT-A and search for 'Attach to Unity process...', then select the Unity process in the popup.

**Comment by van800** [comment]
May be related to https://youtrack.jetbrains.com/issue/RIDER-36256

**Comment by van800** [comment]
@oxysoft F5 executes current active run configuration.
Check if you have it as a shortcut here
![image](https://user-images.githubusercontent.com/1482681/70090008-964f6300-1619-11ea-812c-53a9c136a482.png)

**Comment by oxysoft** [comment]
Hey thanks! I changed the combo button to the left to "Attach to Unity Editor" and it works now.
