### ISSUE TITLE
Unity plugin disappeared

### ISSUE THREAD

**Issue by ssoher** [JetBrains/resharper-unity#1442]
In Unity 2018.4.13f1 LTS version Rider is set as the external editor, double clicking scripts open them in Rider but no Unity plugin is automatically installed and Rider doesn't recognize the solution as Unity solution. Worked fine in 2018.4.12 LTS version.

**Comment by van800** [comment]
Could you please attach logs available via Help->Compress logs and show in Finder.
If you want to submit them privately - use Help->Report a Bug. That would attach logs privately.

**Comment by ssoher** [comment]
Sure, attached

[rider-logs-20191208-152740.zip](https://github.com/JetBrains/resharper-unity/files/3936206/rider-logs-20191208-152740.zip)

**Comment by van800** [comment]
Please check the Unity support plugin presence. I don't see it in the logs.
![image](https://user-images.githubusercontent.com/1482681/70389416-41b43b00-19bf-11ea-89b8-6558db4dca6d.png)

**Comment by ssoher** [comment]
Interesting, it's not installed anymore and I can't find it in the marketplace

**Comment by van800** [comment]
You uninstall Rider and install again. Or use EAP of 2019.3 release, which we are approaching very soon.

**Comment by ssoher** [comment]
And what would be the reason for it to disappear without any change on my part, I only installed the new Unity version. Oh and also why does Unity Support plugin require CSS plugin?

**Comment by van800** [comment]
I have forwarded this question to the team. css plugin maybe required because we added USS support https://youtrack.jetbrains.com/issue/RIDER-20576. @citizenmatt  Is that right?

**Comment by citizenmatt** [comment]
Yes, that's exactly it. USS is treated as a custom implementation of CSS. AIUI, everything should be installed and bundled and so this dependency should effectively be "invisible". Where are you seeing this, and is it causing a problem?

**Comment by ssoher** [comment]
Reinstalling Rider 2019.2 fixed it, still not sure what caused the bundled plugin to become unavailable or visible in the list anymore.

@citizenmatt I'm seeing it in the EAP plugins screen below. It's not causing any problems, just disables the Unity plugin too. I'm not able to use EAP for production at the moment due to other errors I've reported here https://youtrack.jetbrains.com/issue/DEXP-495731 that appeared as soon as I open the solution in the EAP.

![image](https://user-images.githubusercontent.com/4283979/70389626-1d625980-19d3-11ea-9c52-01989c2e67e9.png)

**Comment by ssoher** [comment]
By the way, thank you guys for instant support over the weekend, I really appreciate it. Feel free to close this issue if "fixed by reinstall" is an acceptable solution for this particular problem.

**Comment by van800** [comment]
@ssoher Could you help us a bit with DEXP-495731? Does it really brake some functionality? What problem do you see apart of exception itself?

**Comment by ssoher** [comment]
Didn't do an extensive testing on this but a quick look at this reveals that I'm unable to add breakpoints. Also the Reformat Code action doesn't do anything. Navigate to Class doesn't list my own classes, navigate to symbol is the same.  This error is constantly raised by the way, when I clear all exceptions it pops right back up without me doing anything. Here are some more of the same error (seems like) which are all unique reports.

https://youtrack.jetbrains.com/issue/DEXP-495733
https://youtrack.jetbrains.com/issue/DEXP-495734
https://youtrack.jetbrains.com/issue/DEXP-495735
https://youtrack.jetbrains.com/issue/DEXP-495736

Let me know if you want me to test something specific.

**Comment by citizenmatt** [comment]
Thanks for the info re: CSS. I'll investigate if it's worth making the dependency optional. I didn't think of the scenario about it being disabled. For what it's worth, if you've disabled it for performance concerns, it might not actually make a difference - most of the plugin is registered declaratively/lazily, so nothing (or very little) is created or run until it's actually used.

**Comment by ssoher** [comment]
Thanks for clearing that up, it's just a habit of mine I guess, get rid of everything you don't use. It would be better if CSS wasn't a dependency for people who don't work on custom editors with USS but it's not a huge problem. But when the Unity plugin is disabled due to that, it would be nice if the warning was given in the Event Log, right now it's hard to figure out that one should check the plugins list to see if Rider disabled it without you knowing.

**Comment by van800** [comment]
@citizenmatt I have added a separate issue for css plugin dependency issue https://youtrack.jetbrains.com/issue/RIDER-36523

**Comment by van800** [comment]
@ssoher Could you please share with me settings file
%USERPROFILE%\.Rider2019.2\config\resharper-host\GlobalSettingsStorage.DotSettings
Thanks!

**Comment by ssoher** [comment]
Sure
[GlobalSettingsStorage.zip](https://github.com/JetBrains/resharper-unity/files/3939181/GlobalSettingsStorage.zip)

**Comment by van800** [comment]
Great, thanks. Issue to track https://youtrack.jetbrains.com/issue/RSRP-477301

**Comment by citizenmatt** [comment]
I'm closing this, as it appears everything in here is fixed.
