### ISSUE TITLE
Base type required annotations

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#145]
The following attributes should include `BaseTypeRequired` annotations:

Requires `UnityEngine.ScriptableObject`:
* `UnityEngine.CreateAssetMenuAttribute`
* `UnityEngine.PreferBinarySerialization`

Requires `UnityEngine.Component`:
* `UnityEngine.RequireComponent`

Requires `UnityEngine.MonoBehaviour`:
* `UnityEngine.DisallowMultipleComponent`
* `UnityEngine.ExecuteInEditMode`
* `UnityEngine.HelpURLAttribute`
* `UnityEngine.ImageEffectAllowedInSceneView`

Requires `UnityEngine.StateMachineBehaviour`:
* `UnityEngine.SharedBetweenAnimatorsAttribute`

Requires `UnityEditor.Editor`:
* `UnityEditor.CustomEditor`

Requires `UnityEditor.ObjectPreview`:
* `UnityEditor.CustomPreviewAttribute`

Requires `UnityEditor.GUIDrawer`:
* `UnityEditor.CustomPropertyDrawer`

**Comment by blueblob0** [comment]
UnityEngine.HelpURLAttribute can be used by either ScriptableObject or MonoBehaviour so this creates false negatives

**Comment by citizenmatt** [comment]
@blueblob0 Fixed for Rider 2020.3
