### ISSUE TITLE
Renaming assets through Rider doesn't rename meta file

### ISSUE THREAD

**Issue by mnarimani** [JetBrains/resharper-unity#1461]
When I edit an asset file's name through Rider's refactoring tools, it doesn't update the meta files. It causes Unity to lose the reference to that asset file.

Specifically, I had a scriptable object asset that I renamed through Unity Explorer in Rider (Ctrl + R + R, with VS keymap). After the rename, Unity lost all references to that asset.

**Comment by van800** [comment]
@mnarimani I really willing to fix this, but I can't reproduce.
Could you please check if meta file is renamed together with cs file and GUID in the meta file doesn't change?
![image](https://user-images.githubusercontent.com/1482681/70892110-cd921c80-1fe8-11ea-91a1-6cea5ff92207.png)

**Comment by van800** [comment]
I assume you use Rider 2019.3, right?

**Comment by van800** [comment]
Feel free to comment/reopen if it still reproduces

**Comment by sp-levente-lajtai** [comment]
I've just reproduced this on Rider 2021.2.3, I believe it has something to do with either long file names, or if types extending the renamed type also get renamed.

**Comment by citizenmatt** [comment]
Could you try upgrading Rider, please? We've just released Rider 2022.1, but meta file handling had a major update in Rider 2021.3

**Comment by sp-levente-lajtai** [comment]
I have upgraded Rider, and now it seems to work. Thank you for the quick response! :)
