### ISSUE TITLE
Missing preprocessor defines when opening solutions outside of Unity menu

### ISSUE THREAD

**Issue by cchrisman** [JetBrains/resharper-unity#147]
I haven't looked into the exact mechanism that's causing this, but I've noticed when I open one of my Unity project solutions from Rider directly instead of using the 'Open C# Project in Rider' menu provided by the Unity3dRider plugin, none of the C# preprocessor defines that are normally defined are present.  

Most commonly this is UNITY_EDITOR. Without this define, any references to the UnityEngine namespace are broken, resulting in a project with a lot of erroneous errors.  This results in a bit of a catch 22 when you open a project that *does* have legitimate errors, but the 'Open C# project in Rider' menu is not available, as Unity can't load the custom editor UI that provides the menu item.

I'm not sure whether the fix is most appropriate in resharper-unity or Unity3dRider, but it would be great if the somehow the last set of scripting defines present are preserved from when the solution was last opened from Unity.  The current behavior makes Rider a little unusable for any non-trivial Unity project unless you open it through the Unity menu, which isn't always convenient or even possible.

**Comment by IvanPashchenko** [comment]
@cchrisman could you please provide a repro .sln / .csproj where you encounter such a problem? 

Also,
> This results in a bit of a catch 22 when you open a project that does have legitimate errors, but the 'Open C# project in Rider' menu is not available, as Unity can't load the custom editor UI that provides the menu item.

This is planned to be fixed in EAP23: https://youtrack.jetbrains.com/issue/RIDER-6683.

**Comment by van800** [comment]
@cchrisman set of project defines is written by Unity to csproj and Unity3dRider is not interfering here, so if you still experience the described issue, please check the DefineConstants piece in the csproj and share with us.
