### ISSUE TITLE
Support for ReSharper 2019.3

### ISSUE THREAD

**Issue by jizc** [JetBrains/resharper-unity#1475]
Would love to see support for ReSharper 2019.3 soon 🙏

**Comment by XtroTheArctic** [comment]
Any estimate when it will happen?

**Comment by citizenmatt** [comment]
Should be in the next couple of days.

**Comment by jizc** [comment]
That's awesome, thank you @citizenmatt!

**Comment by citizenmatt** [comment]
New version uploaded, should be available now.

**Comment by XtroTheArctic** [comment]
It's been 8 hours. Still can't see it. :(

**Comment by jizc** [comment]
Yeah, it's still not available in the Extension Manager.

@XtroTheArctic you can download it directly from https://plugins.jetbrains.com/plugin/11629-unity-support, then add the folder where you save the file to the list of package sources in ReSharper options. It will then show up in the Extension Manager and you can install it.

**Comment by citizenmatt** [comment]
Not sure what happened with the feed, but looks like it's there now.

**Comment by XtroTheArctic** [comment]
Yes. Thank you.
