### ISSUE TITLE
Renaming a class in rider doesn't ignore skipped files

### ISSUE THREAD

**Issue by owenlacey** [JetBrains/resharper-unity#1492]
In my list of skipped files, I've got the pattern `*.Designer.cs`, see below.

![image](https://user-images.githubusercontent.com/17511715/72605172-2c162780-3914-11ea-8642-9c1da1cd0618.png)

However, on performing a rename, I would expect these files to be ignored, rather than the below

![image](https://user-images.githubusercontent.com/17511715/72604814-89f63f80-3913-11ea-9f56-8e110858d629.png)

I've got loads of migrations in my solution, and this can cause renaming a class to take up to 10 minutes, the fast majority of the time, these designer files are being processed.

Have I set up my excluded files correctly, or is there a valid reason why skipped files are processed during this action? Also happens in namespace refactors, move to folder, etc.
My rider version is 2019.1.1

**Comment by van800** [comment]
This issue is unrelated to Unity plugin, we can't address it here. Please update Rider to recent version, if the issue is still there, then use Help->Report a Bug in Rider. Thanks!
