### ISSUE TITLE
ScriptableObject.Reset method is suggested yet it doesn't exist.

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#1495]
This can get quite confusing as method will never be called.

https://docs.unity3d.com/ScriptReference/ScriptableObject.html

**Comment by citizenmatt** [comment]
It does get called, but it is also undocumented. We do state this in the UI - the generate methods dialog and popup documentation tooltip in the completion list both state that the method is undocumented.

You can find out a bit more in this [comment](https://github.com/JetBrains/resharper-unity/issues/79#issuecomment-266727851).

**Comment by aybe** [comment]
Thanks!
