### ISSUE TITLE
2 error occured when install on vs2017,but still work

### ISSUE THREAD

**Issue by waswerebeen** [JetBrains/resharper-unity#151]
## install error log:
00:51:44.128 |I| Runs                          | Installer started.
00:51:44.147 |I| Runs                          | Installer Deployment Packaging Identity : 6.0.20160818.172304
00:51:44.216 |I| Runs                          | Application created.
00:51:44.229 |I| Runs                          | WaveInfo: Wave: 6
00:51:44.329 |W| DevenvHostDiscovery           | Error reading the VS Lightweight Install list file at “C:\Users\kogod\AppData\Roaming\Visual Studio Setup\user.json”. 未将对象引用设置到对象的实例。

--- EXCEPTION #1/3 [NullReferenceException]
Message = 未将对象引用设置到对象的实例。
ExceptionPath = Root.InnerException.InnerException
ClassName = System.NullReferenceException
HResult = COR_E_NULLREFERENCE=E_POINTER=80004003
Source = JetBrains.Platform.Util
StackTraceString = “在 JetBrains.Util.DevEnv.DevenvHostDiscovery.GetInstalledVs15Lightweight_Build_2016_03_17(OnError onerror)”

--- Outer ---

--- EXCEPTION #2/3 [InvalidOperationException]
Message = “Error reading the VS Lightweight Install list file at “C:\Users\kogod\AppData\Roaming\Visual Studio Setup\user.json”.”
ExceptionPath = Root.InnerException
ClassName = System.InvalidOperationException
InnerException = “Exception #1 at Root.InnerException.InnerException”
HResult = COR_E_INVALIDOPERATION=80131509

--- Outer ---

--- EXCEPTION #3/3 [LoggerException]
Message = “Error reading the VS Lightweight Install list file at “C:\Users\kogod\AppData\Roaming\Visual Studio Setup\user.json”.”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #2 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  在 JetBrains.Util.OnError.<>c__DisplayClassd.<Warn>b__c(Exception ex)
     在 JetBrains.Util.DevEnv.DevenvHostDiscovery.GetInstalledVs15Lightweight_Build_2016_03_17(OnError onerror)
     在 JetBrains.Util.DevEnv.DevenvHostDiscovery.EnumInstalledVsCore(OnError onerror)
     在 JetBrains.Platform.Installer.Models.PackageSources.VisualStudioHostDiscovery.EnumInstalledVs()
     在 JetBrains.Platform.Installer.Models.PackageSources.VisualStudioHostDiscovery.Init()
     在 JetBrains.Platform.Installer.Runs.<>c__DisplayClass9.<Main>b__4()
     在 JetBrains.Util.ILoggerEx.Catch(ILogger thіs, Action F, ExceptionOrigin origin, LoggingLevel loggingLevel)
     在 JetBrains.Platform.Installer.Runs.Main()
”

**Comment by citizenmatt** [comment]
These errors aren't related to the Unity plugin. The installer here is older than the Visual Studio it's trying to install into. If you're using Visual Studio 2017, you should be using ReSharper 2017.1 as well.
