### ISSUE TITLE
First start Rider with commandline to open file and line - focus got stolen by Unity Explorer

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#1511]

**Comment by citizenmatt** [comment]
There's nothing specific in the Unity Explorer to make it take focus. I think this might be a Rider platform thing - Rider will always open Solution Explorer when you open a project. For Unity projects, Unity Explorer is the active view pane for the Solution Explorer tool window.

**Comment by van800** [comment]
Thank you. I just checked. You are right. When Unity plugin is disabled, then SolutionExplorer grabs focus instead.
