### ISSUE TITLE
[Rider package] "cs" should never disappear from SupportsExtension

### ISSUE THREAD

**Issue by kjyv** [JetBrains/resharper-unity#1519]
When Unity shows e.g. an exception in the Console log, clicking on the \<Path\>:\<Line\> links should open the file at that location in Rider as it does in Visual Studio and I think also as it did in Rider some time back. Also, it only opens the file most of the time, sometimes only changes focus to Rider but nothing else. When it does it never jumps to the line but stays on the current one.

Rider RD-193.6015.57, JRE 11.0.5 10-b520.30x64, Mac OS X(x86_64) v10.15.3, Unity: 2019.3.0f6

**Comment by van800** [comment]
Please copy here some messages (message and stacktrace) for which you double click

**Comment by kjyv** [comment]
Single click on e.g. this:
Doozy.Editor.Nody.Windows.NodyWindow.DrawViewGraph () (at Assets/Plugins/Doozy/Editor/Nody/Windows/NodyWindowDrawViewGraph.cs:76)
Opens on line 1 since I didn't open the file before.

**Comment by van800** [comment]
I just checked - it works as expected https://www.youtube.com/watch?v=oN8sBaqeMM8
You may double click on the message in the list (left column) or single click to path in the right pane.
If it still reproduces for you - please make a video demonstrating the problem.

**Comment by kjyv** [comment]
Sorry, this IS an issue, I just didn't have the time to make a video for you yet. It will simply show what I wrote to you above.

**Comment by kjyv** [comment]
Here is a video
[Bildschirmvideo aufnehmen 2020-02-24 um 14.27.38.mov.zip](https://github.com/JetBrains/resharper-unity/files/4244759/Bildschirmvideo.aufnehmen.2020-02-24.um.14.27.38.mov.zip)

**Comment by van800** [comment]
Weird. Works for me.
But lets check couple of things:
1. Update Rider package in Unity package manager to 1.2.1
2. Make sure you have Rider set as External Editor in Unity.
3. Check the warnings, is there any related to Rider package?

**Comment by kjyv** [comment]
1. and 2. were already done, no warnings relate to Rider. I can try to move all of Rider's config files out of the way and see if there is a difference... No, same behaviour.

**Comment by van800** [comment]
For further investigation you may navigate to `Packages.Rider.Editor.RiderScriptEditor.OpenProject` via Shift-Shift, put a brakepoint in there and click on a stacktrace.

**Comment by kjyv** [comment]
Ah, thats good. Now, the call to SupportsExtension(path) always returned null since the list of HandledExtensions did not include cs. Just adding it in Unity's Preferences seems so solve it. No Idea why it was not in there. Maybe a sanity check or just having a few default extensions would make sense?

**Comment by van800** [comment]
fixed https://github.com/van800/com.unity.ide.rider/blob/0a42b224e6191934884de084ccd59348742a2bc6/Packages/com.unity.ide.rider/Rider/Editor/RiderScriptEditor.cs#L218
