### ISSUE TITLE
ArgumentException: The specified path is not of a legal form (empty).

### ISSUE THREAD

**Issue by iridiculous** [JetBrains/resharper-unity#1524]
Hi there,

I am using Unity 2019.2.19f1 and use the rider plugin via Unity package manager. 
The following issue occurs with version 1.1.4 as well as 1.2.1

When entering playmode, we have an editor script that modifies `EditorBuildSettings.scenes`
and then calls `AssetDatabase.SaveAssets();` This however causes Rider to throw an exception.
This is the stacktrace we get: 
```
ArgumentException: The specified path is not of a legal form (empty).
System.IO.Path.InsecureGetFullPath (System.String path) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.IO.Path.GetFullPathInternal (System.String path) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.IO.FileInfo.Init (System.String fileName, System.Boolean checkHost) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.IO.FileInfo..ctor (System.String fileName) (at <567df3e0919241ba98db88bec4c6696f>:0)
(wrapper remoting-invoke-with-check) System.IO.FileInfo..ctor(string)
Packages.Rider.Editor.ProjectGeneration.ShouldSyncOnReimportedAsset (System.String asset) (at Library/PackageCache/com.unity.ide.rider@1.2.1/Rider/Editor/ProjectGeneration/ProjectGeneration.cs:264)
System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
Packages.Rider.Editor.ProjectGeneration.HasFilesBeenModified (System.Collections.Generic.IEnumerable`1[T] affectedFiles, System.Collections.Generic.IEnumerable`1[T] reimportedFiles) (at Library/PackageCache/com.unity.ide.rider@1.2.1/Rider/Editor/ProjectGeneration/ProjectGeneration.cs:259)
Packages.Rider.Editor.ProjectGeneration.SyncIfNeeded (System.Collections.Generic.IEnumerable`1[T] affectedFiles, System.Collections.Generic.IEnumerable`1[T] reimportedFiles) (at Library/PackageCache/com.unity.ide.rider@1.2.1/Rider/Editor/ProjectGeneration/ProjectGeneration.cs:248)
Packages.Rider.Editor.RiderScriptEditor.SyncIfNeeded (System.String[] addedFiles, System.String[] deletedFiles, System.String[] movedFiles, System.String[] movedFromFiles, System.String[] importedFiles) (at Library/PackageCache/com.unity.ide.rider@1.2.1/Rider/Editor/RiderScriptEditor.cs:251)
UnityEditor.CodeEditorProjectSync.PostprocessSyncProject (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at /Users/builduser/buildslave/unity/build/Editor/Mono/CodeEditor/CodeEditorProjectSync.cs:35)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:154)
UnityEditor.AssetDatabase:SaveAssets()

```

When setting a breakpoint, i can see that Unity is reporting a reimported file without any path/name so that seems to be the root of the problem. 

<img width="1425" alt="Screenshot 2020-02-13 at 14 22 57" src="https://user-images.githubusercontent.com/48098448/74440526-72589b00-4e6e-11ea-9825-e34a4c1cedb8.png">

**Comment by van800** [comment]
I would need your code, which makes issue happen.

Or if you have a bit of time, please try to add some validity check and make a PR, if succeed. https://github.com/van800/com.unity.ide.rider/tree/2.0.0
it is my public mirror of package code.

**Comment by iridiculous** [comment]
Done https://github.com/van800/com.unity.ide.rider/pull/6

**Comment by van800** [comment]
Thanks!

**Comment by van800** [comment]
Btw, `string.IsNullOrEmpty` does the same in a shorter manner.

**Comment by van800** [comment]
@iridiculous 

Could you please check if this would work in your case?
```
    static bool ShouldSyncOnReimportedAsset(string asset)
    {
      return k_ReimportSyncExtensions.Contains(Path.GetExtension(asset));
    }
```

**Comment by iridiculous** [comment]
@van800 absolutely, thats nicer! I just quickly added the fix in github online without proper editor and since i personally keep using IsNullOrEmpty as custom extension method, i kinda forgot you can call it from string type. Looks good & should fix the issue for me thanks :)

**Comment by van800** [comment]
Would be available in Rider package 2.0.0

**Comment by Vectorvision-Bodo** [comment]
Hello there!

In Unity 2019.2.21 with Rider 2.0.2 I am getting this error, too.

ArgumentException: The specified path is not of a legal form (empty).
System.IO.Path.InsecureGetFullPath (System.String path) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.IO.Path.GetFullPathInternal (System.String path) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.IO.FileInfo.Init (System.String fileName, System.Boolean checkHost) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.IO.FileInfo..ctor (System.String fileName) (at <567df3e0919241ba98db88bec4c6696f>:0)
(wrapper remoting-invoke-with-check) System.IO.FileInfo..ctor(string)
Packages.Rider.Editor.ProjectGeneration.ProjectGeneration+<>c.<HasFilesBeenModified>b__27_0 (System.String a) (at Library/PackageCache/com.unity.ide.rider@2.0.2/Rider/Editor/ProjectGeneration/ProjectGeneration.cs:131)
System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
Packages.Rider.Editor.ProjectGeneration.ProjectGeneration.HasFilesBeenModified (System.Collections.Generic.IEnumerable`1[T] affectedFiles, System.Collections.Generic.IEnumerable`1[T] reimportedFiles) (at Library/PackageCache/com.unity.ide.rider@2.0.2/Rider/Editor/ProjectGeneration/ProjectGeneration.cs:131)
Packages.Rider.Editor.ProjectGeneration.ProjectGeneration.SyncIfNeeded (System.Collections.Generic.IEnumerable`1[T] affectedFiles, System.Collections.Generic.IEnumerable`1[T] reimportedFiles) (at Library/PackageCache/com.unity.ide.rider@2.0.2/Rider/Editor/ProjectGeneration/ProjectGeneration.cs:119)
Packages.Rider.Editor.RiderScriptEditor.SyncIfNeeded (System.String[] addedFiles, System.String[] deletedFiles, System.String[] movedFiles, System.String[] movedFromFiles, System.String[] importedFiles) (at Library/PackageCache/com.unity.ide.rider@2.0.2/Rider/Editor/RiderScriptEditor.cs:266)
UnityEditor.CodeEditorProjectSync.PostprocessSyncProject (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at C:/buildslave/unity/build/Editor/Mono/CodeEditor/CodeEditorProjectSync.cs:35)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:154)
UnityEditor.AssetDatabase:SaveAssets()
EnviroCore:SaveProfile() (at Assets/3rdParty/Enviro - Sky and Weather/Core/Scripts/EnviroCore.cs:1326)
EnviroSkyEditor:OnInspectorGUI() (at Assets/3rdParty/Enviro - Sky and Weather/Enviro Standard/Scripts/Editor/EnviroSkyEditor.cs:481)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)

The response from the developer of the code is:

"It sounds like that it is not related to Enviro. Enviro just uses the AssetDatabase.SaveAssets() function"

Is there anything that can be done on the Rider side to fix this problem?

Best, Bodo

**Comment by van800** [comment]
@Vectorvision-Bodo Already fixed in https://github.com/van800/com.unity.ide.rider/tree/2.0.3

**Comment by Vectorvision-Bodo** [comment]
Thx @van800 after having overwritten the ProjectGeneration.cs file, the save function of Enviro is working again :)
