### ISSUE TITLE
Intellisense not working on Unity Event Functions with Visual Studio 2019 and ReSharper 2019.3.1

### ISSUE THREAD

**Issue by XardasLord** [JetBrains/resharper-unity#1527]
I'm unable to use the option to generate Unity Event Functions like `Awake`, `OnCollision`, etc.
But if I disable the resharper Intellisense option in `Extensions ->Resharper -> Options -> Intellisense -> General -> Visual Studio` then everything works as expected.

I'm using:
Visual Studio 2019 v16.4.5
ReSharper 2019.3.1
Unity3D 2019.3.1f1

**Comment by citizenmatt** [comment]
This is working on my machine. What version of the Unity plugin have you got installed? See _ReSharper -> Extension Manager_

**Comment by XardasLord** [comment]
@citizenmatt I have installed the version 2019.3.0.208 of Unity Support

**Comment by XardasLord** [comment]
@citizenmatt It's my bad, sorry for this :) I didn't have installed this extension in my Extension Manager at all... Now when I installed everything works like charm! 

Thank you :)

**Comment by citizenmatt** [comment]
Great, glad that it's working! 👍
