### ISSUE TITLE
Improve RiderPathLocator

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#1529]
1. Instead of localappdata
https://github.com/JetBrains/resharper-unity/blob/16721cf34e2ab0c3efbca642c8cbf60c4174812f/unity/EditorPlugin/RiderPathLocator.cs#L163
use toolbox registry key.
2. Support toolbox custom "Tools install location", by reading `.settings.json`

**Comment by DecoyRS** [comment]
1. Reg key for Toolbox - "HKEY_CURRENT_USER\Software\JetBrains\Toolbox"
2. `.settings.json` is in Toolbox root folder. It will have `install_location` field in root object, if user has set a custom folder for tools.
