### ISSUE TITLE
Duplicated "Generate Unity Event Functions"

### ISSUE THREAD

**Issue by real-mikhail** [JetBrains/resharper-unity#1537]
In context menu for a class there is a duplicated menu item (with different access keys). See screenshot:
![image](https://user-images.githubusercontent.com/3635408/75184271-2e5e7380-5755-11ea-8bf2-ebeb06d73ef9.png)

VS 2017, R# 2019.3.3, Unity 2019.3.2

**Comment by citizenmatt** [comment]
Actually not a R# specific problem. Also happens if "show gutter icons" is set to "always" in Rider.
