### ISSUE TITLE
Different Unity event functions have different highlighting and there is no way to configure it

### ISSUE THREAD

**Issue by real-mikhail** [JetBrains/resharper-unity#1539]
Look at the screenshot:
![image](https://user-images.githubusercontent.com/3635408/75252964-b9d81300-57ee-11ea-900f-efef41c9cb36.png)

One of these functions have (expected) white font's colour while others are blue. And I can't seem to find a way to change it:
![image](https://user-images.githubusercontent.com/3635408/75253218-28b56c00-57ef-11ea-95f0-f7d88b7100b8.png)

**Comment by citizenmatt** [comment]
The blue items should be "ReSharper Unity Implicitly Used Identifier". The question is, why is `OnCanvasHierarchyChanged` shown in white?

**Comment by real-mikhail** [comment]
Well...
This is how "ReSharper Unity Implicitly Used Identifier" looks in the settings:
![image](https://user-images.githubusercontent.com/3635408/76752561-29f40c00-6791-11ea-99a7-a05e86f8d188.png)
And this is default - I didn't change that.

P.S. Besides `OnCanvasHierarchyChanged` there are few more functions which are shown in white: `OnDidApplyAnimationProperties`, `OnParticleSystemStopped`, `OnParticleUpdateJobScheduled`. Not sure why they are so special :)

**Comment by real-mikhail** [comment]
After enabling R# tooltips and R# color identifiers as was suggested here - https://github.com/JetBrains/resharper-unity/issues/1540 - all unity event functions are now have somewhat turquoise color (like all other "normal" methods):
![image](https://user-images.githubusercontent.com/3635408/76754591-74768800-6793-11ea-847e-2c2547313ca7.png)

If I'll change it in settings to any other color (but not `Default` or `Automatic`) then all unity identifiers will be highlighted properly. So now all what is remains - is just minor issue that `Default` and `Automatic` color previews are incorrect in the settings.

**Comment by citizenmatt** [comment]
I've just been investigating this a bit more, and it looks like everything's ok. Once "color identifiers" is enabled, ReSharper will highlight with the same colour as shown in the settings dialog. Default and Automatic are inherited, and appear to be used correctly (that said, we're inheriting "formal language", we could probably inherit "ReSharper all languages Default Identifier"...)

![resharper](https://user-images.githubusercontent.com/222659/105834130-fe9d9880-5fc1-11eb-9d80-ce56a3371e26.png)
