### ISSUE TITLE
Missing documentation in tooltip for Unity event function

### ISSUE THREAD

**Issue by real-mikhail** [JetBrains/resharper-unity#1540]
This information is available via Quick Doc action or when hovering mouse cursor over gutter but I guess that it is naturally expected to be able to see it the in method tooltip.
See screenshots:
![image](https://user-images.githubusercontent.com/3635408/75258272-4555a200-57f7-11ea-89b3-d82735f38b14.png)
![image](https://user-images.githubusercontent.com/3635408/75258328-59999f00-57f7-11ea-9666-9d9703942f3a.png)

**Comment by citizenmatt** [comment]
This appears to be Visual Studio's tooltip, rather than ReSharper's. You can turn ReSharper's on in the "Visual Studio Features" setting page. You should then get the same tooltip.

**Comment by real-mikhail** [comment]
Nice catch! I know about this feature and I'm always enabling it -- I'm surprised that it was disabled this time. Thanks a lot!
