### ISSUE TITLE
"Generate Unity Event Functions" generates deprecated functions

### ISSUE THREAD

**Issue by real-mikhail** [JetBrains/resharper-unity#1545]
```
    private void OnDisconnectedFromServer(NetworkDisconnection info){}
    private void OnFailedToConnect(NetworkConnectionError error){}
    private void OnFailedToConnectToMasterServer(NetworkConnectionError error){}
    private void OnMasterServerEvent(MasterServerEvent msEvent){}
    private void OnNetworkInstantiate(NetworkMessageInfo info){}
    private void OnPlayerConnected(NetworkPlayer player){}
    private void OnPlayerDisconnected(NetworkPlayer player){}
    private void OnSerializeNetworkView(BitStream stream, NetworkMessageInfo info){}
```
^ these functions can be generated by R# though they will lead to compilation error on Unity 2019.3. They are deprecated starting from the 2018.3 (I think)

**Comment by citizenmatt** [comment]
Ah, the types used by these methods are marked as obsolete, with the message:

> The legacy networking system has been removed in Unity 2018.2. Use Unity Multiplayer and NetworkIdentity instead.

Annoyingly, the event functions are still documented through to 2020.1! (e.g. [`MonoBehaviour.OnDisconnectedFromServer`](https://docs.unity3d.com/2020.1/Documentation/ScriptReference/MonoBehaviour.OnDisconnectedFromServer.html), and we generate these event functions from the docs.

I'll mark them as being available up to and including 2018.1. Do you know if these are the only event functions affected?

**Comment by real-mikhail** [comment]
These are the only deprecated functions in MonoBehaviour (afaik). I'm not sure about other engine types (like ScriptableObject and so on).

**Comment by citizenmatt** [comment]
I updated our API doc parser and turns out it's only the messages listed above.
