### ISSUE TITLE
New scripts created in Unity, or scripts moved in Unity not in Solution / Project

### ISSUE THREAD

**Issue by jaykyburz** [JetBrains/resharper-unity#1547]
Apologies if my terminology is not correct, but when I create a new script in Unity, then click on it to edit it in Rider, the script is not recognised as part of the project. Rider doesn't recognise any classes or know what a GameObject is for example. Just treats the file as a stand alone C# text file.

Opening the file instead in Visual Studio somehow refreshes the solution / project file, so that the new class (or moved class) is included in the project. 

Visual Studio does something to the solution that my Rider doesn't know to do?

Any suggestions for how to get this working?

**Comment by van800** [comment]
What is your Unity version?

**Comment by jaykyburz** [comment]
We are on Unity 2019.3.1f1 but I had this same problem when I tried Rider a few months ago on various 2018 releases. Windows 10. Rider 193.6494.30.

Some other info, Unity has no problem with the new file, seems to compile and run OK.  And when opening a new file in Visual Studio there is a brief few seconds when all the types are unknown, then it refreshes and everything works correctly. 

We are using Perforce for Version Control which makes me wonder if there is some file locked somewhere that Rider won't overwrite but Visual Studio will.  The .sln and .csproj files are not in source control.

**Comment by van800** [comment]
Make sure that you have Rider package v 1.2.1 in Unity package manager and External Editor in Unity is set to Rider.

**Comment by jaykyburz** [comment]
Thanks very much, the upgrade to 121 seems to have fixed my problems. (I was on 114 or whatever is verified right now.) There was some weirdness around  EditorPluginIsLoadedFromAssets, but once I got a clean install everything seems to be working. Woo! Thanks for your help.
