### ISSUE TITLE
OnOpenAsset opens all files in Rider

### ISSUE THREAD

**Issue by marcelschmidt1337** [JetBrains/resharper-unity#155]
In this [commit](https://github.com/JetBrains/resharper-unity/commit/ebc634f1550390bb2d0a29c60a111f023f7399d7) the check for MonoScripts and Shader types were removed. As a result all files are opened in Rider (prefabs, scenes, animations etc.)

**Comment by van800** [comment]
fixed, thanks for reporting

**Comment by van800** [comment]
Is it fine to use Rider for 
"UnityEditor.MonoScript", "UnityEngine.Shader", "UnityEngine.TextAsset"
?

**Comment by marcelschmidt1337** [comment]
MonoScript and Shader definitely yes. I suggest to make TextAssets optional since it supports a lot of different formats and people might want to open these files with other applications.

**Comment by van800** [comment]
I have got a request to open txt and xml in Rider. 
I found out that by default Unity includes "txt;xml;fnt;cd" files to Solution, does it mean that opening them in Rider would be desired?
Thanks for advise!

**Comment by marcelschmidt1337** [comment]
Well, I think there are two options:
1. Ignore TextAssets in the plugin (the user can set the default application for txt and xml in the OS settings + he can always open these files from the solution in Rider anyway)
2. Create a flag in the Rider plugin options "Open Text Assets with Rider" and the user can decide which behaviour he wants.

I personally would prefer a flag in the options.

**Comment by van800** [comment]
I added the filtering by extensions, lets try it and see how it goes.
https://github.com/JetBrains/resharper-unity/commit/7c8bfec0ca2b4fa85352fa183a2b322beaeaa3e4
https://github.com/JetBrains/resharper-unity/commit/b278f40c730e84117b9f99da218520658f89c611

**Comment by marcelschmidt1337** [comment]
Thanks, works like a charm.
