### ISSUE TITLE
Add MeansImplicitUse attribute to the ContextMenu attribute

### ISSUE THREAD

**Issue by JeromeJ** [JetBrains/resharper-unity#1557]
So VS doesn't tag the method as unused and suggest getting rid of it.

**Comment by citizenmatt** [comment]
This should already be working - it’s been part of the plugin for a couple of years. It sounds like you’re using ReSharper, do you have the Unity plugin installed? It’s not bundled with ReSharper like it is with Rider.

**Comment by JeromeJ** [comment]
Mh, it's actually installed and active. (I can see the little Unity symbols in the gutters etc etc)

That being said, the Quick Doc does sees it and display it in a darker grey (which means it has been added externally if I remember correctly?)

![image](https://user-images.githubusercontent.com/650065/76097013-40e37300-5fc7-11ea-930f-eedcd624982a.png)


But, as you can also see in my screenshot, my method is still greyed out and mousing over the dotted lines says that my private method is unused and and "Show potential fixes" suggest removing the method.

(But AltEnter doesn't suggest it)

![image](https://user-images.githubusercontent.com/650065/76097267-b2bbbc80-5fc7-11ea-9426-1b23dc5eabca.png)

![image](https://user-images.githubusercontent.com/650065/76097322-cb2bd700-5fc7-11ea-9479-2e5332e1b906.png)

![image](https://user-images.githubusercontent.com/650065/76097357-de3ea700-5fc7-11ea-9bc5-4d23475f4ccd.png)

**Comment by citizenmatt** [comment]
That looks like Roslyn is complaining about the method, not ReSharper. Those three dots are a Roslyn marker (ReSharper's hints are four dots), and if it appears in the "Show potential fixes" menu (Roslyn), but not ReSharper's Alt+Enter menu, then it's a very good indication that Roslyn is causing the trouble here. I'm not sure what the conflict resolution is in this case. Let me follow up.

**Comment by citizenmatt** [comment]
Yep. This appears to be Roslyn. There's not much we can do about this, unfortunately.

**Comment by JeromeJ** [comment]
Should I see with them?

Because I know for a fact that `[MeansImplicitUsage]` does work as intended in other scenario cases (or used to anyway) so I'm wondering why not here.

Thanks for the swift reply btw.

**Comment by citizenmatt** [comment]
Roslyn only adds an unused highlight for private symbols, which are easy to calculate, because it's only used in the current file (or a bounded set of files with partial types). ReSharper's solution wide analysis can look at the whole solution and mark public symbols as unused as well. The attributes prevent ReSharper's analysis from marking them as unused. We can't do anything about Roslyn marking something as unused.

**Comment by JeromeJ** [comment]
Mh I see 🤔 Interesting.
Would be nice if Roslyn could also check the attributes' attributes as well before claiming "unused". :)
I'll see if maybe I can introduce a ticket if it doesn't exist yet.
