### ISSUE TITLE
Unity plugin for ReSharper 2020.1 (EAP)

### ISSUE THREAD

**Issue by real-mikhail** [JetBrains/resharper-unity#1559]
Any ETA on when Unity plugin for ReSharper 2020.1 (EAP) will be available?

**Comment by citizenmatt** [comment]
I'll try and publish one with the next EAP, and try to keep them up to date until release.

**Comment by real-mikhail** [comment]
Thanks!

**Comment by citizenmatt** [comment]
I've just pushed a build for ReSharper 2020.1 EAP 4. It's uploaded as a pre-release build, so you'll need to go to Extension Options in settings to enable support for pre-release extensions. Let us know if you have any issues.

**Comment by real-mikhail** [comment]
Worked amazing, thanks.

There is a minor issue (missing icon in context menu for Generation Event Functions). Not sure whether it is better to create separate issue on post it here:
![image](https://user-images.githubusercontent.com/3635408/76751808-b2be7800-6790-11ea-94fc-aa3ccae2714d.png)

**Comment by real-mikhail** [comment]
https://youtrack.jetbrains.com/issue/DEXP-506459

**Comment by citizenmatt** [comment]
Yep, spotted that with a quick test. A separate ticket is best for issues, please, so I can tick them off before release. I'll leave this one open so I remember to actually post the final release :)
