### ISSUE TITLE
Unity defines are false in custom solution

### ISSUE THREAD

**Issue by Voresh** [JetBrains/resharper-unity#1561]
When I add unity projects in own custom solutions UNITY_EDITOR (and other unity defines) are always false and some symbols cannot be resolved (in example Application.bundleIdentifier)

**Comment by van800** [comment]
Please share your csproj, you may remove all file includes but leave all the rest.

**Comment by Voresh** [comment]
> 
> 
> Please share your csproj, you may remove all file includes but leave all the rest.

Unity proj files are generated by unity, maybe you want me to recreate it?

**Comment by van800** [comment]
I am just saying that it must some misconfiguration, but without seeing your csproj file and sln file, it is very hard to guess.

**Comment by van800** [comment]
Maybe you have solution configuration Release? There are no special defines in Release.
![image](https://user-images.githubusercontent.com/1482681/76299771-ee060600-62bb-11ea-8dad-3a6b49403c62.png)

**Comment by Voresh** [comment]
> 
> 
> Maybe you have solution configuration Release? There are no special defines in Release.
> ![image](https://user-images.githubusercontent.com/1482681/76299771-ee060600-62bb-11ea-8dad-3a6b49403c62.png)

wow, switching to debug helped, thank you so much!

**Comment by van800** [comment]
Hint: To see csproj content just put selection on project and press F4.
