### ISSUE TITLE
Strange ambiguous reference

### ISSUE THREAD

**Issue by Voresh** [JetBrains/resharper-unity#1562]
Hey, I am using photon server plugin and rider shows me error where it is not. 
![изображение](https://user-images.githubusercontent.com/10650413/76302742-92467780-62d1-11ea-9dde-3f70c4ee2c98.png)
Error text is:
\Assets\Scripts\Photon\Photon Unity Networking\Plugins\PhotonNetwork\PhotonNetwork.cs:150512 Ambiguous reference:
  ServerSettings
  ServerSettings
  ServerSettings
match

**Comment by citizenmatt** [comment]
Do you have multiple classes in your code called `ServerSettings`? Using a short name like this is very weakly typed. Unity has to go looking for the type, and will look for a class defined with no namespace, and also for any classes in any namespace. It can find multiple candidates, which is what Rider has done here.

I can't remember how Unity resolves this situation - there's a good chance that Rider isn't doing the same thing. Can you share this project at all?

Ideally, this `CreateInstance` call would be replaced with a strongly typed `CreateInstance<ServerSettings>()`, which would be completely unambiguous about which `ServerSettings` class was being created.

**Comment by Voresh** [comment]
> 
> 
> Do you have multiple classes in your code called `ServerSettings`? Using a short name like this is very weakly typed. Unity has to go looking for the type, and will look for a class defined with no namespace, and also for any classes in any namespace. It can find multiple candidates, which is what Rider has done here.
> 
> I can't remember how Unity resolves this situation - there's a good chance that Rider isn't doing the same thing. Can you share this project at all?
> 
> Ideally, this `CreateInstance` call would be replaced with a strongly typed `CreateInstance<ServerSettings>()`, which would be completely unambiguous about which `ServerSettings` class was being created.

This code is from photon plugin, I don't really want to change its code (in case of plugin updates)

**Comment by Voresh** [comment]
As I can see there is only one class named ServerSettings

![изображение](https://user-images.githubusercontent.com/10650413/76306294-b1480800-62d7-11ea-92d7-137990b60c53.png)
Clicking "Use class" makes nothing

**Comment by citizenmatt** [comment]
Do you have multiple classes in your code called `ServerSettings`?

**Comment by SgtZdog** [comment]
There is only a single class by that name. This problem (unsurprisingly) happens in Rider as well (2020.2.4). It seems to be a problem with detecting both the code filed as well as the compiled assembly? It's worth noting that the code works fine at runtime, this is purely an analysis problem. (Context of this code is a Unity project using Photon for multiplayer.)

**Comment by van800** [comment]
Try to remove Moq plugin in Rider. If it doesn't help, please report a bug in Rider with logs by Help - Report a Bug.

**Comment by SgtZdog** [comment]
I admit I don't know what plugin you're referring to. When checking my list of installed plugins Moq was not one of them.

**Comment by van800** [comment]
Please report a new bug report with logs. You may use Help - Report a Bug.

**Comment by Samm138** [comment]
I've started getting this problem aswell - in VS2019 version 2020.2.4. Solution builds fine but resharper became unusable.

**Comment by van800** [comment]
@Samm138 have you submitted a bug-report with logs?

**Comment by SgtZdog** [comment]
Invalidating cache and restarting seems to fix the issue.
