### ISSUE TITLE
In Unity explorer, folders created in the Editor are locked (tagged as 'Editor') and can't be excluded from namespacing

### ISSUE THREAD

**Issue by CloudyNebula** [JetBrains/resharper-unity#1563]
When using Rider in Unity explorer mode, folders created in the Unity Editor are locked (tagged as 'Editor') and can't be excluded from namespace providing (access to the folder Properties option is absent).

![image](https://user-images.githubusercontent.com/4161395/76353553-3a2f6580-6311-11ea-8746-23906923569c.png)

However, changing to Solution explorer mode makes this problem disappear and user-created directories are now unlocked and the access to their Properties (and therefore the 'Namespace provider' checkbox) is available.

I feel that this should have a more consistent behaviour between modes. Literally spent a whole hour trying to figure this out until someone pointed out the workaround solution to me.

**Comment by van800** [comment]
Currently there is a problem with UnityExplorer, when folder is part of more than one project.
We need either decide which project context should be used or apply action for all of them.

**Comment by CloudyNebula** [comment]
I see! Thank you for that extra insight, them.

**Comment by van800** [comment]
Thank you for reporting.

**Comment by van800** [comment]
Requires https://youtrack.jetbrains.com/issue/RIDER-40915

**Comment by van800** [comment]
closed in favor of https://youtrack.jetbrains.com/issue/RIDER-33805
