### ISSUE TITLE
PlayMode tests always inconclusive

### ISSUE THREAD

**Issue by VacuumBreather** [JetBrains/resharper-unity#1571]
While EditMode tests run fine inside Rider, the PlayMode tests always become inconclusive/not run.
While this happens, the Test Runner in Unity shows the editmode tests in the playmode tab, which is weird. If I "run all" in the Unity Test runner, that view resets to the correct tests again.

JetBrains Rider 2019.3.4
Build #RD-193.6494.48, built on February 27, 2020

[rider-logs-20200316-103147.zip](https://github.com/JetBrains/resharper-unity/files/4337319/rider-logs-20200316-103147.zip)

**Comment by van800** [comment]
What is your Unity version?

**Comment by VacuumBreather** [comment]
Version 2019.3.1f1

**Comment by van800** [comment]
Updating Rider package  to the latest via Unity package manager should help.

**Comment by VacuumBreather** [comment]
I already did that. The package version is 2.0.1

**Comment by van800** [comment]
Have you switched this drop-down in Rider?
![image](https://user-images.githubusercontent.com/1482681/76750297-4a669b00-677e-11ea-9303-547fdd26c183.png)

**Comment by VacuumBreather** [comment]
I have no idea where this button is supposed to be:
![screenshot](https://user-images.githubusercontent.com/61427715/76770289-f8357200-679d-11ea-9e82-1c1a6a98f5d9.jpg)

**Comment by van800** [comment]
That's weird.
![image](https://user-images.githubusercontent.com/1482681/76770472-4f3b4700-679e-11ea-8749-1c73c9ac9b64.png)

**Comment by van800** [comment]
Could you please show me the screenshot of the status-bar?
![image](https://user-images.githubusercontent.com/1482681/76770850-d092d980-679e-11ea-9c7f-491b84a18352.png)

**Comment by VacuumBreather** [comment]
Here you go:
![screenshot2](https://user-images.githubusercontent.com/61427715/76771531-c7eed300-679f-11ea-9257-bf80950f203a.jpg)

**Comment by van800** [comment]
Your project was not recognized as a Unity generated one.

**Comment by VacuumBreather** [comment]
Ah... I opened a Visual Studio Solution filter instead of the solution file itself. Is that the issue? That's kind of a shame. I would rather not see all those third party projects all the time...

**Comment by van800** [comment]
What is that `filter`? Could you please make a screenshot?

**Comment by VacuumBreather** [comment]
In Visual Studio you unload all the projects you don't need, then right click on the solution and do this (see screenshot). That creates a .slnf file, which basically points back to the original solution and just filters out the not-needed projects. It's not a solution in itself. That's a new feature in VS2019. Would be kind of cool if Rider supported those. It can load them. But apparently the Unity plugin doesn't recognize that the filtered solution is a Unity generated one.
![screenshot3](https://user-images.githubusercontent.com/61427715/76774468-3f266600-67a4-11ea-8656-fab9e411389e.jpg)
[Montreal.slnf.zip](https://github.com/JetBrains/resharper-unity/files/4338959/Montreal.slnf.zip)

**Comment by VacuumBreather** [comment]
Opening the solution itself works. Is there any way in rider that I can filter unneeded projects, hide them? Also I guess this can then be turned into a feature request to support solution filter files in the Unity Plugin. Rider is obviously able to load the file type already. The unity plugin just doesn't recognize the solution in that case.

**Comment by citizenmatt** [comment]
What's the name of the original `.sln` file, and the name of the folder? We check that a project is the generated solution by comparing the name of the loaded solution to the name of the current folder.

**Comment by VacuumBreather** [comment]
As it says in the solution filter file if you open it, the solution is called the same.
Montreal.sln, Montreal.slnf and the folder is /Montreal/

**Comment by VacuumBreather** [comment]
A solution filter, when created in VS2019, will always be called the same as the solution it is based on. So unless someone renames it after the fact, that wouldn't be the problem.

**Comment by van800** [comment]
Is there any particular reason why do you use solution generated for VS instead of the one generated by Rider package?

**Comment by VacuumBreather** [comment]
I'm using the solution filter because I don't want to see all the third party projects. I just want to see my projects. Rider doesn't offer that.

**Comment by VacuumBreather** [comment]
Also I am not loading a solution generated for VS. I'm loading a solution filter generated by VS FOR the solution generated by unity. The solution file is identical. I do not create a separate solution.
The benefit is this:
![screenshot4](https://user-images.githubusercontent.com/61427715/76843373-fc17d180-683b-11ea-9bc4-3e0380a0ffbd.jpg)

**Comment by VacuumBreather** [comment]
It would also be cool if Rider could create these solution filter files. Since it already can interprete them, it makes sense for it to be able to create them. Since they are a very simple file format, that should not be difficult.

**Comment by van800** [comment]
Issue is fixed meaning that slnf would be considered a valid Unity solution.

**Comment by van800** [comment]
@VacuumBreather For creating slnf feature you may create a separate issue in https://youtrack.jetbrains.com.
I asked around and got an answer that for now we do not consider implementing `create slnf`.
It feels that VS added this feature because they can't handle really big solutions.
Thank you for your report, it was really valuable.
