### ISSUE TITLE
There is a missing icon for "Generate Event Functions"

### ISSUE THREAD

**Issue by real-mikhail** [JetBrains/resharper-unity#1573]
Issue can be observed in "Generate" Context Menu:
![image](https://user-images.githubusercontent.com/3635408/76757090-0a141680-6798-11ea-87db-897cdf16c829.png)

It can also be observed in "Generate Event Functions" window:
![image](https://user-images.githubusercontent.com/3635408/76757138-231cc780-6798-11ea-90f3-f6f7f572eef0.png)

Also exceptions is thrown when this window is opened:
https://youtrack.jetbrains.com/issue/DEXP-506459

R# version: 2020.1 EAP4

**Comment by citizenmatt** [comment]
Fixed in #1590
