### ISSUE TITLE
Rename got really slow

### ISSUE THREAD

**Issue by Baste-RainGames** [JetBrains/resharper-unity#1576]
The rename modification got really slow. It seems like even if I have "Parse text based assets" turned off, Rider still pops up a loading bar that shows it briefly looking at all my assets each time I rename a Unity serialized field.

Here's a gif:

![Slow](https://user-images.githubusercontent.com/12800067/76839294-8c064d00-6835-11ea-887b-8da9c8ee8eb5.gif)

In Rider 2019, that rename was near instant. What's going on? This is especially annoying since I just made that field, and I know that there's no instances of it in any assets. 

@krasnotsvetov, this is why I'm skeptical of asset integration. If the rename is indeed looking through all of those assets, it's doing it really fast, but it's still slow enough to seriously hamper my workflow.

Together with the "Rename references in Unity asset files?" dialogue and the suggestion to "Add FormerlySerialized as", I'm looking at three different additional popups in order to rename a simple field. 

I'd be interested in asset integration if it was opt-in every time - if I had a shortcut that said "rename this thing and also rename UnityEvents targeting it", I could use it when I knew it was relevant, and not get annoyed by all the popups when I know it's not.

**Comment by krasnotsvetov** [comment]
It is related to previous issue, in EAP5 (this week) you won't have that problem after disabling "Parse text-based assets"

I don't want to close this issue until implementing new setting :)

**Comment by krasnotsvetov** [comment]
Are you annoyed by appering "formerlyserializedas" page each time too?

**Comment by Baste-RainGames** [comment]
Not really, it's a very useful dialogue, as I might often want to apply [FormerlySerializedAs] to the renamed field.

Having different dialogues pop up is a big annoying, though, as it gets disruptive. It would be nice if it would be possible to have the "Do you want to apply [FormerlySerializedAs]" question inside the same popup as the one where we enter the field name.

**Comment by krasnotsvetov** [comment]
Does EAP5 solve your problem with renaming? Also, could you share memory usage of backend when  asset parsing is enabled in your project? (ctrl+shift+a -> Memory Indicator. New indicator will appear in right corner, first value for frontend, second value for backend). Thanks!

**Comment by Baste-RainGames** [comment]
Hi!

Memory when asset parsing is enabled in EAP 5
![image](https://user-images.githubusercontent.com/12800067/77407207-14489d00-6db6-11ea-8f74-8524ce3efa86.png)

It's still not fixed in EAP 5. The window still pops up showing that it's searching through eg. prefabs when I try to rename a public method or a Unity serialized field even if the asset parsing is turned off:

![Slow](https://user-images.githubusercontent.com/12800067/77407367-540f8480-6db6-11ea-89e5-f05802ae1732.gif)

**Comment by krasnotsvetov** [comment]
Fixed in EAP6 (we have lost filter for source files in find usages for assets after yaml grand-refactoring)

**Comment by krasnotsvetov** [comment]
@Baste-RainGames,
Does EAP6 fix that issue?

**Comment by Baste-RainGames** [comment]
Yes, it seems to have!
