### ISSUE TITLE
Unshelving error on first meta file

### ISSUE THREAD

**Issue by bartlomiej-dawidow** [JetBrains/resharper-unity#1579]
To reproduce:
1. Make local modifications to a few of files, including ones that will result in moved / renamed meta files and new meta files.
2. Shelve those changes.
3. Unshelve.

The above results in an error:
> Apply Path
'../SomeFile.meta' already exists in VFS.

<img width="636" alt="Screen Shot 2020-02-13 at 23 57 39" src="https://user-images.githubusercontent.com/9422443/74486361-136e4280-4ebd-11ea-8b1b-6ad37e6a593f.png">

It's not deterministic but it reproduces most of the time.

---------

JetBrains Rider 2019.3.4
Build #RD-193.6494.48, built on February 27, 2020
Runtime version: 11.0.5+10-b520.38 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep

**Comment by van800** [comment]
Do I understand right, that it doesn't crash, but only displays error message?

**Comment by bartlomiej-dawidow** [comment]
> Do I understand right, that it doesn't crash, but only displays error message?

@van800 Yes, the IDE doesn't crash / shutdown, but it displays the error and applying the patch fails (files below the .meta file do not get patched).

**Comment by van800** [comment]
closed in favor of https://youtrack.jetbrains.com/issue/RIDER-48688

**Comment by bartlomiej-dawidow** [comment]
This is still happening on Rider 2020.3.4, com.unity.ide.rider 3.0.2. The `.meta` files do not get unshelved. I've also bumped the YouTrack issue.
