### ISSUE TITLE
Unity3dRider Solution Folder Mangling

### ISSUE THREAD

**Issue by Lattyware** [JetBrains/resharper-unity#158]
The Unity3dRider plugin seems to be mangling my solutions - this is probably because I'm not using a unity-generated solution (mine includes non-unity projects that get included as DLLs in Unity).

The part that seems to be an issue is "Solution Folder" projects (denoted by the `2150E333-8FDC-42A3-9474-1A3956D46DE8` guid). My solution has these for "Solution Items" and organisation of other projects. The rider plugin starts mangling these by inserting lots of extra quotes, I think while trying to rename them to match (non-existant) paths.

E.g: My solution contains:

```Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "utils", "utils", "{916AE1DE-9A48-41CC-BDAD-E3DA7857173B}"```

After running Unity with the Rider plugin installed:

```Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "utils"", "utils"", "{916AE1DE-9A48-41CC-BDAD-E3DA7857173B}"```

And it continues to get more mangled with successive runs:

```Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = ", """, ", """, "{916AE1DE-9A48-41CC-BDAD-E3DA7857173B}"```

This will continue each time Unity restarts and I've ended up with these files growing full of quotes to the point they crash my editors. Of course it's an easy fix just to checkout my sln, but it's a little annoying, so just ignoring these kinds of project would be great.

**Comment by van800** [comment]
I will try to fix it, but without sample it might be not so easy.
It might be faster, if you try to correct the piece of code:
if (line.StartsWith("Project("))
        {
          MatchCollection mc = Regex.Matches(line, "\"([^\"]*)\"");
          //RiderPlugin.Log(mc[2].Value);
          sb.Append(line.Replace(mc[1].Value, GetFileNameWithoutExtension(mc[2].Value)+"\""));
        }

**Comment by van800** [comment]
https://github.com/JetBrains/resharper-unity/commit/823a1c76514c48dc3d59ecb781267d7ae23bff68

**Comment by Lattyware** [comment]
Thanks for the fast fix, this makes my workflow a little nicer. Appreciated.
