### ISSUE TITLE
.asmdef / root namespace

### ISSUE THREAD

**Issue by sebastian-heinz** [JetBrains/resharper-unity#1584]
Hello,

It would be great if there was a way to specify the root namespace for rider/unity projects.
I raised this in the unity forum and got redirected to this issue tracker.
Post: https://forum.unity.com/threads/rider-asmdef-namespace.852121/#post-5619076

I think a great way to solve this would be to be able to specify it inside the .asmdef file.
There us already a way to specify a package name, but using this would restrict the root namespace to the package name, not sure if this would be desired or not.

Having an additional field might require coordination with unity team.

I am unsure if VisualStudio has similiar issues or how it is handled, since .csproj files are generated on the fly it is not really possible to provide this info to the package.

Here is my .asmdef for a local package
![Capture](https://user-images.githubusercontent.com/7891178/77308682-529e7780-6d36-11ea-90aa-459a97da294e.PNG)

Here is the warning about my namespace:
![Capture](https://user-images.githubusercontent.com/7891178/77308519-09e6be80-6d36-11ea-9850-42ffab1edac4.PNG)

Maybe there are other ways to solve this, would be happy if there is a solution or maybe I am missing something that it is already possible and I am doing something wrong.

Thank you

**Comment by van800** [comment]
Related to https://youtrack.jetbrains.com/issue/RIDER-36546

**Comment by Strepto** [comment]
A workaround to the issue with namespaces in the Packages/ folder could be handled the same way as with namespaces in the Assets folder, strip away "Packages/" when suggesting namespace. This is not the best solution, and I would like to handle namespaces within assembly-definitions, but it helps with avoiding the basic namespace clutter.

![image](https://user-images.githubusercontent.com/3185998/77823583-737f1800-70fc-11ea-8984-7db9864f6433.png)

**Comment by van800** [comment]
As a workaround you may switch from UnityExplorer to SolutionExplorer. Right click on packages folder would allow to uncheck Namespace Provider for it.
![image](https://user-images.githubusercontent.com/1482681/77996745-7c573000-732e-11ea-8f74-f2498265dc3b.png)

**Comment by citizenmatt** [comment]
See also [RIDER-36546](https://youtrack.jetbrains.com/issue/RIDER-36546)

**Comment by Nirlah** [comment]
Hey @citizenmatt,
Now that Unity 2020.2 added support for `rootNamespace` in .Asmdef, is there a plan to support it in Rider?

**Comment by van800** [comment]
Rider package 2.0.6 would have it, when combined with Unity 2020.2. @Nirlah

**Comment by citizenmatt** [comment]
And #1677 and #1689 both handle the case where an assembly definition has a root namespace. Folders in the assembly definition project are used as namespace segments against the root namespace.

I'm going to close this now, as it's really a Unity feature that is solved with Unity 2020.2 and supported by Rider 2020.2.

**Comment by Sammmte** [comment]
@van800 I love you, man. You just made my life easier

**Comment by builder-main** [comment]
Hi, does this work with Resharper on VS 2019 ?
