### ISSUE TITLE
Get transient packages + resolved versions when generating project files

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#1586]
Currently, Rider is calculating the list of packages manually, including transient dependencies, by looking at `Packages/manifest.json`, finding the package in the local cache and reading its `package.json`.

While this will list all known packages, it doesn't necessarily reflect the same version resolution strategy that Unity uses. E.g. Rider will choose the highest version number from conflicting dependencies, but Unity might resolve to the closest (higher?) version on the server that isn't reflected in the `package.json` files, and Rider will have an unresolved package.

When generating projects, Rider could also generate a file listing the resolved packages in e.g. `Library/RiderResolvedPacakges.json`. The Packages node of Unity Explorer could then use this file (on a file watcher) to make sure that the details are correct. Whenever a package is added/removed/updated, projects are already re-generated, so we also have the chance to generate a packages list.

Rider should fall back to the current way of resolving transient packages if the file does not exist. This is possible, depending on the version of the Unity Editor plugin currently in use.

**Comment by van800** [comment]
once implemented this would fix also https://github.com/JetBrains/resharper-unity/issues/1585

**Comment by citizenmatt** [comment]
Modern Unity resolves all packages and saves the result in `packages-lock.json`. We use this file in preference to `manifest.json`, if it exists. This gives us accurate resolve details. Currently, I'm not aware of any resolve issues with older versions of Unity (#1585 is fixed), so I'm closing this.
