### ISSUE TITLE
Need a setting to disable UnityPluginInstaller

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#159]

**Comment by Rennan24** [comment]
YES PLEASE! I just posted a reason why [here](https://github.com/JetBrains/resharper-unity/issues/161) but basically it's pretty annoying the way it works now, especially if people like to move their Plugins to the "Standard Assets" folder.

**Comment by van800** [comment]
http://t-machine.org/index.php/2017/04/08/a-real-ide-for-unity3d-how-to-install-jetbrains-rider-c-editor-on-mac-2017-unitytips/

**Comment by marcelschmidt1337** [comment]
I'm symlinking the files from this repository to my project, so +1 on that.
Btw is the version on Github the same as the one from the plugin repository? (1.8 Github vs 1.9 in Rider)

**Comment by Ivian** [comment]
Also, I'm working for a pretty big company, and we are managing a lot of plugins, with our internal tools. Having Rider messing around directly in Plugins is a downside for us.

Also, Rider extension doesn't have to be in the Firstpass Assembly (therefore creating it, if there are no scripts in Firstpass in the whole project). It would be nice if there was on option to move it from Firstpass to Assembly-CSharp-Editor (so basically removing it from Assets/Plugins, and leaving it in some Rider/Editor directory anywhere in the project).
