### ISSUE TITLE
Parameter info popup with Entities.ForEach lags

### ISSUE THREAD

**Issue by kefyru** [JetBrains/resharper-unity#1606]
There is strange behaviour of parameter info popup. It popups from anywhere of included blocks of code with freezes for a 2-3 seconds. 

<img width="694" alt="Снимок экрана 2020-04-03 в 12 26 41" src="https://user-images.githubusercontent.com/29143718/78345895-f09c0880-75a6-11ea-95fc-253b12162b7b.png">
<img width="953" alt="Снимок экрана 2020-04-03 в 12 30 23" src="https://user-images.githubusercontent.com/29143718/78345902-f2fe6280-75a6-11ea-9bb7-113664e8d8fa.png">

**Comment by van800** [comment]
Must have been already fixed in 2020.1 EAP6
see details in https://youtrack.jetbrains.com/issue/RIDER-36736
