### ISSUE TITLE
Name is confusing as it conflicts with Microsoft's Unity DI Framework

### ISSUE THREAD

**Issue by CreepyGnome** [JetBrains/resharper-unity#162]
When I saw this in the list of Extensions in R# I was excited as I thought this was for Microsoft's Unity DI Framework which is typically just called Unity in the context of Microsoft products and technology like Visual Studio and C#, etc.

However, this extension is for Unity 3D from the company Unity Technologies ApS. Since Unity 3D is a cross-platform 3D development environment that supports multiple languages including C# and has its own development environment it is typically a good idea to call it Unity 3D when used within the context of Microsoft technologies to avoid confusion.

At the least change the description that is visible from "ReSharper support for Unity" to "ReSharper support for Unity 3D" as that appears to always be visible when searching for R# extensions within Visual Studio.  Best would be to change the description and the repo name and extension name as just looking at it in the list is confusing as R# is associated with Visual Studio and typically C#.

**Comment by CAD97** [comment]
Changing the repo name would be ill-advised as it would break any incoming links.

Also of note: the engine is just called "Unity" as well.
![compare-logo](https://user-images.githubusercontent.com/5992217/27203257-ff05dcfa-51f2-11e7-8104-01ab0ac1217c.png)

It's an unfortunate fact that name conflicts happen.

**Comment by CreepyGnome** [comment]
I mean I could just as easily say their website is unity3d.com, 

Regardless, I did suggest at least changing the description, since it should be easy and painless to do so that it is not be confused with Microsoft Unity because you are in the Microsoft world with the where you are posting the extension so you should consider that most people may think Microsoft Unity when they just see the word Unity without context.  If you don't like the term 3D just say "ReSharper support for the Unity Game Engine" or "ReSharper support for Unity - The Game Engine" or "ReSharper support for Unity Technologies Unity Game Engine" or  something similar to make it clear which "Unity" you are providing "support" for with the extension.

Right now your description doesn't make it clear what you are an extension for.

**Comment by IvanPashchenko** [comment]
@CreepyGnome thank you for the suggestion, we've updated the description and summary for the plugin. 

We're leaving the name "Unity support" as is — MS themselves referenced to Unity engine as just Unity in the name of their extension:
https://marketplace.visualstudio.com/items?itemName=SebastienLebreton.VisualStudio2015ToolsforUnity

**Comment by CreepyGnome** [comment]
Description and summary are enough. Thanks.
