### ISSUE TITLE
IntelliSense documentation missing from within assembly definition project

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#1621]
When you try to browse from one pre-defined assembly like Assembly-CSharp-Editor, docs work:

![2020-04-14_00-20-25](https://user-images.githubusercontent.com/1537591/79166577-c38cf880-7de5-11ea-9ff2-0519798a1eeb.png)

But when you try doing the same from an assembly definition project, docs fail:

![devenv_2020-04-14_00-20-51](https://user-images.githubusercontent.com/1537591/79166608-d3a4d800-7de5-11ea-80a7-5c9256b53d27.png)

**Comment by van800** [comment]
Tried it in Rider 2020.1 - works fine for me.
What is your Rider version?

**Comment by aybe** [comment]
Sorry, I am talking about latest Visual Studio version.

**Comment by van800** [comment]
I think, if it is fixed in Rider 2020.1, then it would also work fine in ReSharper 2020.1.
I understand it is not yet available, but I don't think we need to keep this issue opened.

**Comment by aybe** [comment]
Okay, I will wait for it and re-open issue if it doesn't work.

**Comment by van800** [comment]
Thanks!

**Comment by flexington** [comment]
I am having the same issue.
IMHO, that's not an editor issue but the way how Unity creates the assembly definition is.
While the original code in the package (under Package/PackageName) does contain all documentation tags, the assembly definition doesn't.
This issue is still valid in Unity 2019.4

**Comment by aybe** [comment]
Seems like R# also sees dupes in IntelliSense, start typing a type name, it'll pop in, now move to end of list by pressing <kbd>Up Arrow</kbd>, you will see at the end of the list the same type but with its namespace in parenthesis!
