### ISSUE TITLE
New meta files appear changed immediately after pull/merge

### ISSUE THREAD

**Issue by Kylotan** [JetBrains/resharper-unity#1622]
I don't have clear repro steps for this, but what seems to sometimes happen is that during a long pull/merge operation from inside Rider, I end up with a lot of meta files which are marked as changed, with new GUIDs.

I think what is happening is that Rider spots new assets, schedules some sort of task to make meta files for them, pulls them down from Git, and eventually overwrites the repository version with the newly generated one.

JetBrains Rider 2019.3.4
Build #RD-193.6494.48, built on February 27, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Unity 2019.3.0f6

**Comment by Kylotan** [comment]
You're probably already aware, but I still see this on the current version. I also see some evidence that this can overwrite more than just the GUID, leaving various other fields changed locally. Thankfully they can all just be rolled back.

It's worth noting that Unity is open during the merge operation, which is merging into my current branch.

JetBrains Rider 2020.1.3
Build #RD-201.7846.1, built on May 15, 2020
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
.NET Framework 4.0.30319.42000
Windows 10 10.0

**Comment by van800** [comment]
@Kylotan In 2020.2 I have removed calling refresh after vcs pull.
