### ISSUE TITLE
Create static constructor error instantly disappears

### ISSUE THREAD

**Issue by JurjenBiewenga** [JetBrains/resharper-unity#1625]
See attached gif, also appears to fail without a good reason
![ezgif-5-765e47f2bfb3](https://user-images.githubusercontent.com/3128681/79546802-4edee600-8093-11ea-9003-8658d60880ec.gif)

**Comment by citizenmatt** [comment]
Do you have a stable repro of this? I can't recreate this. Is the C# file just a normal file in `Assets`? Anything else interesting going on?

**Comment by JurjenBiewenga** [comment]
This is fixed by #1644
