### ISSUE TITLE
The plugin mess up assemblies

### ISSUE THREAD

**Issue by dnadeau-quatral** [JetBrains/resharper-unity#163]
When I add the plugin to my project, the link between Unity and Rider works, but Rider seem to lost reference to the framework and cannot resolve thing part of the framework like 
`void`,`string`, ect... But it only happen if the UnityEditor open Rider when I click on an error or something.

`The reference assemblies for framework ".NETFramework,Version=v4.5,Profile=Unity Subset v3.5" were not found`

If I remove the plugin, the link between Unity and Rider is lost, but Rider can resolve all symbol.

And now the plugin is autoadded by Rider, so the problem is really annoying.

Do I miss something ?

**Comment by van800** [comment]
Could you please share your csproj file? What is your Unity version? OS version? Thanks!

**Comment by van800** [comment]
In Unity - Preferences - Rider there is a checkbox  to avoid targeting 4.5.

**Comment by van800** [comment]
Do you have "Microsoft .NET Framework Developer Pack 4.5.1 or later" installed? It is mentioned in https://rider-support.jetbrains.com/hc/en-us/articles/207288089

**Comment by van800** [comment]
I have reproduced the issue, thanks!
https://youtrack.jetbrains.com/issue/RIDER-7191

**Comment by van800** [comment]
duplicates https://github.com/JetBrains/resharper-unity/issues/164
