### ISSUE TITLE
Make Quick Fixes scoped actions

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#1648]
If a quick fix makes sense to be applied to the whole file/project, it should be implemented as a scoped action. Convert the following quick fixes to scoped actions:

* Convert to `CompareTag`
* Convert to generic `GetComponent`
* Combine setting parent with object creation
* Convert coalescing operator to conditional for Unity `Object` types

This action can be made into a "redundant code" action, so that it is also applied when Code Cleanup has the "Remove code redundancies" option set.

* Remove redundant attribute (`InitializeOnLoad`, `HideInInspector` not applied to a serialised field, `FormerlySerialisedAs` with the current field name, `SerializeField` on a static/not a `MonoBehaviour`, and attributes applied to an incorrect target)

These actions are not going to be converted, usually because it makes no sense to do so:
* Remove redundant event function - this invokes the Safe Delete refactoring, in case the method is also used elsewhere in core, and this cannot be applied in bulk.
* Introduce variable for repeated property access
* Convert to `gameObject.AddComponent` - we don't know which game object to add to
* Convert to `ScriptableObject.CreateInstance` - could be applied in bulk, but not likely to be an issue, so not worth converting
* Create from usage - serialised field, static constructor from `[InitializeOnLoad]`, from string literal
* Split `FormerlySerializeAs` attribute usage on multiple field declaration
* Incorrect method signature fix
* Inefficient multi-dimensional array usage - best to review on a case by case basis
* Ambiguous scene name in `LoadScene` - don't know what to change it to
* Mark type as `[Serializable]` from redundant serialised field
* Reorder vector multiplication - best to review on a case by case basis
* Introduce ID for shader and animator properties - this should replace all usages of the string in the current file, but that's not a scoped action
* Prefer non-allocating API - introduces compilation errors, as it requires an existing array
* Remove `readonly` from serialised field - could be applied in bulk, but not likely to be an issue, so not worth converting

**Comment by JurjenBiewenga** [comment]
What about #1172?

**Comment by citizenmatt** [comment]
That's mentioned in the issue, perhaps by a different name:

> Introduce ID for shader and animator properties - this should replace all usages of the string in the current file, but that's not a scoped action

A scoped action will run the action on each highlight (or apply code cleanup on the file with minimal options active). For caching properties, we don't want to run it multiple times, as it would need to reanalyse each time to see if it's introducing a cached field, or using an existing one. The quick fix should really fix all occurrences by default, or prompt with a choice, like extract variable. So, yes, this should be done, but it's a separate issue.
