### ISSUE TITLE
Border around color for bright colors ?

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#1652]
Some colors are 'invisible' sometimes:

![devenv_2020-05-07_04-16-29](https://user-images.githubusercontent.com/1537591/81247178-9d8bfa00-9019-11ea-876e-3cb65f7b9b27.png)

Maybe add a border around decorator like this:

![chrome_2020-05-07_04-19-07](https://user-images.githubusercontent.com/1537591/81247297-e9d73a00-9019-11ea-9bd1-4e0962e959f6.png)

Thanks

**Comment by citizenmatt** [comment]
This isn't something the Unity plugin can handle, unfortunately. It requires changes in the platform. I've raised an issue for it: [RIDER-45422](https://youtrack.jetbrains.com/issue/RIDER-45422)

**Comment by aybe** [comment]
It's in visual studio in fact!

**Comment by citizenmatt** [comment]
Ah, right, it's a similar issue with the ReSharper platform. I'll add a comment to the issue. Thanks!
