### ISSUE TITLE
Remove the "Rider plugin initialized" message on every compilation.

### ISSUE THREAD

**Issue by Ivian** [JetBrains/resharper-unity#166]
The [InitializeOnLoadAttribute] triggers every compilation, and the initialization message every time can get quite annoying. I'd suggest an option to trigger it once every start of the project, for example by checking the EditorApplication.timeSinceStartup value, or leaving an option to disable this message in settings.

**Comment by van800** [comment]
@IvanPashchenko 
How to disable all logging with new LoggingLevel options?

**Comment by IvanPashchenko** [comment]
@van800 set verbosity to `None`

**Comment by IvanPashchenko** [comment]
@van800 you can't disable all logging, you can leave Warnings and higher

**Comment by van800** [comment]
fix will become available with next Rider EAP build
