### ISSUE TITLE
Generated propertydrawer indenting is incorrect

### ISSUE THREAD

**Issue by JurjenBiewenga** [JetBrains/resharper-unity#1663]
![image](https://user-images.githubusercontent.com/3128681/82295088-7cc78b00-99af-11ea-9095-4d194bc88640.png)

**Comment by citizenmatt** [comment]
How are you generating the property drawer/

**Comment by JurjenBiewenga** [comment]
Right click in the solution view > Add > Property Drawer

**Comment by citizenmatt** [comment]
I can't recreate this. I'm closing for now, feel free to re-open if it's still an issue.
