### ISSUE TITLE
Add posibility to ignore assemblies from package to be analyse by rider

### ISSUE THREAD

**Issue by Sylmerria** [JetBrains/resharper-unity#1670]
If you want have access to method summaries of packages ( which is important for DOTS math package), you have to add theirs csproj to project which can be done in Unity with menu Preference->External tools.

This options add dozens of new csproj which is not attended to be edited so analyse is useless ( and take time and PC resources)

Have the possibility to ignore all directories which have in their path "Library" or "@[NumberVersion]" can solve this

**Comment by van800** [comment]
Maybe we can fix it the other way around? I mean, by fixing the missing documentation?

**Comment by Sylmerria** [comment]
Don't forget now package are not only from Unity but also from Users ( asset store publisher or git repo).

**Comment by van800** [comment]
This set of checkboxes controls for which Packages csproj files would be generated.
![image](https://user-images.githubusercontent.com/1482681/113443696-c61ba000-93f2-11eb-8886-51cb33dac1de.png)
Does it solve the issue for you?

**Comment by citizenmatt** [comment]
See also [RIDER-60749](https://youtrack.jetbrains.com/issue/RIDER-60749)

**Comment by Sylmerria** [comment]
this "bug" has been sent to unity by you guys or do we have to report a bug for unity ?

**Comment by van800** [comment]
We have communicated the xml doc problem several times, but if you report the same from your side, it may speed up the solution.
