### ISSUE TITLE
Whenever I open a script via Unity, I get errors

### ISSUE THREAD

**Issue by Elotha** [JetBrains/resharper-unity#1680]
I couldn't find anything about this issue on the web, so I decided to write it here.

My JetBrains Rider version is 2020.1.3, and Unity version is currently 2019.3.14f1, *(but I had this issue before with an older version of Unity)*

Whenever I open a script via Unity, I get these errors:

**Unable to do OpenFile to Rider from dll, fallback to com.unity.ide.rider implementation.**
**ExecutionEngineException: String conversion error: Illegal byte sequence encounted in the input.**

I tried to get Unity Editor Plugin logs as suggested here: https://rider-support.jetbrains.com/hc/en-us/articles/360001148404-Reporting-Unity-related-issues
But when I tried to access Unity -> Preferences -> Rider, I had another three more errors but this time more than once for each.

In Errors.txt, I provided details of the errors.

[Errors.txt](https://github.com/JetBrains/resharper-unity/files/4708071/Errors.txt)
[rider-logs-20200531-195418.zip](https://github.com/JetBrains/resharper-unity/files/4708072/rider-logs-20200531-195418.zip)
[upm.log](https://github.com/JetBrains/resharper-unity/files/4708069/upm.log)

**Comment by van800** [comment]
Please try to update Rider package in Unity. Thank you!

**Comment by Elotha** [comment]
Thanks for the reply.

I already updated it. Didn't work unfortunately.

[image: image.png]

Ivan Shakhov <notifications@github.com>, 31 May 2020 Paz, 21:24 tarihinde
şunu yazdı:

**Comment by van800** [comment]
It seems that was fixed by https://github.com/van800/com.unity.ide.rider/commit/52732afd2d72127df923bc9e564a321c273d14f7

however this version have not yet been released.
You may either wait or checkout that branch, put `Packages/com.unity.ide.rider` into `Packages/com.unity.ide.rider`.

**Comment by van800** [comment]
Most likely fixed in Rider package `2.0.5`

**Comment by Elotha** [comment]
It seems it solved my problem, thank you!

Ivan Shakhov <notifications@github.com>, 1 Haz 2020 Pzt, 09:43 tarihinde
şunu yazdı:
