### ISSUE TITLE
Test Runner Hanging when using Continuous Testing

### ISSUE THREAD

**Issue by Strepto** [JetBrains/resharper-unity#1695]
When running tests in Unity using the Continuous Testing, Rider often gets stuck running tests (or waiting for coverage). This is not cancellable (the cancel button does nothing), and I need to restart Rider to start testing again.

Example Screenshots:

![image](https://user-images.githubusercontent.com/3185998/84631708-1f5f2500-aeee-11ea-80ce-f6b6fdb9fa35.png)

![image](https://user-images.githubusercontent.com/3185998/84642329-97344c00-aefc-11ea-83ab-401d08fc432b.png)

When I try pressing "Stop Execution" nothing happens. In the screenshot the tests have been stuck since before the weekend, so it is not waiting for anything.
![image](https://user-images.githubusercontent.com/3185998/84642747-322d2600-aefd-11ea-8e27-0ea0be216159.png)

Is this a known issue? Is there anything I can supply to help debugging this issue?

Possible Explanation: It seems to happen more frequently when I change and save any file while the test is running.

Using 
* **Unity 2019.4.0** with **Rider Unity Plugin v2.0.5** and **Unity Test Runner v1.1.14**.
* **Rider 2020.1.3**

**Comment by van800** [comment]
Do you mean tests in Unity are finished, but in Rider still waiting?

**Comment by Strepto** [comment]
The tests seem to be complete in Unity, but Rider sees them as not complete

![image](https://user-images.githubusercontent.com/3185998/84647036-2d6b7080-af03-11ea-9a56-9ae94efa5e75.png)
![image](https://user-images.githubusercontent.com/3185998/84647041-30666100-af03-11ea-826f-c2093858ae4c.png)

**Comment by eirikwah** [comment]
I can reproduce this bug like this:

1. Open a small Unity project with some editor tests. Using Unity 2019.4.0f1, and Rider 2020.1.3, and Rider Editor Unity package 1.1.4. Using macOS.
2) Enable "Continous testing" mode "Run all tests"
3) Do a change and save to trigger that the tests run.
4) While the code is compiling, do another small change, but do not save yet.
5) Wait for all tests to show status "pending" and that the Unity editor starts to prepare for running the tests (the "Test runner" window is cleared for a short time). Now hit save.
6) Observe that the Unity editor runs the tests to completion, but the status is never updated in Rider, is is still "Pending" for all tests, and the stop button does nothing.

**Comment by van800** [comment]
Thank you for the complete repro. I will look into it.
In the meantime, I can only suggest that instead of restart Rider, you can close-open solution, which would be faster.
