### ISSUE TITLE
Rider assembly slows down assembly reload

### ISSUE THREAD

**Issue by RDeluxe** [JetBrains/resharper-unity#1696]
Hi !

Been testing the [Editor Iteration Tool ](https://forum.unity.com/threads/introducing-the-editor-iteration-profiler.908390/) and it seems that Rider it responsible for a good chunk of our assembly reload time.

![Example](https://i.imgur.com/wV36xnN.png)

Anything we can do about this ?

Thanks !

**Comment by van800** [comment]
What Rider package version is that? Is it showing the main thread time?

**Comment by van800** [comment]
On the latest version 2.0.5 I am seeing a lot smaller numbers.

**Comment by RDeluxe** [comment]
I'm sorry, should have given those info :

* Unity 2019.4.0f1 LTS
* Rider 2020.1
* Rider package 2.0.5

**Comment by van800** [comment]
I can have a look at your snapshot. Not sure, why times at your snapshot are so much different.

**Comment by RDeluxe** [comment]
Should I deep profile ? Or normal profiling is enough ?

Here is normal export 
[ProfilerExport.zip](https://github.com/JetBrains/resharper-unity/files/4781337/ProfilerExport.zip)

**Comment by van800** [comment]
Not clear. Please do deep profile.

**Comment by van800** [comment]
Are you seeing the same values on just empty project with Rider package?

**Comment by RDeluxe** [comment]
I'll do both asap.

**Comment by RDeluxe** [comment]
Hi,

I could not reproduce the issue with a new project. 

Here is a deep profile, in which Rider is not at all at the top of the list anymore. Not sure how "deep profiling" interferes with the analysis.

[DeepProfilerExport.zip](https://github.com/JetBrains/resharper-unity/files/4785246/DeepProfilerExport.zip)

**Comment by van800** [comment]
420ms in this DeepProfile snapshot is nearly what I would expect.

**Comment by RDeluxe** [comment]
I'm closing this then, false alarm. Will reopen if I can reproduce !

**Comment by PyTechDrae** [comment]
I'm actually have this same issue. When I open my project compilation takes about 2 seconds. After opening Rider my compile times are up to 50 seconds due to Assembly reload

**Comment by van800** [comment]
@PyTechDrae It is somehow specific to your project. So take a snapshot, share a screenshot here. Mention your OS and Unity version, make sure to use latest Rider. If you are on Unity 2019.2+ make sure to use latest Rider package in Unity.
