### ISSUE TITLE
Handle UnityEditor.dll being split into modules

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#1699]
Unity 2020.2 is splitting `UnityEditor.dll` into modules, e.g. `UnityEditor.CoreModule.dll`. This breaks existing external annotations for UnityEditor. Also make sure that we don't look for `UnityEditor.dll` without a fallback to `UnityEditor.CoreModule.dll.

See comments on #19 and #143

**Comment by aybe** [comment]
It shouldn't be possible to `CreateAssetMenu` for `Editor` type unless I'm mistaken:

![devenv_2020-06-17_17-43-25](https://user-images.githubusercontent.com/1537591/84919316-1161fd80-b0c2-11ea-8a8e-88c739f66175.png)

**Comment by citizenmatt** [comment]
Yeah, sounds like a bug. Can you create a new issue so it doesn't get lost in the `UnityEditor` split work, please?

**Comment by aybe** [comment]
here #1702

**Comment by citizenmatt** [comment]
See also [RIDER-46544](https://youtrack.jetbrains.com/issue/RIDER-46544)
