### ISSUE TITLE
Removed Classes > extension method from Editor > Color Scheme > Language Defaults 

### ISSUE THREAD

**Issue by hovo94** [JetBrains/resharper-unity#1716]
Extension methods now using same color scheme as the regular instance method color.
It is very very useful to have extension method with different color from instance method. Helps very much with navigation in the script. Please add it back.

**Comment by citizenmatt** [comment]
These settings were moved to a C# specific page in a recent release of Rider. You can change the colours there:

<img width="1109" alt="Screenshot 2020-06-27 at 4 17 28 pm" src="https://user-images.githubusercontent.com/222659/85925679-ed58a600-b891-11ea-8009-363e333b8c14.png">

**Comment by hovo94** [comment]
Great!! thank you very much!
