### ISSUE TITLE
Useless auto-property suggestion for EditorTool.iconContent

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#1721]
If you try to do it then you'll get _New accessor introduction not allowed_:

Example:

https://docs.unity3d.com/ScriptReference/EditorTools.EditorTool.html

**Comment by citizenmatt** [comment]
I don't see any suggestions to convert `m_IconContent` into an auto-property, so I think this might have already been fixed in core Rider/ReSharper. I'm closing for now, if it's still an issue, please reopen.
