### ISSUE TITLE
Collaborate support for Rider.

### ISSUE THREAD

**Issue by mihakrajnc** [JetBrains/resharper-unity#173]
We were always using git but have now switched to Collaborate as it offers a much better workflow when artists and level designers are working on the project.

And one of the things I really love(d) about the Git integration in Rider / other IntelliJ based products is the ability to see changes in your files, line by line, and being able to revert each line separately.

Is this a feature that could be integrated into the Unity extension? Pushing / pulling changes isn't a really big feature really, as you basically always have Unity opened alongside Rider, but seeing changes would be a really useful feature.

Looking around, there is a way of getting the project history: https://forum.unity3d.com/threads/please-consider-providing-an-api-like-github.472931/

Thoughts?

**Comment by van800** [comment]
Added a request for Rider https://youtrack.jetbrains.com/issue/RIDER-7609

**Comment by van800** [comment]
Meanwhile you may try the local history in Rider https://blog.jetbrains.com/dotnet/2017/05/17/local-history-rider-undo-redo-steroids/

**Comment by citizenmatt** [comment]
Looks like Collaborate is being rewritten, based on Git. See [this blog post](https://blogs.unity3d.com/2019/05/23/the-first-steps-to-a-new-collaborate/).

**Comment by van800** [comment]
closing this in favor of https://youtrack.jetbrains.com/issue/RIDER-7609
