### ISSUE TITLE
UnityEngine.Object to bool operator is confusing R#

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#1735]
Using this facility ends up confusing R#, but good old check `!= null` does not, however:

![devenv_2020-07-04_18-54-22](https://user-images.githubusercontent.com/1537591/86517252-cb2dcd80-be27-11ea-9c62-f4b447771a08.png)

**Comment by citizenmatt** [comment]
Should be fixed with #1906 (available in Rider/ReSharper 2020.3, starting with EAP6)
