### ISSUE TITLE
Adding null elements to list marked as ItemNotNull doesn't give a warning

### ISSUE THREAD

**Issue by JeromeJ** [JetBrains/resharper-unity#1757]
Not sure if it would be possible to implement because List.Add's parameter is tagged as CanBeNull but I feel like it should or it kinda ruins the point of using it since code analysis doesn't protect us in this scenario.

**Comment by citizenmatt** [comment]
Can you provide some more context, please? Perhaps an example? Is this a Unity specific issue?

**Comment by JeromeJ** [comment]
@citizenmatt Yes sorry,

```
public class A {
  [NotNull] [ItemNotNull]
  public List<Foo> Bar = new List<Foo>();

  public A([CanBeNull] Foo other)  {
    Bar.Add(null); // No warning that i'm potentially doing something unintended.
    Bar.Add(other); // Same
  }
}
```

Ideally, it would work the same way as when trying to assign something potentially null to something marked as not null.

**Comment by citizenmatt** [comment]
Yeah, this repo is just for the Unity support, we can't do anything about issues with the main Rider/ReSharper product, such as C# analysis. You can use the support link you've posted, or raise issues in the main issue tracker - https://youtrack.jetbrains.com.
