### ISSUE TITLE
Add support for including existing projects to sln

### ISSUE THREAD

**Issue by sionzeecz** [JetBrains/resharper-unity#176]
Hi, when I add another project to the solution on 'OnGeneratedCSProjectFiles' it will disappear.
So I added custom *.csproj to the UpgradeProjectFile

```var currentDirectory = Directory.GetCurrentDirectory();
var projectFiles = Directory.GetFiles(currentDirectory, "*.csproj");
var apiFiles = Directory.GetFiles(currentDirectory + "\\~API", "*.csproj"); // There are double back slashes

foreach (var file in apiFiles) {
	UpgradeProjectFile(file);
}

foreach (var file in projectFiles) {
	UpgradeProjectFile(file);
}
```
As you can see above.

So I checked .sln file if there is reference to the project. (Yup it is there -- added in rider press right click on sln project and 'Add existing project...').
Debug notify post-processing about new .csprojs but otherwise it will disappear again.

When parsing slnContent in OnGeneratedCSProjectFiles, the line with my reference to my project is not there. But when I open .sln file in notepad++, the line with reference exists. (before file being parsed)

Any ideas?

Using latest reshaper-unity,
unity: 5.6.2f1

**Comment by IvanPashchenko** [comment]
@sionzeecz I'd strongly advise against modifying RiderPlugin/RiderAssetPostProcessor code directly, as it is going to get rewritten when the plugin updates and you will lose the changes you've made to it. Does this still happen if you implement your own plugin with OnGeneratedCSProjectFiles handler?

**Comment by sionzeecz** [comment]
Oh, it looks like you have true, that is not being due OnGeneratedCSProjectFiles.
I commented that line in Unity3DRider.cs (OnOpenedAsset after InitRiderPlugin).
It looks like the reference to the project is lost when I open any script in Unity.

I tried to find what is it doing. 
When I commented SyncSolution() it works now.

So it's mean it's a function inside Unity :\
https://github.com/MattRix/UnityDecompiled/blob/master/UnityEditor/UnityEditor/SyncVS.cs
line: 189

**Comment by van800** [comment]
Unity will update sln file anyway. Maybe it will just be less frequent.
Describe your setup, why do you need this new project in the sln?
Consider making separate solution, like in this video.
https://www.youtube.com/watch?v=pJPtlEDIemw&feature=youtu.be

**Comment by citizenmatt** [comment]
Is it worth updating Unity3dRider to find extra .csproj files and add them as project references instead of letting Unity add them as file references? Something like what's described in [sailro/UnityExternal](https://github.com/sailro/UnityExternal)?

**Comment by van800** [comment]
@citizenmatt is this approach popular? all commits are from 2015.

**Comment by citizenmatt** [comment]
I don't know, to be honest. It's a sample repo, so last commit isn't necessarily a good indicator. I'll ask on the Unity Slack.
