### ISSUE TITLE
Possible System.NullReferenceException warning if checking for UnityEngine.Object

### ISSUE THREAD

**Issue by ManuelRauber** [JetBrains/resharper-unity#1799]
Hi,

if you check a `UnityEngine.Object` to be null or not, you simply can do the following:

```csharp
private void Update() {
   if (!someGameObject) {
    // is null
    return;
  }

  // is not null here
  someGameObject.DoSomething(); // Possible System.NullReferenceException
}
```

In the last line Rider still suggests that `someGameObject` could be null, which I think is not correct.
That line of code should not be reachable due to the return statement in the if-branch, when `someGameObject` is null.

**Comment by citizenmatt** [comment]
I think this is fixed with #1906 (it will be in EAP6 of Rider 2020.3), but I can't get the original issue to show a warning without adding `[CanBeNull]`. Can you please confirm the repro sample - how is `someGameObject` declared, etc.? I'm closing for now, but happy to reopen if it's not fixed.
