### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by dantreble** [JetBrains/resharper-unity#18]
It doesn't appear in my Extension Manager :-(

http://imgur.com/cjnimga

**Comment by dantreble** [comment]
Please close this, it is now working!

Sadly, I'm not sure what it was that fixed it.

I added this feed https://resharper-plugins.jetbrains.com/api/v2/curated-feeds/Wave_v4.0/ (that alone didn't fix it)

I updated to 10.0.2
To update to 10.0.2 I had to mess around with my license and create a jet brains account

**Comment by citizenmatt** [comment]
Glad to hear it's working!
