### ISSUE TITLE
Distribute Unity3dRider as a dll

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#181]
Next Unity 2017.2 will load precompiled managed dlls upon editor startup, even if there are compile errors in user scripts.
So distributing as a dll will ensure plugin is loaded.

**Comment by van800** [comment]
I wanted to try the Assembly Definition Unity feature, but for now it doesn't seem to work
https://forum.unity3d.com/threads/example-project-assembly-definition-files.482313/#post-3147625

**Comment by citizenmatt** [comment]
If we use a .dll, we'll need to make sure we only use APIs that are available to _all_ versions of the Unity Editor that we support, or ship multiple dlls. Another alternative is a source file that we use to bootstrap loading a .dll that doesn't need to be versioned. This might be useful as we put more functionality into the Unity Editor plugin, e.g. for "Attach and Play".

**Comment by van800** [comment]
I am considering working solution as a bootstrap dll which loads a proper unity-package (stored in  resharper-unity resources)
In future we can ask Unity-team to put the bootstrap part to Unity itself.

**Comment by van800** [comment]
fixed in 2018.1, not public yet
