### ISSUE TITLE
No way to disable erroneous ShaderLab syntax errors

### ISSUE THREAD

**Issue by cchrisman** [JetBrains/resharper-unity#183]
The syntax for Unity ShaderLab .shader files seems to fail to parse a number of valid syntax constructs.  The README states it has "limited support for CG/HLSL"  while CPGROPGRAM / ENDCG blocks do appear to work, but CGINCLUDE / ENDG blocks immediately cause syntax errors.  There are a number of other places where it seems to fail to parse files that Unity's shader compiler accepts without error.

I can understand it may be useful for some projects, but since it appears to be a work in progress, it would be great if there was a way to disable syntax checking for .shader files.  

I've tried to do this in several ways via Rider settings directly, such as removing "*.shader" from the list of registered patterns for the Editor -> File Types -> ShaderLab type.  I've also tried adding "*.shader" to the list of Ignored files and folders in the same dialog, but in both cases, the solution will still parse and display errors for .shader files.  In our project this results in hundreds of errors, which as you can imagine, makes in-solution error analysis sort of useless. 

The only solution I've found is to disable the Unity Support plugin altogether.

**Comment by citizenmatt** [comment]
Do you have an example of the failing syntax? The parser recognises `CGINCLUDE`/`ENDCG` blocks, and successfully parses all of the builtin shaders, for example.

**Comment by cchrisman** [comment]
I'm attaching a really simple Unity project with a shader that reproduces two of the most common errors I'm seeing.

1. CGINCLUDE directives (not sure what about my example differs from your tests)

2. #warning pragmas

There are a few more errors, but it would take a lot more work to rip them out into something that would still compile in a standalone project.  It definitely wasn't my intention to try to enumerate all of the possible fixes to ShaderLab syntax checking, but I would very much like a way to disable or skip syntax checking for this, even if it works flawlessly.

I have voted for this Rider issue: https://youtrack.jetbrains.com/issue/RIDER-6387 but I have no idea when it will make it into a release.

[RiderShaderParsing.zip](https://github.com/JetBrains/resharper-unity/files/1157569/RiderShaderParsing.zip)

**Comment by Baste-RainGames** [comment]
This is really annoying!

When you upgrade a Unity project, Unity automatically updates shaders. One of the things it does is to insert warning comments on top of project. Like this:
`#warning Upgrade NOTE: unity_Scale shader variable was removed; replaced 'unity_Scale.w' with '1.0'`

Now Rider shows the entire file as not compiling, with the error message "shader expected".

There's also some other valid syntax that fails, but that is the biggest one. In our main project, Rider's showing 52 erroneous errors in 40 files. This causes the normal "Go to next/previous error" shortcuts to almost always jump to a shader file instead of the file that's got a real error.

**Comment by citizenmatt** [comment]
Sorry folks. These `#warning` and `#error` directives are undocumented, and I hadn't encountered them until now (my main test suite is the built in shaders source code). Also, a misunderstanding of how Unity processes `CGINCLUDE` and `CGPROGRAM` blocks meant a bad assumption about where the parser expects them to be found.

I've just pushed a workaround which allows you to disable the ShaderLab parsing, and we're just looking to see if it can make the cutoff for the next release.

The good news is that the nice folks at Unity have been very helpful, and I'll be able to fix the parser to correctly handle all of these edge cases.
