### ISSUE TITLE
Rider automatically clean up unity window log

### ISSUE THREAD

**Issue by ZhouJiaZhi** [JetBrains/resharper-unity#1845]
**macOS: 10.15.4
unity: 2019.4.10f LTS
rider version: 2020.2.2** 
I encountered a problem. If I switch the unity scene, the rider will automatically clear the unity window log. I don’t want him to clear my log, is there any solution for this？

**Comment by van800** [comment]
This is fixed in 2020.3, would appear in the first EAP. Sorry for the
inconvenience.
