### ISSUE TITLE
How to hide this prompt button

### ISSUE THREAD

**Issue by ZhouJiaZhi** [JetBrains/resharper-unity#1846]
The buttons in the red box as shown below, how to hide these things, I always accidentally press these buttons, I want to hide them
<img width="851" alt="截屏2020-09-15 上午11 55 49" src="https://user-images.githubusercontent.com/20750357/93163786-95239880-f74a-11ea-9095-d7ecabf1cba1.png">

**Comment by van800** [comment]
Look for "Code Vision" in the Settings.

**Comment by citizenmatt** [comment]
You can also use the "more" link to get to settings, and configure or disable it from there.

<img width="545" alt="Screenshot 2020-09-15 at 8 38 54 am" src="https://user-images.githubusercontent.com/222659/93180388-fc335400-f72e-11ea-8c60-3abb02e67993.png">
