### ISSUE TITLE
Struct Tips Bug

### ISSUE THREAD

**Issue by ZhouJiaZhi** [JetBrains/resharper-unity#1847]
When I use two struct variables as conditions for a while statement, he will prompt me that the loop will not terminate, but I have changed the value of the variable inside the loop, my code works  and the loop will terminate
<img width="805" alt="截屏2020-09-15 下午10 07 31" src="https://user-images.githubusercontent.com/20750357/93221219-0e99a600-f7a0-11ea-9802-1980235f9f1b.png">
If I use new operator to modify the variable, it won't prompt, so this should be a bug
<img width="815" alt="截屏2020-09-15 下午10 11 26" src="https://user-images.githubusercontent.com/20750357/93221485-69cb9880-f7a0-11ea-8865-4ef8e2d5e181.png">

**Comment by citizenmatt** [comment]
This is an issue in the core ReSharper analysis engine. I've raised a ticket against the product: [RSRP-481946](https://youtrack.jetbrains.com/issue/RSRP-481946)
