### ISSUE TITLE
tips for foreach

### ISSUE THREAD

**Issue by ZhouJiaZhi** [JetBrains/resharper-unity#1848]
When I use a **for** loop, the rider will prompt me to use **foreach**. Will using **foreach** to replace **for** as a loop will generate additional GC allocation? If it will increase the burden of GC, is this prompt not good?
<img width="800" alt="截屏2020-09-15 下午10 39 04" src="https://user-images.githubusercontent.com/20750357/93225026-591d2180-f7a4-11ea-8924-8451ccb8629a.png">

**Comment by van800** [comment]
Try to put caret on for and call Alt+Enter, menu would appear. In the menu there should be option to disable the suggestion.
The question is not at all related to Unity plugin. If you want any further details please open a ticket in https://youtrack.jetbrains.com
