### ISSUE TITLE
Exception on running unit tests in Rider

### ISSUE THREAD

**Issue by igisav** [JetBrains/resharper-unity#185]
I'm trying to run Unit Tests from Rider and got System.Reflection.TargetInvocation Exception (screenshot below).

```
OS: macOS Sierra 10.12.6
Rider: 2017.1 RC
Resharper Plugin: 2.0.0
Unity: 5.6.2
Mono: 5.0.1 (using MSBuild.dll 15.0)
TargetFramework: 4.5
```

Is this problem of Rider or Mono or Unity or this plugin?

<img width="995" src="https://user-images.githubusercontent.com/3278767/28585890-1d1d33e8-7172-11e7-8388-3035d950c83c.png">

If I change to Mono bundled in Unity, then I got instead:
```
Microsoft.Build.BuildEngine.InvalidProjectFileException: Cycle in target dependencies detected
  at Microsoft.Build.BuildEngine.Target.BuildOtherTargets (System.Collections.Generic
```

**Comment by IvanPashchenko** [comment]
@igisav Hi, this is a Rider issue.
https://youtrack.jetbrains.com/issue/RIDER-6711

**Comment by igisav** [comment]
@IvanPashchenko Thank you for reply. 
But I think, these are different problems, according to stack trace.
In linked issue is method `Mono.Cecil.TypeDefinition.get_Interfaces` not found, which is not the case in this issue.
Beside this, I **can run** unit tests of example project from 'steps to reproduce'.

**Comment by van800** [comment]
@igisav what are your tests like? I mean if they use GameObject, they can be run only in Unity itself. (https://github.com/JetBrains/resharper-unity/issues/96)

**Comment by IvanPashchenko** [comment]
@igisav 
![image](https://user-images.githubusercontent.com/8605238/28620090-28b5f7e2-7214-11e7-9ea7-09ef7aafd14f.png)

To us this seems the same issue, exception message can be different sometimes, but the get_Interfaces one is mentioned in comments of linked RIDER issue.

**Comment by igisav** [comment]
@van800 
1. The tests don't use GameObject or something Unity specific
2. Unity Test Tool was added in Unity and all tests are green in Unity3D
3. Solution was generated from Unity

**Comment by IvanPashchenko** [comment]
@van800 
This seems related: https://youtrack.jetbrains.com/issue/RSRP-463047

**Comment by igisav** [comment]
There is no possibility to combine Rider with Unity in a project now. 
I'm depending on unit tests. 
Changing the target frameworks doesn't help.
But even simple new project from Unity ends [with such error](http://answers.unity3d.com/questions/1333717/56-nunits-expectedexception-attribute-is-gone.html).
:tired_face:

**Comment by van800** [comment]
@igisav you mean problem with ExpectedException attribute?

**Comment by igisav** [comment]
@van800 No I mean in general, just as [you comment it today](https://youtrack.jetbrains.com/issue/RIDER-6711#comment=27-2346418&u=1499686359938), with new version Unity v5.6 and NUnit 3.

**Comment by SwamyDev** [comment]
I got the very same issue with the most recent Rider build 171.4456.2169 (3rd of August) on Unity 2017.1. However, the test run perfectly Unity 5.5.4 so I suspect the problem lies within Unity's test-tools as I think they upgraded from NUnit 2.6 to 3.5 in Unity 5.6

**Comment by van800** [comment]
It is expected on mac and windows in the next nightly on jetbrains toolbox.
by https://github.com/JetBrains/resharper-unity/pull/256 and https://youtrack.jetbrains.com/issue/RSRP-459932
not yet fixed on linux.

**Comment by van800** [comment]
fixed in latest nightly

**Comment by FrankNine** [comment]
Sorry for commenting on a closed issue.
 
I also ran into this issue. And I worked around this by override nunit.framework reference from the one Unity provided to NUnit official release. The override postprocessor is committed to:
https://github.com/FrankNine/UnityNUnitReferenceOverride

**Comment by van800** [comment]
Do you mean VS+Re#? Because I believe we already do similar thing for Rider https://github.com/JetBrains/resharper-unity/pull/256/files

**Comment by FrankNine** [comment]
I was testing with Rider 2017.2 and totally missed the PR. I am very sorry for the disturbance.
