### ISSUE TITLE
A Question About ReSharper

### ISSUE THREAD

**Issue by ZhouJiaZhi** [JetBrains/resharper-unity#1858]
I’m writing Unity’s nunit test. I don’t want to display the reshaper prompt in the test file. Please see the picture below. If I add [SuppressMessage], the prompt disappears successfully, but my nuuit test contains a lot of files, and I don’t want to SuppressMessage is added to a file one by one. Is there any way to set the reshaper not to detect a special folder or special namespace?
<img width="757" alt="截屏2020-09-23 23 04 19" src="https://user-images.githubusercontent.com/20750357/94031467-762fa100-fdf1-11ea-8a44-04053b440ce7.png">

**Comment by citizenmatt** [comment]
Is this an issue for HeapView? In which case, can I suggest creating an issue in [controlflow/resharper-heapview](https://github.com/controlflow/resharper-heapview)?
