### ISSUE TITLE
Running Unity inspections from TeamCity

### ISSUE THREAD

**Issue by tallior** [JetBrains/resharper-unity#1869]
I am actually not sure if i should've reported this in this repo or in TeamCity.
We are using Rider, and also using TeamCity for building / running tests of our Unity based game(s).

One cool feature in Rider is inspections, and specifically Unity inspections.

In TeamCity, i have the option to run Resharper inspections (which comes out of the box with TeamCity).
My problem is that it seems the 2 inspections are not 100% identical - for example, Unity inspections are missing in TeamCity.

Is there any way to run these inspections as part of our CI pipeline?

**Comment by van800** [comment]
This was fixed targeting release 2020.3 EAP 2
in this issue https://youtrack.jetbrains.com/issue/RSRP-436208
I guess more info would be availble with EAP2 going public (should happen within a week).
If not, please ask directly in that issue comments.
Thanks!

**Comment by van800** [comment]
Update, got info it targets only EAP3. Should be available within 2-3 weeks.
