### ISSUE TITLE
Add Resume button to toolbar

### ISSUE THREAD

**Issue by JustinSchneider** [JetBrains/resharper-unity#1879]
Could we get a Resume button added to the toolbar? It's not critical, as you can use the Debug panel instead, but it'd be nice to not have to open the other panel to quickly step through breakpoints.

Something like this:
![resume](https://user-images.githubusercontent.com/4027412/94938628-18f5b880-049f-11eb-94ed-d5060d53737f.png)

I thought I'd be able to add it myself using Rider's menu customization, but I can't find the Unity plugin toolbar there.

**Comment by van800** [comment]
Do I understand correctly that Resume is about Debug?

**Comment by JustinSchneider** [comment]
@van800 Right, it's the button that's available in the Debug panel. When a breakpoint is hit, the button resumes execution.

The Unity plugin toolbar doesn't have this functionality, and being outside Rider's menu/toolbar system, it doesn't seem it can be customized to add the button there. I was just hoping for a more optimum way of being able to step through code without having to have the Debug panel open.

**Comment by van800** [comment]
If you want Resume button in the main toolbar it feels like a request to Rider itself. Right?

**Comment by van800** [comment]
There must be keyboard shortcut, btw

**Comment by JustinSchneider** [comment]
Oh, is the Unity-specific toolbar not something provided by the Unity plugin? My bad.

There is a keyboard shortcut (CMD+ALT+R), but I've always felt that having one way to do something doesn't mean there shouldn't be another.

**Comment by van800** [comment]
Toolbar with Jnity commands is part of the plugin, but why would you want to mix it with debugger action? Why not put it separately on the main toolbar?

**Comment by JustinSchneider** [comment]
I wanted it because I use the Unity plugin's toolbar to attach to the editor and play, and it just made sense to me to be able to look to that same space to move through code.

I get that the plugin's buttons are intended to match Unity's Play/Pause/Next buttons, but they don't really work the same way. In Rider, if a breakpoint is hit, the Pause button will not be activated (so that deactivating it resumes execution) just like pressing the Pause button in the Editor will not resume. When I had used VS previously, the Pause button and its state seemed to be bound to breakpoint pauses, so pausing/resuming in one would affect the other, whether the pause happened from the Pause button or a breakpoint.

If it's not the intent of the plugin to have this functionality, then I suppose it's not a request worth considering.

**Comment by van800** [comment]
Thank you for sharing your thoughts, might lead to some UX questions raised.

**Comment by citizenmatt** [comment]
You can add the _Resume Program_ action to the _Navigation Bar Toolbar_, under one of the groups such as _Toolbar Run Actions_. It's not visible unless you're actually debugging and stopped at a breakpoint. I don't think we'll be adding this in as part of the Unity plugin, as it's more related to the core product (it affects every project kind and not just Unity), and I understand that the team are already looking at the layout of the toolbar.

<img width="1680" alt="Screenshot 2020-10-02 at 8 37 32 pm" src="https://user-images.githubusercontent.com/222659/94962901-26d32a00-04ef-11eb-8480-f7ed1813ef96.png">
