### ISSUE TITLE
Unit tests were always Pending after a re-run

### ISSUE THREAD

**Issue by beaugunderson** [JetBrains/resharper-unity#1888]
Sharing both an issue and a workaround. In my Unity 2020.1.4f1 project I have some NUnit Editor tests. Using the NUnit runner in Rider works, but every second try (e.g. tests pass, I make some changes, then "Run Selected Tests" or "Repeat Last Run") goes into the Pending state forever. If I go to Diagnostics → Show Last Launch Log then it brings up an empty file.

Stopping that pending run after a few seconds and then running again via the same method always works, however. I have had an issue where if I stopped it immediately (because I knew it was going to go Pending) then the second try would also go Pending forever--it seems like I need to wait a second or two before stopping and starting again.

What fixed the issue for me was switching from "Build Policy: Automatic" to "Build Policy: Automatic (Whole Solution)".

**Comment by van800** [comment]
Are those tests EditMode?

**Comment by beaugunderson** [comment]
Yes, they're Editor tests.

**Comment by beaugunderson** [comment]
My workaround also stopped working, so maybe "Automatic (Whole Solution)" was a red herring. I did notice that if the tests get stuck in pending that making Unity the foreground process seems to un-stick them... It's probably also relevant that I'm on macOS Catalina. Let me know if there's any additional information I can provide! :)

**Comment by van800** [comment]
Looks like issue similar to https://youtrack.jetbrains.com/issue/RIDER-51761

**Comment by van800** [comment]
It might be worth to try Rider 2020.3 EAP.

**Comment by beaugunderson** [comment]
@van800 ah, cool; will do!

**Comment by beaugunderson** [comment]
hmm, 2020.3 EAP is worse...

![image](https://user-images.githubusercontent.com/61791/95684330-bccd1b80-0ba5-11eb-9628-1fbcf521dd9c.png)

this test sits in "Running" forever, and Unity locks up entirely (spinning beachball); aborting the test suite has no effect.

**Comment by beaugunderson** [comment]
hmm, went back to 2020.2 and it also wedges Unity reliably now...

**Comment by van800** [comment]
When you use different version of Rider, make sure to set it as External Editor in Unity.

**Comment by beaugunderson** [comment]
yup, I did that [image: 👍]

**Comment by van800** [comment]
Can you share code in the test?
Does the same issue reproduce with simple empty tests?

**Comment by van800** [comment]
@beaugunderson ^

**Comment by beaugunderson** [comment]
sorry for the delay--the test is very simple, and it's always this one that fails:

![image](https://user-images.githubusercontent.com/61791/96323971-2f8a2c80-0fd4-11eb-9654-d0e77cbb6168.png)

the `Timeout`, which i added just now, also has no effect sadly...

**Comment by beaugunderson** [comment]
when i run the test in debug mode it still wedges unity, and the test stays in this state with no debug output:

![image](https://user-images.githubusercontent.com/61791/96324064-97407780-0fd4-11eb-9f81-2862f2ed3731.png)

**Comment by beaugunderson** [comment]
i have a similar but different test, which always passes:

![image](https://user-images.githubusercontent.com/61791/96324097-c9ea7000-0fd4-11eb-950a-47f8deaf605e.png)

and i've verified that if i call `InitializeRulesWithLambda(0f)` normally in my scene that it does not wedge unity (which is one of the only differences between the test that wedges unity and the one that doesn't)

**Comment by beaugunderson** [comment]
ugh, so sorry, real bug in my code (infinite loop)!

but there is a real issue that the `[Timeout(5000)]` doesn't kill the test... is that known?

**Comment by beaugunderson** [comment]
ah, that does appear to be a [known issue](https://issuetracker.unity3d.com/issues/testrunner-nunit-tests-doesnt-time-out-when-timeout-attribute-is-set)... sorry again for the noise :)
