### ISSUE TITLE
Rider Won't Log Messages

### ISSUE THREAD

**Issue by Evaske** [JetBrains/resharper-unity#1915]
Hi,

I seem to be having an issue where Rider won't log Unity console messages. I can see warning and alert messages but not standard info ones.

Rider Version: 2020.2.4
Unity: 2019.4.13f1 Personal & 2020.1.11f1 Personal

Doing a simple `Debug.Log("Hello World");` I can see it appear in the Unity console window when pressing play but I never see it in the Rider logs, simply says Log is empty. I definitely have the 'Play mode' logs enabled and the 'Messages' button enabled.

![image](https://user-images.githubusercontent.com/819492/97711975-b13e8780-1ab5-11eb-82ef-b96c5a40f9aa.png)

![image](https://user-images.githubusercontent.com/819492/97712004-b8fe2c00-1ab5-11eb-9783-cb8c9728c3dd.png)

![image](https://user-images.githubusercontent.com/819492/97712104-e5b24380-1ab5-11eb-812f-bec3a4cd9f25.png)

![image](https://user-images.githubusercontent.com/819492/97712020-c0253a00-1ab5-11eb-977c-b38d31ac66da.png)

Any ideas?

**Comment by neo-mashiro** [comment]
I have the same issue, Unity console logs are not passed to Rider as expected. Have you solved it?

**Comment by van800** [comment]
Try 2020.3 EAP builds.
