### ISSUE TITLE
Support for Resharper 2017.2

### ISSUE THREAD

**Issue by persn** [JetBrains/resharper-unity#193]
Like the title says, I would like support for Resharper 2017.2

**Comment by citizenmatt** [comment]
The plan is to do this over the next couple of weeks, as we get closer to release. The ReSharper releases have fallen behind as we've been concentrating on Rider, so I need to do some testing of the ShaderLab support and fix a few known parser errors.

**Comment by rolek** [comment]
It's released, any chance for an update please ?

**Comment by citizenmatt** [comment]
Done. Now available in ReSharper's extension manager.
