### ISSUE TITLE
[MetaFileTracker] How come R# creates meta files for non-Unity projects ?

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#1930]
I don't have Unity running in background,

Just realized that R# creates meta files even for non-Unity projects:

![devenv_2020-11-20_00-45-53](https://user-images.githubusercontent.com/1537591/99737981-ca8d8f00-2ac9-11eb-907a-f7250e2a85d6.png)

If I uninstall the extension, problem is gone:

![devenv_2020-11-20_00-46-42](https://user-images.githubusercontent.com/1537591/99738053-eb55e480-2ac9-11eb-8447-ea27a2afd249.png)

**Comment by aybe** [comment]
And for the record, R# is creating meta files on a `MS Test Project (.NET Core)` project.

**Comment by citizenmatt** [comment]
Where are the files for the test project in relation to the rest of the Unity project? Under `Assets` or alongside?

**Comment by aybe** [comment]
- Rijji
  - Assets
    - ....
  - Projects
    - RijjiTests
      - Graphics
        - meta files are here, next to the .cs files

**Comment by van800** [comment]
Fixed with https://github.com/JetBrains/resharper-unity/pull/1489 and https://github.com/JetBrains/resharper-unity/pull/1491

**Comment by van800** [comment]
Likely fixed by https://github.com/JetBrains/resharper-unity/pull/2000
