### ISSUE TITLE
Unabe to attach Rider 2020.2 to debug Unity 2020.1.14f project

### ISSUE THREAD

**Issue by ivaylo5ev** [JetBrains/resharper-unity#1934]
I am unable to debug unity code with Rider. Every time I attempt to connect the debugger, I receive:

> Failed to connect: No connection could be made because the target machine actively refused it 127.0.0.1:56300
> Unable to connect to Unity Editor

The issue pointed me at looking at my firewall settings, but both rider and unity were granted access to private and public networks. My current setup is on a private home network.

I am capable of debugging the same project it via Visual Studio 2019 though, which probably means the problem lies within Rider.

Here is some info on my setup:
Unity Version: 2020.1.14f (latest to date), installed today
Rider 2020.2.4 (installed today after removing Rider 2020.1.4, which also could not be used to debug the project)
OS: Windows 10 Pro, v 2004

**Comment by van800** [comment]
Try checking the Debug Optimisation in Unity settings?
![image](https://user-images.githubusercontent.com/1482681/99986382-69a6d500-2daf-11eb-936d-e7f0626efe27.png)

**Comment by van800** [comment]
I can also take a look at Rider logs, available via Help->Collect Logs
If you want to submit them privately - use Help-> Report a Bug, argee to attach logs.

**Comment by ivaylo5ev** [comment]
> 
> 
> Try checking the Debug Optimisation in Unity settings?
> ![image](https://user-images.githubusercontent.com/1482681/99986382-69a6d500-2daf-11eb-936d-e7f0626efe27.png)

This was already set to  "Debug", I changed it to "Release" and then back to "Debug" just for seeing if it will make a difference, but no. Interestingly, I am able to "remote-control" unity trough the play/stop buttons in the IDE (meaning that Rider is able to talk to Unity), if this information is useful

**Comment by van800** [comment]
Debugging and Controlling PlayMode uses different communication channels.
You may try to attach with Run-> Attach to Unity process. Would it use different port.
Would be interesting to check which port VS uses.
We determine connection port by using process ID like: 56000+pid%1000.
You may also check if there are any Unity.exe processes running in backgroud, you may use Process Explorer for that.

**Comment by ivaylo5ev** [comment]
[EditorPlugin.19300.log](https://github.com/JetBrains/resharper-unity/files/5584420/EditorPlugin.19300.log)
Here, attaching a log

**Comment by ivaylo5ev** [comment]
Well
