### ISSUE TITLE
Quick view documentation for C# interfaces

### ISSUE THREAD

**Issue by gayanW** [JetBrains/resharper-unity#1936]
How to configure ReSharper so as to make quick view documentation popup display additional information such as the method summary for C#'s native symbols?

![Screenshot from 2020-11-25 13-37-39](https://user-images.githubusercontent.com/5927747/100215590-2f683f80-2f37-11eb-9a9c-69a7a405aba8.png)

Currently, for methods, it only displays its method signature.

**Comment by van800** [comment]
![image](https://user-images.githubusercontent.com/1482681/100219237-05eaec00-2f16-11eb-841c-fb026a458d08.png)

There is a certain prerequisite for this to be shown
 - mono with documentation should be installed and Rider settings should point to it.
![image](https://user-images.githubusercontent.com/1482681/100219667-932e4080-2f16-11eb-905c-a3a60ee8144a.png)


Related to https://youtrack.jetbrains.com/issue/RIDER-11155
