### ISSUE TITLE
Moving file to new namespace folder empties root namespace in project properties

### ISSUE THREAD

**Issue by Zaimatsu** [JetBrains/resharper-unity#1947]
1. Under Assembly-CSharp->Properties set `Root namespace:` to RootNamespace.
2. Add namespace to existing file e.g. `RootNamespace.Something { ... }`.
3. Use refactor option `Move file to new folder '<Assembly-CSharp>\Assets\Scripts\RootNamespace\Something'`.
4. Observe new warrning `Namespace does not correspond to file location, should be: 'Something'`.
5. Under Assembly-CSharp->Properties the field `Root namespace` is empty.

**Comment by van800** [comment]
Root namespace is something, which we don't control for Unity-generated projects.
Unity 2020+ has option to set custom namespace for each asmdef, see 
https://youtrack.jetbrains.com/issue/RIDER-36546#focus=Comments-27-4206877.0-0
Previous versions only allowed setting one rootnamespace for the whole solution.

**Comment by Zaimatsu** [comment]
For anyone interested you can change root namespace for whole solution in Unity under:
`Edit->ProjectSettings->Editor->C# Project Generation->Root namespace`
