### ISSUE TITLE
The logic bug of 'ReplaceWithSingleCallToCount'

### ISSUE THREAD

**Issue by kelicto** [JetBrains/resharper-unity#1951]
Please see the bug demo: https://github.com/kelicto/ReplaceWithSingleCallToCountBug.

**Comment by citizenmatt** [comment]
Hi. This looks like a bug that can't be fixed in the Unity support for Rider/ReSharper provided by this repo. Could you create an issue in https://youtrack.jetbrains.com, please?

**Comment by kelicto** [comment]
Thinks, I do it.
