### ISSUE TITLE
Got "Resharper is thinking..." problem when hit Resharper hotkeys sometimes

### ISSUE THREAD

**Issue by weskao** [JetBrains/resharper-unity#1956]
After I installed this Resharper extension, 
I got a problem that sometimes when I hit any of Resharper hotkeys in Visual Studio 2019, 
I got "Resharper is thinking..." showed in screen and I found that IDE is reload Resharper again. 
Did there any solution can provide to me? Thanks.

Here are versions of my develop tools:

- Visual Studio 2019: 16.8.2
- Unity: 2017.4.361

**Comment by van800** [comment]
We are not aware of such issue. Without logs it is impossible to investigate.
Please use https://www.jetbrains.com/help/resharper/Providing_Feedback.html
Agree to attach logs. Thanks!

**Comment by weskao** [comment]
Hi @van800 
Here are my environment information and Resharper logs.
1.**environment information**
Visual Studio:
Version: 16.8.30717.126
Sub Edition: None

Installed Products:
ASP.NET Core Razor Language Services 16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
ASP.NET Web Frameworks and Tools 2019 16.8.553.28003
AzureAppServiceToolsPackage 16.8.553.28003
ClaudiaIdePackage 2.2.14
CodeMaid 11.1.209
CommonAzureToolsPackage 1.10
ContainersToolsPackage 1.0
DebugAdapterHostPackage 1.0
DevOpsPackage 0.4
DockerComposePackage 1.1
ExtensionsPackage 1.0
FileIconPackage 2.7
IntelliCodePackage 1.0
KofePackagePackage 1.0
LibraryManagerPackage 2.1.113+g422d40002e.RR
Microsoft Azure Tools for Visual Studio 2.9
Microsoft SQL Server Data Tools 16.0.62010.06180
Microsoft Visual Basic 3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a
Microsoft Visual C# 3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a
Microsoft Visual F# 16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
MIDebugPackagePackage 1.0
NuGetPackage 5.8.0
ProjectServicesPackage 1.0
ReSharperPlatformVs16
SelectNextOccurrencePackage 1.3.172
Team Explorer
TypeScriptPackage 16.0.21016.2001
UnityPackage 4.8.2.0
VSPackage 1.0
WebJobsPackage 16.8.553.28003
WebProjectPackage 16.8.553.28003
WordHighlightPackage 1.0

.NET Framework:
Versions: 3.5.0;4.8.0


2.**Resharper logs**.
[JetBrainsLog.JetBrains.2020-12-09T15-28-39.devenv#14340.log](https://github.com/JetBrains/resharper-unity/files/5664477/JetBrainsLog.JetBrains.2020-12-09T15-28-39.devenv.14340.log)

**Comment by van800** [comment]
I am sorry, but this has to be reported to Re# bugtracker.
I see OutOfMemory in the logs, maybe you can try disabling solution wide analysis or something else, just to free up some more memory in VS process. You would get a better advice in Re# bugtracker.

**Comment by weskao** [comment]
OK, thanks for your advice.
