### ISSUE TITLE
Cannot resolve symbol fixed4 and SurfaceOutput in shader file

### ISSUE THREAD

**Issue by shiena** [JetBrains/resharper-unity#1957]
JetBrains Rider 2020.3 EAP 10
Build #RD-203.5981.86, built on December 3, 2020

Unity Support bundled 2020.3.0.99

If there is no script in the Unity project, an error occurs.

![image](https://user-images.githubusercontent.com/1295639/101525527-c79e0400-39ce-11eb-854e-6238dfb1ff1c.png)

**Comment by van800** [comment]
This must have been fixed with newer Rider package - try updating to the most recent (3.0.6).
If it would not help - please follow this request https://youtrack.jetbrains.com/issue/RIDER-60508
