### ISSUE TITLE
Warn about Camera.main usage in Update functions

### ISSUE THREAD

**Issue by Zod-** [JetBrains/resharper-unity#196]
`Camera.main` basically calls `FindGameObjectWithTag("MainCamera")` in the background, which you never really want to do in methods that get called often like `Update`, `FixedUpdate` etc. What you want to do instead is cache the reference. 
With each tagged object in the scene the performance will get worse and can get as bad as a few ms per call.
An issue I see with this warning is when the main camera changes a lot but I would think that a project like that would implement it's own system for handling that reference.

This is a similiar issue to the `Find` and `GetComponent` warning in #107

**Comment by ahokinson** [comment]
I'll weigh in and say that this isn't a problem JetBrains should be solving. Maybe I'm wrong, but does Resharper or Rider give performance hints through warnings already? If not, I wouldn't suggest opening that floodgate.

**Comment by Zod-** [comment]
@ahokinson isn't that what the compare tag analyzer already does too?

`"Explicit string comparison with GameObject.tag or Component.tag is inefficient. Use the CompareTag method instead."`

**Comment by StephenHodgson** [comment]
I agree with @Zod- here.

**Comment by citizenmatt** [comment]
I think this can be expanded. There seem to be a list of functions that are very slow and shouldn't be called each frame. It makes sense to call them all out.

So, I need a best effort exhaustive list of methods that should be avoided:

* `MonoBehaviour.Update`
* `MonoBehaviour.LateUpdate`
* `MonoBehaviour.FixedUpdate`

Or is it easier to have a list of magic methods that these slow functions can be called from? `Start`, `Awake`, etc?

And a list of known slow methods/properties that should be cached:

* `Camera.main`
* `Object.FindObjectOfType`
* `Object.FindObjectsOfType`
* `Resources.FindObjectsOfTypeAll`

What else?

**Comment by citizenmatt** [comment]
I've just pushed a new inspection for `Camera.main` in `FixedUpdate`, `Update` and `LateUpdate`, because I'd already written it by the time I asked the question above :)

But please reply and I'll create a new issue to expand this for other methods and properties that should be avoided.
