### ISSUE TITLE
clr exceptions missing

### ISSUE THREAD

**Issue by friuns2** [JetBrains/resharper-unity#1961]
just updated from 2019.3 to 2020.2
and now clr exceptions gone, can't filter by null reference exception and others anymore
![image](https://user-images.githubusercontent.com/16543239/101848171-7ff9b280-3b5d-11eb-9a36-6e3bffea8828.png)

**Comment by van800** [comment]
I am sorry, this has nothing to do with this plugin, it is Rider core functionality.
Please report with Help -> `Report a Bug` in Rider itself.
