### ISSUE TITLE
Unity cannot detect Rider, that installed from the AUR

### ISSUE THREAD

**Issue by ArtemkaKun** [JetBrains/resharper-unity#1974]
Hi.

**Problem**

Manjaro distro. I installed Rider from the AUR (via yay). Unity 2020.2.0f1, JetBrains Rider Editor package version 3.0.3. 

I have no Rider in the External Tools dropdown :(

For which, who wants to use Rider from AUR with Unity - select rider's execution file /usr/bin/rider

**Comment by van800** [comment]
Hi!
There are options:
1. You can browse from it in the file-system. Would that work for you?
2. You can use JetBrains Toolbox App
3. You can send us a pull request here https://github.com/van800/com.unity.ide.rider, specifically this code https://github.com/van800/com.unity.ide.rider/blob/master/Packages/com.unity.ide.rider/Rider/Editor/Discovery.cs#L106

**Comment by van800** [comment]
You may also use snap, if it is supported by your linux distribution.
