### ISSUE TITLE
Rider setting panel "Unity Engine" only displays "Loading..."

### ISSUE THREAD

**Issue by partlyhuman** [JetBrains/resharper-unity#198]
Settings panel displays loading indicator but nothing ever appears. See image. Rider 2017.1 (RD-171.4456.2169). On Windows 10 Creators Update. Attempted with Windows Firewall disabled, no change.

![image](https://user-images.githubusercontent.com/327136/29098558-d17cffa2-7c54-11e7-836f-48eea0f4fedf.png)

**Comment by citizenmatt** [comment]
Could you check to see if there are any exceptions reported in Rider? Check the bottom right of the status bar for a red exclamation mark.

**Comment by van800** [comment]
Exception reporting is disabled in Release build, so please attach logs from Help->Show log in Files

**Comment by partlyhuman** [comment]
Logs revealed that this was my fault. I had known issue '"Your evaluation license has expired" error message after 1st Rider launch' and deleting the .Rider2017.1 and reinstalling didn't fix it. I got a little aggressive and removed `%AppData%\Local\JetBrains\Shared\`, which nuked the plugin dll `JetBrains.ReSharper.Plugins.Unity.dll`. I wasn't aware this was happening until I hit the logs. Sorry for the misfile, user error! (Reinstall solved this)
