### ISSUE TITLE
Fixing asmdef "rootNamespace" leads to a duplicate namespace suggestion

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#1988]
ReSharper 2020.3.2
Unity Support 2020.3.1.132

So R# tells there's an error in amsdef, suggesting you to set `rootNamespace` because it's empty:

_JSON validation failed: String length must not be less than 1_

If you do so then it complains that `namespace A.B` should be `namespace A.B.A.B`.

Please note that:

Error doesn't always appear, as I've set it back to `""` to ensure it's the source of the bug, R# does not show an error on lower right, only when you open the asmdef you can see there is one.

It also affects `Namespace Provider` for folders.

So right now, the only fix is to ignore this error in asmdefs to get normal behavior back.

**Comment by aybe** [comment]
Forgot to mention,

Basically R# should do the following:

1. if root namespace is not set, imply that namespace is usual, e.g. without Assets/Scripts
2. it root namespace is set to what it should be by default then it's a no-op, all is good
3. if root namespace is different, then make sure R# tracks it properly so it doesn't error

**Comment by citizenmatt** [comment]
If the root namespace matches the folder structure you've already got, then there's no need to specify it in the `.asmdef` file. Rather than leaving the field empty, with validation errors, simply remove the field from the file.

**Comment by aybe** [comment]
> If the root namespace matches the folder structure you've already got, then there's no need to specify it in the `.asmdef` file. Rather than leaving the field empty, with validation errors, simply remove the field from the file.

Makes a lot of sense, thanks!

**Comment by aybe** [comment]
@citizenmatt 

For what it's worth,  I have finally been able to figure out why does this subtelty happens in my case.

Juggling between Visual Studio and Rider for a Unity project ends up confusing Resharper at some point, this is because the generated .csproj projects are slightly different depending which IDE is set in Unity. If I regenerate the project for Visual Studio, then the problem is gone.

**Comment by citizenmatt** [comment]
First thing is to make sure you've got the Unity extension installed in ReSharper (ReSharper -> Extension Manager, search for Unity). This has many of the same features as Rider's support, including the namespace handling. I'd expect everything to behave the same way with that.

**Comment by aybe** [comment]
I do have the extension installed, yes, it's night and day without it actually.

Rather, it's more the fact that Resharper for Visual Studio has features that Rider doesn't yet have, but at the same time Rider has features that Visual Studio doesn't have, so I end up using both 😁.
