### ISSUE TITLE
R# is making C# 9.0 suggestions

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#1989]
ReSharper 2020.3.2
Unity Support 2020.3.1.132

For instance, it's suggesting to use `is not null` instead of `!= null` which won't compile.

Now of course you can set a csproj language version but I guess it'll get lost as soon as Unity regenerates them.

**Comment by van800** [comment]
@aybe what Unity version do you run?
What do you see in the LangVersion tag in csproj?

**Comment by aybe** [comment]
@van800 I use 2020.2.1f1 and it reports `<LangVersion>latest</LangVersion>`.

**Comment by van800** [comment]
Sorry for the late reply, somehow I have missed update on the issue.
Is it still actual for you? As I see newer Visual Studio package specifically writes LangVersion to 8.0.
However even if I manually update it to `latest`, the issue still doesn't reproduce with all default settings, unless I specifically set Re# setting to C#9 with this property
![image](https://user-images.githubusercontent.com/1482681/111437593-90dd3580-8703-11eb-9214-f70dd42df05e.png)

**Comment by aybe** [comment]
It's working fine now, thank you.
