### ISSUE TITLE
ignore directories for unity asset file cache processing

### ISSUE THREAD

**Issue by hitheqing** [JetBrains/resharper-unity#1990]
cache processing takes a lot of time for a large project  .and i want to ignore soem directories such as pngs,anim,etc.
![image](https://user-images.githubusercontent.com/21076521/103632925-f8e30300-4f7f-11eb-9549-6a05b418f69d.png)

**Comment by van800** [comment]
Try to use this settings page to ignore files based on their extensions or folders based on their names
![image](https://user-images.githubusercontent.com/1482681/103636125-d7672480-4f49-11eb-9ca4-53faf2bf8d21.png)

**Comment by hitheqing** [comment]
> Try to use this settings page to ignore files based on their extensions or folders based on their names
> ![image](https://user-images.githubusercontent.com/1482681/103636125-d7672480-4f49-11eb-9ca4-53faf2bf8d21.png)

it doesn't seems to work... 
![image](https://user-images.githubusercontent.com/21076521/104144829-d88fca00-53ff-11eb-89d4-64e2f4fec97b.png)

![image](https://user-images.githubusercontent.com/21076521/104144791-b433ed80-53ff-11eb-9a86-5b626db60cb6.png)

**Comment by citizenmatt** [comment]
You can disable cache processing of `.meta`, `.unity`, `.asset` and `.prefab` files in the _Preferences | Languages & Frameworks | Unity Engine_ settings page, by unchecking the "Parse text based asset files" checkbox. This will prevent Rider from seeing usages of C# code in Unity asset files.

However, the cache processing should only occur the first time you open a project (and when you update to a new version of Rider). Once the cache is built, it should be incrementally kept up to date. Are you seeing the cache being rebuilt every time you open the project? Please can you include some logs? Help -> Collect Logs will create a zip file with logs, and Help -> Submit Feedback/Report a Bug will automate the whole thing by collecting logs and attaching them to an issue at https://youtrack.jetbrains.com, where you can also control visibility of attachments to keep things private.
