### ISSUE TITLE
SerializeField attribute marked as redundant on fields of type Vector2Int

### ISSUE THREAD

**Issue by Ursanon** [JetBrains/resharper-unity#1992]
Actual:
`SerializeField` attribute is marked as redundant on fields of types: `Vector2Int` or `Vector3Int`.
No information about initialization from inspector is displayed.

Expected:
Should work as `Vector2` / `Vector3`.

Environment:
```
OS: Ubuntu 20.04
Unity: 2020.2.0f1
IDE: Rider 2020.2.4
Unity Support version: bundled 2020.2.2.328
```

Repro:
```
using UnityEngine;

public class ResharperRepro : MonoBehaviour
{
    [SerializeField]
    private Vector2 _vector2;

    [SerializeField]
    private Vector2Int _vector2Int;
    
    [SerializeField]
    private Vector3 _vector3;
    
    [SerializeField]
    private Vector3Int _vector3Int;
}
```

Preview:
Rider IDE:
![Screenshot from 2021-01-05 20-19-22](https://user-images.githubusercontent.com/8686134/103689256-5896d980-4f93-11eb-8939-9d7250d276e7.png)
Unity inspector:
![Screenshot from 2021-01-05 20-20-09](https://user-images.githubusercontent.com/8686134/103689379-88de7800-4f93-11eb-8f51-6cd53029a8e0.png)

**Comment by citizenmatt** [comment]
This has been fixed in Rider 2020.3 (See #1923).
