### ISSUE TITLE
Remove unused references

### ISSUE THREAD

**Issue by bartlomiej-dawidow** [JetBrains/resharper-unity#1994]
Rider 2020.2 added support for removing unused assembly references, a feature that was previously only available in ReSharper:
https://youtrack.jetbrains.com/issue/RIDER-7943

The feature is super helpful when working with larger projects. Unfortunately, the way it works it removes the references from the .csproj files. It would be great if it also worked with asmdefs. At the very list, it could print out the list of detected unused dependencies.

**Comment by citizenmatt** [comment]
The feature added in #2279 will work with "Remove Unused References". As the project references are removed, the `.asmdef` file is updated. There is no special integration into the "Remove Unused References" refactoring - the dialog will list all references that can be removed, even those added by default by Unity. When Unity next gets focus, these default assemblies will be re-added. However, any `.asmdef` files that are not used will not be added back.
