### ISSUE TITLE
Documentation link in popup goes to the wrong place

### ISSUE THREAD

**Issue by JurjenBiewenga** [JetBrains/resharper-unity#2004]
When clicking the documentation link in the mouse hover popup it tries to find the element that your text cursor is on on the documentation.
E.g.
Hovering `SerializedObject`
Text Cursor on `Selection`
Clicking the documentation link goes to [Selection](https://docs.unity3d.com/ScriptReference/30_search.html?q=Selection) instead of [SerializedObject](https://docs.unity3d.com/ScriptReference/30_search.html?q=SerializedObject)

**Comment by van800** [comment]
Please add a screenshot or a code-example. I don't see link in the documentation popup shown on hover.

**Comment by JurjenBiewenga** [comment]
![image](https://user-images.githubusercontent.com/3128681/105816064-78328800-5fbc-11eb-8d74-1a112c7cd945.png)
The link only shows if your text cursor is on a valid element that it might be able to find documentation for.

**Comment by van800** [comment]
Thank you, reproduced.

**Comment by van800** [comment]
Closed in favor of https://youtrack.jetbrains.com/issue/RIDER-57745
