### ISSUE TITLE
Documentation link should search the docs for the current version

### ISSUE THREAD

**Issue by JurjenBiewenga** [JetBrains/resharper-unity#2005]
Currently it tries to search the documentation for all versions however it would better if it would search the current versions documentation for which the url is: 
https://docs.unity3d.com/{Version(2018.4)}/Documentation/ScriptReference/30_search.html?q={Query}

**Comment by van800** [comment]
Not 100% sure, if it is applicable in all cases.
I have quickly tried in https://github.com/JetBrains/resharper-unity/pull/2006

https://docs.unity3d.com/2021.1/Documentation/ScriptReference/30_search.html?q=InitializeOnLoadAttribute
doesn't load results for me
![image](https://user-images.githubusercontent.com/1482681/105814847-4b797300-5fb2-11eb-9484-51aa072806aa.png)

**Comment by JurjenBiewenga** [comment]
Works fine for me, might be a local problem?
![image](https://user-images.githubusercontent.com/3128681/105816022-69e46c00-5fbc-11eb-9c5d-143634969fd9.png)
