### ISSUE TITLE
Rider hangs when filtering 'Unity Log' view

### ISSUE THREAD

**Issue by MassilY** [JetBrains/resharper-unity#2010]
```
Rider: 2020.3.2
Unity Editor: 2019.4.1
Unity Support Plugin: 2020.3.1.136
```

I have a Unity app that can be very verbose in its logging and when I use a filter in the LogView (whether by using the 'Hide Messages/Warnings/Errors' buttons or the input field) Rider will often hang for varying amount of time.

Hang time seems to be linked to amount of written logs and can range from a few seconds to hours in some cases.
Rider is shown as running fine in Windows Task Manager, with rider64.exe eating up 4~5% of my CPU time.

I can provide Rider logs if needed.
I can't provide the project I'm working on but probably could create a minimal project to reproduce the issue if necessary.

**Comment by MassilY** [comment]
Here's the issue over at youtrack: https://youtrack.jetbrains.com/issue/RIDER-57100

**Comment by van800** [comment]
Ok,  cool, I am closing this issue in favor of that new one. Thank you!
