### ISSUE TITLE
Renaming classes does not update .meta file

### ISSUE THREAD

**Issue by wrymn** [JetBrains/resharper-unity#2027]
**Description:**

Renaming classes via Rider does not update .meta file, breaking all references in a project.

1. Create a class
![image](https://user-images.githubusercontent.com/12801017/108072051-b58fb000-7066-11eb-83ce-abe34ce28f2e.png)

2. Rename it
![image](https://user-images.githubusercontent.com/12801017/108072233-ea036c00-7066-11eb-8ff0-91129e71730b.png)

3. Watch as .cs.meta filename stays the same and does not get named by this plugin

![image](https://user-images.githubusercontent.com/12801017/108072159-d5bf6f00-7066-11eb-85c9-a81b30421049.png)

Unity Support plugin version:

![image](https://user-images.githubusercontent.com/12801017/108072353-1323fc80-7067-11eb-9e00-8d5ec52bb358.png)

**Expected:**

Renaming a class should also rename associated .meta file, so the reference guid stays the same.

Unity settings:
![image](https://user-images.githubusercontent.com/12801017/108072271-fb4c7880-7066-11eb-862b-528648b331b5.png)

**Comment by citizenmatt** [comment]
I can't recreate this with 2020.3. Could you give some more details about your project, please? Is this a normal Unity generated solution, and is `ExampleClass.cs` part of the solution?

If this is reproducible, please can you enable logging for Unity by going to Help -> Diagnostic Tools -> Choose Trace Scenarios and check "Unity", and then try to rename again. You can use Help -> Collect Logs to create a zip file of your logs, which you can attach here, or use the Help -> Report a Bug if you'd prefer to keep your logs private (if you use Help -> Show Log in Explorer, it's the `backend.log` that I'd be interested in here)

**Comment by wrymn** [comment]
hey @citizenmatt, thank you for super quick response.

The file was created and is part of unity solution (it's located in unity's assets folder). I have tried to create brand new unity project, and there renaming works! Very strange. I have also tried to rename it while unity is closed, to make sure it's not locking the .meta file, but that is not the case.

Following are the logs:

[rider-logs-20210216-153407.zip](https://github.com/JetBrains/resharper-unity/files/5989312/rider-logs-20210216-153407.zip)

as above, I created **ExampleClass** using Rider into Assets folder and renamed it into **ExampleClassRenamed**, so the action should show in the logs.

**Comment by citizenmatt** [comment]
Does the problem persist after restarting? If so, can you try quitting Rider and renaming the solution file `charlie.sln` with a lowercase `C` and trying again?

We only update meta files for Unity generated solution, which means the solution name matches the folder name. Normally this means an exact match, including case, but your example has a folder name of `charlie` but a solution name of `Charlie.sln`.

**Comment by wrymn** [comment]
@citizenmatt  you are correct, it was the damn .sln naming! But I had to also delete .idea folder it seems, otherwise it did not work.

Cheers and thanks!

**Comment by citizenmatt** [comment]
Great, glad it's working again. Not sure exactly why deleting the `.idea` folder was necessary, but I do see that using the recent solutions list to load the solution will use the wrong case again. Either way, I've just pushed a change for Rider 2021.1 that will handle this scenario.
