### ISSUE TITLE
Show content of Tooltip attribute in QuickDoc tooltip

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#2032]
Serialised fields can use the `[Tooltip("…")]` attribute to provide a tooltip help message in the Inspector. It would be useful for Rider/ReSharper to show this tooltip as part of the QuickDoc. It would reduce the need for XML documentation on that field.

Furthermore, it might be useful to have a context action (not an inspection) on the summary for XML doc content for a serialised field to move it to a `[Tooltip("…")]`.

**Comment by Skjalgsm** [comment]
These two things should preferably just be [Tooltip]
![rider64_2021-02-18_14-19-11](https://user-images.githubusercontent.com/568589/108397330-1f02f080-7218-11eb-84e2-086c8ad24247.png)
