### ISSUE TITLE
R# is making C# 8.0 suggestions

### ISSUE THREAD

**Issue by rqx110** [JetBrains/resharper-unity#2033]
R# version: 2020.3.2

I have import `<LangVersion>latest</LangVersion>` config from a common file:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <Import Project="..\..\common.props"></Import>
   
  ...
```
where `common.props` has defined:
```xml
<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
...
```

but R# still suggest me to set the LangVersion:
![image](https://user-images.githubusercontent.com/1829209/108649306-089ab480-74f8-11eb-8c6b-182c849cc1c5.png)

![image](https://user-images.githubusercontent.com/1829209/108649447-4ef01380-74f8-11eb-82e5-a7dcf8cdea00.png)

**Comment by van800** [comment]
What Unity version do you have?

**Comment by rqx110** [comment]
I'm sorry, I found that this repo is for Unity platform, and I am not working on it. I will report this by Reshaper feedback.
Thanks anyway!

**Comment by van800** [comment]
(Some new Unity versions support C#8)
