### ISSUE TITLE
Makes bad suggestions for UseNullPropagation 

### ISSUE THREAD

**Issue by ChaosSlave51** [JetBrains/resharper-unity#2036]
When having code like
```
    if (MyGameObject!=  null)
    {
        MyGameObject.Invoke();
    }
```
Resharper will suggest 
` MyGameObject?.Invoke();`
 
 Unfortunately in Unity these are not equivalent. As the == is overloaded, to return destroyed objects as equal to null, and ? uses "is null" this will alter the code. This causes lot's of issues and bugs for anyone just trying to clean up their code. 

The plugin should suppress this behavior for anything of type GameObject/MonoBehavior and add a warning for the developer any time they try to use "is null", "is not null", "?" with GameObject and MonoBehavior

**Comment by citizenmatt** [comment]
Are you using the Unity plugin for ReSharper?

**Comment by ChaosSlave51** [comment]
> Are you using the Unity plugin for ReSharper?
Yes, I understand Resharper would not know this, but I think the plugin should handle this.

**Comment by citizenmatt** [comment]
What are the versions of ReSharper and the Unity plugin that you're using? I don't see the warning on the latest versions.

<img width="553" alt="Screenshot 2021-03-03 at 4 28 47 pm" src="https://user-images.githubusercontent.com/222659/109837921-9172c800-7c3d-11eb-90cf-dd0a39a1a572.png">

**Comment by citizenmatt** [comment]
I'm closing this issue as I can't recreate it locally. Please feel free to reopen with more details if it's still a problem on the latest version.
