### ISSUE TITLE
ShaderLab: wrong indent after non-recognized keywords

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#2037]
(for Visual Studio)

This is quite boring to say the least, whenever you enter a new line after say, `fixed4`, R# does not indent correctly:

```
            fixed4 frag (v2f i) : SV_Target
            {
                fixed4 col = tex2D(_Texture1, i.uv);
            float dist = distance(col.rgb);
```
Furthermore, it appears that it's R# that is disabling <kbd>Tab</kbd>, forcing you to press <kbd>Space</kbd> numerous times. Note that it doesn't matter whether file uses spaces or tabs for that particular issue.

On the other hand, a new line after `float4`, R# uses correct indent:

```
            fixed4 frag (v2f i) : SV_Target
            {
                float4 col = tex2D(_Texture1, i.uv);
                float dist = distance(col.rgb);
```

Thank you

**Comment by citizenmatt** [comment]
What version of ReSharper are you using? And what's the version of the ReSharper Unity plugin?

Also, can you confirm that you have the ReSharper C++ components installed and active, please? ReSharper -> Options -> Products & Features -> ReSharper C++. The shader support requires is based on ReSharper's C++ language

**Comment by aybe** [comment]
Right, enabling it does fix it ... partially ... now there's an entirely new set of bugs/ unwanted warnings.
I'll try to gather them all and open a dedicated issue about them.

Thank you 😃
