### ISSUE TITLE
Adding unity plugin to rider if it was absent

### ISSUE THREAD

**Issue by Sarseth** [JetBrains/resharper-unity#204]
Hey,
issue is that I do not have in rider eap this unity plugin. Had this when using windows, recently went for ubuntu. Unity works like a charm, Rider as well, but no plugin, so I have many warnings for monobehavious methos that are not used. Etc etc.
The problem is, in your guide is the settings are there already, but I do not have them. I've installed Rider through Jetbrains Toolbox. Preferences → Languages & Frameworks → Unity Engine. <- This does not exist. I do not have and cant find plugins in any repository. Is there any other way to install this plugin? Sorry if this is wrong place to ask this.

**Comment by citizenmatt** [comment]
When you look at Preferences &rarr; Plugins, is _Unity Support_ listed and the checkbox ticked?

**Comment by Sarseth** [comment]
Tried that. Dont have it there, that's the issue ;p And cant find any in by "Browse repositories". Rider 2017.1.1 EAP

**Comment by van800** [comment]
@Sarseth Could you please paste an exact buildnumber?

**Comment by Sarseth** [comment]
Build #RD-171.4456.2268, built on August 8, 2017

**Comment by van800** [comment]
I see, this build doesn't have Unity plugin (
171.4456.2475 is good

**Comment by Sarseth** [comment]
Hah ^^ Ok, that's good. At least I know that I am not blind. Thanks for checkig this out. But is there a posbility to install it manually? 
I can change version ofcourse, I am not attached to this version, but what's the issue with this version? Is it to old? To new? Are there specific version containing it, or not? For future reference, just to know if this will happen again.

**Comment by van800** [comment]
We will take action to avoid builds with broken plugins in toolbox.

**Comment by Sarseth** [comment]
Ok thank you very much for support. Have a nice day.
