### ISSUE TITLE
[Tests] UnitySetUp attribute does not tag the method as used

### ISSUE THREAD

**Issue by matheusamazonas** [JetBrains/resharper-unity#2048]
Unlike when using `[Setup]` on a method, `[UnitySetUp]` methods are not tagged as used and a tooltip "Method Setup is never used" is displayed. `[UsedImplicitly]` can be used, but should not be necessary.

**Expected behavior**: using `[UnitySetUp]` should tag the method as used and thus no tooltip/warning should be displayed.

**Experienced behavior**: methods with `[UnitySetUp]` are still being displayed as unused.

**Comment by van800** [comment]
fix would appear in Rider 2020.1.2
