### ISSUE TITLE
Open C# Project not working

### ISSUE THREAD

**Issue by marcelschmidt1337** [JetBrains/resharper-unity#205]
Since I upgraded to Rider 2017.1 released version, the menu item "Open C# Project" in Unity doesn't open the solution in Rider (external script editor points to Rider). It opens Rider **and** Mono Develop but on Rider the solution is not loaded (I see the "Welcome to Rider" screen). Tested this with the bundled Unity plugin and the latest version from this repository.

**Comment by van800** [comment]
Hi! Please check if the Unity3dRider plugin was added to your solution. Please mention the Unity version you have.
![image](https://user-images.githubusercontent.com/1482681/29310224-2f3badf2-81ad-11e7-975a-4a0748332a49.png)

**Comment by marcelschmidt1337** [comment]
Ah sorry I forgot to mention: I am on Unity 2017.1.0p1 and I am usually symlinking `RiderAssetPostprocessor.cs` and `RiderPlugin.cs` from this respository to my project which worked fine with Rider 2017RC and the versions before. I also tested it without the symlinks by installing the plugin from Rider using the `Unity3dRider.cs` but without success. The project is compiling and all files are part of my solution.

**Comment by van800** [comment]
Your OS?
If plugin is in place, does it print something to Unity log?
And is there menu item "Open C# project in Rider" next to "Open C# project"?

**Comment by marcelschmidt1337** [comment]
OSX 10.12. I only have `Open C# project` and it prints the init log. If I set it to verbose it logs the *.sln and *.csproj post-processing.
<img width="485" alt="screens" src="https://user-images.githubusercontent.com/10891885/29311659-1a6ff864-81b3-11e7-883b-a793a0e4eb88.png">

**Comment by van800** [comment]
Does double click to any cs script open Rider fine?

**Comment by marcelschmidt1337** [comment]
Yes, that works

**Comment by van800** [comment]
We do hide the "Open C# project in Rider" for all Unity 2017.1 or newer, because I though that it is supported by Unity since build https://unity3d.com/unity/beta/unity2017.1.0b5
but it seems that your Unity 2017.1 build doesn't have the native support or it doesn't work well.
Workaround is to remove the pre-processor directive around the RiderPlugin.MenuOpenProject
But I would need to test setup similar to yours first, thanks for reporting!

**Comment by marcelschmidt1337** [comment]
This is strange because it used to work before with the same Unity version but Rider RC. Maybe there is an issue with that? I am using Rider in evaluation mode right now.

**Comment by van800** [comment]
Maybe, I will ask Unity team how they check that Rider is a know editor.

**Comment by marcelschmidt1337** [comment]
Ok, a clean environment didn't help, same issue there

**Comment by van800** [comment]
I tested macos, Rider 2017.1 Build #RD-171.4456.2169 and Unity 2017.1.0p1
and it somehow works fine.
Calling "Open C# Project" starts Rider with solution and so, it is opened fine.
Mac-Admin:Managed admin$ ps aux | cat |grep Rider
admin             852   1.0 12.7  6684192 784976   ??  S     3:04PM   1:51.24 /Users/admin/Library/Application Support/JetBrains/Toolbox/apps/Rider/ch-1/171.4456.2169/Rider 2017.1.app/Contents/MacOS/rider /Users/admin/RiderProjects/resharper-unity/resharper/src/resharper-unity/Unity3dRider/Unity3dRider.sln

Could you please check the same process commandline at your side?

**Comment by marcelschmidt1337** [comment]
Same version, that's my output (I called open C# project and manually loaded the solution from the Rider welcome screen):
```
8644  26.2  2.6  6640400 441356   ??  S     2:17PM   0:26.99 /Applications/Rider 2017.1.app/Contents/MacOS/rider
8718  20.2  2.1  3032604 360504   ??  S     2:17PM   0:10.46 /Applications/Rider 2017.1.app/Contents/lib/ReSharperHost/macos-x64/mono/bin/mono-sgen /Applications/Rider 2017.1.app/Contents/libReSharperHost/JetBrains.ReSharper.Host.exe --Port=55417
8731   0.0  0.0  2432804   1916 s000  S+    2:17PM   0:00.00 grep Rider
8723   0.0  0.0  2473768   4932   ??  S     2:17PM   0:00.01 /Applications/Rider 2017.1.app/Contents/bin/fsnotifier
```

**Comment by van800** [comment]
Ok, problem reproduced. It wasn't reproducing on build from toolbox.
I will follow up here with more details later.
Thanks again!

**Comment by marcelschmidt1337** [comment]
Awesome! Thanks for your help 👍

**Comment by van800** [comment]
Menu item restored
https://github.com/JetBrains/resharper-unity/commit/a89dce7c8ba66cd8d6d86bb3dd1c7a82544fe21f
And I am working with Unity team for better Rider detection.

**Comment by van800** [comment]
Unity team confirmed, better Rider detecting is added to the todo list.
