### ISSUE TITLE
Debug.Assert is not recodnized as assertion by Rider

### ISSUE THREAD

**Issue by ZahlGraf** [JetBrains/resharper-unity#207]
Hi,

I'm using Rider with the "Unity Support" plugin. The plugin says, that this repository here is the correct one for Rider, even if it targets ReSharper.

I have an issue with the Debug.Assert in Rider: It is not recognized as assertion.
Thus the following code leads to a "Possible System.NullReferenceException" on the Log-Statement:
```
Debug.Assert(Instances != null);
Debug.Log(Instances.Length);
```

This has already been working for ReSharper with Visual Studio, but for any reasons it does not work in my Rider copy.

**Comment by citizenmatt** [comment]
There might be a couple of reasons for this. Firstly, is your project in Debug or Release mode? (Check the toolbar in the top right corner of the window). `Debug.Assert` is a conditional method that only gets called in Debug mode, and so the warning is only shown in Debug mode. A quick way to tell is if the call to `Debug.Assert` is greyed out. If it is, then there won't be an inspection highlight.

Secondly, if this is a property, then the inspection is correct - there is a chance for a null reference exception here, because you are making two calls to the property, which can (theoretically) return different values each time. If you first assign the property value to a local variable, then the analysis will know that the variable value doesn't change between each line, and can use the assert to know that the call to `Log` will be fine.

FWIW, I've just tested this on my machine, and it works as expected.

**Comment by ZahlGraf** [comment]
Hi Citizenmatt,

thanks for your answer and suggestions. I checked it:
* I'm using the Debug Mode. Actually it is called "Debug | Any CPU" and the Debug.Assert(...) statements are not grey. 
* This is a local variable, which should not change due to race conditions.

This is a screenshot of the code-segment:
![grafik](https://user-images.githubusercontent.com/10481491/29537459-1a5ec0ee-86c2-11e7-9444-d20f6a9339b3.png)

Could it be, that I first need to setup anything on Rider, so it is able to recognize "Debug.Assert(...)" statements as assertions?

**Comment by citizenmatt** [comment]
No, it should be already set up. Could you:

a) Edit something - change the `Instances != null` and then edit it back. This will make Rider re-run the inspection, and might kick start it.
b) Go to File &rarr; Invalidate Caches/Restart and then restart Rider. This will clear the caches and force everything to re-run from scratch (the equivalent of turning it off and back on again 😄)
c) Bring up the Quick Documentation for `Debug.Assert` - put the text cursor on the `Assert` and hit <kbd>Ctrl</kbd>+<kbd>Q</kbd> on Windows, or <kbd>F1</kbd> on Mac. You should see something like this:

<img width="496" alt="screen shot 2017-08-21 at 10 08 42 pm" src="https://user-images.githubusercontent.com/222659/29538359-58fd9550-86bd-11e7-846f-9b7429446632.png">

I'm interested in the `AssertionMethod` and `ContractAnnotation` attributes. These are added by the Unity plugin, and are used by Rider's analysis to prevent the "possible NullReferenceException" warning.

**Comment by ZahlGraf** [comment]
The suggestions a and b did not change anything.
When I do c, I'm clearly missing "AssertionMethod" and "ContractAnnotation" here:
![grafik](https://user-images.githubusercontent.com/10481491/29554501-ab84d8b2-871f-11e7-9d6e-8cb1c1c44e02.png)

Maybe the following version information is important for further debugging:
- Rider 2017.1 Build #RD-171.4456.2169, built on August 3, 2017
- Unity Support Plugin 2.0.2.2395
- Unity Version 2017.2.0b8

This is a beta version of Unity, since the official 2017.1 did not start on my current system.

**Comment by citizenmatt** [comment]
Well that's interesting. Certainly explains why you're getting the warning.

Can you confirm:

a) What OS you're on?
b) What namespace is the `Debug.Assert` method in? Is it `UnityEngine.Debug.Assert`?
c) If you navigate to the `Debug.Assert` method (ctrl+click/cmd+click), Rider will decompile the file. At the very top of the file is a comment which tells us the name and path of the assembly - could you paste that here, please?
d) Are any of the other Unity specific features working? Easiest way to tell - are there little Unity icons next to the class declaration of classes derived from `MonoBehaviour`?

<img width="411" alt="screen shot 2017-08-22 at 9 04 33 am" src="https://user-images.githubusercontent.com/222659/29554961-f74ef356-8718-11e7-85ac-579eb445cc94.png">

**Comment by ZahlGraf** [comment]
a) I'm on Windows 10
b) The namespace is "UnityEngine" in the class "Debug" (which is sealed by the way). And of course the method name is "Assert"
c) The file header is:
```
// Decompiled with JetBrains decompiler
// Type: UnityEngine.Debug
// Assembly: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 6173636B-0A2E-44A4-A6B8-69DF06DB9FC3
// Assembly location: C:\Program Files\Unity 2017.2.0b8\Editor\Data\Managed\UnityEngine\UnityEngine.CoreModule.dll
```
d) Yes those little Unity-Symbols are there. Also when I start Rider for the first time in a project, it will automatically create the "Plugins/Editor/JetBrains/Unity3DRider.cs". So in general the Plugin seems to work.

**Comment by ZahlGraf** [comment]
Good to hear, that you found the root cause. 
Thanks a lot for your help! This issue is not very annoying, so I will simply ignore the notes until the next Rider version is available.

Also thanks for that Unity-Plugin. Working with Rider makes much more fun, than working with Visual-Studio! 

For me it is ok to close this issue, but maybe you will keep it open for tracking?

**Comment by citizenmatt** [comment]
That's fantastic to hear - exactly why we're doing this :)

I'll leave the issue open for now, for tracking.

**Comment by daveyostcom** [comment]
I have the same problem, in 2018.1. Debug. Assert doesn't complain when it should.

**Comment by citizenmatt** [comment]
Do you have an example? As far as I can see, it's working ok, but perhaps I've missed an overload?

<img width="569" alt="screen shot 2018-07-12 at 8 57 30 am" src="https://user-images.githubusercontent.com/222659/42620010-a3520d86-85b1-11e8-9e66-7cd4c32acc25.png">

**Comment by benoit-dubreuil** [comment]
Still happening. It happened many times to me with Rider. It seems Rider doesn't recognize the  `UnityEngine.Assertions.Assert` static class for asserts.

![image](https://user-images.githubusercontent.com/6900372/102724802-3ab54d80-42e0-11eb-80e0-ec8a0e218b02.png)

**Comment by citizenmatt** [comment]
Can you provide some sample code, please? Also, what do you mean by "manually add the exception into my settings"?

**Comment by benoit-dubreuil** [comment]
> Can you provide some sample code, please?

Short code sample :
`Assert.IsNotNull(AdvMap);`

Longer code sample : 
```C#
private void CreateCellsGameObjs()
{
    Assert.IsNotNull(AdvMap);
    Assert.IsNotNull(AdvMap!.Data);

    foreach (AdvMapCellDataSet cellData in AdvMap.Data.Topology.DataIntrinsic.Cells.Values)
    {
        Mesh       cellMesh = cellData.RawDataWrapper.ToUnityMesh();
        GameObject cellObj  = CreateChildGameObj(GameObjNameCellPrefix + cellData.ID.id, cellMesh, m_cellMaterial!, m_cellsParentObj!);
        cellObj.AddComponent < AdvMapCellDataController >()
               .ID = cellData.ID;
    }
}
```

>  Also, what do you mean by "manually add the exception into my settings"?

![image](https://user-images.githubusercontent.com/6900372/102793575-20c74980-4378-11eb-8925-69434767eae5.png)
