### ISSUE TITLE
Auto-complete on Shaderlab functions not working

### ISSUE THREAD

**Issue by Kiefy** [JetBrains/resharper-unity#2086]
I just began a trial for Rider and I'm not sure if it's an issue only on my end, or if this is the actual state of current shaderlab support, but there are some inadequacies that don't seem to be mentioned in any open issues.

## 1) Tooltips are very bare ##

![d](https://i.imgur.com/vAaEHqz.png)

![d](https://i.imgur.com/LYxw9OF.png)

### Compared to VS Code ###

![d](https://i.imgur.com/eisiAOl.png)

![d](https://i.imgur.com/qN7MORi.png)

### Rider ###

![d](https://i.imgur.com/AOvLXBY.png)

### VS Code ###

![d](https://i.imgur.com/2dnAxE6.png)

## System details ##

- Windows 10 Pro 20H2 (19042.928)
- Unity 2021.1.5f1
- JetBrains Rider 2021.1.2 x64

## A note about VS Code ##
VS Code gets it's shaderlab support from the "ShaderlabVSCode" extension, and it is far from perfect itself since there is no code inspection at all. Not even to tell me there's a semicolon missing,

It would seem that Rider & VSCode each have exactly what the other needs.

**Comment by Kiefy** [comment]
I just noticed a lot of the C# System functions are showing equally bare tooltips too. is my editor fubar?

![d](https://i.imgur.com/YMlZ0vh.png)

Unity methods all seem to have good tooltips though.

**Comment by van800** [comment]
For the mono BCL documentation on windows - please see this suggestion https://youtrack.jetbrains.com/issue/RIDER-11155#focus=Comments-27-4099095.0-0

**Comment by Kiefy** [comment]
Thank You van800

I installed the mono x64 package and viola!

![d](https://i.imgur.com/rFmuyRd.png)

So, just Shaderlab to sort out now. :)

**Comment by citizenmatt** [comment]
The problem seems to be that when targeting the .NET Standard, types such as `List<T>` are defined in the `netstandard.dll`  assembly, and neither Unity nor Mono ship the `netstandard.xml` docs file, which means Rider doesn't have any help to show.

**Comment by citizenmatt** [comment]
As for the ShaderLab support - what version of Rider are you trying? I'm using Rider 2021.1.2 and can see both syntax highlighting in the function tooltips and can see completion for functions such as `saturate`. Make sure that Rider is set as the default External Editor in Unity settings, and it might be worth making sure the Rider package is up to date in Unity's package manager. This can affect how files are added to the generated C# projects, which in turn affects how Rider can work with files to show completion, navigation, etc.

<img width="596" alt="Screenshot 2021-05-10 at 9 41 10 am" src="https://user-images.githubusercontent.com/222659/117632079-cdae3180-b174-11eb-90fc-abcdd8a6c57e.png">
<img width="472" alt="Screenshot 2021-05-10 at 9 41 33 am" src="https://user-images.githubusercontent.com/222659/117632096-d0a92200-b174-11eb-8950-41bf1ca42e1a.png">

Rider doesn't show any documentation summary in the tooltip because nothing is defined in the header files that Rider is indexing to build completion lists. I'm not sure where the VS Code extension is getting its hover information from, but it's possible that's all hard coded.

**Comment by Kiefy** [comment]
> neither Unity nor Mono ship the `netstandard.xml` docs file, which means Rider doesn't have any help to show.

So how does Visual Studio do it?

> what version of Rider are you trying?

I am on 2021.1.2. Connection with Unity is good.  I thought it might be because I was using a project originally created in VS, but even on a brand new Unity project with Rider in the front seat. no change.

![d](https://i.imgur.com/dJFeP55.png)

![d](https://i.imgur.com/oXg1jGQ.png)

![d](https://i.imgur.com/jysow23.png)

![d](https://i.imgur.com/0Trm2g4.png)

![d](https://i.imgur.com/dpTJ8Ov.png)

![d](https://i.imgur.com/LN5qusZ.gif)

Anything I can give to help diagnose?   [Logs?](https://www.dropbox.com/s/84o8p1my6gwxtqw/rider-logs-20210510-213835.zip?dl=0)

Oh and yeah. the VS Code extension is absolutely hard-coded.

**Comment by citizenmatt** [comment]
There's nothing obviously wrong from the logs - everything looks ok. Can you share the `.shader` file you're testing with? Is there anything interesting about it? Do you get the same issue with a plain simple shader file from a template, or from a `.cginc` file?

**Comment by Kiefy** [comment]
[This](https://www.dropbox.com/s/elb9e7zvjze8t95/NewUnlitShader.shader?dl=0) is the shader I was using in the screenshots.  I've created a few different fresh shaders in Unity.  Unlit, Surface, etc.  They all exhibit the same behaviour.

I opened the `UnityCG.cginc` file and it too has the same issue.

![d](https://i.imgur.com/xxJCrlv.png)

**Comment by Kiefy** [comment]
I've had a realisation. The same thing happens in Visual Studio when using Resharper+UnityPlugin.  So that rules out Rider itself.

It doesn't rule out any kind of catastrophic misconfiguration in my operating system though.  If I am the only person having this problem, then maybe it's time I reformatted my C drive.

**Comment by citizenmatt** [comment]
ReSharper and the Unity plugin will be doing exactly the same as Rider - it's the same code under the hood. I don't think it's time to reformat your hard drive just yet, but I'm not clear on what's going wrong (and I very much appreciate your time trying to figure it out). 

I don't see any functions in your completion screenshots at all. Can you confirm if you do see any?

And secondly, could you try to create a new, simple project, please? It's worth testing to see if it happens for all projects, and if you can then share the project folder, I can see if there's something strange in the project files.

**Comment by van800** [comment]
@Kiefy The described problem with folder without cs file was already fixed in Rider package. Please update Rider package in Unity package manager to the latest version (3.0.6+).

**Comment by Kiefy** [comment]
Oh right yeah.  That's because I was in the test project I just created and forgot about the package updates.  I can assure you that was a one-off though.  I haven't spent all this time with old packages. :)

ah. Guess I gotta do it again. :D

**Comment by citizenmatt** [comment]
Don't worry - I don't think it will make any difference. The test project you've shared works fine on my machine. But I'm concerned that you don't see any functions at all in code completion. That's very weird. I've got the C++ team involved behind the scenes to take a look at this.

Could you also share you global config, please? Click the _Manage Layers_ button in the Preferences window, right click on _This Computer_ and _Open Containing Folder_. Attach the `GlobalSettingsStorage.DotSettings` file. There might be some personal information in the file (path names) - you can open it up in a text editor and remove those files before attaching, or email it privately if you'd prefer.

**Comment by Kiefy** [comment]
It's fine. as long as their ain't no IP addresses in there.  [GlobalSettingsStorage.DotSettings](https://pastebin.com/ZngenDng)

**Comment by Kiefy** [comment]
I ended up formatting, and now the functions appear!

![d](https://i.imgur.com/FHJOPn6.png)

Sure hope it doesn't happen again. :P

**Comment by citizenmatt** [comment]
The ticks for the packages shouldn't make any difference, especially for the test project - that didn't have any packages, but you still had problems with shader completion. 

I can't explain what went wrong there, but I'm glad it's working again. Sorry that it took a drastic step of formatting to fix! We'll keep looking to see if we can find out what happened. In the meantime, I'm going to close this issue, please comment/reopen if you need to. And I know at the top you said you were giving the trial a go, if you drop me an email (matt at jetbrains), then I can extend the evaluation period for you.
