### ISSUE TITLE
Avoid false positives of "repeated property access of built in components is inefficient" with coroutines

### ISSUE THREAD

**Issue by philippitts** [JetBrains/resharper-unity#2091]
It is possible for the value of a built-in component property to change when used before and after a yield statement within a Unity coroutine. For example, take the following:

```c#
private void Start()
{
    StartCoroutine(AnimatePosition());
    StartCoroutine(PrintTwoAnimationSteps());
}

private IEnumerator AnimatePosition()
{
    const float animationTime = 10f;

    var elapsed = 0f;
    while (elapsed < animationTime) {
        transform.position = Vector3.Lerp(Vector3.zero, Vector3.forward, elapsed / animationLength);
        elapsed += Time.deltaTime;
        yield return null;
    }
}

private IEnumerator PrintTwoPositions()
{
    Debug.Log(transform.position);
    yield return null;

    // Rider gives repeated property access of built in components warning, but position may have changed
    Debug.Log(transform.position);
}
```

Would it be possible to disable this warning when used inside methods that return `IEnumerator`? Or is there a better way to detect if the component may be changed by another coroutine? I assume (but have not tested) that this is also an issue with async / await patterns.

Similar issue: https://github.com/JetBrains/resharper-unity/issues/1544
Warning documentation: https://github.com/JetBrains/resharper-unity/wiki/Avoid-multiple-unnecessary-property-accesses

**Comment by citizenmatt** [comment]
Starting with 2024.1, this inspection is set to "do not show" as the default severity ([RIDER-53077](https://youtrack.jetbrains.com/issue/RIDER-53077)).
