### ISSUE TITLE
Rider doesn't detect scripting define symbols in UPM packages.

### ISSUE THREAD

**Issue by mnarimani** [JetBrains/resharper-unity#2095]
It's true that UPM packages are read only, but Rider should support navigating in them. Rider doesn't recognize any of scripting define symbols.  

So if a class from UPM package is declared within `#if #endif` (which happens ALL the time), Rider just stops working for that script. No navigation, no intellisense, **and most importantly, it doesn't detect/show XML docs from the class or its members.**

**Comment by van800** [comment]
The known workaround is to generate projects for those packages. Make sure to update Rider package to the latest version (3.0.6) and see ckeckboxes in In Unity settings near selection of the external editor.
The downside may be some small performance slowdown.

**Comment by mnarimani** [comment]
@van800 Thank you so much! I checked all the checkboxes and it solved all the issues.
