### ISSUE TITLE
Rider's Machine Learning often prefers System.Numerics.<Type> over Unity's Vector3, Quaternion etc.

### ISSUE THREAD

**Issue by Kiefy** [JetBrains/resharper-unity#2096]
I'm not sure if I should post this here or not.  I already reported on the [JetBrains Tracker](https://youtrack.jetbrains.com/issue/RIDER-63160) but since it is very Unity related. I thought it might be better here?

![d](https://i.imgur.com/mlpibIH.png)

![d](https://i.imgur.com/dSzHzP9.png)

**Comment by citizenmatt** [comment]
Thanks. Raising it in YouTrack is the best place, as I don't think there's going to be much we can do from the Unity plugin. That said, it's very useful to have it pointed out here, too. I'm going to close this issue, in favour of [RIDER-63160](https://youtrack.jetbrains.com/issue/RIDER-63160), but I'll also follow up with the teams internally. Thanks for raising it!
