### ISSUE TITLE
Rider: Inspections related to C# 8 features unsupported by Unity do not work as expected

### ISSUE THREAD

**Issue by sbergen** [JetBrains/resharper-unity#2099]
The list of C# 8 features not supported in Unity can be found at https://docs.unity3d.com/2021.1/Documentation/Manual/CSharpCompiler.html
* Default interface methods
* Indices and ranges
* Asynchronous streams
* Asynchronous disposable

We've observed that at least the `UseIndexFromEndExpression` suggestion pops up, and no errors are shown for using functionality that requires indices and ranges.

Expected behaviour in a Unity project in Rider:
* No hints or suggestions related to using unsupported features are shown 
* Using unsupported features shows an error

I'm not sure if this should be considered two different issues or not, so feel free to split it :)

**Comment by van800** [comment]
Could you please provide us with example code demonstrating the problem?

**Comment by van800** [comment]
I am getting different result here 
![image](https://user-images.githubusercontent.com/1482681/120448364-cc46e200-c38b-11eb-95a7-c6439b494081.png)

**Comment by van800** [comment]
It is a Unity-generated solution, which you are using? Specifically, using JetBrains Rider package in Unity.

**Comment by sbergen** [comment]
> It is a Unity-generated solution, which you are using? Specifically, using JetBrains Rider package in Unity.

Yes, but I dug into this a bit deeper, and it seems that indexes are working because the Unity code coverage packages contains `System.Index` as a public implementation (in `com.unity.testtools.codecoverage@1.0.0/lib/ReportGenerator/ReportGeneratorMerged.dll`). So I'm guessing Rider detects its presence somehow, and then enables that suggestion?

One of the problems here is that it's an editor-only dll. But I'm no longer sure what the proper way to address the issue would be...

**Comment by van800** [comment]
Thank you for reporting, I have created a different requiest https://youtrack.jetbrains.com/issue/RSRP-484701 for the core team.

**Comment by van800** [comment]
Devs in Unity Coverage package should also consider internalizing all types in that System.dll, which the embed.

**Comment by van800** [comment]
Update: I can see System.Index in the coverage package is internal, which makes total sense.
![image](https://user-images.githubusercontent.com/1482681/120475251-6701e980-c3a9-11eb-8452-518907a76095.png)

**Comment by sbergen** [comment]
> Update: I can see System.Index in the coverage package is internal, which makes total sense.

Ah, yes, my bad. With the other stuff in that package (e.g. `IAsyncEnumerable` and `IAsyncDisposable`), you'll get a "cannot access internal interface" error, as expected, but by just using an index expression, there's no error. This made me think it's public. But you're right, it is internal.

**Comment by van800** [comment]
The issue would be addressed on the Re# side. Thanks again for reporting.
