### ISSUE TITLE
CSC.rsp please add support for exluding folders from analyzers

### ISSUE THREAD

**Issue by studentutu** [JetBrains/resharper-unity#2112]
I have to use a lot of plug-ins and while using the Microsoft.Unity.Analyzer - it throws 500 warnings at a time,
The problem is - some of those plug-ins like magic leap - does not support assembly definitions yet, so I couln't simply put anothe [TargetAssemblyDefinitionName].ruleset underneath, nor could I put another csc.rsp under that folder (as it will be ignored).
Could you please help?

I need to exclude those folders from being analyzed. 
I've tried putting another ignoredcsc.rsp file - but secondary global .rsp file is ignored.

What should I do?

**Comment by van800** [comment]
csc.rsp only supports what it supports, we can't make it support specific rules for folders.

Why not excluding everything and including only asmdef based projects?

You may also be interested to follow this approach https://github.com/JetBrains/resharper-unity/issues/1835#issuecomment-701373444

**Comment by studentutu** [comment]
@van800 thank you, will try it later. For now if I've managed to do the same - but instead of a single scs.rsp - I have one for each target project that I need analyzers for. It is not ideal, but still works
