### ISSUE TITLE
Seven errors occurred installing unity support

### ISSUE THREAD

**Issue by milkare** [JetBrains/resharper-unity#2114]
- Install completed with 7 errors.
- 
- 22:10:54.472 ReSharperPlatformVs16_27bc41b4: Error resolving type JetBrains.ReSharper.Psi.Cpp.Caches.CppFileLocation from assembly “JetBrains.ReSharper.Psi.Cpp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “JetBrains.ReSharper.Plugins.Unity, Version=2021.1.2.127, Culture=neutral, PublicKeyToken=0f46ab053645825e”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
- 
- 22:10:54.492 ReSharperPlatformVs16_27bc41b4: Error resolving type JetBrains.ReSharper.Psi.Cpp.Caches.CppFileLocation from assembly “JetBrains.ReSharper.Psi.Cpp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “JetBrains.ReSharper.Plugins.Unity, Version=2021.1.2.127, Culture=neutral, PublicKeyToken=0f46ab053645825e”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
- 
- 22:10:54.662 ReSharperPlatformVs16_27bc41b4: Error resolving type JetBrains.ReSharper.Feature.Services.Cpp.CodeStyle.ICppCustomFormattingInfoProvider from assembly “JetBrains.ReSharper.Feature.Services.Cpp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “JetBrains.ReSharper.Plugins.Unity, Version=2021.1.2.127, Culture=neutral, PublicKeyToken=0f46ab053645825e”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
- 
- 22:10:54.663 ReSharperPlatformVs16_27bc41b4: Error resolving type JetBrains.ReSharper.Feature.Services.Cpp.CodeStyle.ICppCodeFormatterExtension from assembly “JetBrains.ReSharper.Feature.Services.Cpp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “JetBrains.ReSharper.Plugins.Unity, Version=2021.1.2.127, Culture=neutral, PublicKeyToken=0f46ab053645825e”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
- 
- 22:10:54.665 ReSharperPlatformVs16_27bc41b4: Error resolving type JetBrains.ReSharper.Psi.ILanguageCppZone from assembly “JetBrains.ReSharper.Psi.Cpp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “JetBrains.ReSharper.Plugins.Unity, Version=2021.1.2.127, Culture=neutral, PublicKeyToken=0f46ab053645825e”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.
- 
- 22:10:56.589 ReSharperPlatformVs16_27bc41b4: The type “JetBrains.ReSharper.Psi.ILanguageCppZone, JetBrains.ReSharper.Psi.Cpp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325” is not a module zone because it does not derive from the JetBrains.Application.BuildScript.Application.Zones.IZone interface.
- 
- 22:10:56.593 ReSharperPlatformVs16_27bc41b4: The type “JetBrains.ReSharper.Psi.ILanguageCppZone, JetBrains.ReSharper.Psi.Cpp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325” is not a module zone because it does not derive from the JetBrains.Application.BuildScript.Application.Zones.IZone interface.

Something happened with the unity support installation that I don't know how to handle. Above are the logs.——Automatic translation from DeepL.

**Comment by citizenmatt** [comment]
The ReSharper plugin requires ReSharper C++ to be installed, because it reuses the C++ parser for the shader file support. Please reinstall ReSharper with the C++ support included. There is a ticket to separate the Unity support to make shader file support optional, based on C++ being available: [RSRP-480936](https://youtrack.jetbrains.com/issue/RSRP-480936)

**Comment by milkare** [comment]
> The ReSharper plugin requires ReSharper C++ to be installed, because it reuses the C++ parser for the shader file support. Please reinstall ReSharper with the C++ support included. There is a ticket to separate the Unity support to make shader file support optional, based on C++ being available: [RSRP-480936](https://youtrack.jetbrains.com/issue/RSRP-480936)

Thanks! The problem had been solved when I install that. Thank you very much!
