### ISSUE TITLE
ReSpeller tool not support thai language.

### ISSUE THREAD

**Issue by kitti332** [JetBrains/resharper-unity#2117]
![Screenshot 2021-07-09 070738](https://user-images.githubusercontent.com/47498293/125004805-81a04000-e084-11eb-86c1-9ea75e7f0da9.png)

**Comment by citizenmatt** [comment]
Hi. This repo is for just the Unity support in ReSharper/Rider - we don't work on other features such as ReSpeller. Please could you report your issue to https://youtrack.jetbrains.com, please? That will get seen by the correct team. Thanks!
