### ISSUE TITLE
Can't set breakpoints when attached to a Unity game on Android

### ISSUE THREAD

**Issue by tallior** [JetBrains/resharper-unity#2126]
We are using Unity 2019.4.22, trying to debug a game running on a phone (Android).
Rider is able to attach to the process running on the phone, but no breakpoints can be set.

When setting a breakpoint, it is colored in grey, and an error message is shown:
```
"File.cs not found among the loaded symbol documents"
5:14
```
After re-attaching to the process, sometimes i would get this error:
`"Not found associated module for breakpoint File.cs:lineNumber"`

The game is built on a build server, and not on the local machine where debugging is attempted, in case that matters in any way.

Should this scenario be supported? what might be wrong here?

**Comment by van800** [comment]
Is it compiled in Debug mode on a buildserver? Are there pdb files near the dll files? We can take a look at the logs, especially DebuggerWorker folder (Help->Diagnostic Tools -> Show log in Files)

**Comment by tallior** [comment]
> Is it compiled in Debug mode on a buildserver? Are there pdb files near the dll files? We can take a look at the logs, especially DebuggerWorker folder (Help->Diagnostic Tools -> Show log in Files)

What do you mean by Debug mode? We are building a development build + script debugging enabled.
I will attach the logs later today, thanks :)

**Comment by tallior** [comment]
@van800 attached. let me know if you could find anything useful there.
[JetBrains.Debugger.Worker.2021_7_20_11_51_09.zip](https://github.com/JetBrains/resharper-unity/files/6854669/JetBrains.Debugger.Worker.2021_7_20_11_51_09.zip)
[JetBrains.Debugger.Worker.2021_7_20_11_43_15.zip](https://github.com/JetBrains/resharper-unity/files/6854670/JetBrains.Debugger.Worker.2021_7_20_11_43_15.zip)

**Comment by tallior** [comment]
Hi @van800 any updates on this? did you find anything useful in the logs i attached ?
Should this scenario be supported? e.g: building on a build machine then debugging on another ?

**Comment by van800** [comment]
I have asked a colleague from the debugger team to take a look. I will remind again. Thank you for following up.

**Comment by van800** [comment]
Got a response saying that according to the logs Rider doesn't have info about loaded symbols, we have to try reproduce it on our end.

**Comment by tallior** [comment]
@van800 by symbols you mean .pdb files or anything else? il2cpp converts the code to c++ so Unity can export another type of symbols (.sym.so files).

Also, where does it look for these symbols? Unity automatically compiles the code so it should have the .dll + .pdb files in some temp folder, i wonder why Rider cannot find them.

**Comment by tallior** [comment]
any update on this ? @van800

**Comment by van800** [comment]
I was able to debug on my android phone a locally compiled game (with IL2CPP).
Would help, if you can share a guide or steps for us to try your case with Cloud build and manual deploy. So we can reproduce exactly your case.

**Comment by van800** [comment]
I can see unresolved brakepoint, if I compile and deploy the app, but then move the whole folder to a different location and try to debug from there.

**Comment by tallior** [comment]
@van800 so our scenario is essentially the same - we have a build machine which is just a Mac mini machine with Unity. It builds the game from the command line (calling BuildPipeline.BuildPlayer), then we download the .apk and attach to it and try to debug. This is pretty much similar to building it on 1 machine then moving to another machine (or building in 1 folder, then moving to another one).

My main question is what files is it looking for exactly, and where ?

**Comment by van800** [comment]
Try using the same project location on mac mini and locally

**Comment by tallior** [comment]
@van800 its problematic since the build machine builds the project from an entirely different folder... is there a way to control this behaviuor somehow ?

**Comment by van800** [comment]
I have done, what I could, here is a request for the debugger team https://youtrack.jetbrains.com/issue/RIDER-66147, please vote it to get updates.
