### ISSUE TITLE
I'm expanding, but I don't know how to get columns and members

### ISSUE THREAD

**Issue by doudousha** [JetBrains/resharper-unity#2130]
// Right click to select a file
public class ProjectActionItem : IExecutableAction, IInsertLast<IntoSolutionItemGroup>
    {
     
        public void Execute(IDataContext dataContext, DelegateExecute nextExecute)
        {
// How Get Current CsSharpFile Method or Field  ?
}

}

**Comment by citizenmatt** [comment]
Hi. Can you provide some more context please? Is this a Unity specific question, or a general plugin development question?

**Comment by citizenmatt** [comment]
I'm closing this for now. If there's more information, please feel free to comment, and we can reopen.
