### ISSUE TITLE
OnGeneratedCSProjectFiles not being called

### ISSUE THREAD

**Issue by tallior** [JetBrains/resharper-unity#2131]
Our project has our own type that implements this method (OnGeneratedCSProjectFiles) to "patch" the generated .csproj files.

I am not sure for how long, but this code is not being fired anymore. I suppose that Rider may have something to do with it. I looked around and found this code:
```
private static void OnGeneratedCSProjectFiles(Type[] types)
{
  foreach (var type in types)
  {
    var method = type.GetMethod("OnGeneratedCSProjectFiles",
      System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic |
      System.Reflection.BindingFlags.Static);
    if (method == null)
    {
      continue;
    }

    Debug.LogWarning("OnGeneratedCSProjectFiles is not supported.");
    // RIDER-51958
    //method.Invoke(null, args);
  }
}
```
This is the references [Rider ticket](https://youtrack.jetbrains.com/issue/RIDER-51958).

I wonder if our code is not being fired anymore because Rider integration "catches" the callback but never calls any other implementations in the project? not really sure. I am using Jetbrains Rider Editor v3.0.5 (package manager)

Should this be supported? is there any workaround?
Our .csproj processor adds Roslyn analyzers to the .csproj file (since it is not supported out of the box on Unity 2019.4 LTS)

**Comment by van800** [comment]
Yes, you can use another similar callback for postprocessing csproj. Let me find it ...

**Comment by tallior** [comment]
@van800 but which callback is it ? :)

**Comment by van800** [comment]
`public static string OnGeneratedCSProject(string path, string contents)`

**Comment by van800** [comment]
instead saving file on disk you return the edited content and Unity would save it for you.

**Comment by van800** [comment]
This avoids saving file multiple times.

**Comment by van800** [comment]
Example https://github.com/JetBrains/resharper-unity/blob/32e336d21a55688654670c142165f09aab7f0e0f/unity/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs#L50

**Comment by van800** [comment]
Btw even in Unity 2019.x there are also couple of different options 
see https://stackoverflow.com/a/67047592/309130
