### ISSUE TITLE
False positive "You must add a reference to assembly"

### ISSUE THREAD

**Issue by bartlomiej-dawidow** [JetBrains/resharper-unity#2138]
After upgrading to Rider 2021.2, the integration with Unity appears to have stopped working. Rider shows hundreds of errors like this one:

```
The type ‘……’ is defined in an assembly that is not referenced. You must add a reference to assembly ‘….’
```

The project itself compiles and works fine in Unity. Rider 2021.1.5 and earlier did not that problem.

Note that the project uses asmdefs heavily.

After downgrading to 2021.1.5 the errors did not immediately go away, I had to restart Unity. So the problem might be with how the Unity plugin generates project files.

----

I have also filed a YouTrack bug report, not sure where this one belongs:
https://youtrack.jetbrains.com/issue/RIDER-66057

**Comment by citizenmatt** [comment]
Either here or on YouTrack is fine. We'll see them either way 😄 

I'm not sure what's going on with this particular issue. We've had another report, [RIDER-66047](https://youtrack.jetbrains.com/issue/RIDER-66047), so we're trying to figure out more details and/or a repro. I'm going to close this issue in favour of the YouTrack ticket.
