### ISSUE TITLE
PLEASE ADD UNINSTALL DOC

### ISSUE THREAD

**Issue by madstacksofcash** [JetBrains/resharper-unity#214]
This really needs SOMETHING regarding how to uninstall. Any pointers are appreciated

- It changes how unity works and not obvious how to uninstall

Like in my case with a big existing Unity project, something is messed up now and I don't want to have to reinstall Unity or have to have some kind of wild goose chase.

**Comment by citizenmatt** [comment]
What product are you using, Rider or ReSharper? If it's ReSharper, go to _ReSharper_ &rarr; _Extension Manager_ and select uninstall. If it's Rider, you can't uninstall it, because it's bundled with the IDE. But if you go to _Preferences_ &rarr; _Plugins_, search for Unity and then uncheck it. Restart and it'll be disabled.

But what do you mean by the fact that it changes how Unity works? What is it that's messed up - what's broken?

**Comment by cmcpasserby** [comment]
I think he must be referring to AssetPostprocessor and the Menu entries that are added to unity by Rider's unity plugin.

if that is the case, you can simply just delete the `Assets/Plugins/Editor/JetBrains` folder from your project.

**Comment by madstacksofcash** [comment]
I'm referring to how it changes the way Unity creates the c# project files. They are messed up now and the project doesn't work as well in VisualStudio anymore.

Specifically the project view thing on the side that shows the different files/classes/scripts now shows ALL unity assets and folders, which is horrible.

**Comment by van800** [comment]
Just set Visual Studio as an External Editor in Unity and double click any csript in Unity. Unity will regenerate sln an csproj in Visual Studio way.

**Comment by madstacksofcash** [comment]
Already tried both of those things.

Why would it ever be a good idea to show all files in a unity project in an IDE? In jetbrains it showed all files as well. 

Perhaps I'm just unlucky or this is a bug? Any ideas on how to fix

**Comment by citizenmatt** [comment]
What do you mean by all files? It should only include .cs, .shader and I think .txt. Are you seeing other file types? Could you post a screenshot?

**Comment by van800** [comment]
Feel free to reopen this, if any new info will come.

**Comment by ALanMAttano** [comment]
2019 there are no instructions on how to uninstall Rider from Unity in the foot of the first page?

**Comment by van800** [comment]
@ALanMAttano For Unity 2019.2+ with Rider package there is no need to uninstall anything at all, just change external editor and that's it.
For previous versions you may want to remove `Assets/Plugins/Editor/JetBrains/JetBrains.Rider.Unity.Editor.Plugin.Repacked.dll`,
however anyway, when external editor is not Rider, it would not actually do anything.

**Comment by ALanMAttano** [comment]
@van800  Can you put that?

**UNINSTALL**

For Unity 2019.2+ with Rider package, there is no need to uninstall anything at all, just change external editor and that's it.
