### ISSUE TITLE
Classes added to generated csproj dissapear

### ISSUE THREAD

**Issue by kapral** [JetBrains/resharper-unity#2141]
I don't know if this is an issue or I am just using this in a wrong way.

If I generate a .csproj from Unity and then add classes to it from Solution explorer the csproj gets immediately re-generated by Unity and new file gets removed from the project.

1. Should I only add new classes under  `Assets` when `Unity` is selected in the explorer? If so do I need to have the csproj at all?
2. Let's say I need more complex structure, can I create separate projects in the solution and reference them?

**Comment by van800** [comment]
Files added to Assets are compiled by Unity.
So if you have some structure outside, you have to make sure, instead its output is put into Assets.
