### ISSUE TITLE
Resharper stops working if Unity gets closed

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#2146]
I have come accross an interesting situation if I close Unity and leave Visual Studio open:

- R# stops working and its icon disappears
- I must restart VS for R# to work again

Also, this comes at the same time with a problem I've been experiencing lately:

When I double-click an item in console so it gets focused in Visual Studio, Unity thinks for a long moment, decides that there's no instance of Visual Studio open while in fact there is one and decides to open a second instance of Visual Studio.

In turns out that then it's impossible to close it by mouse, only using the keyboard and you're granted with the following:

<img width="302" alt="devenv_2021-08-16_05-57-55" src="https://user-images.githubusercontent.com/1537591/129509707-e11c1e5b-1025-49e1-a795-b5c0dfb5dd47.png">

Environment:

Visual Studio 2019 16.11.0
Unity Support 2021.2.0.129

Unity 2020.3.16f1
Visual Studio Editor 2.0.11

**Comment by van800** [comment]
Might be worth checking if it the behaviour reproduces without this plugin.
If it is unrelated to this plugin, you may report in https://youtrack.jetbrains.com/issues/RSRP
with ReSharper and VS logs
as described here https://www.jetbrains.com/help/resharper/Introduction__Troubleshooting.html#logs

**Comment by aybe** [comment]
Alright, thanks!

**Comment by citizenmatt** [comment]
Just to add that ReSharper doesn't communicate with the Unity editor at all - that's handled by VSTU

**Comment by aybe** [comment]
Okay I'll check with them then, thanks!
