### ISSUE TITLE
Meta files being created for non-Unity projects

### ISSUE THREAD

**Issue by vertxxyz** [JetBrains/resharper-unity#2203]
Using 2021.3 EAP 6 Build #RD-213.5455.4 (Unity support bundled 2021.3.0.78) on a net5.0 project creating files and folders will create an accompanying .meta file.
If this is my fault by accidentally enabling something, or these are not Unity meta files (they look like them) please let me know!

**Comment by van800** [comment]
Thank you for reporting. I hope it will get fixed shortly. Already reported in https://youtrack.jetbrains.com/issue/RIDER-70098, so closing this as duplicate.
