### ISSUE TITLE
Unity overwrites Root Namespace in project file. 

### ISSUE THREAD

**Issue by grosserzampano** [JetBrains/resharper-unity#221]
Currently Unity overwrites the Root Namespace which I can set in Rider in the Project settings. Would be nice if the plugin would save this value and restore it after Unity generated the .csproj file.

**Comment by van800** [comment]
https://rider-support.jetbrains.com/hc/en-us/community/posts/115000556230-Change-Namespace-Folder-Name
Please follow this thread.

**Comment by piersb** [comment]
Link is broken...

**Comment by citizenmatt** [comment]
I think the thread is available here: https://rider-support.jetbrains.com/hc/en-us/community/posts/360001346239-Change-Namespace-Folder-Name

With later versions of Unity, you can specify a root namespace in settings, and each .asmdef can specify a root namespace, too. On top of that, the handling of namespace providers has been updated to work better with packages. Check out #1677 for more details.

**Comment by piersb** [comment]
Thanks!
