### ISSUE TITLE
Unit testing with coverage often 'livelocks'

### ISSUE THREAD

**Issue by Kylotan** [JetBrains/resharper-unity#2238]
I have a set of about 400 unit tests (including combinations/sequentials) in a Unity project, but trying to track the coverage is unreliable.

If I run the tests in Unity, all pass in about 2 seconds.

If I run the tests from Rider via Run All Tests in the Unit Tests tool window, all pass in about 5 or 6 seconds. This is whether I've started Unity with Coverage or not.

If I run the tests from Rider via Cover All Tests in the Unit Tests tool window, having started Unity with Coverage, one of two things happens:

- **sometimes**, they all pass, after about 50 seconds.
- **usually**, at some point (different each time) the number of passed tests in Rider stops incrementing, and the progress bar in Unity stops changing, except for the timer ticking upwards. Both processes are responsive to events but are making no progress on the testing. The tests cannot be stopped from Rider or Unity, but killing the Unity process allows Rider to recover.

There are no exceptions or errors shown in the Unity console which could explain it, nor any events appearing in Rider.

This is using Unity 2020.3.25f1 (the current LTS version, at time of posting) on Windows 10.

Rider version is:

JetBrains Rider 2021.3.2
Build #RD-213.6461.51, built on December 22, 2021
Licensed to Ben Sizer
Subscription is active until April 3, 2022.
Runtime version: 11.0.13+7-b1751.21 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET Framework 4.0.30319.42000
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 16
Registry:
    ide.mac.bigsur.window.with.tabs.enabled=false
    indexing.enable.entity.provider.based.indexing=false
    ide.new.project.model.index.case.sensitivity=true
    rdclient.asyncActions=false

Non-Bundled Plugins:
    net.vektah.codeglance (1.5.4)
    com.intellij.resharper.HeapAllocationsViewer (2021.3.0)
    com.intellij.plugins.riderkeymap (201.6251.22)
    com.intellij.ideolog (203.0.27.0)
    com.andrey4623.rainbowcsv (2.0.1)
    com.alayouni.ansiHighlight (1.2.4)
    izhangzhihao.rainbow.brackets (6.21)
    String Manipulation (8.24.203.5981.1)
    com.microsoft.vso.idea (1.162.0)

The plugins window says:
 - Unity support is bundled 2021.3.2.229.
 - dotCover is bundled 213.6461.51

**Comment by van800** [comment]
Hey! Thank you for reporting.
Here is what you may try right away - close Unity, call action "Start Unity with Coverage", after it starts, try to cover the tests. If all your tests are Edit/Play mode, try to switch specifically to the mode
![image](https://user-images.githubusercontent.com/1482681/148656036-5c5a38b7-9f4f-4c4d-8ef9-4ada7c631069.png)

I might be able to say more, after examining the logs, so it would be better to reproduce the problem once again, call Help->Report a Bug (in Rider), agree to attach logs. Post link to that newly created issue here.

**Comment by Kylotan** [comment]
https://youtrack.jetbrains.com/issue/RIDER-73302

I have some tests of both types, but I don't think the mode drop-down makes any difference.

**Comment by van800** [comment]
Thank you for reporting in YT. I am closing this issue here, in favor of [RIDER-73302](https://youtrack.jetbrains.com/issue/RIDER-73302)
