### ISSUE TITLE
Can't find DotSettings file

### ISSUE THREAD

**Issue by Spartanace1024** [JetBrains/resharper-unity#224]
I'm trying to save a team wide settings file in Rider using the layers provided. 

After searching through my game directory though I don't see any DotSettings files as is specified [here](https://resharper-support.jetbrains.com/hc/en-us/articles/115001216530-Where-to-find-DotSettings-files-associated-with-settings-layers).

Thanks for any help in advance!

**Comment by van800** [comment]
This [link](https://rider-support.jetbrains.com/hc/en-us/articles/115001239810-Where-to-find-DotSettings-files-associated-with-settings-layer-) is Rider specific. Does it help?

**Comment by Spartanace1024** [comment]
Unfortunately I had seen that link already and checked that location. According to the link, the team shared settings file should be at the root of my Unity project and it's nowhere to be found.

Could this be a bug?

**Comment by Spartanace1024** [comment]
I just noticed that on my mac I have two settings files stored. However on my PC the settings files don't show up. Below are the names of the files.

- Assembly-CSharp.csproj.DotSettings
- jump.sln.DotSettings.user

Also am I correct to assume that neither one of these is my team shared settings (jump is my solution name)?

**Comment by citizenmatt** [comment]
Correct, the team shared settings should be `jump.sln.DotSettings`.

What are you trying to save to team settings? When changing a value, did you use the Save To button to Save To Team Shared Settings?

**Comment by Spartanace1024** [comment]
Ah I figured out the issue. I was trying to save my current settings to team settings by just clicking save to team without changing anything. I didn't realize whatever I had changed would then be set team settings upon saving.

Thanks for the help!
