### ISSUE TITLE
Rider for Unity is broken on MacOS

### ISSUE THREAD

**Issue by jeroenjacobs79** [JetBrains/resharper-unity#2242]
Auto-complete doesn't work and I'm getting errors in Rider.

Unity Version: 2021.2.8f1
Rider version: 2021.3.2 (Installed via ToolBox)

in Unity, Editor was set in Preferences->External Tools to "Rider". When double-clicking a .cs file in Unity, Rider opens but auto-completion doesn't work. 

When switching to "Solution"-view in Rider, I see the following errors:

```
Assembly-CSharp . Load failed
Assembly-CSharp-editor . Load failed
```

Clicking on those errors reveals the following:

```
MSBuild process was started from '/Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/MSBuild.dll', but IDE failed to connect to it. It means MSBuild crashed or froze during startup.  This error usually occurs because of invalid Mono. Try to update Mono Runtime. Current Mono: /Library/Frameworks/Mono.framework/Versions/5.8.1/bin/mono-sgen64
```

When clicking "detailed log", I see the following:

```
Microsoft (R) Build Engine version 15.4.0.0 (xplat-master/67e8006d Thu Mar  8 17:15:24 EST 2018) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.
MSBUILD : error MSB1001: Unknown switch.
Switch: /var/folders/nz/rcfccl0d3dvf4cm_s7gf14240000gn/T/Kynesoj.proj
For switch syntax, type "MSBuild /help"
```

I did not install a Mono runtime when installing Rider. I assume the Mono version mentioned above is the one installed by Unity itself? 

It seems it is parsing the path as command-line switch? (due to the path starting with `/` character)

**Comment by jeroenjacobs79** [comment]
Hmmz, I just noticed that the Mono version it refers to, was installed on my machine 2018. No clue where this installation comes from.

Will install a more recent version, and see what it does.

**Comment by citizenmatt** [comment]
Yes please, a more recent version of Mono should help.

**Comment by van800** [comment]
Alternatively dotnet core msbuild is also working fine.

**Comment by jeroenjacobs79** [comment]
Updating Mono solved the issue. Thanks for the feedback :)
