### ISSUE TITLE
Solution fails to load with package version 3.0.10 

### ISSUE THREAD

**Issue by tconkling** [JetBrains/resharper-unity#2245]
I just updated the JetBrains Rider Editor Unity package from 3.0.9 to 3.0.10, and Rider is no longer able to open my Unity project. For most libraries in the solution, Rider emits a variant of this error:

```
Project 'ParadoxNotion.csproj' targets 'NET_4_6'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.0'. at (1655:5)  Target: _GetProjectReferenceTargetFrameworkProperties Task: GetReferenceNearestTargetFrameworkTask  Open Microsoft.Common.CurrentVersion.targets Open TheHunt.Runtime.csproj
```

The commonality in the few libraries that _do_ load seems to be that they don't have dependencies on other libraries?

I tried invalidating Rider caches and restarting, and I also tried regenerating the csproj files from within Unity (Preferences > External Tools > Regenerate project files) with no luck.

Reverting to package 3.0.9 fixes things.

Here are my environment details:
- Unity 2020.3.26f1 (the latest LTE release)
- Rider 2021.3.2 (the latest release)
- macOS 11.6.2
- Unity project API Compatibility Level: .NET 4.X

![Screen Shot 2022-01-14 at 3 05 09 PM](https://user-images.githubusercontent.com/709022/149596759-b15c35ca-1c2b-46ce-98d3-8e7e28b9fdd0.png)

**Comment by van800** [comment]
Thank you for reporting.
Is your solution generated by Unity or it is custom one with Unity projects? Which msbuild is specified in Rider settings?
![image](https://user-images.githubusercontent.com/1482681/149616642-f91cf875-1ac6-47d5-9857-af29a11cb704.png)

**Comment by tconkling** [comment]
- msbuild version is 16.0 (I believe I installed dotnet via homebrew, but it's possible I just downloaded the installer from Microsoft?)
- My solution is auto-generated by Unity
- I'm attaching the `TheHunt.Runtime.csproj` (I don't mind the filenames being visible, so I didn't remove them)

![Screen Shot 2022-01-15 at 9 49 56 AM](https://user-images.githubusercontent.com/709022/149632459-25486f66-fc5f-456d-8478-1f27a1683a69.png)

[TheHunt.Runtime.csproj.zip](https://github.com/JetBrains/resharper-unity/files/7875499/TheHunt.Runtime.csproj.zip)

**Comment by tconkling** [comment]
I just uninstalled dotnet-sdk 3.1.402 and installed dotnet-sdk 6.0.101, and the solution now loads properly, so I'm good!

(This still feels like a regression, since the previous version of the Unity package worked with the older SDK, and the newer version doesn't tell the user to upgrade their dotnet-sdk.)

**Comment by Cixelyn** [comment]
Also ran into this exact issue on `3.0.10`. Downgrading to `3.0.9` seems to work as a workaround.

**Comment by van800** [comment]
Problem reproduced at my end (with dotnet 3.1 msbuild), thank you for the information.

**Comment by mrstruijk** [comment]
I have the same issue! Downgrading to 3.0.9 worked out for mee too.

**Comment by tconkling** [comment]
Just a note to the people who are downgrading to 3.0.9 - you can also upgrade to .NET 6.0, which includes msbuild 17, and this will work as well. (On a Mac, you can install .NET 6 from homebrew via `brew install dotnet-sdk`, or download the bundled installer from MS directly: https://dotnet.microsoft.com/en-us/download)

**Comment by JasonStein** [comment]
Apple silicon Mac user here, even tho .NET 6.0 is the only .NET framework installed on my machine, I am still encourtering this issue. However, downgrading to 3.0.9 solves my problem.

**Comment by van800** [comment]
I am pushing the hotfix through Unity release process, sometimes it takes a day, sometimes unfortunately it takes couple of weeks.

The fix can be tried by changing a line in the manifest.json:
```
"com.unity.ide.rider": "3.0.10",
```
into
```
"com.unity.ide.rider": "https://github.com/van800/com.unity.ide.rider.git?path=/Packages/com.unity.ide.rider#3.0.11",
```
