### ISSUE TITLE
Setup path to Unity project in plugin settings

### ISSUE THREAD

**Issue by morga4** [JetBrains/resharper-unity#2254]
Hello,

"Unity Support" plugin for Rider works only in case when you open Unity's generated sln or create your own sln in the same folder. It means that once you create a sln outside this folder - you won't be able to use Unity mode for Explorer (only Solution, File System, Assemblies), no "Unity Editor connection" icon in the bottom status bar, no .meta files handle once you create/delete files for Unity's csproj, etc.

To support the case when you manage sln outside Unity's project directory - it would be necessary to specify a relative path to the directory in plugins settings as layered one.

**Comment by van800** [comment]
This is by design. You may though put your custom solution in the same folder as unity-generated one, that would be supported.

**Comment by morga4** [comment]
Yep, it is clear that it's by design. Is it some hard design decision that can not be tweaked or potentially it can be done as enhancement in future?

`You may though put your custom solution in the same folder as unity-generated one, that would be supported.`
This one works but it invents mess when you have multiple repositories and have specific desires where to place sln.

**Comment by citizenmatt** [comment]
It is a hard design decision. Many features rely on the file layout of the Unity project folder - `Assets`, `Packages`, `ProjectSettings` and `Library`, and expect the solution to live in the root of the Unity project.

Recognising that we're opening a Unity project is based on this folder structure. Finding process IDs to attach the debugger expects to find the file `Library/EditorInstance.json`. The Unity explorer view is displaying a hybrid view of the file system and project model, rooted in the Unity project folder, and so on.

All of these features would need to be reworked to get a new root folder from somewhere, plus mechanisms would need to be created to convert a non-Unity Rider solution into a Unity solution, including storage of this new root folder. This is a lot of work for the current level of demand. If there is more demand in future, we could reconsider.

**Comment by morga4** [comment]
I see, thanks for details.
Is it means that if I create a sln outside of the Unity project folder and then add existing Unity-generated csproj then Rider should behaves as usual (zero Unity plugin features)?
Right now I see Unity-plugin run widget (Attach to Unity Process, Unity Settings, Attach to Unity Editor, Unity dotTrace profile) instead of non-Unity one. Should I go on and create a ticket for this one?

**Comment by van800** [comment]
We provide feature-subset for all solutions with a reference to UnityEngine/UnityEditor assemblies.
