### ISSUE TITLE
Brand new run widget is missing (2021.3)

### ISSUE THREAD

**Issue by morga4** [JetBrains/resharper-unity#2256]
Hello,

Rider 2021.3 [introduced](https://blog.jetbrains.com/dotnet/2021/11/16/rider-2021-3-brand-new-main-toolbar/) a new run widget with 'Launch another configuration' option. But it is missing when working with Unity project.

Steps to reproduce:

1. open Unity's generated sln (with enabled Unity plugin)

Expected: new run widget is available
Actual: old run widget is presented

- JetBrains Rider 2021.3.2
- Rider's plugin: Unity Support 2021.3.2.229

**Comment by van800** [comment]
I have referenced this report in https://youtrack.jetbrains.com/issue/RIDER-73557
Thank you!

**Comment by rwx788** [comment]
Please, also see https://youtrack.jetbrains.com/issue/RIDER-72700
We don't have new toolbar for Unity yet, whereas it is planned to add it. Please, do not hesitate to to add yourself to the watch list. Cheers!

**Comment by citizenmatt** [comment]
Fixed in 2022.2
