### ISSUE TITLE
Create New C# Script can destabilize Rider Unity Plugin

### ISSUE THREAD

**Issue by fergjoe** [JetBrains/resharper-unity#2259]
If there is any error in naming a C# script (duplicate name, typo, invalid characters), Unity will report the compiler error as normal.  Opening the file in Rider will disconnect that file from the project even after errors are corrected and the project is recompiled.  Error detection either won't start or no longer processes project class references or using statements.  Other code is unaffected and appears normal. Reopening file, closing and reopening Rider doesn't fix the issue.  

To Reproduce:
1 - In Unity: Create - New C# Script or use CTRL+D to duplicate existing script
2 - Name script improperly (by accident of course!)  😄 
3 - Allow Unity to compile
4 - In Rider: open badly named file and attempt to fix, recompile.

WORKAROUND : Close and restart Unity or force a recompile of Unity's plugins via the package manager will solve issue.

**Comment by van800** [comment]
If you are using Rider package version 3.0.10, please fall back to 3.0.9. I have a suspicion that problem might be caused by the bug in that version.

**Comment by van800** [comment]
Please follow up / reopen, if this still happens with Rider package 3.0.12.
