### ISSUE TITLE
Allow Custom Plugin Path

### ISSUE THREAD

**Issue by ahokinson** [JetBrains/resharper-unity#226]
It's great that Rider can update the plugin to the latest version automatically, but it would be nice to be able to move the file to another location. Currently, by moving the `Unity3DRider.cs` file, you will end up with duplicates once Rider reinstalls to the old location.

I know that Unity has a suggested path for things that are editor related, but organizing first by namespace and then by Editor folder would allow for less confusing installations.

Example, your ordering vs. another plugin
![screen shot 2017-09-11 at 1 12 23 pm](https://user-images.githubusercontent.com/1762048/30287413-f71cb672-96f2-11e7-9dd0-d5dbfd15209e.png)

Since I only have two plugins, this isn't terribly important for me right now, but I do feel that since users have organizational preferences in their Unity projects, this should be considered

**Comment by IvanPashchenko** [comment]
@ahokinson Hi!
Actually, moving `Unity3DRider.cs` should not generate duplicates — in fact, this is the preferred method of changing its' installation place (as long as the `Unity3DRider.cs` file is still in the solution structure).
Could you please tell us the environment info? (OS, Rider version, Unity version). 

Also, an exact repro (describing when you switch to Unity Editor as that's when project model gets regenerated) or logs would be helpful!

Logs can be found by accessing the Help -> Show Log in Finder/Explorer. 
Things that interest us would be `backend.log` file. If you're unable to provide full log, please show any strings that have mention of `UnityPluginInstaller`.

**Comment by ahokinson** [comment]
This was something that I previously experienced and only just thought about again today so it may no longer be an issue.  Let me try later tonight to reproduce and I will update here.

**Comment by van800** [comment]
@ahokinson Is it fine to close this?

**Comment by ahokinson** [comment]
@van800 I can't reproduce it anymore, so I believe I was reacting to an old issue I experienced.
