### ISSUE TITLE
Advanced Unity integration is unavailable:

### ISSUE THREAD

**Issue by prehonor** [JetBrains/resharper-unity#2268]
Advanced Unity integration is unavailable: Make sure "JetBrains Rider Editor" is installed in Unity’s Package Manager and Rider 2021.3.2 is set as the External Editor.
unity ： 2020.3.26f1c1
Unity Support：2021.3.2.229

I open Rider from Unityhub and got the errors above these are too uselessl to figure it out.
How to solve it step by step ，such as view logging ？

**Comment by van800** [comment]
I believe this was already improved targeting 2022.1

**Comment by yuanke7** [comment]
> 

No , it doesn't

**Comment by van800** [comment]
@yuanke7 Lets get it to a separate request? Could you please, reproduce the problem, and then call Help->Report a Bug->Agree to attach logs. Thanks!
