### ISSUE TITLE
The type or namespace name 'Xcode' does not exist in the namespace 'UnityEditor.iOS'

### ISSUE THREAD

**Issue by Ethan-VisualVocal** [JetBrains/resharper-unity#227]
**Issue:**
Error when building "Assembly-CSharp-Editor-firstpass": `The type or namespace name 'Xcode' does not exist in the namespace 'UnityEditor.iOS'`

This occurs every time Unity regenerates the csproj files.

This issue has existed before for me in Rider, ([see previous](https://github.com/JetBrains/Unity3dRider/issues/15)) ... and I'm not sure if it has returned because an issue with the Unity editor, the Rider plugin, or something unique to my setup. 

**Workaround:** 
Manually re-add the `UnityEditor.iOS.Extensions.Xcode` reference to the Assembly-CSharp-Editor-firstpass.csproj, then rebuild.

**Environment:**
Reproduced in Unity_2017.1p2 and Unity_2017.1.1p1

Rider 2017.1.1
Build #RD-171.4456.2813, built on August 21, 2017
Licensed to VISUAL VOCAL / Ethan
JRE: 1.8.0_112-release-736-b22 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

Rider "Unity Support" plugin: 2.0.3.2540

**Example code:**

```
#if UNITY_IOS

using System.IO;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;
using UnityEditor;

public class UnityWebViewPostprocessBuild {
    [PostProcessBuild(100)]
    public static void OnPostprocessBuild(BuildTarget buildTarget, string path) {
        if (buildTarget == BuildTarget.iOS) {
            string projPath = path + "/Unity-iPhone.xcodeproj/project.pbxproj";
            PBXProject proj = new PBXProject();
            proj.ReadFromString(File.ReadAllText(projPath));
            string target = proj.TargetGuidByName("Unity-iPhone");
            proj.AddFrameworkToProject(target, "WebKit.framework", false);
            File.WriteAllText(projPath, proj.WriteToString());
        }
    }
}

#endif
```

Any advice/help? Should I file a ticket with Unity? Is there some obscure alteration I can make on my Unity project to fix it?

**Comment by van800** [comment]
Fast workaround would be enabling line 
https://github.com/JetBrains/resharper-unity/blob/master/resharper/src/resharper-unity/Unity3dRider/Assets/Plugins/Editor/JetBrains/RiderAssetPostprocessor.cs#L80
I was sure that this is fixed in Unity in 2017.1, so I put it under pre-processor directive.

**Comment by Ethan-VisualVocal** [comment]
@van800 That worked, thanks so much! 

I just did some additional testing: It seems they did fix it mostly in 2017.1, because I cannot repro this issue by creating a new project that includes my example code. 

No clue why the issue is cropping up specifically in my project -- I've done multiple Reimport-All in Unity and/or clean checkout & rebuilds (where a clean checkout only includes `/Assets and `/ProjectSettings` -- Unity has to generate the `/obj`, `/Library` folders and csproj, sln files from scratch.)  

Also, I confirmed that using MonoDevelop also reproduces my issue -- so definitely NOT Rider's problem! (But suggestion to alter your plugin works nicely around my issue, so thank you!)

**Comment by mikejohnstn** [comment]
@van800 I'm having this same issue in 2017.3.0p3. Commenting out the `!UNITY_2017_1_OR_NEWER` directives worked for me as well as a workaround.

**Comment by van800** [comment]
Thanks for the report

**Comment by van800** [comment]
fixed for upcoming Rider 2017.3.1

**Comment by CF-Carl** [comment]
Has this issue regressed? I'm on Rider 2018.2.3 and Unity 2018.1.7 and need to manually add the XCode reference to the firstpass project in order to get it to compile.

**Comment by van800** [comment]
Please follow this new issue https://github.com/JetBrains/resharper-unity/issues/855
Share with us correct dll path on your machine.
@CF-Carl Workaround should be adding mcs.rsp or csc.rsp file to Assets with "-r:fullPathToDll".
