### ISSUE TITLE
Unity Rider Plugin Unusable in 2021.2.13f1

### ISSUE THREAD

**Issue by EaTa** [JetBrains/resharper-unity#2287]
**What steps will reproduce the issue?**
_Create a new Unity 2021.2.13f1 project from the Hub using the "3D (HDRP)" template._

**What is the expected result?**
_A working HDRP project is created and opened._

**What happens instead?**
_Unity immediately detects errors in the Rider Package Plugin._

**Notes:**
**The 2.x.x version of the Unity Rider Plugin seems to function properly in Unity 2020.x.x_**

JetBrains Rider 2021.3.3
Build #RD-213.6775.4, built on January 26, 2022

Unity 2021.2.13f1

**_Initial project creation from the Hub._**
![2022-03-01 13_53_37-LAPTOP-9CQUO287](https://user-images.githubusercontent.com/1959816/156259068-068d5901-67b8-4382-86c1-14053560aa76.png)

**_Resulting opened project showing Rider package errors in the Unity console panel._**
![2022-03-01 13_53_09-LAPTOP-9CQUO287](https://user-images.githubusercontent.com/1959816/156259103-e1366acb-df3f-4741-93dd-eecfe34cc220.png)

**_External Rider plugin unavailable in Unity Prefs._**
![2022-03-01 14_34_02-LAPTOP-9CQUO287](https://user-images.githubusercontent.com/1959816/156260278-171e4624-0fc4-4482-8c35-6d1e3783e2e9.png)

**_Rider IDE warning concerning Unity advanced integration._**
![2022-03-01 14_25_44-LAPTOP-9CQUO287](https://user-images.githubusercontent.com/1959816/156260087-66318270-b813-4550-9390-96d13e04ffe6.png)

**_Rider logs for the Unity project, as requested._**
[rider-logs-20220301-1428383731249502973439527.zip](https://github.com/JetBrains/resharper-unity/files/8165170/rider-logs-20220301-1428383731249502973439527.zip)

**Comment by EaTa** [comment]
Perhaps!  However, the Package Manager shows 3.0.12 as the latest available / recommended.  I have "Pre-Release Packages" enabled in, but there's no indication 3.0.13 is available in the Packages stream.

I did a little more investigation and this is **_DEFINITELY_** a problem with 3.0.12.  I pulled up Unity on my workstation at the office, which is running Unity 2021.2.13f1 with version 3.0.9 of the Rider Editor package plugin, and it's fine.  So, back on my personal machine, I removed the Rider 3.0.12 package the "broken" Unity 2021.2.13f1 / Rider 3.0.12 project, and then edited the package manifest to force a "downgrade" to Rider Editor 3.0.9.  Everything works great again!!  So, there's something definitely amiss with 3.0.12.  

**_Only 3.0.12 is available in the Package Manager...._**
![2022-03-02 10_57_08-LAPTOP-9CQUO287](https://user-images.githubusercontent.com/1959816/156429829-d157b479-eb58-4e5a-9f6a-3bb847734c7e.png)

**Comment by citizenmatt** [comment]
The messages about the `.meta` files not having valid GUIDs is very odd, as though the files were corrupt (possibly empty?)

If this happens again, please can you check the contents of the reported files?

**Comment by van800** [comment]
I have tried that very Unity 2021.2.13f1 on Mac with the same project 3D(HDPR), but it didn't reproduce for me.

**Comment by EaTa** [comment]
Well timed! I was just creating a new HDRP project which, by default, installs the "Engineering Package", which includes the latest Rider Editor.  So, taking one of the noted meta files - PluginSettings.cs.meta - as an example, this is it!  All NULL's, ie corrupted
![2022-03-02 13_51_37-LAPTOP-9CQUO287](https://user-images.githubusercontent.com/1959816/156455973-0da0f0a0-45de-4a3c-b943-78abb8918a0c.png)
.

**Comment by EaTa** [comment]
Looking at the same meta file from the 3.0.9 plugin package cache, this is what it _should_ look like..
![2022-03-02 13_55_29-LAPTOP-9CQUO287](https://user-images.githubusercontent.com/1959816/156456242-d94b794e-b3af-4c55-8f1f-e203b1e4c8e4.png)
.

**Comment by van800** [comment]
What if you clean up 3.0.12 package from the PackageCache?

**Comment by EaTa** [comment]
I've tried that multiple times.  When a project opens and reconciles the cached packages against the manifest and sees Rider is missing, it simply downloads 3.0.12 again and immediately the project console is filled with Rider plugin errors (and the ability to choose Rider as the external editor in the Unity Prefs is gone).

Also, regarding the new Unity "Package Features" in the Package Manager: Rider 3.0.12 is part of the "Engineering" feature pack, as shown below.  In order to downgrade Rider Editor to 3.0.9 you need to first remove the feature pack (which, oddly, does NOT remove the individual packages that make up the pack), then remove the individual Rider 3.0.12 package, close Unity and, finally, manually edit the package manifest for the project to force it to use Rider Editor 3.0.9
![2022-03-02 14_05_32-LAPTOP-9CQUO287](https://user-images.githubusercontent.com/1959816/156458478-58b7c764-6904-4041-930b-a338400b7586.png)

Package manifest file after removing both the "Engineering Features" and Rider 3.0.12 packages from the Package Manager, and then hacking it to force use of Rider 3.0.9.
![2022-03-02 14_12_03-LAPTOP-9CQUO287](https://user-images.githubusercontent.com/1959816/156458494-8db146a6-0a05-4ffa-a909-ee21ab621d9b.png)
.

**Comment by van800** [comment]
Please report this issue also to Unity.
Thank you for the details, I will try to recreate it.

**Comment by citizenmatt** [comment]
Check the files in the global package cache. If these are also corrupt, you should be able to delete this cache folder and Unity will re-download, and hopefully the new files will be correct.

On Mac, check `~/Library/Unity/cache/packages/packages.unity.com/com.unity.ide.rider@3.0.12`. Windows should be something like `%LOCALAPPDATA%\Unity\cache\packages\packages.unity.com\com.unity.ide.rider@3.0.12` or `%ALLUSERSPROFILE%\Unity\cache\packages\packages.unity.com\com.unity.ide.rider@3.0.12`

**Comment by EaTa** [comment]
Well, you learn something new every day!  I didn't realize Unity maintained a persistent user AppData cache of all DL'ed packages, present and past.  For the record, on Windoze that cache (for me) was located @ `<BOOTDRIVE>:\Users\<USERNAME>\AppData\Local\Unity\cache\packages\packages.unity.com\com.unity.ide.rider@3.0.12` and it was, indeed, the source of the corruption!!

Thank you **_SO_** much for the help!!!  Not only did it solve my immediate issue, I now have yet another bit of arcane Unity knowledge tucked away in my brain for future use.  I wish there was an exposed way to, ad hoc, flush the Package Manager cache from the Unity interface, similar to being able to invalidate project caches in Rider.

Cheers!  Stay safe.

**Comment by citizenmatt** [comment]
No worries. Glad it's working! The global cache is the download cache, and the package is then copied into the local cache where it might be modified by the API updater (you don't want the global cache updated!)
