### ISSUE TITLE
mcs.rsp not supported

### ISSUE THREAD

**Issue by tactile-readonly** [JetBrains/resharper-unity#229]
Since Unity 5.5, the gmcs.rps and smcs.rps files has been replaced by mcs.rsp. This means that mcs.rps now sets the defines for both the editor and the "play" assemblies. 
gmcs.rps and smcs.rsp is still supported in Unity, however, the documentation does not mention it anymore, hinting at the fact that it will become obsolete at some point. 
Currently in my projects, rider can not read these defines, as we have moved on to use mcs.rsp. In our case, it makes rider unusable.

Another small note is that the defines is also not applied to firstpass assemblies. This should usually not be needed, but there might be custom cases where it would be required.

**Comment by van800** [comment]
Could you please attach your mcs.rsp?

**Comment by van800** [comment]
What Unity version do you use?

**Comment by van800** [comment]
fixed in https://github.com/JetBrains/resharper-unity/pull/230
