### ISSUE TITLE
iOS debugging "The given assembly name or codebase was invalid"

### ISSUE THREAD

**Issue by ManuelRauber** [JetBrains/resharper-unity#2298]
Hi!

Setup is:

* Unity 2021.2.9f1
* Rider 2021.3.3
* macOS 12.2.1
* Unity Rider Package: 3.0.12
* iPhone 12 Max Pro, iOS 15.4
* XCode 13.3

I currently can not debug/set breakpoints anymore. 

I build the game with this options:

![image](https://user-images.githubusercontent.com/740791/160812923-59355889-fef4-4edd-8fee-96edd066fceb.png)

IL2CPP Backend and .NET Standard 2.1.

In Rider, I go to Run -> Attach to Unity Process. There, I'll find the iPhone player:

![image](https://user-images.githubusercontent.com/740791/160812951-31b7cb9e-f44f-46f7-a43a-8493751c17d9.png)

After that, I can see the assemblies getting loaded:

![image](https://user-images.githubusercontent.com/740791/160812967-f680db32-00c9-422c-92f6-3a87df820204.png)

In this list, there's also my own assembly from the game.

However, when I set a breakpoint, I get the following message:

> Could not set breakpoint at location <wholePathToTheGameFolder>/_Game/Scripts/SceneManagement/InitializationLoader.cs : 86 (The given assembly name or codebase was invalid. (0x80131047))

However, the same setup for Android (except using the Mono backend instead of IL2CPP) it works as expected. So it looks like everything for debugging itself is set up correctly, but however will not work for iOS.

Older version of the same game where I've used Unity 2020 LTS I could debug flawlessly. 

Do you have any ideas, what I could try to make debugging work again with iOS?

Thanks!

cross-posted to the Unity Forums: https://forum.unity.com/threads/ios-debugging-with-rider-the-given-assembly-name-or-codebase-was-invalid.1260362/

**Comment by van800** [comment]
I think it is worth trying Rider 2022.1 EAP, it might be already fixed.
If not fixed in EAP, please submit it with Help->Report a Bug, agree to attach logs.
I am closing this report, because it is not something, which can be fixed inside this plugin. It is either Unity or Rider core functionality.
