### ISSUE TITLE
Do not mark as unused all Editor callbacks

### ISSUE THREAD

**Issue by DmitriyYukhanov** [JetBrains/resharper-unity#23]
Would be nice to add support for methods marked with callback attributes like [DidReloadScripts]:
http://docs.unity3d.com/ScriptReference/Callbacks.DidReloadScripts.html

and any other attributes from the UnityEditor.Callbacks namespace

**Comment by citizenmatt** [comment]
So, does this mean that Unity will call any method with this attribute? Does it need special arguments or should the method only exist on `MonoBehaviour` classes?

This sounds like it could be easily fixed using the [`MeansImplicitUseAttribute`](https://www.jetbrains.com/resharper/help/Reference__Code_Annotation_Attributes.html#MeansImplicitUseAttribute) on the `DidReloadScripts` attribute as an external annotation.

**Comment by DmitriyYukhanov** [comment]
Hey,

yes, any static method AFAIR.

And method may exist in class deriving from any other class including System.Object.

Yes, MeansImplicitUseAttribute should work here.
