### ISSUE TITLE
Rider for Unreal Engine with Unity

### ISSUE THREAD

**Issue by CertifiedRice** [JetBrains/resharper-unity#2309]
[Rider for Unreal Engine](https://www.jetbrains.com/lp/rider-unreal/) works very well with Unity C# but it doesn't seem to want to connect with the Rider Unity plugin, I've updated it many times but it still won't work. Any explanation?

I want to use Rider as my Go to game development IDE.

**Comment by van800** [comment]
What unity version do you have? Try to update Rider package in unity to 3.0.14 and check if correct version of Rider is set as external editor in Unity preferences.

**Comment by CertifiedRice** [comment]
![image](https://user-images.githubusercontent.com/73188873/164912820-5b525945-f976-448f-8f74-fc17ca1b6521.png)
Unity version 2019.4.17f1

**Comment by van800** [comment]
Have you updated the Rider package?

**Comment by CertifiedRice** [comment]
yes

**Comment by van800** [comment]
It used to work https://youtrack.jetbrains.com/issue/RIDER-51203, I will check. However you may also use Rider 2022, which has unreal stuff integrated in the main product.

**Comment by CertifiedRice** [comment]
Does Rider 2022 have the same features as the current Unreal Engine Rider or just near it? 
Like C++ and C along as Visual Studio C/C++ project files

**Comment by citizenmatt** [comment]
Rider 2022.1 has merged the Rider for Unreal Engine preview into just "Rider". So Rider 2022.1 contains all of the existing Rider functionality (Unity, asp.net, web, databases, etc.) and now also has C/C++, `.vcxproj` support, Unreal support, etc.

**Comment by CertifiedRice** [comment]
pog so like all of the stuff provided in VS(yk what I mean) in Rider? C++ code completion etc?

**Comment by citizenmatt** [comment]
Yes, Rider has excellent support for C++. It supports syntax highlighting, code completion, navigation, find usages, inspections, quick fixes, context actions, refactorings and so on. On top of that, it has Unreal features, such as control play mode from the IDE, show the Unreal log in the IDE, and best of all, integration with Blueprints, so you can see where your C++ classes are used in Blueprints, what functions are used, and even the values of serialised fields. It's got a lot of cool features.

**Comment by CertifiedRice** [comment]
nice, I can uninstall the Unreal Engine preview now
