### ISSUE TITLE
What is the correct way to replace DLL built-in references (e.g. CoreModule.dll) in a csproj file with my own modified DLL?

### ISSUE THREAD

**Issue by mohumohu-corp** [JetBrains/resharper-unity#2310]
I have rewritten csproj with the OnGeneratedCSProject() function to use Unity's built-in DLL modified by me, but it does not work.

`   <Reference Include="UnityEngine.CoreModule"><HintPath>E:\MyCustomPath\UnityEngine.CoreModule-415699825.dll</HintPath>
</Reference>`

![captured2](https://user-images.githubusercontent.com/85362386/164991907-bbee7c51-7903-4c9a-b940-24aa358cc717.png)

Compilation works fine (I use custom Roslyn compiler), but the IntelliSense on the Rider side still refers to the pre-modified DLL.
I would like to know if there is a solution to this problem.

**Comment by mohumohu-corp** [comment]
I want to replace an existing assembly with a publicized assembly. This will make the use of [IgnoresAccessChecksTo] more user friendly. Code completion (for private, internal members) will not work without generating a publicized reference assembly. Simply rewriting <Reference> in the csproj file was not sufficient.

In a nutshell, all I need is for Intellisnse to be enabled. I' m looking through the MSBuild docs, but so far have no clue.

**Comment by van800** [comment]
How would you make Unity to compile such code?

**Comment by mohumohu-corp** [comment]
1. make precompiled plugins public and cache them
2. compile each script assembly with a custom Roslyn compiler, resolving dependencies.
3. rewrite the Unity rsp file to reference the assemblies already made public and have Unity compile them
4. finally, use ILPostprocessRunnner and Mono.Cecil to add the necessary attributes to the assembly.

**Comment by van800** [comment]
Could you please share the publicized CoreModule.dll?

**Comment by mohumohu-corp** [comment]
I found that clearing the assembly cache solved the problem. Is there an option to disable the assembly cache?
![pic](https://user-images.githubusercontent.com/85362386/165140714-dc3b54de-2f8f-40ea-a312-b39380566d35.png)

**Comment by van800** [comment]
In your OnGeneratedCSProject, you can check the path and either apply the change or not.
I am not sure how that cache works, can you provide me with a repro solution, which would demonstrate the issue and I will pass it to the dev team.
You may create a new issue with Help->Report a Bug and attach that repro solution there. Thanks!
