### ISSUE TITLE
Debugger failing to attach to Unity

### ISSUE THREAD

**Issue by Spartanace1024** [JetBrains/resharper-unity#234]
Whenever I try to attach to the debugger in Rider I get the following error.

"/Users/myname/Library/Application Support/JetBrains/Toolbox/apps/Rider/ch-0/171.4456.2169/Rider 2017.1.app/Contents/lib/ReSharperHost/runtime.sh" "/Users/myname/Library/Application Support/JetBrains/Toolbox/apps/Rider/ch-0/171.4456.2169/Rider 2017.1.app/Contents/lib/ReSharperHost/JetBrains.Debugger.Worker.exe" 60225

This happens whether I click the actual debug icon in the upper left or if I go to Run->Attach To Local Proccess->Unity.

It happens pretty sporadically. Sometimes the debugger will work, sometimes randomly it just wont find the connection.

Thanks in advance!

**Comment by van800** [comment]
What you pasted, it is not an error. Please attach zipped Rider logs from Help->Show log in Files

**Comment by Spartanace1024** [comment]
I have attached the logs below. Hope this helps!

[Archive.zip](https://github.com/JetBrains/resharper-unity/files/1307532/Archive.zip)

**Comment by van800** [comment]
And your Unity version?

**Comment by Spartanace1024** [comment]
Unity version is 2017.1.0f3

**Comment by Spartanace1024** [comment]
Just curious if any headway has been made on the bug. I'm still experiencing the issue even after updating to the latest version of Rider (2017.1)

**Comment by ArsenyChernyaev** [comment]
Hi! Does debugging work using MonoDevelop?

**Comment by Spartanace1024** [comment]
I'll check and report back.

**Comment by ArtOfSettling** [comment]
Just wanted to give this a bump up as I'm also not able to connect the debugger to a running instance. Unfortunately, I updated Rider and Unity at the same time, so I'm unable to figure out which caused the issue.

**Comment by IvanPashchenko** [comment]
@ArtOfSettling @Spartanace1024 hey, does still happen with Rider 2017.3.1?

**Comment by van800** [comment]
Closed due to inactivity, please try [Rider 2018.1 EAP](https://www.jetbrains.com/rider/eap/)
