### ISSUE TITLE
More code analysis styling features in Rider

### ISSUE THREAD

**Issue by DomenPigeon** [JetBrains/resharper-unity#2342]
Hello,
would it be possible that Rider would support other analysis styling features than those originally provided by Roslyn analyzers (Hint, Suggestion, Warning, Error)?

For example Rider already has this kind of styling for expensive method invocation:
![image](https://user-images.githubusercontent.com/35853390/182332022-5df3533b-0d0e-4044-86e0-e40d378f9340.png)

Would it be possible that Rider would inspect Roslyn analyzers for some predefined tags/properties and make it possible to create such warnings inside custom analyzers?

**Comment by citizenmatt** [comment]
Hi there. I'm afraid this is a repo for Unity specific Rider features, and what you're asking for is a change to the core Rider product. Could you create a request in the main issue tracker, please? https://youtrack.jetbrains.com

**Comment by DomenPigeon** [comment]
Ah, yes sorry, my bad ...
