### ISSUE TITLE
Rider integration not detected on Unity

### ISSUE THREAD

**Issue by ffarps** [JetBrains/resharper-unity#2347]
unity v: 2021.3.5f1
Rider v:2022.2.2
OS: POP!_OS (Ubuntu based distro)

expected behaviour: chosing JetBrains Rider of the list

actual behaviour: IDE not in the list, I had to chose manually and when I open a Script Rider opens the file and  does not recognise Unity and says that the unity integration is unavailable.

The code is recognized as "IL Code", instead of Unity, and to not display definitions of methods and such 

here's a screenshot:
![Screenshot from 2022-08-23 17-51-37](https://user-images.githubusercontent.com/73230223/186216916-ff53231b-16ad-42ce-9d5a-0dd13a953474.png)

**Comment by van800** [comment]
Try to install Rider with JetBrains toolbox app.

**Comment by ffarps** [comment]
thanks, it works now
