### ISSUE TITLE
resharper CLT with this plugin: "Method 'Start' is never used" and other unity specific warnings

### ISSUE THREAD

**Issue by Nevey** [JetBrains/resharper-unity#2349]
Hello!

Using: 
```jb inspectcode --no-build "C:\Projects\Unity\My project\My project.sln" --verbosity=INFO --output:"C:\tmp\output.xml" --extensions=JetBrains.Unity```

Versions:
JetBrains Inspect Code 2022.2.2
JetBrains Unity 2022.2.0.143

Will give the following issues output for a specific assembly called "NewAssembly":
```
  <Issues>
    <Project Name="NewAssembly">
      <Issue TypeId="RedundantUsingDirective" File="Assets\NewBehaviourScript.cs" Offset="0-25" Message="Using directive is not required by the code and can be safely removed" />
      <Issue TypeId="RedundantUsingDirective" File="Assets\NewBehaviourScript.cs" Offset="27-60" Line="2" Message="Using directive is not required by the code and can be safely removed" />
      <Issue TypeId="UnusedType.Global" File="Assets\NewBehaviourScript.cs" Offset="97-115" Line="5" Message="Class 'NewBehaviourScript' is never used" />
      <Issue TypeId="UnusedMember.Local" File="Assets\NewBehaviourScript.cs" Offset="246-251" Line="10" Message="Method 'Start' is never used" />
      <Issue TypeId="UnusedMember.Local" File="Assets\NewBehaviourScript.cs" Offset="349-355" Line="16" Message="Method 'Update' is never used" />
    </Project>
  </Issues>
```
    
The code is just one script, in a Unity 2022.1.13f1 project (but can reproduce with older unity versions):
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NewBehaviourScript : MonoBehaviour
{
    [SerializeField] private float _testMe;

    // Start is called before the first frame update
    void Start()
    {
        Debug.Log(_testMe);
    }

    // Update is called once per frame
    void Update()
    {

    }
}
```
    
Using older versions of both resharper CLT & this unity plugin will not output these issues (except for the using directives which can be removed, which is correct).

Am I doing something wrong?

**Comment by van800** [comment]
Thank you for reporting, this is already on our radar. I closing this now in favor of https://youtrack.jetbrains.com/issue/RIDER-80879/Fix-zone-issue-with-Unity-plugin-for-CLT
