### ISSUE TITLE
[Question] Does the package support Resharper 2022.2.2?

### ISSUE THREAD

**Issue by StephenHodgson** [JetBrains/resharper-unity#2351]
Does the package support Resharper 2022.2.2?

I see the last release explicitly says 2020.2.1

**Comment by citizenmatt** [comment]
Yes, latest version supports 2022.2. It currently requires ReSharper C++ to be installed. This is for support of shader files, and is not currently treated as an optional dependency.

**Comment by StephenHodgson** [comment]
![image](https://user-images.githubusercontent.com/13334553/187557600-cbb62231-5ddd-41b2-a90d-bf671db2eadd.png)
Seems like it says it's incompatible.

@citizenmatt please double check

**Comment by citizenmatt** [comment]
Do you have ReSharper C++ installed? As mentioned above, it's currently a required dependency. If it's not installed, the plugin is marked as incompatible.

**Comment by StephenHodgson** [comment]
I do

**Comment by StephenHodgson** [comment]
I even tried updating just to be sure, but it's still saying it is incompatible

**Comment by TheJustLink** [comment]
Same :thinking:

**Comment by TheJustLink** [comment]
I rollback resharper to 2022.2.1 and all works fine

**Comment by StephenHodgson** [comment]
@citizenmatt let's update the documentation please.

Even with C++ 2022.2.2 installed it's not compatible

**Comment by citizenmatt** [comment]
Sorry folks. I've been out of office and not able to look into this properly. The plugin supports 2022.2.1, but requires ReSharper C++ to be installed. Something has changed in 2022.2.2, and we're currently investigating what's going on. Please follow up in #2354 for more details and progress.
