### ISSUE TITLE
Missing documentation on tooltips and when writing code

### ISSUE THREAD

**Issue by emrys90** [JetBrains/resharper-unity#2353]
Does anyone know how to fix this issue in Rider? I'm getting no info on tooltips for any of the Unity API. I have to open the website documentation to see any of it.

This includes when typing code as well, I don't get any info on what the methods/properties do unless I open the external website documentation.

![image](https://user-images.githubusercontent.com/20632855/187810382-af4c1897-2648-4fd5-9df0-a7de6d2fdcc9.png)

**Comment by emrys90** [comment]
I fixed this by changing the External Script Editor in Unity Preferences from Rider to VS, regenerating files, then switching it back to Rider and regenerating files again.

**Comment by citizenmatt** [comment]
That's odd. Rider gets the documentation from the `.xml` files that sit next to the referenced Unity assembly files. It's possible the original project files were pointing to a different copy of these files, and regenerating has pointed to the correct location. If it happens again, could you save the Rider generated project files and compare them with any newly generated files, so we can see what's changed, please?

**Comment by emrys90** [comment]
It's possible. I had recently updated Unity, I can't recall if that is when the issue started or not.
