### ISSUE TITLE
Option to move dependencies to an asset when moving it to another folder

### ISSUE THREAD

**Issue by lucipurrr** [JetBrains/resharper-unity#2359]
When moving assets to a new folder, ask if we want to move dependencies (related to those assets) at the same time.

**Comment by citizenmatt** [comment]
Interesting idea, thanks. I'm not sure what you mean by dependencies though - could you give some examples, please?

**Comment by citizenmatt** [comment]
The issue hasn't been updated for a while, so I'm closing it for now. We can reopen again
