### ISSUE TITLE
Remove option to disable ShaderLab parsing

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#236]
Now that the parser is (hopefully) complete, we should remove the option to disable the ShaderLab PSI parser.

The only question is when - in time for Rider 2017.2, or leave it as a safety net until 2017.3?

**Comment by haolly** [comment]
I use the latest version from ReSharper, but encounter #244

**Comment by citizenmatt** [comment]
This is because the ReSharper plugin doesn't have the latest changes. IIRC, it's the same as Rider 2017.1. I'll make sure a new version is released when we release Rider 2017.2, which is coming very soon.
