### ISSUE TITLE
Namespace does not match file location warning not showing up in Rider

### ISSUE THREAD

**Issue by emrys90** [JetBrains/resharper-unity#2360]
Is there a way to enable this? I want the option to see when the namespace does not match file location, and to refactor it to fix the issue. This was something that was available in Visual Studio.

**Comment by van800** [comment]
Try to check this setting
![image](https://user-images.githubusercontent.com/1482681/195267671-cbce3ac2-10c2-410c-aca5-1a7333e4c843.png)

**Comment by emrys90** [comment]
It's already enabled
![image](https://user-images.githubusercontent.com/20632855/195272665-bdc53e9d-36de-4b2e-b803-dd701c8d14d9.png)

**Comment by van800** [comment]
We'd need more information. Could you please attach some simple project, which demonstrates the problem?
If you can't publicly post the code, you may use Help->Report a Bug (in Rider) and change the whole issue visibility or comment/attachment visibility individually.

**Comment by citizenmatt** [comment]
Closing this issue due to lack of information. Please feel free to add a comment and we can reopen.
