### ISSUE TITLE
"This request is not supported by the protocol version implemented by the debuggee.!!!!!!"

### ISSUE THREAD

**Issue by ALEXTANGXIAO** [JetBrains/resharper-unity#2362]
Version: 2022.2.2
Build: RD-222.3962.23
Timezone: Asia/ShenZhen
Environment: RD-222.3962.23, JRE 17.0.4 7-b469.44x64 JetBrains s.r.o., OS Windows 10(amd64) v10.0 
Unity:2018.4.8f1, JetBrains Rider package: missing

![image](https://user-images.githubusercontent.com/45391272/194795440-c406af61-9624-4ec1-bdef-da73fe706383.png)

![image](https://user-images.githubusercontent.com/45391272/194795591-18dd6ba0-b041-4471-82db-457c105d2837.png)

**Comment by van800** [comment]
Please submit such requests (Debugger, Rider core, everything unrelated to this plugin) in Rider with Help->Report a Bug, agree to attach logs. Thank you!

**Comment by ALEXTANGXIAO** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
