### ISSUE TITLE
ReSharper Unity Plugin Installed with 5 errors in VS 2022

### ISSUE THREAD

**Issue by keyable** [JetBrains/resharper-unity#2363]
hey, I am trying to install ReSharper Unity Plugin for VS 2022, but getting 5 errors in the end. Here is a log, any help pls?  THNX!

Install completed with 5 errors.
  00:18:44.553 ReSharperPlatformVs17_e047f5c1: Error resolving type JetBrains.ReSharper.Psi.Cpp.Caches.CppFileLocation from assembly “JetBrains.ReSharper.Cpp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “JetBrains.ReSharper.Plugins.Unity.Shaders, Version=2022.2.3.162, Culture=neutral, PublicKeyToken=0f46ab053645825e”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.

  00:18:44.616 ReSharperPlatformVs17_e047f5c1: Error resolving type JetBrains.ReSharper.Psi.Cpp.Caches.CppFileLocation from assembly “JetBrains.ReSharper.Cpp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “JetBrains.ReSharper.Plugins.Unity.Shaders, Version=2022.2.3.162, Culture=neutral, PublicKeyToken=0f46ab053645825e”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.

  00:18:44.775 ReSharperPlatformVs17_e047f5c1: Error resolving type JetBrains.ReSharper.Psi.ILanguageCppZone from assembly “JetBrains.ReSharper.Cpp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “JetBrains.ReSharper.Plugins.Unity.Shaders, Version=2022.2.3.162, Culture=neutral, PublicKeyToken=0f46ab053645825e”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.

  00:18:44.776 ReSharperPlatformVs17_e047f5c1: Error resolving type JetBrains.ReSharper.Feature.Services.Cpp.CodeStyle.ICppCustomFormattingInfoProvider from assembly “JetBrains.ReSharper.Feature.Services.Cpp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “JetBrains.ReSharper.Plugins.Unity.Shaders, Version=2022.2.3.162, Culture=neutral, PublicKeyToken=0f46ab053645825e”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.

  00:18:44.777 ReSharperPlatformVs17_e047f5c1: Error resolving type JetBrains.ReSharper.Feature.Services.Cpp.CodeStyle.ICppCodeFormatterExtension from assembly “JetBrains.ReSharper.Feature.Services.Cpp, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”, request originating from assembly “JetBrains.ReSharper.Plugins.Unity.Shaders, Version=2022.2.3.162, Culture=neutral, PublicKeyToken=0f46ab053645825e”. Could not find a referenced assembly by the TT_ASSEMBLYREF token.

**Comment by citizenmatt** [comment]
The Unity plug-in requires ReSharper C++ for shader support. Could you update your installation and try again, please?
