### ISSUE TITLE
Revert script deletion issue (.meta recreated - different guid)

### ISSUE THREAD

**Issue by Flavelius** [JetBrains/resharper-unity#2372]
When deleting a script in rider the corresponding meta file seems to be automatically deleted in a separate history step.
When later reverting both steps together, there seems to be an issue with the order of operations/reloads in background unity as the resulting meta file gets a new guid (this atleast happened to me which i only noticed later on).
I haven't tested it yet, but i guess the workaround is to first revert the auto-meta deletion step and then the script one, but it would be nice if this worked better/more failsafe by default.

**Comment by van800** [comment]
Is it the same https://youtrack.jetbrains.com/issue/RIDER-81449/Doesnt-work-file-recovery-by-CtrlZ-in-local-packages?
Just got fixed yesterday.

**Comment by Flavelius** [comment]
I didn't use ctrl-z, but selected both history steps in the 'local history' window and selected 'revert', but it's potentially the same problem. I'll see if the next update fixes it.

**Comment by van800** [comment]
I have reproduced the issue with local history. Thanks!
I am closing this request in favor of https://youtrack.jetbrains.com/issue/RIDER-84724/Improve-MetaTracker
