### ISSUE TITLE
Better support for IL Viewer

### ISSUE THREAD

**Issue by PeturDarriPeturs** [JetBrains/resharper-unity#2376]
With Rider 2022.3, we can now use the IL Viewer to decompile code into high and low-level C#, to see what our code looks like without syntax sugar. However, this tool doesn't work very well with Unity projects.
 - You have to build the solution in Rider separately
 - Because of this, the assembly that is decompiled is not the same one that's built by Unity, so it doesn't include modifications from IL Post Processors and probably some other differences.

It would be really nice if this plugin could make the IL Viewer load the assemblies from the `Library/ScriptAssemblies` folder instead, which would fix both of these issues.

**Comment by van800** [comment]
There seem to be a workaround.
Open some Empty Solution, open AssemblyExplorer, open your assembly from `Library/ScriptAssemblies` in the AssemblyExplorer, find your code in AssemblyExplorer, show the ILViewer.
![image](https://user-images.githubusercontent.com/1482681/206458494-abfaf90f-8831-4747-b637-86e436ccfff5.png)

**Comment by van800** [comment]
close this in favor of https://youtrack.jetbrains.com/issue/RIDER-86108/ILViewer-for-Unity-projects
