### ISSUE TITLE
Can't get it to work with Unity 2022.2 and Visual Studio 2022

### ISSUE THREAD

**Issue by innat3** [JetBrains/resharper-unity#2379]
I'm getting the following warning after installing this package in Visual Studio 2022:

`Warning	CS8032	An instance of analyzer Unity.MonoScriptGenerator.MonoScriptInfoGenerator cannot be created from C:\Program Files\Unity\Hub\Editor\2022.2.1f1\Editor\Data\Tools\Unity.SourceGenerators\Unity.SourceGenerators.dll: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified..`

My Unity project is targeting .NET Standard 2.1. Any ideas?

**Comment by citizenmatt** [comment]
Hi. Could you provide some more details, please? Which package do you mean? This repo is for a plugin for Rider and ReSharper, and isn't a package you can install in Visual Studio.

**Comment by innat3** [comment]
Hi @citizenmatt, I've a similar issue to this [Post](https://resharper-support.jetbrains.com/hc/en-us/community/posts/115000783750-Extension-Manager-cant-find-Unity-Support-). I want to use Resharper with Visual Studio on my Unity projects, but I get a lot of "fake" warnings in my code (due to how Unity handles programming syntax). This used to be solved with a handy extension from the Resharper Extension Manager which added Unity support for Visual Studio but I can't find it anymore... So I came here and tried to download and add the nuget package manually. Thats where the warning message I previously posted comes into play.

**Comment by CliffCawley** [comment]
@citizenmatt I've got the same issue in Reshaper in VS 2022.

The addon no longer appears when searching in the 'ReSharper Extensions' window and if I download it and try to add it manually, it fails to load.

This is using the latest Resharper 2022.3.1 built on 2022-12-18 (2022.3.20221218.162156) and Visual Studio 2022 (64-bit) v17.4.3.

**Comment by jinroku42** [comment]
I have kind of similar issue.
On clean install of VS 2022 and latest Resharper I can't find Unity extension in .NET Products Gallery, but I also can't add it manualy too.
![изображение](https://user-images.githubusercontent.com/10035130/211142436-38cbf160-7662-41d7-9670-f302085eb4ff.png)
![изображение](https://user-images.githubusercontent.com/10035130/211142452-ff7f6df2-ef3f-422c-8ee4-5844fdd81c80.png)

**Comment by CDTR-MattConroy** [comment]
Any update on this?

**Comment by citizenmatt** [comment]
Sorry for the delay (thanks Windows VM!) the plugin for ReSharper 2022.3 is now available in the extension manager.

**Comment by CliffCawley** [comment]
Hey @citizenmatt, thanks for doing this, but it looks like it's not fully working.

It now definitely appears in the Extensions browser, but it's listed as 'Incompatible'.

![image](https://user-images.githubusercontent.com/6046554/213588368-510657da-6c39-4aba-bab3-796315161802.png)

I'm still using all the same versions as before.
