### ISSUE TITLE
Assembly-CSharp generated without content when using asmdefs

### ISSUE THREAD

**Issue by Flavelius** [JetBrains/resharper-unity#2383]
Hi,
i'm not sure if this is a rider/unity-plugin or just a unity issue.
But for my project where i'm using asmdefs for everything, an Assembly-CSharp csproj is still generated, just without anything in it.
From looking at the csproj file it seems to me that this might somehow be related to rider or the unity plugin:
https://pastebin.com/jVyeU6Xd

**Comment by van800** [comment]
Hey!
This is expected, it contains the Assets folder. It is a way to improve the copy-paste experience.
Imagine, when project doesn't exist pasting file to the Assets folder is generating a lot of ambiguity and only regenerating projects from Unity would help to resolve.

**Comment by Flavelius** [comment]
Is there a setting to disable this? It's unnecessarily adding clutter to an already cluttered view, with projects using many asmdefs

**Comment by van800** [comment]
There's no setting for it now, but please explain further, how it brakes your workflow. I was expecting everyone uses Unity view instead of the Solution view.
Some screenshots would help a lot. Thanks!

**Comment by Flavelius** [comment]
It doesn't break my workflow, it's just unnecessary clutter, as i don't use scripts outside asmdef'ed folders. I personally  prefer using the project view because it's consistent between using unity and godot.
Here's a screenshot of a typical solution where the assembly-csharp projects are just unnecessary:
![grafik](https://user-images.githubusercontent.com/8841352/212556316-3e4e0069-a8d9-4a29-8906-29cbdbe966fe.png)

**Comment by van800** [comment]
Thank you for the feedback.
The related code can be seen [here](https://github.cds.internal.unity3d.com/unity/com.unity.ide.rider/blob/next/master/Packages/com.unity.ide.rider/Rider/Editor/ProjectGeneration/ProjectGeneration.cs#L250).
However I don't have immediate plans to change it. Adding an option to avoid project generation for folders would cause worse cut-paste/drag-n-drop/refactoring behavior.
