### ISSUE TITLE
Private [SerializedField] fields are triggering the "Field is never assigned" warning

### ISSUE THREAD

**Issue by innat3** [JetBrains/resharper-unity#2385]
In your MonoBehaviour scripts, a common way of attaching unity components or adding editable variables from the Unity Editor is to declare a field as public or private (with the SerializedField tag). For instance:

```
public class MyClass: MonoBehaviour
{
    public Buttton myButton;

   //OR

    [SerializeField] private Button myButton;
}
```

The latter is triggering said warning. Could you fix this?

**Comment by citizenmatt** [comment]
This should be working already. What version of Rider or ReSharper are you using? And if you're using ReSharper, have you got the Unity extension installed via ReSharper -> Extension Manager?
