### ISSUE TITLE
Adjust namespaces is wrong for asmdefs

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#2390]
2022.3.0.191

It is also offering to adjust namespaces in Assembly-CSharp which is plain wrong:

<img width="481" alt="devenv_0d0t2lkIAi" src="https://user-images.githubusercontent.com/1537591/220832859-928dfbca-30df-45c7-b0c5-3041d37a70da.png">

<img width="225" alt="devenv_B5ZIzURTky" src="https://user-images.githubusercontent.com/1537591/220833062-c3510473-68a4-4918-b274-153d5c870d84.png">

Furthermore, adjust namespaces in the asmdef only will not update relevant code and you end up with errors.

**Comment by citizenmatt** [comment]
Could you provide some more details, please? This looks like you've got an `asmdef` living inside `Assets`. Do those files (from the `asmdef` project) report incorrect namespaces when you open them in the editor, and if so, what's the suggested namespace? And can you just confirm that these files, such as `ArrayTransform.cs`, are definitely not included in `Assembly-CSharp.csproj`?

And finally, what errors do you see when you do adjust namespaces? What's it adjusted the namespaces to, and which files are not correctly updated?

**Comment by aybe** [comment]
I think I have found the cause of the problem: symbolic links 😁
