### ISSUE TITLE
Inspection on managed IComponentData is incorrect.

### ISSUE THREAD

**Issue by vertxxyz** [JetBrains/resharper-unity#2393]
![image](https://user-images.githubusercontent.com/21963717/223278041-15eb26b5-0a9d-415f-a8e5-671b9652aa5c.png)

[Managed components](https://docs.unity3d.com/Packages/com.unity.entities@1.0/manual/components-managed-create.html) exist!

**Comment by jorgeamado** [comment]
Thanks for your report
This issue will be fixed in the upcoming 2023.1 rider release
