### ISSUE TITLE
Unity package manager can't find Riders packages

### ISSUE THREAD

**Issue by BonaparTT** [JetBrains/resharper-unity#2396]
Hi guys i got recent issue, unity cant find riders packages, so rider cant attach to Unity. I tried a lot of things. Delete, re-install Rider, change parameters in configuration file. If someone can help, i would appreciate.
![Screenshot from 2023-03-27 11-16-24](https://user-images.githubusercontent.com/129048819/227899393-ff7de3e7-7d45-4588-8e7a-e1b94de02660.png)
![Screenshot from 2023-03-27 11-17-07](https://user-images.githubusercontent.com/129048819/227899431-0ae74e89-7dd4-44c3-8115-3c110b75849d.png)

**Comment by van800** [comment]
Hi! 
Could you please share the `manifest.json` and Unity Editor log?
If you want to keep them private, please report a new issue from Rider with Help->Report a Bug and attach them to that new issue. On the YouTrack you would be in control of privacy for any attachment.

**Comment by van800** [comment]
After all I think I understand, what is wrong - just switch the drop-down to Package:Unity Registry and retry to search.
**
<img width="817" alt="image" src="https://user-images.githubusercontent.com/1482681/227904507-c194a728-1f48-4c91-818d-36b1f99a0017.png">
**

**Comment by BonaparTT** [comment]
> After all I think I understand, what is wrong - just switch the drop-down to Package:Unity Registry and retry to search. ** <img alt="image" width="817" src="https://user-images.githubusercontent.com/1482681/227904507-c194a728-1f48-4c91-818d-36b1f99a0017.png"> **

im kinda stupid, thank you for help !
