### ISSUE TITLE
Resharper constantly reloads solution when clicking the console

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#2397]
JetBrains ReSharper 2022.3.2 Build 223.0.20230125.121441 built on 2023-01-25
Unity Support 2022.3.0.191
Visual Studio 17.5.3
Unity 2022.2.12

This is a pretty annoying issue,

Whenever clicking the call stack to browse to a certain line, the solution will be reloaded even though there have been no changes.

I think I have found what could be causing this, when implementing `OnGeneratedCSProject`, Unity will update the projects and their modified date/time.

At this point, Resharper blindly reloads the solution though there have been zero changes in them.

Changing the _solution model_ option does not change anything.

Couldn't Resharper for instance hash them for comparison instead of relying on date/time for when to reload?

Here's the post-processor currently used:

```
#pragma warning disable

using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using UnityEditor;
using UnityEngine;

namespace Whatever
{
    internal sealed class ProjectGeneration : AssetPostprocessor
    {
        private static string OnGeneratedCSProject(string path, string content)
        {
            var document = XDocument.Parse(content);

            var root = document.Root!;

            var ns = root.GetDefaultNamespace();

            var propertyGroupName = ns + "PropertyGroup";

            var propertyGroup = root.Descendants(propertyGroupName).FirstOrDefault();

            if (propertyGroup == null)
            {
                root.Add(propertyGroup = new XElement(propertyGroupName));
            }

            var nullableName = ns + "Nullable";

            var nullable = root.Descendants(nullableName).FirstOrDefault();

            if (nullable == null)
            {
                propertyGroup.Add(nullable = new XElement(nullableName));
            }

            nullable.Value = "enable";

            var noWarnName = ns + "NoWarn";

            var noWarns = root.Descendants(propertyGroupName).Descendants(noWarnName);

            foreach (var noWarn in noWarns)
            {
                var set = new HashSet<string>(noWarn.Value.Split(';'))
                {
                    "8618", // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.
                    "8632"  // The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
                };

                noWarn.Value = string.Join(";", set);
            }

            // ReSharper disable once ConvertToUsingDeclaration

            using (var writer = new Utf8StringWriter())
            {
                document.Save(writer);

                content = writer.ToString();
            }

            return content;
        }

        private sealed class Utf8StringWriter : StringWriter
        {
            public override Encoding Encoding { get; } = Encoding.UTF8;
        }
    }
}
```

**Comment by van800** [comment]
I would compare new text with the current csproj content and avoid write if nothing has chnaged.

**Comment by van800** [comment]
Disregard the previous idea.
Please see the doc https://learn.microsoft.com/en-us/visualstudio/gamedev/unity/extensibility/customize-project-files-created-by-vstu
You are not supposed to make an actual write file to disc. You have to just return the content and VSTU or Unity would do the rest.

**Comment by aybe** [comment]
That's exactly what I'm doing, not writing anything to the input path.

Minus the additions, that's how the example was in the docs, they return an UTF8 string.

**Comment by van800** [comment]
Try to investigate/debug why VSTU decides to write csproj to disc. What is different if you compare content and actual csproj file content?

**Comment by van800** [comment]
I have even better idea. Just create Directory.Build.props file in the sln folder. Put all the property mods inside and there would be no need in the asset post processor at all.

**Comment by aybe** [comment]
The props file used to work back a while ago but not anymore.

I diffed the files and guess what, they're non-deterministic, the order of references changes!

That actual problem didn't happen, say, three months ago, so basically, they broke it... once again.

As we're onto bags of tricks, this one worked out, sort the refs in the processor:

```
            var itemGroups = root.Descendants(ns + "ItemGroup").ToArray();

            foreach (var itemGroup in itemGroups)
            {
                var references = itemGroup.Elements(ns + "Reference").ToArray();

                if (references.Length == 0)
                {
                    continue;
                }

                var elements = references.OrderBy(s => s.Attribute("Include")!.Value).ToArray();

                references.Remove();

                foreach (var reference in elements)
                {
                    itemGroup.Add(reference);
                }
            }
```

Amazingly, I just realized that every single time you click on the console, the solution is regenerated; how inefficient...

Anyway, thanks for the support, problem is solved! 🎯😀

**Comment by citizenmatt** [comment]
We should check to see if the Rider package has the same problem

**Comment by aybe** [comment]
Seems like the previous fix wasn't enough, still sporadically getting this:

![Code_H2mizcgkcV](https://user-images.githubusercontent.com/1537591/229259997-718073f3-e866-4e31-8942-d9cc5f470dfe.png)

This appears to fix it for now:

```
            var rootNamespaces = root.Descendants(ns + "RootNamespace").ToArray();

            foreach (var rootNamespace in rootNamespaces)
            {
                if (Regex.IsMatch(rootNamespace.Value, @"^\s*$", RegexOptions.Multiline))
                {
                    rootNamespace.Value = string.Empty;
                }
            }
```
