### ISSUE TITLE
After opening a MonotBehavior project, Resharper 10 Option menu turns dark

### ISSUE THREAD

**Issue by rob8861** [JetBrains/resharper-unity#24]
Hello,
I just installed the new Unity Plugin version 1.2.0 and noticed that after I opened my unity project, if I try to invoke the Resharper Options menu , the background turns pitch dark which makes it impossible to read the text and make changes. It is important to mention that this behavior does not happen if I open a different c#/.NET or c++ prjects. It seems like it only happens when I open a MonoBehavior project (a.k.a Unity).

How to reproduce:
1. Install Reharper Ultimate version 10.0.2.
2. Install Unity Support extension version 1.2.0
3. Open a new MonoBehavior project , either via Unity Editor or straight from Visual Studio. 
4. Click on Resharper -> Options and then choose Intellisense -> autopopup for instance.

EDIT:
I forgot to mention that I am running on Windows 10. 

here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/1551002/12878320/6ecc97b4-cdd7-11e5-8320-066a3d4e483f.png)

**Comment by citizenmatt** [comment]
This is really odd - the unity plugin has absolutely nothing to do with the colours and themes used in dialogs. These come straight from Visual Studio itself. If you open a non-unity project, does it still look dark?

One thing you can try is to follow [these instructions](https://resharper-support.jetbrains.com/hc/en-us/articles/206546479-ReSharper-Fonts-Colors-settings-do-not-appear-in-Visual-Studio-after-installation), which will reset Visual Studio's font and colours cache. This will fix a similar issue where the colours are wrong for the text editor - with similar dark blue on black(ish) background.

**Comment by rob8861** [comment]
Hi,
Over the weekend I did some more testing and noticed that the dark coloration also happens if the unity extension is not installed. I also tried a complete fresh installation of Resharper (on a different PC) without the unity extension and noticed the same dark color. At that point I suspected it is the VSTU plug-in (Visual Studio tools for unity) so I uninstalled it and the dark color disappeared. 
so this is what I found:

1. If the following are installed - Resharper + Unity extention + VSTU -> will cause the Dark color to appear ONLY in unity projects. The dark color WILL NOT appear if I work on a non-unity project.
2. If the following are installed - Resharper + VSTU -> will cause the dark color to appear in unity projects only.
3. if the following are installed - Resharper + unity extention -> no dark color in unity projects

so based on my testing I suspect that the cause of the dark coloration in the Resharper Option menu is due to  VSTU . Not sure why but I opened a ticket with Resharper and VSTU (Microsoft) tech support.

p.s: unity extension = resharper-unity extension

**Comment by benjaminrickels** [comment]
I have the same problem.
Normal projects work just fine, but once I open a Unity project, some option pages (e.g. Environment > IntelliSense > Autopopup) become dark and unreadable; however others work just fine (e.g. Code Inspection > Inspection Severity ).
I also have the "Cyclomatic Complexity" extension for ReSharper installed and it's options page is also unreadable.
Just closing the project doesn't help: One has to restart Visual Studio.
Reinstalling ReSharper didn't help either and the ReSharper Unity Extension isn't the culprit as well.

**Comment by rob8861** [comment]
I have reported this issue to the VSTU team and they replied back that they will investigate it. 
If you try and uninstall VSTU, the issue will disappear.

**Comment by StefanoFiumara** [comment]
VSTU should no longer be required with the latest version of Unity, if I'm not mistaken, you should be able to uninstall it without losing any functionality.

**Comment by citizenmatt** [comment]
@rob8861 I'd somehow missed your earlier comment - thanks for spotting this! I've [raised an issue](https://youtrack.jetbrains.com/issue/RSRP-455598) in the ReSharper tracker, so we'll take a look too, and see if we're doing something wrong. Thanks!

**Comment by rob8861** [comment]
@citizenmatt I don't think it is even related to resharper. Alexander (one of JetBrains support engineer) noticed that even if resharper is not installed, VSTU still screws up the coloring in visual studio option menu.

**Comment by rob8861** [comment]
Hi Guys,
Just wanted to quickly drop a line that someone from the VSTU team emailed me and said that they have fixed the issue. hopefully the next release of VSTU will remedy the whole coloring bug.

Cheers,

**Comment by citizenmatt** [comment]
As this seems to be a VSTU issue, and not ReSharper or this plugin, I'm closing this issue. Thanks all!
