### ISSUE TITLE
Unknown type when viewing collection in Debugger

### ISSUE THREAD

**Issue by Thundernerd** [JetBrains/resharper-unity#240]
When debugging a Unity project and trying to view a collection in the Debugger view I get the following message instead of appropriate results

Unknown type 'System.Collections.Generic.CollectionDebuggerView`1, mscorlib.dll'

Unity Version: Unity 5.6.3p1 (64 Bit)
Rider Version: Rider 2017.1.2 Build RD-171.4456.3568

**Comment by IvanPashchenko** [comment]
Rider tracker issue here https://youtrack.jetbrains.com/issue/RIDER-5242, linking for convenience.
@Thundernerd what OS are you using?

**Comment by Thundernerd** [comment]
Using Windows 10. Not sure what version and build number but can check those next Monday.

**Comment by vallcrist** [comment]
Same happens here.

Windows 10
Unity 5.6.2f1
Rider 2017.1.2

**Comment by IvanPashchenko** [comment]
Reproduced on the latest 2017.2 / W10, simple repro is attached to RIDER-5242.

**Comment by citizenmatt** [comment]
The [RIDER-5242](https://youtrack.jetbrains.com/issue/RIDER-5242) issue is marked as fixed in the final build of 2017.2, so I'm going to closed this. If it's still a problem, please feel free to reopen.
