### ISSUE TITLE
Unity Massive problem in Version 3.0.20 - April 17, 2023

### ISSUE THREAD

**Issue by firesightstudios** [JetBrains/resharper-unity#2400]
Unity 2021 3.21f1

Ever since getting the notification within Rider IDE to look for Unity Rider package update, It just continues to load, at least 15 times before Unity Editor becomes responsive again.

Rider 2023.1
Build #RD-231.8109.212

**Comment by citizenmatt** [comment]
Just to follow up, package 3.0.21 has been in the Unity Package Manager for a few days now. Please upgrade, and apologies again for the inconvenience
