### ISSUE TITLE
Compiler errors with Unity package 3.0.21

### ISSUE THREAD

**Issue by HalfHeardGames** [JetBrains/resharper-unity#2401]
Unity 2021.3.1f1
JetBrains Rider Editor package version 3.0.21
Rider 2022.1.1

After upgrading the Rider Editor package to version 3.0.21 from 3.0.18, I get the following two compiler errors:

"Library\PackageCache\com.unity.ide.rider@3.0.21\Rider\Editor\ProjectGeneration\ProjectGeneration.cs(556,34): error CS1061: 'ScriptCompilerOptions' does not contain a definition for 'AnalyzerConfigPath' and no accessible extension method 'AnalyzerConfigPath' accepting a first argument of type 'ScriptCompilerOptions' could be found (are you missing a using directive or an assembly reference?)"

"Library\PackageCache\com.unity.ide.rider@3.0.21\Rider\Editor\ProjectGeneration\ProjectGeneration.cs(576,42): error CS1061: 'ScriptCompilerOptions' does not contain a definition for 'RoslynAdditionalFilePaths' and no accessible extension method 'RoslynAdditionalFilePaths' accepting a first argument of type 'ScriptCompilerOptions' could be found (are you missing a using directive or an assembly reference?)"

Manually editing the manifest.json to rollback to "com.unity.ide.rider": "3.0.18", provides a work-around for now.

**Comment by van800** [comment]
Thank you for reporting, I will fix that for the next package version.

**Comment by van800** [comment]
Just for the context
2021.3.0 release was 11.4.2022 and [the change](https://github.com/Unity-Technologies/UnityCsReference/commit/0a2eeb7a72710d89cccdb6aeee8431d27ee99cd1) landed 14.4.2022.

**Comment by van800** [comment]
Would appear in the Rider package 3.0.22, if we wouldn't see any problem during testing.

To try the new version, you may just update manifest.json, substitute
"com.unity.ide.rider": "3.0.18",
by
```
"com.unity.ide.rider": "https://github.com/van800/com.unity.ide.rider.git?path=/Packages/com.unity.ide.rider#3.0.22",
```

**Comment by HalfHeardGames** [comment]
The new version works great, thanks very much!
