### ISSUE TITLE
[Feature request] How about showing references from persistent listeners?

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#2403]
It would be really nice if Resharper could show up references from persistent listeners.

Example:

This method is hooked to from `Button.onClick` in the inspector, but there are no references being shown:

![devenv_G4gyL6YPsu](https://user-images.githubusercontent.com/1537591/235336911-b9293010-acb9-429d-9510-0517f7fd0b37.png)

**Comment by citizenmatt** [comment]
IIRC that's a Visual Studio counter that isn't extensible. The Unity plugin for ReSharper already does index your assets, and can Find Usages inside scenes, assets and prefabs. It can also rename handlers like this and automatically update the asset. But because that's a VS counter, we can't modify it.

**Comment by aybe** [comment]
Alright, thank you!

**Comment by citizenmatt** [comment]
I should probably say that of course Rider supports all of this in a more integrated manner 😁

Dedicated Code Vision links and counts for usages and asset usages, find usages that opens a tool window in the Unity Editor from which you can navigate to the usage, prefab or component…

**Comment by citizenmatt** [comment]
Sorry for the delay in replying. Yes, that's a VS provided popup, and yes, Rider provides better support here. However, Rider doesn't currently have a docking system that's as flexible as Visual Studio's. While it is possible to float editors and dock tool windows to these floating editors, it's not currently possible to dock multiple floating tool windows together. This is something we want to improve in the very near future.
