### ISSUE TITLE
Rider crash when opened.

### ISSUE THREAD

**Issue by JuliGame** [JetBrains/resharper-unity#2406]
Rider crashes when It has to index unity scripts.
This only happens when I directly edit a script with the edit button in unity, If I open the proyect directly with rider it does not happen, but I cannot use unity references.

**Im using:**
Rider 2023.2 EAP4 with the Toolbox.
Unity: 2022.3.1f1 (flatpak)
Os: Arch linux.

https://www.youtube.com/watch?v=aS9pZzreg4o

**Comment by citizenmatt** [comment]
Could you open Rider normally, then use Help -> Report a Bug and create an issue in our YouTrack issue tracker, please? I know you've just created an issue here, but using this menu item makes it very easy to attach logs, which I think we need to see to try and figure out what's going wrong. Thank you!
