### ISSUE TITLE
Reload Script Assemblies popup pops up on top of Rider every time (macOS)

### ISSUE THREAD

**Issue by joonjoonjoon** [JetBrains/resharper-unity#2407]
When "Automatically refresh assets in Unity" is enabled, and I hit ctrl+s, the Reload Script Assemblies popup will pop up on top of the code I'm editing. It resets its position every time.

This has made me and several other developers in my community disable the feature.
Is there a way that the dialogue can remember its position, or that it doesn't take foreground focus?\

![image](https://github.com/JetBrains/resharper-unity/assets/1086635/0dc661b8-4d71-4bc1-907b-bbf338afd9fa)

**Comment by citizenmatt** [comment]
Unfortunately, this is a Unity issue - the dialog is created as a "topmost" window, and there is nothing Rider can do to prevent this. The only workaround right now is to disable the option. Please can you report the issue to Unity?
