### ISSUE TITLE
Add support for "Package" include path for shaders

### ISSUE THREAD

**Issue by guoxx** [JetBrains/resharper-unity#2409]
Resharper HLSL features don't work with shader code that included by "Package/xxx"

![image](https://github.com/JetBrains/resharper-unity/assets/1138365/16af3d3d-0eba-442c-9284-7988c75656d6)

**Comment by van800** [comment]
Doesn't reproduce for me.
![image](https://github.com/JetBrains/resharper-unity/assets/1482681/e95f5b4c-605b-4559-b30b-c69eb4df4487)

If it is still actual for you with Rider 2023.2 EAP8, could you please report it with Help->Report a Bug, agree to attach logs. Please also attach some of your files or a simple solution, which demonstrates the problem. Thanks!

**Comment by guoxx** [comment]
I'm using ReSharper with visual studio. 
From what I know, Rider has better support for HLSL including Packages search path recognition and user macro definition, but we don't have it in ReSharper.

**Comment by van800** [comment]
Very likely related to [RIDER-91999](https://youtrack.jetbrains.com/issue/RIDER-91999)

**Comment by citizenmatt** [comment]
Note that this is an issue that has been fixed as part of the 2023.2 release, and the ReSharper Unity plugin will be released when Rider is released.
