### ISSUE TITLE
Unity reference detection in pre-compiled DLL projects got broken for Unity 2017.2

### ISSUE THREAD

**Issue by XtroTheArctic** [JetBrains/resharper-unity#241]
Unity team split up the main Unity DLLs into small namespace oriented DLLs for Unity 2017.2. Now we can reference those new DLLs in our regular Visual Studio assembly projects. For example, instead of referencing UnityEngine.dll, now we can reference UnityEngine.CoreModule.dll. Resharper Unity plugin doesn't recognize a VS project as a pre-compiled Unity enabled one.

Resharper Unity plugin should search for "UnityEngine" name in references list instead of "UnityEngine.dll" now.

Please see this issue for history of this problem: https://github.com/JetBrains/resharper-unity/issues/150

**Comment by XtroTheArctic** [comment]
Expected version?

**Comment by citizenmatt** [comment]
Ah, it would be nice if GitHub had some kind of link between issues, milestones and releases…

It should all be in [Rider 2017.2, released last week](https://blog.jetbrains.com/dotnet/2017/10/12/jetbrains-rider-2017-2-released/).

**Comment by XtroTheArctic** [comment]
Errr. I am a VS user. What about that?

**Comment by citizenmatt** [comment]
Oops :) I'll get a ReSharper release sorted tomorrow.

**Comment by citizenmatt** [comment]
I've just pushed a new ReSharper release, for ReSharper 2017.2. It should be available in the Extension Manager now. And [here are the release notes](https://github.com/JetBrains/resharper-unity/releases/tag/v2.1.2-resharper).

**Comment by XtroTheArctic** [comment]
ty
