### ISSUE TITLE
Debugger failing

### ISSUE THREAD

**Issue by slacker-jake** [JetBrains/resharper-unity#2414]
Hi,

Been having an issue for awhile where the debugger fails to attach correctly.  Things look fine but break points are never hit.  It seems adding a breakpoint slows down execution in the editor, like its about to hit but never does.  I had similar issue with Visual Studio and moved over to JetBrains primarily because of this.  Now JetBrains behaving the same.  Have to restart Unity for things to work once again but isn't long before it starts failing to attach.  So frustrating!

Unity 2022.3.5f1
JetBrains Rider 2022.3.2

**Comment by van800** [comment]
Could you please report with Help-> Report a Bug, agree to attach logs after the issue happens again? Thank you!
