### ISSUE TITLE
[Bug] Error when Rider is selected as external tool - Reorderable List

### ISSUE THREAD

**Issue by jai-lingokids** [JetBrains/resharper-unity#2416]
Hi, we are facing an issue regarding the usage of Rider + Rider Unity Plugin.

We have a custom inspector that uses a reorderable list, however, when using Rider as external tool it give us internal unity errors.

I managed to debug a bit internally, here are some screenshots:

With VSCode:
<img width="747" alt="Screenshot 2023-09-01 at 15 29 42" src="https://github.com/JetBrains/resharper-unity/assets/122615031/a2acc2a6-ebe0-4d55-87ea-143d133b6301">

With Rider:
<img width="855" alt="Screenshot 2023-09-01 at 15 30 45" src="https://github.com/JetBrains/resharper-unity/assets/122615031/2d489d4b-3b80-4ce2-b083-2b9a32d1c8cf">

As you can see in the case of Rider it's null.

It happens when it's a Reorderable List inside a PropertyDrawer.

Any info is appreciated, thanks.

**Comment by van800** [comment]
Do I understand correctly that it is about debugger evaluation? 
Would you please report this issue with Help -> Report a Bug, agree to attach logs?
It would also help, if you provide us with a code sample.
Thank you.
