### ISSUE TITLE
Assertions/erorrs about IsMapping()

### ISSUE THREAD

**Issue by jchowdown** [JetBrains/resharper-unity#2425]
Hi, we're running 3.0.26 against Unity 2022.3.10 and are getting these errors, does anyone know how we might clear these please?

Assertion failed on expression: 'IsMapping()'
Tried to get mapping information from scalar node

Both happen at

`UnityEngine.StackTraceUtility:ExtractStackTrace ()
Packages.Rider.Editor.Util.FileSystemUtil:GetFinalPathName (string) (at ./Library/PackageCache/com.unity.ide.rider@3.0.26/Rider/Editor/Util/FileSystemUtil.cs:20)
Packages.Rider.Editor.RiderScriptEditor:GetEditorRealPath (string) (at ./Library/PackageCache/com.unity.ide.rider@3.0.26/Rider/Editor/RiderScriptEditor.cs:77)
Packages.Rider.Editor.RiderScriptEditor:InitializeInternal (string) (at ./Library/PackageCache/com.unity.ide.rider@3.0.26/Rider/Editor/RiderScriptEditor.cs:218)
Packages.Rider.Editor.RiderScriptEditor:.cctor () (at ./Library/PackageCache/com.unity.ide.rider@3.0.26/Rider/Editor/RiderScriptEditor.cs:32)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes (System.Type[])
`

We got these with 3.0.24 as well and I thought upgrading to .26 would help but it didn't.
We're running multiple flavors of Rider (2022.1.2, 2022.2.3, 2022.3.1) if it helps.

**Comment by van800** [comment]
Hi! What is the OS and path to Rider, which cause the error?

**Comment by jchowdown** [comment]
Closing because I forgot all about this but I have more info so I'll open a new one

**Comment by OSG-Bart** [comment]
woopsie, where's the new one? Just got this error after integrating a third party package
