### ISSUE TITLE
Unity plugin for ReSharper 2023.3

### ISSUE THREAD

**Issue by MPleskunina** [JetBrains/resharper-unity#2428]
Unity plugin is currently not available for the latest ReSharper release version - 2023.3.

**Comment by citizenmatt** [comment]
We've had a small problem with the builds, so it might take a day or two to get the release sorted. Should hopefully be released tomorrow (Dec 12)

**Comment by citizenmatt** [comment]
Sorry for the delay. The 2023.3 version of the ReSharper plugin is now available in the extension manager
