### ISSUE TITLE
Compiler errors with Unity package 3.0.26 - 3.0.27

### ISSUE THREAD

**Issue by Coruh211** [JetBrains/resharper-unity#2430]
Unity 2022.3.13f1
JetBrains Rider Editor package version 3.0.26 - 3.0.27
Rider 2023.3.3

After updating the Rider to version 2023.3.3 and updating the Rider Editor package to 3.0.26 - 3.0.27(both versions produce these errors). I get errors like this in Unity:

Library\PackageCache\com.unity.ide.rider@3.0.26\Rider\Editor\Discovery.cs(3,23): error CS0234: The type or namespace name 'PathLocator' does not exist in the namespace 'JetBrains.Rider' (are you missing an assembly reference?)

Library\PackageCache\com.unity.ide.rider@3.0.26\Rider\Editor\RiderScriptEditor.cs(6,23): error CS0234: The type or namespace name 'PathLocator' does not exist in the namespace 'JetBrains.Rider' (are you missing an assembly reference?)

Library\PackageCache\com.unity.ide.rider@3.0.26\Rider\Editor\RiderScriptEditorData.cs(3,23): error CS0234: The type or namespace name 'PathLocator' does not exist in the namespace 'JetBrains.Rider' (are you missing an assembly reference?)

Library\PackageCache\com.unity.ide.rider@3.0.26\Rider\Editor\Discovery.cs(57,44): error CS0246: The type or namespace name 'IRiderLocatorEnvironment' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.unity.ide.rider@3.0.26\Rider\Editor\Discovery.cs(16,28): error CS0246: The type or namespace name 'RiderPathLocator' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.unity.ide.rider@3.0.26\Rider\Editor\Discovery.cs(59,12): error CS0246: The type or namespace name 'OS' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.unity.ide.rider@3.0.26\Rider\Editor\Discovery.cs(17,28): error CS0246: The type or namespace name 'RiderFileOpener' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.unity.ide.rider@3.0.26\Rider\Editor\RiderScriptEditorData.cs(18,31): error CS0246: The type or namespace name 'RiderPathLocator' could not be found (are you missing a using directive or an assembly reference?)

The rollback method to 3.0.22 helps https://github.com/JetBrains/resharper-unity/issues/2401

**Comment by van800** [comment]
Would you please attach Editor.log from Unity?
In those versions of the package RiderPathLocator is supplied inside the assembly.
So I assume, for some reason it is not loaded.

**Comment by Coruh211** [comment]
> Не могли бы вы прикрепить Editor.log из Unity? В этих версиях пакета RiderPathLocator поставляется внутри сборки. Так что предполагаю, почему-то не нагружается.

Sorry for the trouble, I reinstalled Unity using a clean uninstall and now everything is fine, thanks for the help)
