### ISSUE TITLE
When creating a project on 2022.3.16f1, the Rider libraries are not installed

### ISSUE THREAD

**Issue by whiskas009** [JetBrains/resharper-unity#2432]
Hello! I want to create a project using version 2022.3.16f1, but after creating it, the Rider libraries are not installed, and the script editor cannot be selected in “External Tools”.

On version 2022.3.13f1, when updating the plugin to 3.0.27, these errors appear, on 3.0.26 everything is fine

Version 2022.3.20f1 also has this error

Also, in my other project on Unity version 2021.3.22f1, when updating the version from 3.0.18 to 3.0.27, the same errors appear

![Screenshot_1](https://github.com/JetBrains/resharper-unity/assets/76867818/22483f37-8619-407b-bfe6-908532a3602b)
![Screenshot_2](https://github.com/JetBrains/resharper-unity/assets/76867818/b17e0917-4d36-4d25-9297-31374af0ccb2)

**Comment by van800** [comment]
Hi! 
This has been reported once, but resolved by itself with clean uninstall-install of Unity.
https://github.com/JetBrains/resharper-unity/issues/2430#issuecomment-1916609866

**Comment by van800** [comment]
closing this in favor of [RIDER-106210](https://youtrack.jetbrains.com/issue/RIDER-106210)

**Comment by whiskas009** [comment]
> Hi! This has been reported once, but resolved by itself with clean uninstall-install of Unity. [#2430 (comment)](https://github.com/JetBrains/resharper-unity/issues/2430#issuecomment-1916609866)

Need to reinstall Unity Hub or Unity Editor?

**Comment by van800** [comment]
IDK, please attach the Editor.log to [RIDER-106210](https://youtrack.jetbrains.com/issue/RIDER-106210)

**Comment by whiskas009** [comment]
Clearing the global UPM cache and then re-creating the project helped
