### ISSUE TITLE
Rider "Parse text based asset" keeps disabling itself even if "Automatic Disable" is turned off

### ISSUE THREAD

**Issue by builder-main** [JetBrains/resharper-unity#2433]
Hi it was working before, I think I just updated Rider some times ago and now "Parse text based asset files for script and event handler usages"  disables itself even if "Automatic Disable" is turned off. It's a top tier feature and I'd like to be using it again. And yes we have a quite large project.

Unity plugin version :
![image](https://github.com/JetBrains/resharper-unity/assets/32265170/ac762274-442f-40f6-ac3a-9e43d8580b1c)

Rider Build #RD-233.14015.60, built on January 18, 2024

**Comment by builder-main** [comment]
Alright, so after having disabled "Automatic Disable", relaunching Rider seems to have fixed it.

**Comment by krasnotsvetov** [comment]
Hi! There is definitely a bug with forcing asset mode. I have discovered it too some time ago and fixed in 2024.2 during refactoring for asset support, will try to backport fix to 2024.1
