### ISSUE TITLE
Advanced Unity Integration is Unavailable

### ISSUE THREAD

**Issue by AsherSE** [JetBrains/resharper-unity#2436]
I've been using Rider with Unity for a couple of years now, and it's always been fine. I got a new computer and it was good for a little bit, and then recently nothing has worked. Rider is a total mess full of fake errors, incorrect colouring, completely missing intellisense data and so on. 

I'm also not entirely sure what 'installing Rider Editor in the package manager' means. As far as I'm aware the only rider plugin available is called Rider Flow. I've attached an image of the error in Rider and also the setting in Unity because that doesn't look right either... 

<img width="395" alt="image" src="https://github.com/JetBrains/resharper-unity/assets/4086317/9af6ef4b-892d-4330-a56a-3784c43de659">

<img width="629" alt="image" src="https://github.com/JetBrains/resharper-unity/assets/4086317/70297fce-b264-4450-8678-cdf57c62ff64">

<img width="755" alt="image" src="https://github.com/JetBrains/resharper-unity/assets/4086317/f9e3082f-4931-441a-af51-ccda61b1fc25">

**Comment by van800** [comment]
Please share manifest.json and Unity version with me. Thank you!

**Comment by AsherSE** [comment]
OK will do! I'm not near my computer right now but I'll get them asap!

**Comment by AsherSE** [comment]
[manifest.json](https://github.com/JetBrains/resharper-unity/files/14826161/manifest.json)
unity version is 2022.3.2f1

Rider seems to be completely unusable in this state. It can't even navigate to the source of functions.

**Comment by van800** [comment]
Try to add
```
    "com.unity.ide.rider": "3.0.28",
```

**Comment by AsherSE** [comment]
I still see 
"Make sure JetBrains Rider Editor is installed in Unity’s Package Manager and Rider 2023.3.4 is set as the External Script Editor." in Rider. Additionally (I may be remembering this wrong) but it doesn't look right when I set Rider to be the IDE in the Unity settings.

<img width="834" alt="image" src="https://github.com/JetBrains/resharper-unity/assets/4086317/b60a6e30-7975-4f27-b051-29de70d1d2ee">

**Comment by AsherSE** [comment]
Ah ok no, that did work. I just had to restart unity

**Comment by AsherSE** [comment]
Thank you!
