### ISSUE TITLE
Can't find plugin JetBrains.Unity using inspectcode 2024.1

### ISSUE THREAD

**Issue by metakirby5** [JetBrains/resharper-unity#2438]
When specifying the plugin via the `-x` flag in [inspectcode](https://www.jetbrains.com/help/resharper/InspectCode.html), the output `Warning: Can't find plugin JetBrains.Unity` is observed, and Unity inspections are not applied. This did not occur in `2023.3.3`. Additionally, it does not occur for other plugins (e.g. `PowerToys.CyclomaticComplexity`) in `2024.1`, so I suspect the issue lies with the `JetBrains.Unity` plugin.

Example:

```
$ ~/Downloads/JetBrains.ReSharper.CommandLineTools.2024.1/inspectcode.sh \
  --no-build --severity=ERROR \
  --eXtensions="JetBrains.Unity;PowerToys.CyclomaticComplexity" \
  --format='Xml;Html' --output=inspectcode Project.sln
Warning: Can't find plugin JetBrains.Unity
JetBrains Inspect Code 2024.1
PowerToys CyclomaticComplexity 2024.1.0-eap01
Running on ARM64 OS in ARM64 architecture, .NET 7.0.2 under Darwin 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
Using toolset version 17.0 from /usr/local/share/dotnet/sdk/7.0.102
Configuration: Debug, Platform: Any CPU

```

**Comment by sr4dev** [comment]
ReSharper 2024.1

I have a similar issue. I don't see all my extensions in the Extension Manager in ReSharper.
I think it's probably a server issue.

![image](https://github.com/JetBrains/resharper-unity/assets/9159336/1f90f00d-21e0-440b-b3df-1a9f17207387)

If you add old url to Extension Manager option, you can find Unity Extension.
(But it's not work in 2024.1)

![image](https://github.com/JetBrains/resharper-unity/assets/9159336/4ebe4df2-546d-467a-8eec-10e90b9c9e31)

**Comment by innat3** [comment]
For now, you can download it and add it manually from [https://plugins.jetbrains.com/plugin/11629-unity-support/versions/stable]( https://plugins.jetbrains.com/plugin/11629-unity-support/versions/stable)

**Comment by citizenmatt** [comment]
Hi folks. The Unity plugin for ReSharper was updated yesterday, could you try again, please? And the blank Extension Manager in 2024.1.1 is indeed a server issue, and should hopefully be fixed now.

**Comment by sr4dev** [comment]
I have confirmed that the server issue has been resolved in Extension Manager. Thank you!

![image](https://github.com/JetBrains/resharper-unity/assets/9159336/eb9cacbb-d60e-40fb-9967-45992af46d2b)

**Comment by metakirby5** [comment]
Thanks, @citizenmatt - I tried the same command again today, but no luck 😥

I noticed the following logs with `--verbosity=VERBOSE`:

```
No environment variables for additional packages are set.
  CACHE https://resharper-plugins.jetbrains.com/api/v2/curated-feeds/RSU-2024.1.0.65536/FindPackagesById()?id='JetBrains.Unity'&semVerLevel=2.0.0
Warning: Can't find plugin JetBrains.Unity
  CACHE https://resharper-plugins.jetbrains.com/api/v2/curated-feeds/RSU-2024.1.0.65536/FindPackagesById()?id='PowerToys.CyclomaticComplexity'&semVerLevel=2.0.0
Found plugin package/PowerToys.CyclomaticComplexity 2024.1.0-eap01 for PowerToys.CyclomaticComplexity (>= 0.0.0) in .NET Products Gallery [https://resha
```

Looking at https://resharper-plugins.jetbrains.com/api/v2/curated-feeds/RSU-2024.1.0.65536/FindPackagesById()?id='JetBrains.Unity'&semVerLevel=2.0.0 I see there are no entries, but for https://resharper-plugins.jetbrains.com/api/v2/curated-feeds/RSU-2024.1.0.65536/FindPackagesById()?id='PowerToys.CyclomaticComplexity'&semVerLevel=2.0.0 there are.

**Comment by citizenmatt** [comment]
Apologies. The plugin was automatically verified against 2024.1.1, but not 2024.1.0. So it was in the 2024.1.1 feed, but not the 2024.1.0 feed. It should be available in both now.

**Comment by metakirby5** [comment]
It's working perfectly now, thank you!
