### ISSUE TITLE
The pattern where the File Layout settings for Unity only work in Rider and not in ReSharper.

### ISSUE THREAD

**Issue by sr4dev** [JetBrains/resharper-unity#2439]
When I use Windows, I use Visual Studio + ReSharper, and when I'm on a Mac, I develop using Rider.
Recently, I updated to ReSharper 2024.1.1 and Rider 2024.1.1.

After the update, the File Layout for Unity that used to work well is no longer working in ReSharper, but it still works in Rider.

Below is the Unity File Layout that I am using.
<details>
<summary>XML</summary>

	<s:String x:Key="/Default/CodeEditing/Unity/AdditionalFileLayout/Pattern/@EntryValue">&lt;Patterns xmlns="urn:schemas-jetbrains-com:member-reordering-patterns" xmlns:unity="urn:schemas-jetbrains-com:member-reordering-patterns-unity"&gt;
    &lt;TypePattern DisplayName="Serializable Type" RemoveRegions="All"  Priority="100"&gt;
        &lt;TypePattern.Match&gt;
            &lt;unity:SerializableClass /&gt;
        &lt;/TypePattern.Match&gt;
        &lt;Entry DisplayName="Static Fields and Constants"&gt;
            &lt;Entry.Match&gt;
                &lt;Or&gt;
                    &lt;Kind Is="Constant" /&gt;
                    &lt;And&gt;
                        &lt;Kind Is="Field" /&gt;
                        &lt;Static /&gt;
                    &lt;/And&gt;
                &lt;/Or&gt;
            &lt;/Entry.Match&gt;
            &lt;Entry.SortBy&gt;
                &lt;Kind Order="Constant Field" /&gt;
            &lt;/Entry.SortBy&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="Nested Types"&gt;
            &lt;Entry.Match&gt;
                &lt;Kind Is="Enum" /&gt;
            &lt;/Entry.Match&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="Public Enums" Priority="100"&gt;
            &lt;Entry.Match&gt;
                &lt;And&gt;
                    &lt;Access Is="Public" /&gt;
                    &lt;Kind Is="Enum" /&gt;
                &lt;/And&gt;
            &lt;/Entry.Match&gt;
            &lt;Entry.SortBy&gt;
                &lt;Name /&gt;
            &lt;/Entry.SortBy&gt;
        &lt;/Entry&gt;
        &lt;Region Name="Inspector"&gt;
            &lt;Entry DisplayName="Serialized Fields"&gt;
                &lt;Entry.Match&gt;
                    &lt;!-- Keep serialised fields and auto-properties with serialised backing
                         fields together, unsorted, to maintain order in the Inspector
                         window --&gt;
                    &lt;Or&gt;
                        &lt;unity:SerializedField /&gt;
                        &lt;unity:AutoPropertyWithSerializedBackingField /&gt;
                    &lt;/Or&gt;
                &lt;/Entry.Match&gt;

                &lt;!-- No sorting --&gt;
            &lt;/Entry&gt;
        &lt;/Region&gt;
        &lt;Entry DisplayName="Non-serialised Fields"&gt;
            &lt;Entry.Match&gt;
                &lt;And&gt;
                    &lt;Kind Is="Field" /&gt;
                    &lt;Not&gt;
                        &lt;unity:SerializedField /&gt;
                    &lt;/Not&gt;
                &lt;/And&gt;
            &lt;/Entry.Match&gt;

            &lt;Entry.SortBy&gt;
                &lt;Readonly /&gt;
            &lt;/Entry.SortBy&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="Public Delegates" Priority="100"&gt;
            &lt;Entry.Match&gt;
                &lt;And&gt;
                    &lt;Access Is="Public" /&gt;
                    &lt;Kind Is="Delegate" /&gt;
                &lt;/And&gt;
            &lt;/Entry.Match&gt;
            &lt;Entry.SortBy&gt;
                &lt;Name /&gt;
            &lt;/Entry.SortBy&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="Auto Properties"&gt;
            &lt;Entry.Match&gt;
                &lt;Kind Is="Autoproperty" /&gt;
            &lt;/Entry.Match&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="Properties, Indexers"&gt;
            &lt;Entry.Match&gt;
                &lt;Or&gt;
                    &lt;Kind Is="Property" /&gt;
                    &lt;Kind Is="Indexer" /&gt;
                &lt;/Or&gt;
            &lt;/Entry.Match&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="Interface Implementations" Priority="100"&gt;
            &lt;Entry.Match&gt;
                &lt;And&gt;
                    &lt;Or&gt;
                        &lt;Kind Is="Property" /&gt;
                        &lt;Kind Is="Indexer" /&gt;
                    &lt;/Or&gt;
                    &lt;ImplementsInterface /&gt;
                &lt;/And&gt;
            &lt;/Entry.Match&gt;
            &lt;Entry.SortBy&gt;
                &lt;ImplementsInterface Immediate="True" /&gt;
            &lt;/Entry.SortBy&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="RuntimeInitializeOnLoadMethod"&gt;
          &lt;Entry.Match&gt;
            &lt;HasAttribute Name="UnityEngine.RuntimeInitializeOnLoadMethod" /&gt;
          &lt;/Entry.Match&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="Constructors"&gt;
            &lt;Entry.Match&gt;
                &lt;Kind Is="Constructor" /&gt;
            &lt;/Entry.Match&gt;
            &lt;Entry.SortBy&gt;
                &lt;Static /&gt;
            &lt;/Entry.SortBy&gt;
        &lt;/Entry&gt;
        &lt;Region Name="Unity Event"&gt;
            &lt;Entry DisplayName="Event Functions"&gt;
                &lt;Entry.Match&gt;
                    &lt;unity:EventFunction /&gt;
                &lt;/Entry.Match&gt;
            &lt;/Entry&gt;
        &lt;/Region&gt;
        &lt;Entry DisplayName="Interface Implementations" Priority="100"&gt;
            &lt;Entry.Match&gt;
                &lt;And&gt;
                    &lt;Kind Is="Member" /&gt;
                    &lt;ImplementsInterface /&gt;
                &lt;/And&gt;
            &lt;/Entry.Match&gt;
            &lt;Entry.SortBy&gt;
                &lt;ImplementsInterface Immediate="True" /&gt;
            &lt;/Entry.SortBy&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="Nested Types"&gt;
            &lt;Entry.Match&gt;
                &lt;Kind Is="Type" /&gt;
            &lt;/Entry.Match&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="All other members"&gt;
            &lt;Entry.SortBy&gt;
                &lt;Access /&gt;
                &lt;Static /&gt;
            &lt;/Entry.SortBy&gt;
        &lt;/Entry&gt;
    &lt;/TypePattern&gt;
    &lt;TypePattern DisplayName="Default Pattern" RemoveRegions="All"&gt;
        &lt;TypePattern.Match&gt;
            &lt;Not&gt;
                &lt;Or&gt;
                    &lt;HasAttribute Name="System.Serializable" Target="Type" /&gt;
                    &lt;InheritsFromType Name="UnityEngine.Object" /&gt;
                &lt;/Or&gt;
            &lt;/Not&gt;
        &lt;/TypePattern.Match&gt;
        &lt;Entry DisplayName="Static Fields and Constants"&gt;
            &lt;Entry.Match&gt;
                &lt;Or&gt;
                    &lt;Kind Is="Constant" /&gt;
                    &lt;And&gt;
                        &lt;Kind Is="Field" /&gt;
                        &lt;Static /&gt;
                    &lt;/And&gt;
                &lt;/Or&gt;
            &lt;/Entry.Match&gt;
            &lt;Entry.SortBy&gt;
                &lt;Kind Order="Constant Field" /&gt;
            &lt;/Entry.SortBy&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="Nested Types"&gt;
            &lt;Entry.Match&gt;
                &lt;Kind Is="Enum" /&gt;
            &lt;/Entry.Match&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="Public Enums" Priority="100"&gt;
            &lt;Entry.Match&gt;
                &lt;And&gt;
                    &lt;Access Is="Public" /&gt;
                    &lt;Kind Is="Enum" /&gt;
                &lt;/And&gt;
            &lt;/Entry.Match&gt;
            &lt;Entry.SortBy&gt;
                &lt;Name /&gt;
            &lt;/Entry.SortBy&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="Fields"&gt;
            &lt;Entry.Match&gt;
                &lt;And&gt;
                    &lt;Kind Is="Field" /&gt;
                    &lt;Not&gt;
                        &lt;Static /&gt;
                    &lt;/Not&gt;
                &lt;/And&gt;
            &lt;/Entry.Match&gt;
            &lt;Entry.SortBy&gt;
                &lt;Readonly /&gt;
                &lt;Static /&gt;
                &lt;Virtual /&gt;
            &lt;/Entry.SortBy&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="Public Delegates" Priority="100"&gt;
            &lt;Entry.Match&gt;
                &lt;And&gt;
                    &lt;Access Is="Public" /&gt;
                    &lt;Kind Is="Delegate" /&gt;
                &lt;/And&gt;
            &lt;/Entry.Match&gt;
            &lt;Entry.SortBy&gt;
                &lt;Name /&gt;
            &lt;/Entry.SortBy&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="Properties, Indexers"&gt;
            &lt;Entry.Match&gt;
                &lt;Or&gt;
                    &lt;Kind Is="Property" /&gt;
                    &lt;Kind Is="Indexer" /&gt;
                &lt;/Or&gt;
            &lt;/Entry.Match&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="Constructors"&gt;
            &lt;Entry.Match&gt;
                &lt;Kind Is="Constructor" /&gt;
            &lt;/Entry.Match&gt;
            &lt;Entry.SortBy&gt;
                &lt;Static /&gt;
            &lt;/Entry.SortBy&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="Interface Implementations" Priority="100"&gt;
            &lt;Entry.Match&gt;
                &lt;And&gt;
                    &lt;Kind Is="Member" /&gt;
                    &lt;ImplementsInterface /&gt;
                &lt;/And&gt;
            &lt;/Entry.Match&gt;
            &lt;Entry.SortBy&gt;
                &lt;ImplementsInterface Immediate="True" /&gt;
            &lt;/Entry.SortBy&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="All other members"&gt;
            &lt;Entry.SortBy&gt;
                &lt;Access /&gt;
                &lt;Static /&gt;
            &lt;/Entry.SortBy&gt;
        &lt;/Entry&gt;
        &lt;Entry DisplayName="Nested Types"&gt;
            &lt;Entry.Match&gt;
                &lt;Kind Is="Type" /&gt;
            &lt;/Entry.Match&gt;
        &lt;/Entry&gt;
    &lt;/TypePattern&gt;
&lt;/Patterns&gt;</s:String>
</details>

Below is the .DotSettings file that I am using.
[dotsettings.zip](https://github.com/JetBrains/resharper-unity/files/15031967/dotsettings.zip)

By the way, is there any plan to add a Unity-specific File Layout tab to ReSharper?
When I need to edit the File Layout for Unity, 
I follow the method described at https://github.com/JetBrains/resharper-unity/issues/1771, but this method is quite painful.

**Comment by sr4dev** [comment]
I have identified the pattern.

The Unity scripts like MonoBehaviour and ScriptableObject are not using the Unity File Layout; instead, they're using a standard File Layout.

**Comment by citizenmatt** [comment]
That's very unexpected. I have ReSharper 2024.1.1 and Unity Support 2024.1.0.307 installed just fine. I'm not seeing it marked as "incompatible", and don't understand how we could have different results there. Have you restarted VS since installing the Unity Support plugin? It might be worth uninstalling, restarting VS and reinstalling.

**Comment by sr4dev** [comment]
Yes, whenever I upgraded ReSharper or downgraded it, I always restarted VS. I also restarted VS every time I installed Unity Support or deleted the existing version.

However, I haven't rebooted my PC yet. I'll try that later. I'll also try reinstalling VS.

**Comment by citizenmatt** [comment]
Shouldn't need to restart your PC or reinstall VS. It might be that you need to install ReSharper C++. The shader support in the Unity plugin uses the C++ engine to parse the code, but previous versions have been ok to run without it installed. Something might have changed.

**Comment by sr4dev** [comment]
Thank you for the feedback! Installing ReSharper++ solved all the issues!
