### ISSUE TITLE
Shader parse issue

### ISSUE THREAD

**Issue by haolly** [JetBrains/resharper-unity#244]
![image](https://user-images.githubusercontent.com/2383231/31269554-8c1ac844-aab3-11e7-92d6-f99de7b9d697.png)

FallBack could has another param, but this feature is not documented in unity.

One more issue:
![image](https://user-images.githubusercontent.com/2383231/31269758-365b1714-aab4-11e7-85a1-30d8cf5e9e0b.png)

> Texture property options (removed in 5.0)
Before Unity 5, texture properties could have options inside the curly brace block, e.g. TexGen CubeReflect. These were controlling fixed function texture coordinate generation. This functionality was removed in 5.0; if you need texgen you should write a vertex shader instead. See Implementing Fixed Function TexGen page page for examples.

**Comment by citizenmatt** [comment]
This has already been fixed in the latest EAP builds for Rider 2017.2. Are you using 2017.1? Can you try upgrading?

**Comment by citizenmatt** [comment]
I saw the comment on #236 - if this is ReSharper, it's also already been fixed, but not released yet. A release will come soon, probably next week.

**Comment by citizenmatt** [comment]
I'm going to close this in favour of #246
