### ISSUE TITLE
Resharper 2024.1.2 - Not in list of extentions

### ISSUE THREAD

**Issue by MazakTheDwarf** [JetBrains/resharper-unity#2444]
I examined the other issues describing the incompatible extension, but as you can see I have ReSharper c++ installed.

JetBrains ReSharper 2024.1.2
Build 241.0.20240506.152321 built on 2024-05-06
dotCover 2024.1.20240506.152321
dotTrace 2024.1.20240506.152321
ReSharper C++ 2024.1.20240506.152321
ReSharper 2024.1.20240506.152321
AI Assistant 2024.1.20240506.152321
dotMemory 2024.1.20240506.152321

In my testing to solve the incompatible issue, I uninstalled the release version and now unity is not available to install.

![image](https://github.com/JetBrains/resharper-unity/assets/158404677/722bb4fa-5d88-4a01-a28b-9daefa8b07b5)

I am running visual studio 2019 and 2022 - both have the same issue.

**Comment by MazakTheDwarf** [comment]
I had to manually download the nuget package from jetbrains site.

**Comment by benblo** [comment]
Yep, not showing for me either...
