### ISSUE TITLE
Resharper 2024.1.3 on Visual Studio 2022: Incompatible with Unity Support

### ISSUE THREAD

**Issue by Piyotato** [JetBrains/resharper-unity#2447]
**Environment**
JetBrains ReSharper 2024.1.3
Build 241.0.20240607.153524 built on 2024-06-07
- ReSharper, 2024.1.20240607.153524 (up to date)
- ReSharper C++, 2024.1.20240607.153524 (up to date)
- dotTrace, 2024.1.20240607.153524 (up to date)
- dotCover, 2024.1.20240607.153524 (up to date)
- dotMemory, 2024.1.20240607.153524 (up to date)

I attempted to install Unity Support from the JetBrains [site](https://plugins.jetbrains.com/plugin/11629-unity-support/versions#tabs) (2024.1.0.307) which claims to be compatible with ReSharper 2024.1.1 - 2024.1.3, but ReSharper's extension manager still says it is incompatible. From #2444 and #2442 it seems that I only need to install ReSharper C++, which I have done but to no avail.

Here is what the extension manager shows:
![image](https://github.com/JetBrains/resharper-unity/assets/17792019/ac94a5c8-270c-4411-96fe-aa04077f0abe)

**Comment by PoisonerSC** [comment]
Maybe the compatibility information has a mistake. I have tried 2024.1.2 and 2024.1.3, with ReSharper C++ installed.
However, Unity Support can only be used with 2024.1.1 right now, so I have gone back to 2024.1.1 for now.

**Comment by JianjianGit** [comment]
When can this be fixed?

**Comment by citizenmatt** [comment]
Apologies for the delay. A version that is compatible with 2024.1.2 and above is now available.

**Comment by JianjianGit** [comment]
健健已收到你的邮件
