### ISSUE TITLE
Odin support for MinValue and Range are reversed.

### ISSUE THREAD

**Issue by vertxxyz** [JetBrains/resharper-unity#2452]
Min attempts to get a max position from the attribute:

https://github.com/JetBrains/resharper-unity/blob/98f45648cbf4c1e6d05cb99c7fedeb0ee8cca255/resharper/resharper-unity/src/Unity/Odin/Feature/Services/CodeAnnotations/OdinMinAttributeInformationProvider.cs#L35

![image](https://github.com/JetBrains/resharper-unity/assets/21963717/3cbf3941-5354-437c-8f38-c67119fa80be)

And range's upper bound is max value:
https://github.com/JetBrains/resharper-unity/blob/98f45648cbf4c1e6d05cb99c7fedeb0ee8cca255/resharper/resharper-unity/src/Unity/Odin/Feature/Services/CodeAnnotations/OdinRangeAttributesInformationProvider.cs#L39

![image](https://github.com/JetBrains/resharper-unity/assets/21963717/89d2a8a3-ce40-4c82-84c3-0f733cde0f0a)

**Comment by citizenmatt** [comment]
Fixed as part of 2024.2
