### ISSUE TITLE
No code completion in expression evaluator inside #if UNITY_EDITOR blocks

### ISSUE THREAD

**Issue by Khairex** [JetBrains/resharper-unity#2453]
I originally wrote this up on [YouTrack](https://youtrack.jetbrains.com/issue/RIDER-114659/No-code-completion-in-expression-evaluator-inside-if-UNITYEDITOR-blocks), but It seems more relevant here so I'm posting it again.

Rider Version 2024.1.2 & 2024.2 EAP6
Unity: 2021.1.19f1, JetBrains Rider package: 3.0.31

**Steps to reproduce** 
Create a simple MonoBehaviour script with an easy breakpoint location eg.

```
    public void OnValidate()
    {
        int x = 1;
        Debug.Log(x);
#if UNITY_EDITOR
        int y = 2;
        Debug.Log(y);
#endif
    }
```

There are 2 places this occurs, one while debugging and one not.

1. Create a breakpoint inside any `#if UNITY_EDITOR` block
2. Edit the breakpoint's Condition (or Evaluate and Log expression)
3. Press (CTRL+Space) for code suggestions

<br>

1. Start debugging and Attach to Unity Editor
2. Reach a breakpoint inside any `#if UNITY_EDITOR` block
3. Navigate to either expression evaluator window
    - Window in Debug/Threads & Variables (ALT+I)
    - Dialogue Window (CTRL+ALT+Q)
4. Press (CTRL+Space) for code suggestions

<br>

**Expected result:** 
Code suggestions appear normally

<br>

**Actual result:** 
No suggestions available

<br>

**Additional information** 
Code completion still works in the script file itself, just not the Expressions Evaluator

Also, the actual evaluation of the expressions still work, the code just won't autocomplete for you when writing them

This also appears to not be limited to just the `UNITY_EDITOR` define, the bug also persists with other active unity defines such as `UNITY_STANDALONE_WIN` and `UNITY_5_3_OR_NEWER`. If I create a new define `FOO` in the same file and use that, the code suggestions work normally.

![image1](https://github.com/user-attachments/assets/ae89a017-1533-4390-8adf-e68f9d3e2614)

![image](https://github.com/user-attachments/assets/192e5e27-e173-4bb0-bfd5-9c153ab4433c)

**Comment by citizenmatt** [comment]
Thanks for raising the issue. I think this is better handled as an issue in YouTrack, as I think this is more likely an issue with how the expression evaluator handles preprocessor branches, rather than anything specific to Unity or the Unity symbols. I'm going to close this issue in favour of the YouTrack issue. Thanks!
