### ISSUE TITLE
Unresolved shader name 'xyz' false warning can't be suppressed

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#2458]
Basically, it's unable to figure out stock shaders:

![image](https://github.com/user-attachments/assets/6f3725d6-5018-4c27-8342-d30a53aa971f)

![image](https://github.com/user-attachments/assets/62ae8cd3-7fb0-4108-9e03-a972a6cca176)

**Comment by mirasrael** [comment]
Hi. We can't reproduce the issue on the latest version. Can you please provide information about your version?

**Comment by aybe** [comment]
Sorry, I should have upgraded first, I did and it works now.

For the record:

```
JetBrains ReSharper 2023.3.5
Build 233.0.20240415.205308 built on 2024-04-15
ReSharper C++ 2023.3.20240415.212818
ReSharper 2023.3.20240415.211937
JetBrains ForTea 2023.3.0 (Compatible)
JetBrains Unity 2023.3.2.100 (Compatible)

Visual Studio Enterprise 2022
Version 17.11.2, InstanceId a77197d5.
...
JetBrains Unity build 2023.3.2.100 on 0001-01-01

```

Thank you.
