### ISSUE TITLE
External Documentation for .Net types goes to dead Mono site

### ISSUE THREAD

**Issue by roger-o3h** [JetBrains/resharper-unity#2459]
All .Net documentation links to docs.go-mono.com which seems to be completely down. Example: http://docs.go-mono.com/?link=M:System.Type.GetType(System.String)

Ideally .Net types would link to documentation.microsoft.com. Example: https://learn.microsoft.com/en-ca/dotnet/api/system.type.gettype?view=netstandard-2.0#system-type-gettype

<img width="711" alt="Screenshot 2024-08-26 at 13 04 36" src="https://github.com/user-attachments/assets/c3a4407e-2e39-4f36-8c59-37249f1e6a04">

If there is some way to change this in Rider, or by editing Unity's builtin `UnityReferenceAssemblies`, I could not find it - please advise if so!

**Comment by van800** [comment]
Thank you for reporting!
I have created https://youtrack.jetbrains.com/issue/RIDER-116449/Review-doc-provider-for-mono-BCL
