### ISSUE TITLE
Packages are not recognized properly after 6000.0.22f1

### ISSUE THREAD

**Issue by ilterbilguven** [JetBrains/resharper-unity#2462]
<img width="387" alt="image" src="https://github.com/user-attachments/assets/da4a4668-1291-42b8-8ce7-a6f871bd57ce">

[With Unity 6000.0.22f1 update](https://unity.com/releases/editor/whats-new/6000.0.22#changes), packages are started being stored differently in `Library/PackageCache` (again! ugh!). Thus, Rider can't recognize them now. (Using Rider 2024.3 EAP3, Unity plugin version: 243.18137.48)

**Comment by van800** [comment]
Thank you for reporting. I will look into it.

**Comment by van800** [comment]
closed in favor of https://youtrack.jetbrains.com/issue/RIDER-118402
