### ISSUE TITLE
Plugin no longer available in Visual Studio Resharper

### ISSUE THREAD

**Issue by StephenHodgson** [JetBrains/resharper-unity#2464]
Went to download the plugin today in extension manager but Unity plugin is nowhere to be found. 

2024.3

**Comment by innat3** [comment]
This is a recurring problem every time Resharper releases a new version and it's quite annoying to be honest, since the plugin takes a few days if not weeks to become compatible once more.

**Comment by sr4dev** [comment]
Is it not possible to release ReSharper and the Unity Plug-in at the same time?
If so, at least make it known that the latest version of ReSharper does not support the Unity Plug-in.

**Comment by citizenmatt** [comment]
Apologies all. The plugin is available in the Extension Manager now. We're hoping to improve the release process for the ReSharper plugin in the next release.

**Comment by StephenHodgson** [comment]
@citizenmatt still says incompatible for me

![image](https://github.com/user-attachments/assets/ead1883c-cabe-4d72-b45e-9726a90e3fa2)

**Comment by citizenmatt** [comment]
What version of ReSharper are you using? That's the plugin for ReSharper 2024.1, but there are new versions available for both 2024.2 and 2024.3.

**Comment by citizenmatt** [comment]
That's odd. Can you check what the URL is for the plugins feed, please? In ReSharper Options -> Extension Manager

**Comment by StephenHodgson** [comment]
I already rolled back to a previous version.

I'll try to report back when I get a chance.
