### ISSUE TITLE
Hide Unity Gutter Icon in Visual Studio

### ISSUE THREAD

**Issue by Ed-Warpin** [JetBrains/resharper-unity#250]
Hey!

I could only find a way to hide the Unity Gutter Icons in Rider. Is there anyway you can disable them in Visual Studio?

**Comment by citizenmatt** [comment]
No, there isn't. This has been requested before, back in #94. It might be time to take another look at this. I'd still like to see some kind of highlighting for methods/fields/classes that are used by Unity, even when they're not marked with the icons. Do you have any suggestions?

**Comment by Ed-Warpin** [comment]
If there was an option to turn off the hints or ignore specific ones that would be perfect for all users. I think the hints are great if you're new to working with Unity but over time they become unnecessary and a bit noisy. 

In #94 you mention highlighting and setting things bold. I think setting methods bold could work well and wouldn't be so intrusive, but I think setting fields bold or highlighting them would be a bit too much. Another idea if you are set on using the Unity icon is to make it a lot smaller and transparent.

**Comment by citizenmatt** [comment]
Fixed in #998
