### ISSUE TITLE
how to disable unity field icons ?

### ISSUE THREAD

**Issue by friuns2** [JetBrains/resharper-unity#253]
Hi i installed plugin and now i see those unity icons that i don't need, how can i disable them?

https://i.imgur.com/SMKDi5V.png

**Comment by CAD97** [comment]
See #250. It's possible in Rider but not Visual Studio + ReSharper currently.

**Comment by poopledoople** [comment]
I came here for the same feature. I don't find the icons to be helpful at all and it's a bit of an eyesore being so contrasted against the dark themed background.

Please consider adding an option to turn it off.

**Comment by jonas-johansson** [comment]
Chiming in. Nice extension, but those icons take too much focus from me in Visual Studio to be able to use the extension. I hope it can be turned off in the future.

**Comment by van800** [comment]
Closing in favor of https://github.com/JetBrains/resharper-unity/issues/250
