### ISSUE TITLE
suggestion, It would be great if resharper-unity highlight the same variable 

### ISSUE THREAD

**Issue by haolly** [JetBrains/resharper-unity#254]
this plugin is great, I tried it, but there are many thing need to improve, like function parameter tips, auto suggestion, and highlight the same variables.

BTW, the indent is incorrect also
![image](https://user-images.githubusercontent.com/2383231/32053756-d21bf7b0-ba8e-11e7-9f12-61a3f076b675.png)

I use the latest version shipped with Resharper

**Comment by citizenmatt** [comment]
Rider 2020.3 (and possibly 2020.2) will highlight the element under the cursor for shader blocks and `.HLSL` files.
