### ISSUE TITLE
Rider flags methods called from Unity UI buttons as "unused"

### ISSUE THREAD

**Issue by Alfaifi** [JetBrains/resharper-unity#263]
I noticed this when going through some old projects I have!

every function that is being called from a UI event (i.e button clicks) is flagged as unused when it actually is.
Can this capability be implemented into this plugin?

**Comment by SugoiDev** [comment]
On external bindings like that, I mark the methods with the `UsedImplicitly` attribute.

For Rider to actually know where or to what Unity is binding a given method would require parsing scenes, assets and prefabs and it would require a lot of work (and performance would suffer quite a bit, too).

**Comment by Alfaifi** [comment]
I thought we could fetch such info from unity meta files.

**Comment by citizenmatt** [comment]
See also #488

**Comment by citizenmatt** [comment]
For Rider 2018.3, if a project has asset serialisation set to `ForceText`, then Rider will parse scenes and other assets, and will correctly mark event handlers as in use. Find Usages also works on these items, showing the usage, grouped by component and game object. See #870, #873 and #903.

If the project doesn't have `ForceText` set, Rider will fall back to marking any method that matches the signature for an event handler as in use, to avoid false negatives.
