### ISSUE TITLE
Can I print Unity log in the Rider Console?

### ISSUE THREAD

**Issue by zhuxianzhiniko** [JetBrains/resharper-unity#264]

**Comment by van800** [comment]
Currently it is not possible. We can investigate the possibility. Could you please describe the use-case? Is it for Play mode or Editor mode?

**Comment by xylo** [comment]
I would like to use this feature in play mode.  My feeling is that the Unity console is horrible (you have to use the mouse to open and to close it, just to see the details of an exception).  It would be great if I can just see the exception details in the IDEA console (which I can already open and close via keyboard shortcuts).

An additional feature would be of course if IDEA can parse exceptions and add links to the corresponding classes in the console.  But that should be probably handled in another feature request.

**Comment by SugoiDev** [comment]
Unity console really is subpar and not meant for high frequency logging at all.

I've been using a third party tool [Editor Console Pro](https://www.assetstore.unity3d.com/en/#!/content/11889) that has served me well for many years now, but outputting directly to an external listener while bypassing Unity's logging system could be very useful, especially when using a trace level and during profiling sessions. That is, as long as actually calling the interfaces is sufficiently lightweight.

**Comment by van800** [comment]
fixed in 2018.1, not public yet
