### ISSUE TITLE
Rider doesn't switch solutions when opening a source file from a different Unity project

### ISSUE THREAD

**Issue by liortal53** [JetBrains/resharper-unity#266]
We are developing multiple releases of our game in parallel, as well as using different versions of Unity for that.

I have a few Unity projects opened at the same time and i navigate between them.
When i already have Rider opened with a particular .sln (from one project), and i click on a source code file from a different Unity project, Rider will not close and reopen with the relevant solution. Instead, it opens the source file in the currently opened instance.

This is annoying since the real solution is not being loaded, so navigation to different code files and other features don't work.

In such a case, i would expect Rider to open the proper .sln file of the project that the source file that was clicked belongs to.

**Comment by van800** [comment]
same here https://github.com/JetBrains/Unity3dRider/issues/70

**Comment by liortal53** [comment]
Sorry I tried looking it up before but missed that

**Comment by van800** [comment]
No problem, at some point we should me all issues from old repository.

**Comment by van800** [comment]
fixed in 2018.1, not public yet
