### ISSUE TITLE
Rider in debug mode, automatic breaking on exceptions. As in the bundle Visual Studio + Unity Tools

### ISSUE THREAD

**Issue by EduardKurilov** [JetBrains/resharper-unity#269]
In debug mode, automatic breaking on exceptions. As in the bundle Visual Studio + Unity Tools

**Comment by IvanPashchenko** [comment]
@EduardKurilov Hi! Could you please expand on that?

What do you want us to improve? :)

**Comment by van800** [comment]
@EduardKurilov 
Please try this
https://rider-support.jetbrains.com/hc/en-us/community/posts/208387065/comments/115000443930

**Comment by EduardKurilov** [comment]
Hi! Unity + Visual Studio can break when an Exception is thrown in my code
and showing debug info. I love Rider, but I need to switch to the Visual
Studio for debugging exceptions, when somthing go wrong. I didn't find way
to do the same in the Rider and I am asking you to add this feature to the
Rider.

Similar links:
https://answers.unity.com/questions/777117/unityvs-not-breaking-on-exception-and-missing-debu.html
https://connect.microsoft.com/VisualStudio/feedback/details/1026187/visual-studio-tools-for-unity-is-unable-to-break-on-exception

2017-11-12 17:45 GMT+03:00 Ivan Shakhov <notifications@github.com>:

**Comment by van800** [comment]
@EduardKurilov Have you tried my suggestion?
https://rider-support.jetbrains.com/hc/en-us/community/posts/208387065/comments/115000443930
It worked for me.

**Comment by EduardKurilov** [comment]
Thank You Very Much, Ivan!!! )))

2017-11-13 11:33 GMT+03:00 Ivan Shakhov <notifications@github.com>:

**Comment by van800** [comment]
I am glad that helped.

**Comment by van800** [comment]
In case you are concerned also about breaking on unhandled exceptions, we are investigating the issue.
