### ISSUE TITLE
Rename/migrate fields

### ISSUE THREAD

**Issue by hwallander** [JetBrains/resharper-unity#27]
Would like an option to right-click a field on a ScriptableObject field and make migrations such as field rename, type migrations (perhaps via a user custom static method to make conversion of individual objects).

**Comment by citizenmatt** [comment]
I'm afraid I don't know what this means - I'm not a big user of Unity, so I'm not familiar with various workflows and such. Would you be able to provide more details, please?

**Comment by TarasOsiris** [comment]
Unity has its own serailization and basically ScriptableObject is the class you inherit from when you want your class to be persisted. Often you make custom editors for these classes and access their fields like

public class WarriorData : ScriptableObject
{
    public int someField;
}

`serializedObject.FindProperty("someField");` - so you specify filed name as a string. Probably first part of the request is when renaming the field to change all FindProperty("someField") occurences.

I also don't understand about type migrations

**Comment by citizenmatt** [comment]
I'm not sure what the migrations bit is, but I've created a new issue to describe working with `FindProperty` - #47. I'm going to close this now, but I'm happy to reopen if you provide more details about migrations.

**Comment by sindrijo** [comment]
What @hwallander possibly means by 'migrations' is avoiding data-loss when renaming serialized fields. I've already created two separate feature requests for refactorings to take that into account, see: #54 and #55 .

I'm not sure what 'type migration' in this context would be though.

**Comment by hwallander** [comment]
@sindrijo you are correct in your interpretation.

What i mean by type migration is some way to be able to change types on a field, for instance an int -> string migration.

**Comment by sindrijo** [comment]
@hwallander 
To do that the plugin would have to edit scene files, prefabs and ScriptableObject assets... probably a little out of scope for this plugin.
