### ISSUE TITLE
Quick Fix "Add reference in mcs.rsp"

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#274]
References to some framework libs in Unity are not added by default.
But they can be used by adding -r:DllName.dll line in mcs.rsp file.
For now this trick is not supported by any tools, it is done manually.
Example https://forum.unity.com/threads/httpclient.460748/ and https://github.com/JetBrains/resharper-unity/issues/270

It would be cool to add a QF for it.

**Comment by FaizanDurrani** [comment]
+1 really annoying having to deal with constant errors

**Comment by van800** [comment]
What do you mean by constant errors? Adding mcs.rsp manually doesn't work for you? @FaizanDurrani

**Comment by FaizanDurrani** [comment]
My bad, my error is somewhat unrelated.

Basically, Rider picks up the assemblies but says 
![image](https://user-images.githubusercontent.com/4832034/37341786-75ca2af0-26e4-11e8-9c3c-561445f221a6.png)
![image](https://user-images.githubusercontent.com/4832034/37341796-81c5ce7c-26e4-11e8-941b-fe5fc05d279a.png)

It works in Unity though. Rider Settings
![image](https://user-images.githubusercontent.com/4832034/37341855-c0f5fc66-26e4-11e8-8284-d03787356d18.png)

**Comment by van800** [comment]
Have you tried different MSbuild? MSBuild 4 is old for this kind of references.
https://rider-support.jetbrains.com/hc/en-us/articles/207288089-Using-Project-Rider-under-Windows-without-Visual-Studio-prerequisites

**Comment by FaizanDurrani** [comment]
I've tried MSBuild 14, gives the same error

**Comment by van800** [comment]
@FaizanDurrani I added a separate request for your problem.
https://github.com/JetBrains/resharper-unity/issues/435
Could you please confirm that you have 
`<Reference Include="System.Reactive.Core"/>`
without hint path in the unity-generated csproj.
Thanks for reporting!

**Comment by FaizanDurrani** [comment]
![image](https://user-images.githubusercontent.com/4832034/37346200-882dbf98-26f0-11e8-9f1a-60d951e3230a.png)

**Comment by FaizanDurrani** [comment]
Huh, for some reason its missing "Data/" before "MonoBleedingEdge" in the hintpath

**Comment by FaizanDurrani** [comment]
And its not the only one 
![image](https://user-images.githubusercontent.com/4832034/37346372-f9ca33e8-26f0-11e8-9ae5-b946b1167710.png)

**Comment by FaizanDurrani** [comment]
Removed the assemblies, Restarted Rider, Restarted Unity. HintPath is gone but the issue persists
![image](https://user-images.githubusercontent.com/4832034/37347231-2ba032f8-26f3-11e8-9360-11b207a6bc51.png)

**Comment by van800** [comment]
And can you share contents of your mcs.rsp?

**Comment by FaizanDurrani** [comment]
![image](https://user-images.githubusercontent.com/4832034/37348059-05fa4c9e-26f5-11e8-8312-b348668afc01.png)

**Comment by van800** [comment]
@FaizanDurrani What Unity version do you have?

**Comment by FaizanDurrani** [comment]
2017.3.1f1

**Comment by van800** [comment]
I have tried this version, because I am trying to reproduce the case, when HintPaths were added.
Have you used VisualStudio or some other IDE?
VS

**Comment by FaizanDurrani** [comment]
Nope I've only used Rider for this project.

Note: I did at some point manually add the references by right-clicking > add reference so that may have caused the hintpath, maybe?

**Comment by van800** [comment]
https://github.com/JetBrains/resharper-unity/pull/437

**Comment by van800** [comment]
I expect build with this fix will out tomorrow via https://www.jetbrains.com/toolbox/download/

**Comment by van800** [comment]
Not yet in todays nightly, should be out tomorrow. I will follow up.

**Comment by van800** [comment]
Fix with HintPaths fix is public, available via https://www.jetbrains.com/toolbox/download/

**Comment by citizenmatt** [comment]
@van800 does this issue still match the title and initial comment/description? If not, can we rename this and create a new one for the original problem please?

**Comment by van800** [comment]
@citizenmatt sure, will do.
