### ISSUE TITLE
Is this possible to debug/breakpoint iOs build?

### ISSUE THREAD

**Issue by nicloay** [JetBrains/resharper-unity#284]
I have only "attach to editor" option, so the question is how to debug iOS. 
When i build iOS project i have enabled "Script Debugging". What I want is the same as I do on mono - run build through xCode and then debug it in mono-develop.

**Comment by van800** [comment]
You may try Run->Attach to local processes. Let us know if it helps.

**Comment by nicloay** [comment]
I tried that.
Rider show me 1449 PID.

**Comment by van800** [comment]
Sorry, I was mistaken about the command. Please try the Run->Attach to Unity process command.

**Comment by nicloay** [comment]
Thank you very much.
Yes now it see device process. and debugger connect to the process. but breakpoints don't work probably it's another issues. 
I'll try to find more details about the issue.

**Comment by van800** [comment]
If it works fine in MD, we are very interested to have it working in Rider also. If so, please reopen the issue, we will try to reproduce and fix issues if any.
