### ISSUE TITLE
Rider cannot resolve symbol from DLLs.

### ISSUE THREAD

**Issue by mihakrajnc** [JetBrains/resharper-unity#285]
I've had this problem for a while now. Using TextMeshPro in my case, Rider fails to resolve symbols from it's DLLs. For instance, when I write:
```csharp
TMP_InputField.OnChangeEvent onChangeEvent = new TMP_InputField.OnChangeEvent();
onChangeEvent.AddListener(ValidateFields); // This compiles ok but Rider displays an error
```

It will compile fine in Unity, but will display an error in rider:
![image](https://user-images.githubusercontent.com/8857844/33122131-98d2678a-cf76-11e7-8c38-7a8c8de37fee.png)

Using Rider 2017.2.1 and plugin version 2.1.2.1737 (both currently latest).

To reproduce this, open a new project, import TextMeshPro from the asset store, create a new script, and copy the above code into `Start()`

**Comment by van800** [comment]
Hi! I tried your repro, but TMP_InputField is not resolved. It seems something else is also required. It would be super-nice, if you can attach a simple example project demonstrating the issue. Thanks!

**Comment by mihakrajnc** [comment]
@van800 No problem, here is a project with the bug: [TMPTest.zip](https://github.com/JetBrains/resharper-unity/files/1498794/TMPTest.zip)

**Comment by van800** [comment]
Reproduced.
Errors from build in Rider.
>   TestScript.cs(9, 23): [CS0012] Assets/TestScript.cs(9,23): error CS0012: The type 'UnityEvent<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
>   TestScript.cs(9, 23): [CS1061] Assets/TestScript.cs(9,23): error CS1061: 'TMP_InputField.OnChangeEvent' does not contain a definition for 'AddListener' and no extension method 'AddListener' accepting a first argument of type 'TMP_InputField.OnChangeEvent' could be found (are you missing a using directive or an assembly reference?)

I guess for Unity build reference to UnityEngine.CoreModule is used behind the scenes.

I tried to manually add UnityEngine.CoreModule, but got different error:
  TestScript.cs(4, 27): [CS0433] Assets/TestScript.cs(4,27): error CS0433: The type 'MonoBehaviour' exists in both 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by van800** [comment]
@mihakrajnc I have got a response from Unity team on this issue.
> TextMeshPro reference UnityEngine.CoreModule.dll, which it shouldn’t be doing.
They will ask the author to fix it.
Given all that I don't think I should change anything on our side.
Thanks for reporting, I hope it will be fixed soon.

**Comment by mihakrajnc** [comment]
Quick update for anyone looking at this, TextMeshPro from the Asset Store has been updated with the fix.
