### ISSUE TITLE
(Rider) Unity hangs when double click a script in Unity

### ISSUE THREAD

**Issue by thirdcoke** [JetBrains/resharper-unity#297]
When I double click a script in Unity(project view and inspector), the unity hangs for a while and 10 or 20 seconds(I don't know maybe longer than that) later, Rider opens the file and Unity come back.
Version:
**Rider 20172.1** RD 172.4144.1873
**Unity3DRider** 2.1.2.1737
**Unity** 2017.1.0.f3

**Comment by thirdcoke** [comment]
`[Rider] [Verbose] Exception in DetectPortAndOpenFile: System.Net.WebException: Error: ConnectFailure (No connection could be made because the target machine actively refused it.
) ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it.

  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP, Boolean requireSocketPolicy) [0x00000] in <filename unknown>:0 
  at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.DownloadDataCore (System.Uri address, System.Object userToken) [0x00000] in <filename unknown>:0 
UnityEngine.Debug:Log(Object)
Plugins.Editor.JetBrains.RiderPlugin:Log(LoggingLevel, String) (at Assets/Plugins/Editor/JetBrains/Unity3DRider.cs:329)
Plugins.Editor.JetBrains.<DetectPortAndOpenFile>c__AnonStorey0:<>m__0(Int32) (at Assets/Plugins/Editor/JetBrains/Unity3DRider.cs:645)
System.Linq.Enumerable:Any(IEnumerable`1, Func`2)
Plugins.Editor.JetBrains.RiderPlugin:DetectPortAndOpenFile(Int32, String, Boolean) (at Assets/Plugins/Editor/JetBrains/Unity3DRider.cs:625)
Plugins.Editor.JetBrains.RiderPlugin:OnOpenedAsset(Int32, Int32) (at Assets/Plugins/Editor/JetBrains/Unity3DRider.cs:602)
`

Here's the rider plugin log

**Comment by van800** [comment]
Is it first Rider opening or next ones?

**Comment by thirdcoke** [comment]
OKj, I found the problem. Seems like the port 63342 being used for no reason on my computer, and I change it both in Rider and Unity3DRider and it works, thanks

**Comment by tallior** [comment]
i am also seeing this issue on my machine (Unity 2017.1.1)

**Comment by jamius19** [comment]
Running into the same problem as you.
Same log.
What can I do to resolve it?

Rider 2017.3
Unity 2017.1.1f

**Comment by van800** [comment]
@jamius19 
Change port in your Unity3dRider script like here
https://github.com/JetBrains/resharper-unity/blob/wave11-rider-2017.3.1/resharper/src/resharper-unity/Unity3dRider/Assets/Plugins/Editor/JetBrains/RiderPlugin.cs#L357
and here
![image](https://user-images.githubusercontent.com/1482681/35474625-279a3ba2-0391-11e8-992e-47c378508a53.png)

Problem is addressed in upcoming Rider 2018.1

**Comment by jamius19** [comment]
@van800 Thank you for your time.
Very much appreciated!

**Comment by jamius19** [comment]
Found another interesting solution.
If you change the port to any other number and check the "Can accept external connections" checkbox, it also works.

**Comment by van800** [comment]
fixed in 2018.1, but not public yet
