### ISSUE TITLE
(Rider) use a coroutine in Async as syntax error 

### ISSUE THREAD

**Issue by yadiate** [JetBrains/resharper-unity#298]
https://github.com/zsaladin/Asyncoroutine

Unity compiler works without errors.

(rider)
![screenshot_2](https://user-images.githubusercontent.com/1768519/33550683-2d072f84-d932-11e7-9d55-971369620a4a.png)
(unity)
![screenshot_3](https://user-images.githubusercontent.com/1768519/33550689-310bffa6-d932-11e7-8344-619bf937c394.png)

**Comment by van800** [comment]
I added a resharper issue for this ticket.
https://youtrack.jetbrains.com/issue/RSRP-467376

**Comment by citizenmatt** [comment]
Ha ha! Beat me to it: https://youtrack.jetbrains.com/issue/RSRP-467377 😆
