### ISSUE TITLE
ReShader!

### ISSUE THREAD

**Issue by justinlueders** [JetBrains/resharper-unity#3]
Better syntax highlighting and and code completion for Unity3D shaders.  Extra points for adding in a way to view the results of said shader in a preview window.

**Comment by citizenmatt** [comment]
Work in progress. See #78, which targets .shader files, but not (yet) `CGPROGRAM` code islands.

**Comment by IvanPashchenko** [comment]
#78 is now merged, with keywords-based highlighting of CG for Rider.

**Comment by citizenmatt** [comment]
Closing this. We're not fully there with all functionality (e.g. ReSharper standard code completion, navigation and inspections) but we're getting there, and if we leave this open until we have everything, it'll stay open forever :)
