### ISSUE TITLE
Not Available in ReSharper 10.1

### ISSUE THREAD

**Issue by bjennings76** [JetBrains/resharper-unity#30]
I'm on the bleeding edge of ReSharper and currently testing out ReSharper 10.1 EAP, but unfortunately, Unity for ReSharper exist in ReSharper Extensions screen and the previously installed Unity for ReSharper plugin doesn't get loaded.

Steps to Reproduce:
1. Install ReSharper 10.1 EAP 6 into Visual Studio
2. Open Unity project in Visual Studio
3. Notice Unity for ReSharper isn't working
4. Look for Unity for ReSharper in ReSharper Extension Manager

Results:
[Unity for ReSharper isn't found.](http://screencast.com/t/sQNKtz6h)

Expected Results:
Unity for ReSharper is available to install.

**Comment by citizenmatt** [comment]
It's not been updated for ReSharper 2016.1 (nee 10.1) yet. I'm just looking at it now.

**Comment by derigel23** [comment]
Fixed in #33
