### ISSUE TITLE
Lambda expression not assignable to System.Func`2

### ISSUE THREAD

**Issue by karl-** [JetBrains/resharper-unity#301]
Lately my linq expressions have been getting marked with error squiggles incorrectly. Unity doesn't mind the lambdas, and I'm pretty certain this wasn't always a problem.

![lambda](https://user-images.githubusercontent.com/1683036/33626215-e64b355e-d9c7-11e7-89cd-720a06746ffa.png)

**Comment by van800** [comment]
Could you please provide a piece of code?
Are you on Eap2 build?

**Comment by karl-** [comment]
Tested on macOS 10.12 & Windows 10. Rider 2017.2 (#172.4144.1459, Oct. 11 2017),.

```
using UnityEngine;
using UnityEditor;
using System.Collections;
using System.Linq;

public class LinqExample : Editor
{
	[MenuItem("Window/Show Linq Syntax")]
	static void MenuInit()
	{
		string[] list = new string[]
		{
			"1",
			"2",
			"3",
			"4"
		};

		bool anyStringMatchesOne = list.Any(x => x.Contains("1"));

		Debug.Log("Any string == 1?  " + (anyStringMatchesOne ? "Yes" : "No"));
	}
}
```

**Comment by van800** [comment]
I can't reproduce it for now, I would need to know Unity version and used mono version.

**Comment by citizenmatt** [comment]
Is this still an issue?

I'm going to close this right now, due to inactivity. If it's still a problem, please reopen and we'll get some more details to try and recreate.

**Comment by samuelgoldenbaum** [comment]
seeing this
