### ISSUE TITLE
Use local documentation from current Unity instance

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#306]
The plugin should use the path of the currently running Unity Editor instance to find local documentation.

The current implementation for displaying external documentation of Unity symbols (see #304) will first look up local documentation in the default install locations for Windows, Mac and Linux, before falling back to perform a search on Unity's website. But Unity might not be installed at the default locations, or the currently running editor instance might be a different version installed at a different location. Rider and ReSharper should use the install path of the current Editor instance to find the local documentation.

Unity are going to add `EditorApplication.applicationPath` to the `EditorInstance.json` file (adding the `app_path` property). This gives us the path to the editor executable (`.app` on Mac) but would need manipulating to get to the docs. Hopefully, they'll also add `EditorApplication.applicationContentsPath` too, which will give us the equivalent of (depending on install location):

* `C:\Program Files\Unity\Editor\Data` on Windows
* `/Applications/Unity/Unity.app/Contents` on Mac
* `/opt/Unity-2017.3.0b2/Unity/Editor/Data` or `~/Unity-2017.3.0b2/Unity/Engine/Data` on Linux

Appending `Documentation/en` to this path will give us the local documentation root on all platforms.

**Comment by van800** [comment]
You may update search path logic to similar https://github.com/JetBrains/resharper-unity/blob/master/resharper/src/resharper-unity/Rider/UnityPathTemplateParameter.cs#L34

**Comment by citizenmatt** [comment]
Make sure to also support documentation installed with Unity Hub, as per 3980f917d86312a2c89bd9dc15a28801898aad03:

* `/Applications/Unity/Hub/Editor/2018.1.0/Documentation/en`
* `C:\Program Files\Unity\Hub\Editor\2017.3.1f1\Documentation\en`

And update the online search to include the version:

* `https:////docs.unity3d.com/2017.4/Documentation/ScriptReference/30_search.html?q=...`

**Comment by rob8861** [comment]
@citizenmatt @van800 I am glad this is being worked on. However, to date I have not been able to find a way to open the unity docs directly from Rider, even the online ones will be great. Is there a way from Rider to point the carter at a Unity symbol and open the Unity docs (not the quick docs)???

**Comment by citizenmatt** [comment]
The "Quick Documentation" action shows a popup that has a link at the bottom "External documentation for 'element'", which will open a browser to view the docs, either locally or online, via a search on Unity's site. The shortcut for this differs per keymap - do Alt+Enter and type "quick doc".

So this ticket is _mostly_ working, with a few issues.

E.g. for various awkward technical reasons, we can't show a better name than `'element'` in the popup (see [RIDER-22890](https://youtrack.jetbrains.com/issue/RIDER-22890)), and the "External Documentation" action and associated shortcut don't currently work either.

And also (IIRC, I need to check) we open the "default" installed version's docs instead of the version of Unity you've currently got open. The same for the online site - we search on the default version only.

**Comment by StudentYanling** [comment]
Hi, Has this problem been solved? 

I still can't access Unity documention using "External Documentation".

**Comment by van800** [comment]
@StudentYanling Hey! Thank you for the heads-up. I have checked it on modern Unity version. It seems we are looking for local documentation in a wrong place and thus always fallback to online documentation. Just to clarify, do you see the online documentation?

**Comment by StudentYanling** [comment]
@van800 Thank you for your reply. I don't see any change when I use "External Documentation". Neither local nor online shows up. 

I found it worked very well in "Event Function->View Documentation", But this seems to only apply to Unity Functions. When I want to view the documentation of a Unity class, such as "Image", I don't know what to do.
![eventfunction](https://user-images.githubusercontent.com/34509356/150759899-bd5c4d62-eaf2-47fd-8e0c-aa52037aa6a7.jpg)

**Comment by StudentYanling** [comment]
I used VS+Resharper for development before that, Unity support for VS has a feature called "UnityAPI Reference". You can visit this address to see it. [Unity API Reference](https://docs.microsoft.com/en-us/visualstudio/gamedev/unity/get-started/using-visual-studio-tools-for-unity?pivots=windows#unity-documentation-access) Hope this helps.

**Comment by van800** [comment]
@StudentYanling Please try shortcut "F1" or "Quick Documentation" popup and press the link inside
![image](https://user-images.githubusercontent.com/1482681/150770037-b58c187b-de12-4307-944c-c185896876c7.png)
which opens [this link](https://docs.unity3d.com/2021.2/Documentation/ScriptReference/30_search.html?q=Image) for me.

**Comment by StudentYanling** [comment]
@van800 This is OK! Oddly enough, I've tried this on my company computer, but nothing works. I tried it on my home computer just now, and it worked very well.Maybe it's some weird network problem. Finally, thank you for your prompt reply!

**Comment by van800** [comment]
You are welcome @StudentYanling. If the problem with the company computer persists, please submit a new issue with logs - Help->Report a Bug, agree to attach logs.
