### ISSUE TITLE
Generate unity event functions may add "using System;"

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#316]
if file doesn't have "using System;", then generate unity event functions generates red code.

![image](https://user-images.githubusercontent.com/1482681/34277288-56190fde-e6a5-11e7-8505-b2fbabaa9d4a.png)

**Comment by citizenmatt** [comment]
That's weird. It should be using the `void` keyword, rather than the `System.Void` type. The generated method declarations are created with `System.Void`, but it should all rewrite itself as the keyword. Is this reproducible? Windows or Linux?

**Comment by van800** [comment]
Reproduces on linux, doesn't reproduce on mac.

**Comment by van800** [comment]
I found a way to reproduce it on mac.
If I change TargetFrameworkVersion in csproj to some non-existing <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
Then generate action starts producing Void.
