### ISSUE TITLE
RiderPlugin.cs in 2017.3 fails in GetDefaultApp

### ISSUE THREAD

**Issue by oleschaper** [JetBrains/resharper-unity#320]
If running Unity in headless mode, building fails with an exception in RiderPlugin.cs because GetDefaultApp() receives null or empty string from the GetExternalScriptEditor() call in line 46.

On our build server we do not have an external script editor (obviously we do not edit code on the build server).

This is a regression bug to Rider version 2017.2.

**Comment by van800** [comment]
Thanks for reporting.
Here is a fix https://github.com/JetBrains/resharper-unity/commit/bb6a03dee19da6798b7888408aeca4327b1ceb42
You may apply it yourself to file in your codebase for now and it will be included into 2017.3.1 Rider build.

**Comment by van800** [comment]
I have updated the fix https://github.com/JetBrains/resharper-unity/commit/93ce895d923284ba07862e02d819b56c8ac1e350

**Comment by paulcsiki** [comment]
Thanks for the fix @van800, works great!

**Comment by samuelgoldenbaum** [comment]
Thanks

**Comment by van800** [comment]
Available also in nightly builds
https://rider-support.jetbrains.com/hc/en-us/articles/360000009804-How-to-get-Rider-Nightly-build-
