### ISSUE TITLE
[unity 2018.1.0b2] [netstandard2.0] Ambigous Reference

### ISSUE THREAD

**Issue by sebastian-heinz** [JetBrains/resharper-unity#329]
I'm not sure if this is a unity or rider issues, if this is not related please close.

I noticed that when using netstandard2.0 I will get alot of 'Ambigous Reference'-errors. The project runs fine in unity, its just a bit hard to spot real errors in code if alot of parts are market red.

A related unity thread can be found here: https://forum.unity.com/threads/2018-1-0b2-netstandard2-0-ambigous-reference.512188/

I have not yet tested if the suggested latest Visual Studio for Mac version has the same problems.

![](https://forum.unity.com/proxy.php?image=https%3A%2F%2Fi.imgur.com%2FqAgu1mC.png&hash=98742ea3f7c14b5704194211ccb7f00c)

![](https://forum.unity.com/proxy.php?image=https%3A%2F%2Fi.imgur.com%2FBCqEPJW.png&hash=79e31d782f99015c7e3a106312be2dea)

![](https://forum.unity.com/proxy.php?image=https%3A%2F%2Fi.imgur.com%2FHtcBhHx.png&hash=6257d45920186f9155a8a8a2dd69e887)

![](https://forum.unity.com/proxy.php?image=https%3A%2F%2Fi.imgur.com%2FwpZmaBS.png&hash=d1ca1b15f23604aad23fa21bfeb4e57c)

![](https://forum.unity.com/proxy.php?image=https%3A%2F%2Fi.imgur.com%2F4pNgoLe.png&hash=85f4a8789260c130b68c8e7974bfcfdc)

**Comment by van800** [comment]
@sebastian-heinz What is your OS, version of Rider and which MsBuild is configured in Rider?
Please attach Rider logs from Help->Show log in Finder.
Thanks!

**Comment by van800** [comment]
fixed by https://github.com/JetBrains/resharper-unity/commit/7ebdababd70d0670fcb692ddef3383e07ff8be9c

**Comment by geoter** [comment]
Hi I am facing a similar problem in 2020.3 
<img width="554" alt="Screenshot 2021-01-20 at 3 14 27 PM" src="https://user-images.githubusercontent.com/4948217/105179723-535c9180-5b32-11eb-8663-331a7fb315b8.png">
