### ISSUE TITLE
Unity extension was removed by upgrade 2016.1

### ISSUE THREAD

**Issue by rob8861** [JetBrains/resharper-unity#33]
Hello,

After upgrading to ReSharper 2016.1 , the Unity extension was removed and is no longer available in the Extension Manager.

Cheers,

**Comment by derigel23** [comment]
Hi @rob8861!
[New version 1.2.1](https://resharper-plugins.jetbrains.com/packages/JetBrains.Unity/1.2.1) compatible with ReSharper 2016.1 is released.

**Comment by rob8861** [comment]
thank you.
