### ISSUE TITLE
Rider freezes when trying to Index files (First time opening the project with Rider) & never completes

### ISSUE THREAD

**Issue by HHammerite** [JetBrains/resharper-unity#330]

**Comment by IvanPashchenko** [comment]
Seems similar to https://youtrack.jetbrains.com/v2/issue/RIDER-11505

**Comment by IvanPashchenko** [comment]
@HHammerite Hi, what versions of Rider and Unity are you using?

**Comment by HHammerite** [comment]
I'm using Rider 2017.3 & Unity 2017.3
My only work around so far seems to be having to completely remove Rider from the project and trying again. After a couple of attempts it usually works.

**Comment by IvanPashchenko** [comment]
@HHammerite okay, usually when we have a problem like that, we dump the content model that Rider builds for itself, but seeing as you have the UI freeze, we'll need something more specific. Are you willing to try opening this solution with a custom Rider build that will provide us with the needed logs?

**Comment by HHammerite** [comment]
@IvanPashchenko Sure, I will try to recreate the problem for you.

**Comment by citizenmatt** [comment]
I'm going to close this due to inactivity. If it's still a problem with Rider 2018.1, please reopen and we'll get some logs to investigate further.

**Comment by edcasillas** [comment]
I got here while searching for an answer to this same issue. Using Rider 2019.3.1 and Unity 2018.4.13f1 on MacOS Catalina.

Everything was working fine yesterday. I created a new branch on my project to try upgrading it to the latest version of Unity (2019.2.19f1); one of the multiple errors I had (most of them non related to this) asked me to delete the Plugins/Editor/JetBrains/JetBrains.Rider.Unity.Editor.Plugin.Repacked.dll, so I did, then opened Rider again, it installed the plugin, came back to Unity to load it, then came back to Rider and everything seemed good.

Then I went back to my old branch and opened the project in Unity 2018.4.13f1 again and double clicked a script. Rider opened but it went frozen after a few seconds. I removed the dll again, and also removed the .idea, Library, obj and Temp folders as well as *.sln and *.csproj files; opened Unity again, double clicked a script again, Rider was opened and it frozen just after displaying the message "Unity Editor plugin installed: Please switch to Unity Editor to load the plugin.". If I then switch to Unity it shows a progress bar "Compiling scripts" and when it's finished Unity is all good, but Rider stays frozen showing that message and doesn't allow to do anything.

I've tried the last steps several times (removing folders and files, open Unity then Rider) to no avail.

**Comment by van800** [comment]
Unity 2019.2+ requires Rider package installed via Package Manager in Unity. Sorry for inconvenience.

**Comment by edcasillas** [comment]
oh I see, that's good to know, thanks!

Anyway I'm back now to Unity 2018.4.13f1 and keep trying to make it work.

Fortunately, I just found that reverting Rider to 2019.3 fixes the problem (was using 2019.3.1).

**Comment by echeg** [comment]
Have same problem Infinity "construction components"
on all Rider start from 2019.x-2020.1 and Unity 2019.3.x
Normal work on Rider 2018.3
Try reinstall Rider packages(1.x.x-2.0.2), change Rider versions 2019.x-2020.1

In logs. 
--- EXCEPTION #2/2 [LoggerException]
Message = “ClientSocket-UnityClient: $System.Net.Sockets.SocketException raised during ACK, seqn = 2474658262151069696 An existing connection was forcibly closed by the remote host”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600

I close all. (uinty rider etc) 
After Remove Assets\Plugins\Editor\JetBrains\JetBrains.Rider.Unity.Editor.Plugin.Repacked.dll. 
After Open sln in Visual Studio
After Open sln in Rider (loading without problems)
After Open Unity
And bug is gone...

**Comment by van800** [comment]
@echeg If the problem starts again, please call "Help | Diagnostic Tools | Collect Backend Thread Dump" couple of times during the infinite progress. And report a new issue with "Help->Report a bug". I would love to investigate.

**Comment by avivazran** [comment]
same problem here using the new rider for unreal preview and unreal engine 4.25.
any solution for that?

**Comment by van800** [comment]
@avivazran You may try to disable Unity plugin and see, if it causes the issue.
My guess is, that it is not, so just report it to Rider main bugtracker or to Help->Report a Bug in Rider itself.
