### ISSUE TITLE
Generating the rider plugin files in large projects causes extremely long compilation times

### ISSUE THREAD

**Issue by doctorpangloss** [JetBrains/resharper-unity#334]
We need an option to prevent the Rider from constantly creating a new `Plugins/Editor/JetBrains/Unity3DRider` file because it triggers huge recompilations in assembly-def enabled projects.

**Comment by van800** [comment]
If Unity3dRider.cs is already there, it should not be added again. Only updated when Rider itself was updated.

**Comment by van800** [comment]
As a fast workaround you may use this option.
![image](https://user-images.githubusercontent.com/1482681/35086314-861ae01c-fc2c-11e7-9995-a3fb418d9004.png)

**Comment by doctorpangloss** [comment]
Thanks, that did the trick!

**Comment by van800** [comment]
BTW In 2018.1 Unity3dRider will be distributed as an assembly.

**Comment by doctorpangloss** [comment]
Great!
