### ISSUE TITLE
Exclude some Unity* processes from Attach dialog

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#343]
![image](https://user-images.githubusercontent.com/1482681/35561672-5e61c070-05b1-11e8-963b-3215d2954389.png)

**Comment by van800** [comment]
Also, check that EditorInstance.json really doesn't exist. It seems that it exists and contains proper id.

**Comment by van800** [comment]
close this as duplicate to https://youtrack.jetbrains.com/issue/RIDER-13658

**Comment by citizenmatt** [comment]
Fixed by #442
