### ISSUE TITLE
Rider can't properly open generated solutions

### ISSUE THREAD

**Issue by dkozlovtsev** [JetBrains/resharper-unity#347]
I've encountered the following problem: 
Rider can't load references for projects and solution is shown as not compilable
The following text can be found in event log
```
30.01.2018
20:05	Project 'Assembly-CSharp' load failed: Unexpected error during project loading: Object reference not set to an instance of an object.

20:05	Project 'Assembly-CSharp-Editor' load failed: Unexpected error during project loading: Object reference not set to an instance of an object.

20:05	Project 'Assembly-CSharp-Editor-firstpass' load failed: Unexpected error during project loading: Object reference not set to an instance of an object.
```
So far the only way to make problem go away is to reinstall rider, which I have done twice already.
The problem seem to happen after I try to use Open Project In Rider while having already opened another unity project.

Nothing aside from "Post-processing X" can be found in Rider plugin log on Verbose logging level

**Comment by van800** [comment]
Could you please attach a screenshot and zip & attach everything from Help->Show log in Files

**Comment by dkozlovtsev** [comment]
Logs:
[idea.zip](https://github.com/JetBrains/resharper-unity/files/1680945/idea.zip)
That is how it looks like in rider
![resharper issue](https://user-images.githubusercontent.com/19802630/35613433-1cc0575e-067d-11e8-8b8d-36abad662737.png)

**Comment by dkozlovtsev** [comment]
[idea.zip](https://github.com/JetBrains/resharper-unity/files/1681006/idea.zip)
![image](https://user-images.githubusercontent.com/19802630/35613652-c87ae3a2-067d-11e8-9e53-be203a0fbaf6.png)

**Comment by van800** [comment]
It is only idea.log, here, is there any other *.log files in the same folder? Thanks!

**Comment by dkozlovtsev** [comment]
Here is the whole folder
[log.zip](https://github.com/JetBrains/resharper-unity/files/1681042/log.zip)

**Comment by dkozlovtsev** [comment]
Anything on this? Currently it prevents me from using Rider

**Comment by xtmq** [comment]
Yes, we will fix in in 2018.1. Hope till EAP1 will be published.

**Comment by xtmq** [comment]
By the way there is a change we have fixed the issue already, could you try Rider 17.3.1? We published it 2 days ago =)

**Comment by dkozlovtsev** [comment]
Rider 17.3.1 seems to have fixed it. I'll comment again if i manage to reproduce it again

**Comment by wagenheimer** [comment]
[logs.zip](https://github.com/JetBrains/resharper-unity/files/2197968/logs.zip)
I have a similar problem!

I'm opening a Unity Project, but in Rider, the "Loading Projects" does not finishes and nothing is working as expected.

What can I do?

**Comment by van800** [comment]
@wagenheimer There must be some installation problem in your case. 
 [STDERR] java.io.FileNotFoundException: C:\Program Files\JetBrains\JetBrains Rider 2018.1.3\lib\winp.x64.59DDBA6E777434D039AE09539E6AE899.dll

Please reinstall. Sorry for the delayed response.
