### ISSUE TITLE
Rider solution postprocessor corrupts file

### ISSUE THREAD

**Issue by Nezz** [JetBrains/resharper-unity#348]
We are using solution folders. Normally it looks like this:
![screen shot 2018-01-31 at 14 10 59](https://user-images.githubusercontent.com/431167/35622502-bd4a50b8-0690-11e8-946a-cf6613bf6fe8.png)

However, the Rider plugin in Unity is rewriting the solution file, which messes up parsing:
![screen shot 2018-01-31 at 14 10 28](https://user-images.githubusercontent.com/431167/35622501-bd1aab7e-0690-11e8-8541-3fda69f3f417.png)
Eventually it messes up the file:
`Solution 'Unity' load finished with warnings: The following projects have the same ProjectGuid '00000000-0000-0000-0000-000000000000': , , , `

The issue is that lines like this:
`Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Shared", "Shared", "{8FCD7D66-2D91-456C-AE4E-E2F6F5B8BCAD}"`
get rewritten to
`Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Shared"", "Shared", "{8FCD7D66-2D91-456C-AE4E-E2F6F5B8BCAD}"`
Notice the extra `"` after `Shared`

Sample solution file:
https://www.dropbox.com/s/f6pr3xs62uusmem/Unity.sln?dl=1

The issue is caused by this part of the code:
https://github.com/JetBrains/resharper-unity/blob/master/resharper/src/resharper-unity/Unity3dRider/Assets/Plugins/Editor/JetBrains/RiderAssetPostprocessor.cs#L48-L56

Here are the relevant logs:
```
[Rider] 14:08:09:25 [Info] mc[1]: "Shared"
[Rider] 14:08:09:25 [Info] mc[2]: "Shared"
[Rider] 14:08:09:25 [Info] to:Shared"
[Rider] 14:08:09:25 [Info] Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Shared", "Shared", "{8FCD7D66-2D91-456C-AE4E-E2F6F5B8BCAD}"
[Rider] 14:08:09:25 [Info] Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Shared"", "Shared", "{8FCD7D66-2D91-456C-AE4E-E2F6F5B8BCAD}"

[Rider] 14:08:09:25 [Info] mc[1]: "ThirdParty"
[Rider] 14:08:09:26 [Info] mc[2]: "ThirdParty"
[Rider] 14:08:09:26 [Info] to:ThirdParty"
[Rider] 14:08:09:26 [Info] Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "ThirdParty", "ThirdParty", "{1C9EEF40-04F5-4EC0-9B3B-DBEF7BD3FFD6}"
[Rider] 14:08:09:26 [Info] Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "ThirdParty"", "ThirdParty", "{1C9EEF40-04F5-4EC0-9B3B-DBEF7BD3FFD6}"
```

**Comment by van800** [comment]
fixed in branch, please feel free to copy-paste to your Unity3dRider.cs
https://github.com/JetBrains/resharper-unity/tree/wave11-rider-2017.3.1/resharper/src/resharper-unity/Unity3dRider/Assets/Plugins/Editor/JetBrains

**Comment by Nezz** [comment]
@van800 I just updated to `JetBrains Rider 2018.1 EAP Build #RD-181.4035.96, built on March 6, 2018` and the issue happens again. It seems to me that when the editor plugin got redesigned, this fix was lost.

**Comment by Nezz** [comment]
I only have `JetBrains.Rider.Unity.Editor.Plugin.Repacked.dll`:
![screen shot 2018-03-09 at 15 52 40](https://user-images.githubusercontent.com/431167/37210575-e9eda924-23b1-11e8-952c-6ecfab37810f.png)

In our case the Unity generated solution gets updated by our own solution postprocessor to have solution folders, see sample solution file in the issue description. Then the Rider solution postprocessor rewrites some things and turns the line
`Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Shared", "Shared", "{8FCD7D66-2D91-456C-AE4E-E2F6F5B8BCAD}"`
into
`Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Shared"", "Shared", "{8FCD7D66-2D91-456C-AE4E-E2F6F5B8BCAD}"`

Maybe the fix you mentioned has never actually fixed the issue. I haven't overwritten the plugin with the one you linked to verify the fix.

**Comment by van800** [comment]
Ah, I see.
It is hard to fix this without repro case.
So maybe you can
share with me your custom procesor code (to share it privately only with jetbrains - make a private issue in https://youtrack.jetbrains.com/issues/RIDER)

or take our processor code from https://github.com/JetBrains/resharper-unity/blob/master/unity/JetBrains.Rider.Unity.Editor/EditorPlugin/AssetPostprocessors/SlnAssetPostprocessor.cs, fix it and send a pull request.

**Comment by Nezz** [comment]
The repro case is included in the original issue description:
>Sample solution file:
https://www.dropbox.com/s/f6pr3xs62uusmem/Unity.sln?dl=1

Just run the `SlnAssetPostprocessor` on it.

**Comment by van800** [comment]
https://github.com/JetBrains/resharper-unity/commit/3f1c72ce73152ff7d8a9e0b0232f3d4637897956

**Comment by van800** [comment]
Available in nightly build via https://www.jetbrains.com/toolbox/download/
