### ISSUE TITLE
How to import XML Documentation Comment file?

### ISSUE THREAD

**Issue by zyccsnow** [JetBrains/resharper-unity#349]
I put the dll file and xml comment file together
but the Rider shows me many errors like "Cannot resolve symbols *** "
But when I try to use Visual Studio to open the solution, evething in VS is ok.
I think Rider didnt import the xml file ,how to fix this problem? 
Thank you!

**Comment by van800** [comment]
Do you try VS and Rider on the same machine, right?
Could you please post a screenshot and all log files from "Help->Show log in Explorer"
Thank you!

**Comment by van800** [comment]
@zyccsnow I will close this for now, but if it is still an issue for you and you can provide the information above, I would be glad to reopen it and investigate.
