### ISSUE TITLE
Supress "Replace '?:'-operator with '??'" suggestion

### ISSUE THREAD

**Issue by witcher112** [JetBrains/resharper-unity#35]
Hello!

As Unity explains:

> When you do this in Unity:
> if (myGameObject == null) {}
> 
> It behaves inconsistently with the ?? operator, which also does a null check, but that one does a pure c# null check, and cannot be bypassed to call our custom null check.

_Source:_ [http://blogs.unity3d.com/2014/05/16/custom-operator-should-we-keep-it](http://blogs.unity3d.com/2014/05/16/custom-operator-should-we-keep-it/)

This suggestion might mislead the programmer while comparing UnityEngine.Objects.
Would it be possible to supress it?

Thanks in advance!

PS. Huge thanks for this amazing utility :smile: !

**Comment by citizenmatt** [comment]
Rider 2017.3 no longer suggests to convert to `??` or `?.`, and Rider 2018.1 will have a warning if you try and use these operators on a type deriving from `UnityEngine.Object`.
