### ISSUE TITLE
.Net 4.5 targeted instead of 4.6

### ISSUE THREAD

**Issue by RDeluxe** [JetBrains/resharper-unity#352]
Hi !

I've been having some issues lately :  

![rider64_2018-02-01_16-18-44](https://user-images.githubusercontent.com/2767681/35686041-a1af08a4-076b-11e8-9790-5546a1c79e3e.png)

I've been migrating to ASMDEF recently, I'm not 100% positive that this bug is due to asmdef, I could check quickly if you want. Basically all my solutions are targeting .net 4.5 instead of 4.6. Manually re-targeting does not last after a compilation.

![rider64_2018-02-01_16-20-02](https://user-images.githubusercontent.com/2767681/35686137-dd3219fc-076b-11e8-80b9-62196a869387.png)

**Comment by van800** [comment]
Hi!
It is configurable
![image](https://user-images.githubusercontent.com/1482681/35686707-32fc7d40-076d-11e8-84ae-5b5d22228a18.png)

**Comment by van800** [comment]
And we try to use 4.6 as default
https://github.com/JetBrains/resharper-unity/blob/wave11-rider-2017.3.1/resharper/src/resharper-unity/Unity3dRider/Assets/Plugins/Editor/JetBrains/RiderPlugin.cs#L128
Our older version used 4.5 as default, it may have been saved to settings and used in your case.
