### ISSUE TITLE
Customize only Unity-generated csproj files, not just all in the CurrectDirectory

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#361]
initially requested here https://rider-support.jetbrains.com/hc/en-us/community/posts/360000080824--Unity-ItemGroup-keeps-being-added-to-csproj-files

**Comment by van800** [comment]
This changes will not be backported to 2017.3.1. 
You may fix your local Unity3dRider.cs or just move your custom csproj files to any other directory.

**Comment by vl4dimir** [comment]
@van800 Hi, I reported the bug on the link above. Will this be fixed in 2018.1? Just checking since you added it to the 2018.1 milestone and then closed the issue.

**Comment by citizenmatt** [comment]
Yep, it's fixed with the following change: 16fbdf09f50825adcbe9fd507990d2bb2bdb37bf

**Comment by vl4dimir** [comment]
@citizenmatt Awesome, thanks! 😄
