### ISSUE TITLE
Remove “Open C# Project in Rider” menuitem, if it is not needed starting with some Unity version

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#364]
It will require testing several Unity versions starting with 2017.1 and release Rider installed via installer and via toolbox. 

As far as I can remember, in the past Unity was not matching "JetBrains Rider.exe" as a known external editor.

**Comment by van800** [comment]
“Rider*.app” recognition on macOS was fixed in Unity 2017.3.1p2 and above, but we can't remove the menuitem, because there are no means in Unity to conditionally remove-add menu-items.
We can only enable-disable them.

**Comment by van800** [comment]
Only solution is to provide a separate plugin dll for different versions of Unity.

**Comment by edencakir** [comment]
I wish we could disable this, very annoying

**Comment by van800** [comment]
@edencakir do you mean disable or remove? Removing is hard. Disabling is doable.

**Comment by edencakir** [comment]
@van800 Both works tbh

**Comment by van800** [comment]
@edencakir what is your Unity version?

**Comment by edencakir** [comment]
@van800 Unity 2017.4.2 (we're planning to use LTS channel for at least 6 months)

**Comment by edencakir** [comment]
any updates on this?

**Comment by van800** [comment]
@edencakir isn't it disabled for you?
![image](https://user-images.githubusercontent.com/1482681/43509916-4a57e3fe-9574-11e8-8c48-d9a1efd48fdd.png)

**Comment by edencakir** [comment]
@van800 ah sorry, I misunderstood the issue entirely.

`Cannot add menu item 'Assets/Open C# Project in Rider' for method 'PluginSettings.MenuOpenProject' because a menu item with the same name already exists.`

Just wanted to get rid off this warning ^

**Comment by van800** [comment]
@edencakir I guess you have 2 plugins doing same thing. Look for Unity3dRider.cs and remove it. Look for duplicates of "JetBrains\JetBrains.Rider.Unity.Editor.Plugin*.dll"

**Comment by edencakir** [comment]
Thank you!

**Comment by van800** [comment]
In Unity 2019.2+ MenuItem is not be present.
