### ISSUE TITLE
Supress "field is never assigned"

### ISSUE THREAD

**Issue by ortin** [JetBrains/resharper-unity#37]
Supress "field is never assigned" for public (and marked as [SerializeField]) fields in classed derived from MonoBehaviour

**Comment by citizenmatt** [comment]
This is a duplicate of #15, which is fixed, but not yet released. I'll try and push a release next week.

**Comment by ortin** [comment]
oh, sorry
didn't check closed ones

**Comment by citizenmatt** [comment]
No problem :) It's not very obvious that a release is overdue...
