### ISSUE TITLE
Please add drag-n-drop file in Unity Explorer

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#383]

**Comment by van800** [comment]
https://youtrack.jetbrains.com/issue/RIDER-15697

**Comment by sdarkwell** [comment]
I agree with @Humberd. I have stopped using the Unity Explorer, because when I try to use it, I find myself constantly switching back to the Solution Explorer. It becomes more cumbersome than helpful.

**Comment by van800** [comment]
On 2018.2EAP1 drag-n-drop is working only partially.
I can't move file to Editor folder here, because there are no other cs files in it, thus no Assembly-Editor.csproj

![2018-06-29_12-30-41](https://user-images.githubusercontent.com/1482681/42088029-63c716fc-7b98-11e8-9712-1b174ce74836.gif)

**Comment by vinhui** [comment]
It also seems it won't allow me to move a file to a `asset`/`assets` sub folder. For example `Assets/Scripts/MyModule/Assets`.

**Comment by van800** [comment]
just for internal reference https://github.cds.internal.unity3d.com/unity/com.unity.ide.rider/pull/34
fix in Rider package should help with drag-drop into empty folders

**Comment by van800** [comment]
Drag-n-drop for folders, which are out of the project was fixed in Rider 2019.3. Would be available in first EAP.

**Comment by sebas77** [comment]
It seems I am having this issue with 2019.2.3 I have to open the solution explorer to be able to move an existing file into a new folder. This also mean that the perforce plugin won't be able to do its job. This is happening also with the file explorer view, I don't think it's unity related.

**Comment by van800** [comment]
I stated `Rider 2019.3`.

**Comment by sebas77** [comment]
yes but the title also states that it happens only in the Unity Explorer, so I added that is not my case in case is a useful add :)

**Comment by van800** [comment]
If you have an issue in non-unity project, please report it in https://youtrack.jetbrains.com
