### ISSUE TITLE
EditorPlugin is not installed

### ISSUE THREAD

**Issue by KasperKnop** [JetBrains/resharper-unity#387]
According to [this](https://github.com/JetBrains/resharper-unity/issues/266) post the issue was resolved in 2018.1, but in the new 2018.1 EAP I still cannot use multiple solutions at the same time?

**Comment by van800** [comment]
Have you cleaned up Unity3dRider.cs?

**Comment by KasperKnop** [comment]
How do I do that exactly? I deleted the script and now I cannot get Rider to reinstall it in my project.

**Comment by van800** [comment]
New plugin is named JetBrains.Rider.Unity.Editor.Plugin.Repacked.dll

**Comment by van800** [comment]
If still plugin is not installed, please zip and attach all log files from Help->Show log in Files.

**Comment by KasperKnop** [comment]
My Rider settings have always been set up to install and update the Rider Editor plugin automatically. I have this issue on both my work laptop and home PC. Here are the [log](https://github.com/JetBrains/resharper-unity/files/1770376/log.zip) files from my laptop.

**Comment by van800** [comment]
Very soon (maybe tomorrow or after weekend) nightly builds with fixed plugin installation will become available. Can we wait that new build, if it will not work for you, we will make a call and investigate it together. Is it fine for you?

**Comment by KasperKnop** [comment]
Sure thing! Thanks :)

**Comment by van800** [comment]
Nightly build is already available.
It is accessible via https://www.jetbrains.com/toolbox/download/

**Comment by KasperKnop** [comment]
Thanks, but the plugin still does not install itself on either of my two computers with the nightly build.

Here is the [log.zip](https://github.com/JetBrains/resharper-unity/files/1777360/log.zip)

**Comment by van800** [comment]
Logs say
11:09:42.899 |I| UnityPluginDetector           | No unity generated projects found. Skipping installation.
11:09:42.899 |I| UnityPluginInstaller          | Plugin should not be installed.

Is it true that you work with Unity-generated solution?

**Comment by KasperKnop** [comment]
I'm not sure I understand your question.

If I create a new project in Unity, Unity will create my Microsoft Visual Studio Solution file.

When I then create a new script and open it with Rider as my default editor, no plugin get's added to my Unity project.

**Comment by van800** [comment]
Lets have a call on Monday-Tuesday. I am really curious, what is a problem. Do you work Europe time?
Skype or google meeting? Thanks!

**Comment by KasperKnop** [comment]
Sure thing! Yes CET. I work from 8-16 both days, but I am available any time after that. If you can set up a google meeting that would be fine with me. Just tell me if you need any specific information or you want me to prepare or test anything beforehand.

**Comment by KasperKnop** [comment]
I have found a workaround to consistently install the plugin:

If I open the project solution in Visual Studio, Rider will start to install the missing plugin automatically.

**Comment by van800** [comment]
Yes, now I seem to understand how it happens. Unity without our plugin generates csproj with TargetFrameworkVersion 4.6 or 3.5 depending on version of Unity. But new msbuild requires dotnet target pack installed of exactly same version as TargetFrameworkVersion. So reference to Unity Engine dll is not resolved and it affects plugin installation.
MSBuild 4.0 is good, but only for LangVersion 4. Will not work with LangVersion 6.

I am leaving the issue opened and will think of the solution.

**Comment by van800** [comment]
Fix is in the nightly build, available via https://www.jetbrains.com/toolbox/download/

**Comment by elloop** [comment]
i solve this problem by installing the lateset stable Mono.framework
