### ISSUE TITLE
Disable warning 649 on fields with SerializeFieldAttribute

### ISSUE THREAD

**Issue by Deadcows** [JetBrains/resharper-unity#39]
To skip "field is newer assigned" warning with private fields with SerializeField (assigned via inspector) I had to flood my code with "#pragma warning disable 649" and "#pragma warning restore 649". Will be good to skip this warning somehow if possible

**Comment by citizenmatt** [comment]
If this is a warning from the compiler, there is nothing ReSharper can do about it. If it's just a ReSharper warning, in the editor, then this should be fixed by bd67def92fdc0bf9f302e31e5a0efcae1cadaed4, but I haven't yet had the chance to release.

**Comment by hymerman** [comment]
This is a compiler warning; you can use smcs.rsp and gmcs.rsp to tell Visual Studio to disable them - I forget the syntax now but give those names a google and you'll find it!

**Comment by citizenmatt** [comment]
ReSharper can't do anything about compiler warnings. The plugin will mark fields like this as assigned (as of 1.3), so closing this for now.
