### ISSUE TITLE
Disable "play" button for Attach debug configurations

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#390]
The "play" button should be disabled for the "Attach to Unity Editor" and "Attach and Play" debug configurations - run means nothing, and does nothing.

**Comment by citizenmatt** [comment]
This appears to be an IntelliJ bug: [IDEA-187519](https://youtrack.jetbrains.com/issue/IDEA-187519)

**Comment by citizenmatt** [comment]
Fixed in Rider 2018.1 EAP2

**Comment by van800** [comment]
@citizenmatt is there way to hide it completely?
cc: @kskrygan

**Comment by citizenmatt** [comment]
Not that I know of. And it might be needed by other run configurations. It's possible to add them in a Unity project, even if unlikely.
