### ISSUE TITLE
Easily open editor.log and player.log from Log View

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#391]
Like in Unity's Console

![image](https://user-images.githubusercontent.com/222659/36807246-561d3334-1cba-11e8-8a89-2e8638cee4e6.png)

**Comment by van800** [comment]
@citizenmatt I looked into Unity code.
There are two options and their combination:
1. Call existing Unity public methods  OpenEditorConsole/OpenPlayerConsole, which opens log in the application associated with log extension in the OS.
2. Try to guess path to log and open it in Rider. https://docs.unity3d.com/Manual/LogFiles.html
Location of the Player log can be changed via commandline parameter.

I like option1. It is more predictable.

**Comment by van800** [comment]
In development
![image](https://user-images.githubusercontent.com/1482681/40685135-b4419160-6393-11e8-8b25-db47170b3de5.png)
