### ISSUE TITLE
Option to clear Unity logs window automatically

### ISSUE THREAD

**Issue by zharovakate** [JetBrains/resharper-unity#393]
The Unity logs window does not clear or stacks logs as Unity does, the stacking feature I don’t really care, but not clearing automatically or option to make it possible (not the button to clear), really annoy me.

**Comment by van800** [comment]
Will it be fine if we do "Clear on Play" without options?
Getting option value from Unity itself is a hack with reflection, which I would love to avoid.

**Comment by van800** [comment]
https://github.com/JetBrains/resharper-unity/pull/398

**Comment by van800** [comment]
Fix is already in the nightly build. Available via https://www.jetbrains.com/toolbox/download/
