### ISSUE TITLE
File templates not working in 2018.1 EAP1

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#396]
The Unity specific file templates are not showing up in the Add menu of 2018.1 EAP1

**Comment by citizenmatt** [comment]
Ugh. I'm an idiot. The project was out of date, with invalid references to UnityEngine.dll after an update in Unity Hub. Fix the project files, and the file templates work again.

**Comment by van800** [comment]
I see the file templates problem on latest nightly build. Nighties are now from master.
