### ISSUE TITLE
Saving a script in Rider 2018.1 EAP with Rider plugin v2.1.3.2067 triggers a recompile in Unity

### ISSUE THREAD

**Issue by SugoiDev** [JetBrains/resharper-unity#402]
Using latest Rider 2018.1 EAP with Unity 2018.1.0b9
Rider plugin is v2.1.3.2067

I just let Rider install the latest integration and noticed this behavior.
I have "Auto Refresh" disabled in Unity, but every time I save a script in Rider, I see Unity recompiling in my second monitor.

This isn't very good, since a lot of times when we're coding, it isn't ready to be compiled until we're done.

Removing the integration plugin makes the problem go away.

**Comment by van800** [comment]
I will add "Auto Refresh" as a precondition for that "Refresh on each Save".

**Comment by SugoiDev** [comment]
Sounds good.
