### ISSUE TITLE
Wrong message about plugin installation path when Rider auto-installs it

### ISSUE THREAD

**Issue by SugoiDev** [JetBrains/resharper-unity#403]
Using latest Rider 2018.1 EAP
Rider plugin is v2.1.3.2067

This is the message that is shown

    Rider plugin v2.1.3.2067 for the Unity Editor was automatically installed for the project 'Unity3D'
    This allows better integration between the Unity Editor and Rider IDE.
    The plugin file can be found on the following path:
    ..\Assets\Plugins\Editor\JetBrains\Unity3DRider.cs.
    Please switch back to Unity to make plugin file appear in the solution.

But this isn't right, since the DLL is being installed, not script file.

**Comment by van800** [comment]
Already fixed in the nighty builds, available via JetBrains toolbox app.

**Comment by van800** [comment]
https://www.jetbrains.com/toolbox/download/
