### ISSUE TITLE
Add option to allow "sync solution" to be disabled when opening files from Unity

### ISSUE THREAD

**Issue by SugoiDev** [JetBrains/resharper-unity#404]
In `OnOpeAssetHandler.OnOpenedAsset(int instanceID, int line)`, at [this part](https://github.com/JetBrains/resharper-unity/blob/6aeb70d65d495a5f345983d3b652ffcf8f11c210/unity/JetBrains.Rider.Unity.Editor/EditorPlugin/OnOpenAssetHandler.cs#L48), a solution sync is forced when we're opening a file from Unity.

This is a request to have an option to disable this behavior.

The reasoning for this request are these two points
1. sometimes the code is broken and in a state that doesn't compile. Forcing this sync will trigger a recompilation and Unity will now know that the code is broken.
2. if the sync request causes a recompilation (and then an assembly reload), changes in playmode will be lost. I had this happen when doing small changes to the code based on what I was seeing in playmode, but then playmode broke because a reload was triggered by the recompile (caused by the sync request).

**Comment by van800** [comment]
Could you please try the nighly build from [toolbox]( https://www.jetbrains.com/toolbox/download/) and see how it works for you?
With this fix https://github.com/JetBrains/resharper-unity/pull/412/commits/16632d0e87c948e1f715ccc6e385f21e5b736972
sync is only called when 
1. file was added or removed
2. we are in edit mode
3.  AutoRefresh is enabled

**Comment by SugoiDev** [comment]
Did a quick test and it looks good.

Thanks!

**Comment by van800** [comment]
I would need to get back the possibility to force refresh by pressing a button in Rider. Will do shortly.

**Comment by van800** [comment]
fixed with https://github.com/JetBrains/resharper-unity/pull/431

**Comment by van800** [comment]
available in the latest nightly build via https://www.jetbrains.com/toolbox/download/
