### ISSUE TITLE
"show all files" possibility for UnityExplorer

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#405]
I have got a comment, that sometimes it is needed to view them.

**Comment by citizenmatt** [comment]
I thought it did show all files, except for certain hidden files (.meta, .tmp, etc. see "Hidden Assets" at the bottom of [this page](https://docs.unity3d.com/Manual/SpecialFolders.html))?

**Comment by van800** [comment]
Yes, it shows all except some extensions, but I propose to add an option to show really all files.
Similar to the "show all files" option we have in Solution Explorer.
