### ISSUE TITLE
Methods called by Invoke marked as never used

### ISSUE THREAD

**Issue by BioTiNe** [JetBrains/resharper-unity#41]
For Example:
```
using UnityEngine;

public class Example : MonoBehaviour
{
    private void Start()
    {
        Invoke("SomeMethod", 0f);
    }

    void SomeMethod() // <- Marked as never used
    {
        Debug.Log("Hello World");
    }
}
```

**Comment by cmcpasserby** [comment]
Not exactly sure how you would expect it to do so, when you are calling it via a string, and to me it seems like it is already doing what is expected.

**Comment by BioTiNe** [comment]
But wouldn't it be possible to detect usage when calling it with a string literal?
