### ISSUE TITLE
Disable recompilation when switching to Unity.

### ISSUE THREAD

**Issue by oxysoft** [JetBrains/resharper-unity#410]
I have a plugin in Unity which makes it only recompile when the game isn't playing, and now the Rider integration plugin seems to force recompilation in-game.

**Comment by van800** [comment]
Could you please share, how the mentioned plugin works? If you can share sources or dll, please.
Thanks!

**Comment by oxysoft** [comment]
It is [ConsoleEnhanced](https://assetstore.unity.com/packages/tools/utilities/console-enhanced-free-42381). You can find the setting in its "Misc" settings category.

**Comment by van800** [comment]
Could you please try the nightly build from https://www.jetbrains.com/toolbox/download/
I made a fix https://github.com/JetBrains/resharper-unity/commit/16632d0e87c948e1f715ccc6e385f21e5b736972
which could have fixed your problem.

**Comment by van800** [comment]
Please reopen or just comment if it is still an issue.

**Comment by oxysoft** [comment]
Still doesn't work.

**Comment by van800** [comment]
Do you have Auto Refresh enabled in Unity?

**Comment by van800** [comment]
May be fixed by https://github.com/JetBrains/resharper-unity/commit/15194b98163aa8634898f26a4c0891c15a1491b3
Need to check later.

**Comment by van800** [comment]
Available in nightly build via https://www.jetbrains.com/toolbox/download/
