### ISSUE TITLE
By default use autodetected TargetFrameworkVersion, unless specifically overrided

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#417]
Need to rethink the approach to storing the TargetFrameworkVersion in the Unity settings.
Initial problem is that Unity itself always generated TargetFrameworkVersion = 4.6 disregarding what packs are installed on user machine.

We have some detect of installed dotnet targets packs on windows, but for now we use it only first time. Later it is saved to Unity settings and next time used as if it is a user-desired value.

Need to change it maybe to the following logic:
Call Autodetect every time and use its value unless user specifically checks some setting to override it.

**Comment by utoxin** [comment]
I like the suggestion you make for a solution. Might be nice to have a button to trigger an autodetection if it's been over-ridden manually as well.

**Comment by van800** [comment]
Available in nightly build via https://www.jetbrains.com/toolbox/download/
