### ISSUE TITLE
private void OnEnable & OnDisable are marked as not used

### ISSUE THREAD

**Issue by petemounce** [JetBrains/resharper-unity#42]
I've got solution-wide analysis turned on in addition to colour-identifiers. These methods are shaded slightly to indicate they're not used by anything, but solution-wide analysis does not have an issue with them.

I think they should not be shaded; they're definitely used by Unity.

**Comment by citizenmatt** [comment]
I think this is a duplicate of #22 Support EditorWindow messages. Closing for now.
