### ISSUE TITLE
Debug messages flooding in Unity freezes Rider.

### ISSUE THREAD

**Issue by oxysoft** [JetBrains/resharper-unity#424]
Disabling messages in the Unity windows stops this from happening.

**Comment by van800** [comment]
How many messages it was approximately? Thanks for reporting!

**Comment by oxysoft** [comment]
Hard to say, it was flooding for sure. Just making a script which calls `Debug.Log("zzz");` every frame should be enough to stall Rider. If you pause or stop the game, Rider catches up after a few seconds.

**Comment by van800** [comment]
Available in nightly build via https://www.jetbrains.com/toolbox/download/
