### ISSUE TITLE
Syntaxic highlight coloration for unity specific types

### ISSUE THREAD

**Issue by Baccanno** [JetBrains/resharper-unity#426]
Would it be possible to add "Unity Scripting component" and other similar things this extension detects to Visual syntax color filters ?

It would be great to have a different color for components vs regular classes.

Great job!

Best

**Comment by citizenmatt** [comment]
Hi. I'm not sure what you mean here. Could you explain further, please?

**Comment by oxysoft** [comment]
I think he means files that contain a MonoBehaviour should be highlighted a different color in the solution explorer to visually distinguish them quickly.

**Comment by Baccanno** [comment]
Sorry fir the delay. Yes it's indeed what I meant. For now we're suffixing
"Behaviour" anything that inherits from MonoBehaviour, but there is no
other way to figure this out.

2018-03-14 19:42 GMT+01:00 Nicolas M <notifications@github.com>:

**Comment by citizenmatt** [comment]
So, you want any file that contains a MonoBehaviour or other Unity class to be highlighted in a different colour in the Solution Explorer? Or highlight the class name a different colour in the editor?

**Comment by Baccanno** [comment]
Any class that is assignable to a MonoBehaviour could have a distinction
from regular c# classes. For instance we have a BaseMonoBehaviour that
inherits from MonoBehaviour and that will parent any concrete Behaviour we
implement.

I guess that both a different color in Solution Explorer and on the actual
Class identifier in the cs file can be of interest.


2018-03-16 15:33 GMT+01:00 Matt Ellis <notifications@github.com>:

**Comment by Baccanno** [comment]
Class identifier, and fields, parameters,etc that are MonoBehaviours as well

2018-03-16 15:55 GMT+01:00 Michaël Picovschi <michael.picovschi@gmail.com>:

**Comment by citizenmatt** [comment]
Fixed in #901. Implicitly used items such as `MonoBehaviour` based classes, serialised fields, event functions and event handler methods/setters are now highlighted as "implicitly used". By default this is a bold highlight, but can be configured in options.
