### ISSUE TITLE
NUnit "theory" tests are "Inconclusive: Test not run" (Unity3D)

### ISSUE THREAD

**Issue by Arakade** [JetBrains/resharper-unity#428]
While regular unit test methods are run fine, those annotated with "Theory" have the curious state "Inconclusive: Test not run" at the end of the test run.

I'm doing this with a Unity3D project if that's of relevance and testing the same functionality in both the regular and theory tests (no particularly Unity-specific functionality).

Here are files showing the problem.  Let me know if any problems.  Thx.
[Theory.zip](https://github.com/JetBrains/resharper-unity/files/1799303/Theory.zip)

P.s. it's awesome that Rider is able to run unit tests outside Unity at all!
p.p.s. Whoops, I just noticed I left "SimpleSQL" and "Beebyte Obfuscator" references in the code I sent.  Just delete the problematic references -- they're unnecessary to show the problem!  Sorry again!

**Comment by van800** [comment]
Fixed in the latest available nightly build. https://rider-support.jetbrains.com/hc/en-us/articles/360000009804-How-to-get-Rider-Nightly-build-
