### ISSUE TITLE
"C# 7.0 language feature" error when using alexzzzz's C#7+ integration

### ISSUE THREAD

**Issue by SugoiDev** [JetBrains/resharper-unity#429]
Using [alexzzzz's C# 7+ integration](https://bitbucket.org/alexzzzz/unity-c-5.0-and-6.0-integration/overview) with the latest Rider and the latest resharper-unity integration, I'm getting those errors when using C# 7+ features.

![screenshot 2018 03 11-13 03 02](https://user-images.githubusercontent.com/7355630/37255824-b60c3fb4-2530-11e8-87a9-f212e3d87dc4.png)

Checking the csproj files, I see that they have `<LangVersion>6</LangVersion>` (instead of using **7**).
I see that the resharper-unity's csproj asset processor should be using **7** if it sees the **CSharp70Support** directory present.

Maybe we should add a **public override int GetPostprocessOrder() => 10;** (or some high number like that), to ensure it runs after anything else that could be modifying the csproj files as well? alexzzzz's integration also modifies the csproj files (see [CSharpProjectPostProcessor](https://bitbucket.org/alexzzzz/unity-c-5.0-and-6.0-integration/src/3a35c6f20d46ad918a6fc37380682c8e5f4598dd/CSharp%20vNext%20Support%20Solution/CSharpVNextSupport/CSharpProjectPostprocessor.cs?at=default&fileviewer=file-view-default)), but it uses **latest** as the LangVersion. Maybe Rider has trouble with that?

**Comment by citizenmatt** [comment]
Rider understands `latest`. But our integration only sets `<LangVersion>` if it isn't already set, so either it's not us setting C# 6, or there's a bug in our code and we don't recognise the `CSharp70Support` folder.

Where does the `CSharp70Support` folder live?

**Comment by van800** [comment]
I have reproduced the issue, when we are setting LangVersion 7, but 7.2 is allowed.

**Comment by van800** [comment]
I think we can generate latest. @citizenmatt 

But I don't understand how @SugoiDev is seeing LangVersion = 6.

**Comment by van800** [comment]
https://github.com/JetBrains/resharper-unity/commit/aab88fbaee745eb6860ef377b9d9be577ca37f2a

**Comment by van800** [comment]
@SugoiDev Could you please do some external source debug for the case?
1. From your solution in Rider call Goto everything (Shift-Shift), look for CsprojAssetPostprocessor, find GetLanguageLevel and set a brakepoint inside, attach to UnityEditor.
2. Goto Unity and call Assets->Sync C# project
You' ll be able to see what LangLevel is Rider setting.

**Comment by SugoiDev** [comment]
What seems to be happening is not that the integration is setting the wrong value, but that the value it sets is being overridden. 

Since the asset post processors order is random, unless `GetPostprocessOrder` is overridden, the integration sets the correct value, but it is lost as another post processor (possibly even Unity itself, when generating the projects) sets it to another value, after rider's.

I'm currently testing with your changes from aab88fbaee745eb6860ef377b9d9be577ca37f2a (using "latest") and with an added a `GetPostprocessOrder` of 10. I also added a Debug.Log right before the integration sets the LangVersion, and it is being set properly.

```
[13:24:23.282 (0010)] Added langVersion=<LangVersion xmlns="http://schemas.microsoft.com/developer/msbuild/2003">latest</LangVersion>
```

Will report back soon.

**Comment by van800** [comment]
Available in nightly build via https://www.jetbrains.com/toolbox/download/

**Comment by goneale** [comment]
New Rider user here, basically can't compile my Web API project so reverting to VS until it's functioning I suppose.

**Comment by goneale** [comment]
Just getting a ton of this, and C# 7.0 not selectable in Options. However, project builds fine in VS with no changes. Love the hair!
![image](https://user-images.githubusercontent.com/107109/40599106-e7e10ce0-628e-11e8-9a8d-8d01e4ad322e.png)

![image](https://user-images.githubusercontent.com/107109/40599119-f12ca8fe-628e-11e8-936a-99badb150761.png)

**Comment by van800** [comment]
@goneale I guess you have MSBuild 14 selected as a build tool in Rider - change it to MSBuild 15.

**Comment by citizenmatt** [comment]
This looks like a web project - this project is focussed on the Unity support in Rider, which means we don’t really know much about web projects 😔. And I’m afraid I don’t have good enough WiFi right now to look, but you’ll get better help speaking to JetBrains’ support department, either at https://youtrack.jetbrains.com or support@jetbrains.com. Sorry I can’t help further - complete lack of decent internet right now!
