### ISSUE TITLE
Treat [SerializeField] fields as [UsedImplicitly]

### ISSUE THREAD

**Issue by hymerman** [JetBrains/resharper-unity#43]
Currently I get an "Unassigned field" warning on fields that are private but with a `[SerializeField]` attribute. These fields are set by Unity serialization. Marking them with `[UsedImplicitly]` fixes this and seems like the correct thing to do, but could perhaps also live in this plugin since it does a similar thing for e.g. `Awake` and `Update` on `MonoBehaviour`.

This is maybe more complex than it seems though since it would have to work not just `MonoBehaviour` and `ScriptableObject` fields, but on any fields in classes serialized by them. Just fields directly on those classes would be a good start though!

**Comment by citizenmatt** [comment]
Fixed in bd67def92fdc0bf9f302e31e5a0efcae1cadaed4. Will be released with 1.3
