### ISSUE TITLE
Move remaining Unity code from Rider codebase into plugin

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#442]
We have some Unity code that's still sitting in the Rider codebase instead of in the plugin, specifically around debugging - searching for local Unity processes and some util code for filtering out Unity processes.

We should move this into the plugin. There's no need for it to be in the main product, and makes it harder to change.

See #343 and [RIDER-13658](https://youtrack.jetbrains.com/issue/RIDER-13658)

**Comment by van800** [comment]
сс: @ArsenyChernyaev

**Comment by ArsenyChernyaev** [comment]
Moved code to plugin, remove merge in progress

**Comment by citizenmatt** [comment]
Fixed with a655c5c956a9b74868bdaa00007b9e9c63f02b07
