### ISSUE TITLE
Parse printed stacktrace

### ISSUE THREAD

**Issue by tgouala** [JetBrains/resharper-unity#457]
There is some situation where an exception stacktrace cannot be read immediately and need to be printed to the log for debug purpose. 

For example, using the promise pattern :
```C#
LoadLevel(levelPath, levelName).Then(level => level.Start())
	.Catch(e => Debug.LogError("An exception happened while loading level : " + levelPath + levelName + 
"\n" + e.Message + "\n" + e.StackTrace));
```

I noticed that in this case, the printed stacktrace is not parsed and it's not possible to click on any hyperlink inside Rider Unity tool panel.

Is it a limitation, or is it something that could potentially be on your roadmap ?

**Comment by van800** [comment]
Could you please give me a simple example demonstrating the problem?

**Comment by SugoiDev** [comment]
I use the pattern of printing two messages in those cases.
One using the normal `Debug.LogError` (and saying the exception will follow next) and a second one using `Debug.LogException` with the exception itself.

More specifically, I have a helper for that, so I just use `Logger.PrintException(ex, "some message")`
Here's a simplified version

```
public static void PrintException(
    Exception exception,
    string prefixMessage = "",
    object context = null) {
    try {
        var possibleUnityObjectContext = context as UnityEngine.Object;
        if (!string.IsNullOrWhiteSpace(prefixMessage)) {
            UnityEngine.Debug.Log($"{prefixMessage} (see next message for exception)", possibleUnityObjectContext)
        }

        UnityEngine.Debug.LogException(exception, possibleUnityObjectContext);
    }
    catch (Exception e) {
        UnityEngine.Debug.LogError("Got exception while trying to print exception. See next message for the exception.");
        UnityEngine.Debug.LogException(e);
        UnityEngine.Debug.LogError("See next message for the original exception we tried to print.");
        UnityEngine.Debug.LogException(exception);
    }
}
```

Trying to parse the exception when it is being printed with messages is very hard and very expensive. I got all kinds of edge cases when playing with that.

**Comment by tgouala** [comment]
@SugoiDev Tested your solution, works pretty well in the Rider Unity log tool.

@van800 Here a simple example :
```C#
try
{
	var table = new int[3];
	table[3] = 3;
}
catch (Exception e)
{
	Debug.LogError("An exception occured : " + e.Message + "\n" + e.StackTrace);
}
```

When the exception occurs, the whole string `"An exception occured : " + e.Message + "\n" + e.StackTrace` appears in the left part of the Rider log view. On the right side (where stacktrace is displayed) you can only navigate to where Debug.LogError was called.

![image](https://user-images.githubusercontent.com/17229296/37562126-eb20d128-2a9a-11e8-847d-90dcedbb16d5.png)

With @SugoiDev solution, the exception is fully displayed in the right panel of Rider Unity log view. So you can navigate to the line `table[3] = 3;`

With

```C#
try
{
	var table = new int[3];
	table[3] = 3;
}
catch (Exception e)
{
	Debug.LogError("An exception occured, see next message for the complete exception");
        Debug.LogException(e);
}
```

I can navigate to the exception.

**Comment by van800** [comment]
I think we won't fix this. Proposed workaround looks cleaner.
