### ISSUE TITLE
Rider can't see define symbols in DLL source that was built with AssemblyBuilder

### ISSUE THREAD

**Issue by SugoiDev** [JetBrains/resharper-unity#461]
The [AssemblyBuilder](https://docs.unity3d.com/ScriptReference/Compilation.AssemblyBuilder.Build.html) allows us to build dlls as if their source were in the project itself.
It's useful to build stuff that you don't want to have in the project in source form.

I'm using the latest nightly Rider with Unity 2018.1.0b10. Also using the latest of alexzzz's compiler integration. This situation would probably reproduce the same with the normal mono compiler if it generated pdb files but, since it doesn't, rider wouldn't know how to navigate to the source of the built dll.

---

How to reproduce with the attached project

* open in Unity and let it compile
* confirm that there's a single menu item in the **AssemblyBuilder Example** menu
* use that single menu item (Build AssemblyBootstrapper DLL)
* confirm that there's a second menu item now. This one is wrapped into a ifdef and will be provided by the dll that was just built

* In Rider, navigate to symbol **ScriptBuilderRiderDEFINEExample** (its source will be in the Temp folder)
* notice that Rider says that the define symbol **ASSEMBLY_BUILDER** is not present. 

It really isn't present in the project itself, but we know that this define was set in the built DLL because the menu item is there (opening the dll also shows that).
Since we're navigating to the source of the dll and we have the symbols from the pdb file, I would expect Rider to know that the symbol was present when DLL was built.

---

**How it looks like in Rider**

![screenshot 2018 03 18-03 03 09](https://user-images.githubusercontent.com/7355630/37563264-4981447c-2a5b-11e8-806c-4eb4fd48683a.png)

---

**Complete reproduction project**
[resharper-unity_DEFINE_issue_clean.zip](https://github.com/JetBrains/resharper-unity/files/1822402/resharper-unity_DEFINE_issue_clean.zip)

---

PS: The name ASSEMBLY_BUILDER is a bit weird in this repro case so it deserves some clarification. It is taken directly from my project, where it makes a bit more sense: when it is defined, it means we're using the actual assembly builder (not its bootstrapper). The bootsrapper is just to create a dll for this builder so the builder's menu item is available even when we have compilation errors.

**Comment by van800** [comment]
I am not sure, we can fix it actually.
Rider uses defines from unity-generated csproj, but there are no ASSEMBLY_BUILDER define in that csproj.
Do you mean, Editor plugin should add it, while post-processing csproj-s?

**Comment by van800** [comment]
It seems to be a request for Assembly Builder asset itself.
Adding define to csproj can be done similar to our code: https://github.com/JetBrains/resharper-unity/blob/master/unity/JetBrains.Rider.Unity.Editor/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs#L204

**Comment by van800** [comment]
Feel free to reopen though.
