### ISSUE TITLE
Firstpass projects and unsafe code

### ISSUE THREAD

**Issue by cNoNim** [JetBrains/resharper-unity#463]
Hi all.
Why '-unsafe' from rsp files does not applied to firstpass projects?
In CsprojAssetPostprocessor.cs exists two functions
IsPlayerProjectFile
and
IsEditorProjectFile,
but they do not know nothing about firstpass projects.

**Comment by cNoNim** [comment]
Can i help you with something?

**Comment by van800** [comment]
@cNoNim No, thanks! I have already consulted with Unity team. You are right, it should affect all projects. Will be fixed shortly.

**Comment by cNoNim** [comment]
Do I understand correctly?
smcs.rsp and gmcs.rsp
Don't work for firstpass projects?

**Comment by van800** [comment]
I made a fix, it will be merged during this week.

**Comment by cNoNim** [comment]
I saw your fix. But in that fix smcs.rsp and gmcs.rsp affect only on Editor and Player projects. mcs.rsp affect on all projects. Is it correct behaviour? Why smcs.rsp and gmcs.rsp don't apply settings to firstpass projects?

**Comment by van800** [comment]
@cNoNim I thought, you are using mcs.rsp.
It appeared to me that smcs and gmcs are for Unity prior to 5.5.
What version do you use?

**Comment by cNoNim** [comment]
I use Unity 5.6, and msc.rsp. 
But i think it's inconsistent behaviour.
If this is not a problem, then I'm satisfied with the fix. 
I used gmsc and smsc early.

**Comment by van800** [comment]
We got that gmcs, smcs logic from PR
https://github.com/JetBrains/resharper-unity/pull/230
cc: @trondgtrond 
I don't want to change it, unless someone really requests it.

**Comment by van800** [comment]
Fix must be in the nightly build.
