### ISSUE TITLE
Resharper-unity plugin causes a noticeable delay when typing in file/class/namespace scope

### ISSUE THREAD

**Issue by rob8861** [JetBrains/resharper-unity#471]
Hello,

I recently noticed a performence issue with intellisense when writing code inside a method scope vs class/file scope. When editing/writing code inside a method, intellisense is super responsive, but when editing in class scope, a noticable lag is observed.

For example, consider the following file:

```
Person.cs

public class Person
{
// here R# intellisense exhibits a lag when typing reserved keywords like private, public, float, int etc.
// performence is below normal and a noticeable lag can is felt when typing code.

public void DoSomething()
{
// here , R# intellisense is quick and responsive. Performence is comparable to native
}

}
```

please note that when I disable the plugin, the lag goes away. There seem to be an issue when the plugin is enabled and intellisense is trying to open the popup but only when you are outside of a method scope. kinda weird but I am sure you guys can figure out what's going in. 

Thanks,

Environment:
Windows 10 64bit
VS 2017 v15.6
Resharper 2017.3.2
Unity 2017.2.0p1

**Comment by citizenmatt** [comment]
Could you grab a profile snapshot, please? You can do this directly from ReSharper - [here are the instructions](https://resharper-support.jetbrains.com/hc/en-us/articles/207243205-How-to-collect-a-performance-snapshot-and-send-it-to-JetBrains-Team). Please let me know the issue number that gets created, and I can take a look at the snapshot.

**Comment by rob8861** [comment]
the resharper snapshot uploader hardly ever works, so I had to share it via dropbox

https://www.dropbox.com/s/da6gfo1byuz1d7g/Zumezyg.zip?dl=0

since you did not specify which profiling snapshot, I created a timeline. If you also need a sampling let me know.
The snapshot only captures few seconds of me typing code outside of a method. This is where I notice a significant lag from the time I start typing to the time intellisense wakes up and display code completion popup.

**Comment by citizenmatt** [comment]
Thanks. This looks like we're being inefficient when adding the lookup items for Unity's event functions. Could you just confirm that this happens in methods that derive from a Unity class, such as `MonoBehaviour` (the example above doesn't)? You shouldn't see any lag in classes that don't.

**Comment by robfazio** [comment]
Hi Matt,
I was actually about to update you regarding the MonoBehaviour part but looks like you already figured that out :-) . So yes, you are correct. There is no lag if the class is not derived from MB.
