### ISSUE TITLE
Portable PDB support with Unity 2018.1.0b12 and the PdbAssetPostprocessor

### ISSUE THREAD

**Issue by SugoiDev** [JetBrains/resharper-unity#474]
b12 supports portable pdb files now.
Trying to generate mdb for portable PDB files in `PdbAssetPostprocessor` is probably no longer need on b12 when using .NET 4.x.

Relevant release notes section:
>Scripting Upgrade: Portable PDBs are supported when running with the new scripting runtime.

Link: https://unity3d.com/unity/beta-download

**Comment by van800** [comment]
We never supported portable pdb
https://github.com/JetBrains/resharper-unity/blob/master/unity/JetBrains.Rider.Unity.Editor/EditorPlugin/AssetPostprocessors/PdbAssetPostprocessor.cs#L32-L35

So is it true that no action is required?

**Comment by SugoiDev** [comment]
Yeah, no action required!
It's no longer a shortcoming, not being able to generate a mdb from a portable pdb. Portable pdb are now first class citizens!
