### ISSUE TITLE
Opening files in "packages" in Unity 2018.1

### ISSUE THREAD

**Issue by SugoiDev** [JetBrains/resharper-unity#475]
2018.1 is finally using packages.

The packages folder is a sibling of the Assets folder, and any packages there will be compiled and have a csproj created for them.

They'll be added to the sln as if they were in the Assets folder itself.

I use a console enhancement that allows me to override the opening of an asset when double clicking the console entry.

I can extract the path of the file to open, as well as a line number.

The problem is that the [OnOpenAssetHandler.OnOpenedAsset](https://github.com/JetBrains/resharper-unity/blob/c98a0814456d6f1a8038c26c8da6770eb1ac14bc/unity/JetBrains.Rider.Unity.Editor/EditorPlugin/OnOpenAssetHandler.cs#L30) only accepts an instanceID with line number.

Since files in packages are not under the Assets folder, they don't have the concept of instanceID, neither are UnityObjects (so we can't do the checks for assetObject.GetType().ToString() against "UnityEditor.MonoScript", for example).

---

A way to solve this, is to provide a public method similar to `PluginEntryPoint.CallRider`, but with a signature of `string fileName, int lineNumber`

This involves refactoring the `OnOpenAssetHandler.OnOpenedAsset` to separate the Unity part of the part that does the raw actual opening/activation of Rider.

**Comment by citizenmatt** [comment]
Yep, we definitely want to provide great support for packages, but there hasn’t been much detail available to date. Do you have any links that describe about the .csproj generation, or have a sample project?

Also, I’m not too sure what you mean with the refactoring of OnOpenedAsset - could you elaborate please? What kind of log message are you double clicking?

**Comment by SugoiDev** [comment]
I'm working on an example project, for a issue with Rider not recognizing C#7 in package items.
Will post soon and comment back here.

---

In the meantime,

>Do you have any links that describe about the .csproj generation

From what I gathered, it uses the same hooks as the normal generation.
They are even processed and have "latest" as LangVersion, and 4.7 for framework version.


>What kind of log message are you double clicking?

Log messages coming from scripts in a package.

>Also, I’m not too sure what you mean with the refactoring of OnOpenedAsset - could you elaborate please? 

Of course.
Currently, it begins with this:
```
public bool OnOpenedAsset(int instanceID, int line)
{
  UnityEngine.Object assetObject = EditorUtility.InstanceIDToObject(instanceID);
  string fullPath = Path.GetFullPath(AssetDatabase.GetAssetPath(assetObject));
  if (!(assetObject.GetType().ToString() == "UnityEditor.MonoScript") && !(assetObject.GetType().ToString() == "UnityEngine.Shader") && (!(assetObject.GetType().ToString() == "UnityEngine.TextAsset") || !EditorSettings.externalVersionControl.Contains(Path.GetExtension(fullPath).Substring(1))))
    return false;
```

This is the "Unity" part. It deals with `EditorUtility` and `AssetDatabase`. 
In the end, it wants to extract `fullPath` from the given instanceID. Also, since we have a UnityEngine.Object, we can also check its type and make sure the Rider can open that.

The rest of the method is generic and would work perfectly as long as it was fed a `string fullPath` and a `in line`.

So this "second half" of the method could be its own method. Maybe an overload, like `OnOpenedAsset(string fullPath, int line)`

Then, the current `OnOpenedAsset(int instanceID, int line)` could be simplified to this:

```
public bool OnOpenedAsset(int instanceID, int line)
{
  //the Unity part, like above
  
  return OnOpenedAsset(fullPath, line);
}
```

To complete this and get it working on the user side, we would would need to add a `public static bool OnOpenedAsset(string fullPath, int line)` (and maybe  `public static bool OnOpenedAsset(int instanceID, int line)`, for completion sake), to `PluginEntryPoint`.

---

With those changes, the user can call either overload of `PluginEntryPoint.OnOpenedAsset()` and have the plugin handle opening the asset properly.

Having this would allow us to pass the `fullPath` directly, without depending on the `AssetDatabase`, and this would give us a way of opening a package item via a console that allows us to override how it opens something when double clicking a console log entry.

---

In the future, the plugin could optionally override the double click handling on the normal Unity console and provide this feature out-of-the-box: double clicking log entries coming from package items will open the package item in Rider, as normal.

**Comment by SugoiDev** [comment]
I could not find a free console replacement that allowed overriding the behavior of double clicking the stacktrace/source preview/log message. 

Unity's default console (from ConsoleWindow.cs) has nothing of the like.
When an entry is double clicked, this method is executed: `LogEntries.RowGotDoubleClicked(clickedRow)`
But that's an `extern` method, so we can't play around with it, sadly.

---

If you guys think this issue is out of scope or too specific, feel free to close it.

Also, if you're willing to accept/review a PR, I can submit one with the mentioned changes.

Let me know.

**Comment by van800** [comment]
Do you mean you are going to use the new method 
public bool OnOpenedAsset(string assetFilePath, int line)
from your own plugin to Unity?

Will you be satisfied with the following change?
https://github.com/JetBrains/resharper-unity/commit/893c337a73f7ffb93a3befff7c9a1236e6eeee37#diff-2b47a45d45e97f0aea4a79889975b8e2R52

**Comment by SugoiDev** [comment]
>Do you mean you are going to use the new method from your own plugin to Unity?

Yes. I'm already using `PluginEntryPoint.CallRider` with success, but it forces extract knowledge on how to use the args formatting from the plugin, as well as having to get the private field `PluginEntryPoint.SlnFile`.


>Will you be satisfied with the following change?

Yeah! It would be perfect it there was a way to call it without using reflection. Maybe adding a method with the same signature to the `PluginEntryPoint` (since it already has a public `CallRider` method).

**Comment by van800** [comment]
If you like the change, I will merge it. 
If you need anything different, please make PR-s, we are willing to review/accept.

**Comment by SugoiDev** [comment]
>If you like the change, I will merge it.

Perfect!
I'm considering this issue solved.

I'll send a PR with the changes on the PluginEntryPoint when I'm playing with this again.
