### ISSUE TITLE
Disable refreshing when ctrl-s is pressed without disabling auto-refresh in Unity

### ISSUE THREAD

**Issue by oxysoft** [JetBrains/resharper-unity#478]
First off, I don't see the use of this feature in the first place. However, I find it annoying mostly because I spam the hell out of CTRL-S when I'm writing code, which means Unity is constantly recompiling in the background which increases CPU usage, decreases battery life, and worst of all, makes it alt-tab automatically to Unity when it is done. Disabling auto-refresh in the Unity preferences obviously works as part of a recent change 2 weeks ago, but I wish to keep auto-refresh so that it recompiles when I do switch to Unity. i.e. I want the classic behavior.

**Comment by van800** [comment]
Are you on Mac?

**Comment by oxysoft** [comment]
Windows 10.

**Comment by van800** [comment]
Unity version?

**Comment by oxysoft** [comment]
2017.3.1f1

**Comment by van800** [comment]
I have never seen Unity focus itself after Refresh from Rider. And I was doing it a lot on Windows 10.
How can I reproduce it?

**Comment by oxysoft** [comment]
Hard to say, we're using several Unity plugins in our project right now, could be caused by one of those. I'll have to try a clean project to be sure. Either way, adding a setting to disable refreshing on save should be fine.

**Comment by van800** [comment]
Adding a setting is relatively easy, but I want to understand all the circumstances. Too much settings is generally a bad practice.

**Comment by van800** [comment]
@oxysoft 
We have several triggers for Refresh
1. Save all (https://github.com/JetBrains/resharper-unity/blob/master/rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/SaveAllTracker.kt)
2. Save document https://github.com/JetBrains/resharper-unity/blob/master/resharper/src/resharper-unity/Rider/UnityRefreshTracker.cs#L92
3. Project model change (like deleting file) https://github.com/JetBrains/resharper-unity/blob/master/resharper/src/resharper-unity/Rider/UnityRefreshTracker.cs#L107

Do you want setting which will affect all this triggers?

**Comment by pbhogan** [comment]
Oh wow, yes please add a setting to completely turn this off in every regard. It should be off by default too... seriously, background compilation before switching back to Unity is just such a waste of time and system resources. I hit save continuously while working and often make breaking changes to code in one file before fixing it in another file... 99% of compilation would be wasted. I basically only switch back to Unity once in a while when I actually finish some unit of work, expect compilation to succeed and I want to do a test run. In fact, a lot of the time I'll just test building right in Rider to catch errors if that's all I'm checking, so that is what I want my CPU spending time on, not unnecessary things in the background.

If anything, add a "Build in Unity" button to the IDE that brings in any compilation errors back to the IDE. But automatic background compilation in Unity... thanks but no thanks.

**Comment by van800** [comment]
@pbhogan We already have the manual Action for that.
![image](https://user-images.githubusercontent.com/1482681/37982202-3a9bd62e-31f0-11e8-87b1-2a8c42041dfa.png)

**Comment by van800** [comment]
For now Automatic Refresh doesn't fire in Play mode and doesn't fire if AutoRefresh is disabled in Unity.

**Comment by pbhogan** [comment]
Ah good to know.

> For now Automatic Refresh doesn't fire in Play mode and doesn't fire if AutoRefresh is disabled in Unity.

How does this address the issue, or am I misunderstanding? We want AutoRefresh when switching back to Unity, just not automatically triggered by Rider.

**Comment by van800** [comment]
It doesn't. It was just an info.

**Comment by TheMinefighter** [comment]
I love auto refresh so please keep that

**Comment by van800** [comment]
Fix is public in the nightly #181.4379.683
![image](https://user-images.githubusercontent.com/1482681/38410946-3afed1fa-3986-11e8-9f02-edbd883c52df.png)

**Comment by Deepscorn** [comment]
>> I love auto refresh so please keep that
I love too. Besides, we disabled recompilation when in play mode with this script:
https://gist.github.com/Deepscorn/cf74f4a712ea17c86d26f6ea536ed7e9

**Comment by citizenmatt** [comment]
Current behaviour is that Rider will auto refresh by default, in the background, but not during Play mode. Rider’s auto refresh can be disabled in Rider’s settings, but this doesn’t affect Unity’s own auto refresh setting - Unity will still refresh when you switch to the editor.

**Comment by oxysoft** [comment]
This option (Automatically refresh Assets in Unity) is now broken in the latest EAP! It's always enabled even if it's not checked in the options.
