### ISSUE TITLE
Soft wrap setting in the Unity log window stacktrace is re-enabled at seemingly random, even though the toggle button is off

### ISSUE THREAD

**Issue by oxysoft** [JetBrains/resharper-unity#479]
![](https://i.imgur.com/lqjMb92.png)

Enabling soft wrap and then re-disabling it fixes it, but the setting seems to be discarded at seemingly random, or at certain moments which I haven't been able to isolate. As you can see in the picture, soft-wrap is disabled but it is still enabled in the stacktrace.

I will add further information if I'm able to isolate when exactly it reverts back.

**Comment by van800** [comment]
reproduced

**Comment by van800** [comment]
Will become available in couple of days in nightly builds. Thanks for reporting!
