### ISSUE TITLE
Refactor asset post processors for project generation

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#483]
We should look at older versions of Unity and see if we can use these methods for project and solution generation - we can return strings and have Unity only update if the files are actually different. Prevents multiple reading/writing if there are more post processors installed:

[`OnGeneratedSlnSolution` callback](https://github.com/Unity-Technologies/UnityCsReference/blob/ad97c800c25267281e7d2aba03413811c4ea489f/Editor/Mono/AssetPostprocessor.cs#L59).

[`OnGeneratedCSProject` callback](https://github.com/Unity-Technologies/UnityCsReference/blob/ad97c800c25267281e7d2aba03413811c4ea489f/Editor/Mono/AssetPostprocessor.cs#L74-L86).

**Comment by van800** [comment]
This two are new sinse 2018.10b8
See internal [slack thread](https://jetbrains.slack.com/archives/G4EUFJYDB/p1520842266000301?thread_ts=1518605941.000013&cid=G4EUFJYDB) 
I would avoid using them, since we target old Unity versions and we try to target only non-secret API.
