### ISSUE TITLE
Add extra post processor event functions

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#484]
Now that the Unity source is available for reference, some more `AssetProcessor` event functions are visible:

* [`OnGeneratedCSProject`](https://github.com/Unity-Technologies/UnityCsReference/blob/ad97c800c25267281e7d2aba03413811c4ea489f/Editor/Mono/AssetPostprocessor.cs#L74-L86)
* [`OnGeneratedSlnSolution`](https://github.com/Unity-Technologies/UnityCsReference/blob/ad97c800c25267281e7d2aba03413811c4ea489f/Editor/Mono/AssetPostprocessor.cs#L59-L71)

**Comment by citizenmatt** [comment]
In fact, do a search for `Type.GetMethod` and see if there are any other undocumented methods.

Will also need to check supported versions.

**Comment by van800** [comment]
fixed with https://github.com/JetBrains/resharper-unity/commit/96e8f13f5bcdc95a8c8e581e62dcff0cd02327c7
