### ISSUE TITLE
Extension does not work with visual studio "15" preview 4

### ISSUE THREAD

**Issue by BioTiNe** [JetBrains/resharper-unity#49]
The extension does not work when using visual studio "15" preview 4 with visual studio vnext tools package :(

**Comment by citizenmatt** [comment]
What version of ReSharper are you using? And what do you mean by "not working"?

**Comment by BioTiNe** [comment]
I'm using Resharper 2016.2.2, and by not working I mean that methods and fields used implicty by unity are marked as not used , code completition for Invoke is not working, etc.

**Comment by citizenmatt** [comment]
OK, can you confirm that you're running 1.3 of the plugin (you can check this in the Extension Manager) and that the project is also a Unity project - if you open the .csproj file in notepad, you'll see a `ProjectTypeGuids` element that contains `{E097FAD1-6243-4DAD-9C02-E9B9EFC3FFC1}`.

**Comment by BioTiNe** [comment]
Yes, I'm running 1.3 and the ProjectTypeGuids contains E097FAD1-6243-4DAD-9C02-E9B9EFC3FFC1

**Comment by citizenmatt** [comment]
This should hopefully be fixed with the latest version of the plugin for ReSharper 2016.3, which itself has better support for VS2017. Please reopen if it's not working.
