### ISSUE TITLE
Incremental compiler alpha triggers rebuild on any code change

### ISSUE THREAD

**Issue by JayPavlina** [JetBrains/resharper-unity#490]
Unity released an [alpha for its incremental compiler](https://forum.unity.com/threads/unity-incremental-c-compiler.523993/). It mostly works, but every time I change something, Rider starts reanalyzing the whole project. Rider also doesn't seem to detect C# 7.2 support.

Just wanted to make you aware of this in case its something you want to work on supporting.

**Comment by citizenmatt** [comment]
I think in order to get 7.2 support, you need to make sure that you've got .net 4 selected in Unity. Do you have a repro project we can take a look at to see about the reanalysing? Also, what kind of analysis is it doing - indexing or the full solution wide analysis?

**Comment by JayPavlina** [comment]
I have .net 4.x selected. Somebody in the thread [mentioned the same thing happening](https://forum.unity.com/threads/unity-incremental-c-compiler.523993/page-2#post-3445052) with the reanalysis. It's reanalyzing the whole solution. You can probably test with any project.

**Comment by SugoiDev** [comment]
Also noticed that issue on my side.

I'm grateful that rider doesn't block the UI and close my files randomly when it reloads the projects/re-analyze the solution, like VS. This is actually what drove me away from VS in the first place.

But having the analyzer resetting on every tiny recompile isn't ideal.

The incremental compiler creates one .rsp for each project. Maybe Rider will be able to tap to that and prevent full reloads of the projects. Instead, it can update the projects model internally using the data from those response files.

**Comment by citizenmatt** [comment]
It would be great if anyone has a test project ready to go, otherwise this will have to wait until I have chance to take a look at that page and create a new project.

**Comment by SugoiDev** [comment]
If @JayPavlina doesn't have one, I will attach one later.

**Comment by citizenmatt** [comment]
Great, thanks!

**Comment by van800** [comment]
@JayPavlina Are you on Windows? Do you have dotnet 4.7.1 installed? Please check if you have it in
`C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework`

**Comment by van800** [comment]
I have fixed potential problem with rewriting LangVersion multiple times, but I am not completely sure that it was the case. I guess it will become public in nightly builds in couple of days.

But It would be still good to have a repro solution + video-recording of the problem.
@JayPavlina @SugoiDev

**Comment by SugoiDev** [comment]
With the incremental compiler, setting the language version should become unnecessary, since the compiler is already doing them.

The incremental compiler also adds the defines `CSHARP_7_OR_LATER` and (for now) `CSHARP_7_2`

---

With the latest incremnetal compiler, I've stopped seeing Rider doing a full solution analysis, so I think this issue is probably solved, at least on Windows.

---

For reference, the latest incremental compiler build is attached here. The csproj processing is done in the `UnityEditor.Compilation.RoslyCSProjectAssetPostProcessor` class, in the `Unity.PureCSharpTests.dll` assembly (internally named `Unity.PureCSharpTests.dll`).

[com.unity.incrementalcompiler@0.0.32.zip](https://github.com/JetBrains/resharper-unity/files/1885159/com.unity.incrementalcompiler.0.0.32.zip)

**Comment by van800** [comment]
Thanks, I am in progress of investigation.
https://forum.unity.com/threads/unity-incremental-c-compiler.523993/page-2#post-3452943

**Comment by SugoiDev** [comment]
Ah, I just replied to you on the forums, didn't notice the username!

**Comment by van800** [comment]
Unfortunately I can't reproduce full re-analysis. I tried on Mac. The only problem so far is LangVersion, which is written by Unity multiple times. First it is 6 and then 7.2. But since I can't see the problem, I am not sure.
I see progress, when I save file in Rider, but I see the same in Unity 2017.3.1. It is not specific to roslyn compiler.

**Comment by JayPavlina** [comment]
That makes sense that Lang version was changing because I thought C# 7 was working and then it stopped working. I can try the new version and let you know. Do I just wait a few days?

**Comment by van800** [comment]
I will follow up here, when build with fix is out, thanks!

**Comment by van800** [comment]
@JayPavlina nightly build is out. Available via https://www.jetbrains.com/toolbox/app/
Please follow up, whether it helped or not. Thanks!

**Comment by JayPavlina** [comment]
The problem is still occurring. I made a gif.

![incremental compiler problems](https://user-images.githubusercontent.com/8941771/38522551-8f5c6d36-3c0e-11e8-9f33-7821a0347c01.gif)

**Comment by van800** [comment]
What do you have in manifest.json?
I have:
{
  "dependencies": {
    "com.unity.incrementalcompiler": "0.0.32"
  },
  "registry": "https://staging-packages.unity.com"
}

Please attach also couple of logs from $TMPDIR/Unity3dRider.

**Comment by JayPavlina** [comment]
manifest.json is the same, but I was on version 0.0.30. I updated to 0.0.32 but still experience the same issue. I also updated to Rider 181.4379.923 and problem still occurs.

I would send you the log but not sure how to find it.

**Comment by van800** [comment]
Ah, sorry, I forgot to mention that.
1. Enable logs in Unity->Preferences->Rider->LoggingLevel=Trace
![image](https://user-images.githubusercontent.com/1482681/38538064-6aa409fc-3c92-11e8-9e14-6b4d93a478cd.png)
2. Reproduce the issue.
3. In terminal write without quotes: "open /$TMPDIR/Unity3dRider/"

**Comment by van800** [comment]
I see, I am glad you found it.
Here in Unity Rider settings, you need to select which Rider do you want to use.
![image](https://user-images.githubusercontent.com/1482681/38542787-15b85040-3ca3-11e8-9d8a-9ae1777a6732.png)
RD-181.x are builds 2018.1.x
Unity3dRider.cs was added by Rider 2017.x
Rider 2018.1.x has logic to detect and remove the old plugin, however Rider 2017.x doesn't know about the new dll plugin.

**Comment by van800** [comment]
Please reopen or just comment on this issue, if something related is still not working for you.

**Comment by RDeluxe** [comment]
Not quite sure if it's the same problem, but I'm also using the incremental compiler beta and rider seems to re-analyze my projet a lot.

I'm not 100% sure Rider launches an full analyze after each rebuild, but it's sure is common and pretty annoying.

**Comment by van800** [comment]
@RDeluxe Does it reproduce on nightly builds?
These are distributed via https://www.jetbrains.com/toolbox/app/
