### ISSUE TITLE
Disable forcing C# 5 for Unity 5.5

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#50]
The extension sets ReSharper's C# language level to C# 5, as existing versions of Unity don't support C# 6. Unity 5.5 will [target .net 4.6 and use the C# 6 compiler](https://forum.unity3d.com/threads/upgraded-mono-net-in-editor-on-5-5-0b4.433541/), so we shouldn't change language level in this case.
- How do we decide this? Based on version of unity assemblies?
- The article describes changing the target to .net 4.6 - is there a flag in the project file for this?
- Should we still set it for older Unity versions?

**Comment by cmcpasserby** [comment]
A thing to keep in mind with this, is how the equality operator is overridden in Unity for Components and GameObjects.

This
```
Destroy(go);
if (go != null) {
    go.DoThatThing();
}
```
and
```
Destroy(go);
go?.DoThatThing();
```
will result in different outcomes, since in the first example the operator overload for equality will be taken into consideration and it will return null. But in case number 2 it won't be null till the GC kicks in and you will be attempting to make a call to a object that is dead on the C++ side of things.

**Comment by citizenmatt** [comment]
Yeah. Related to #35. Do you know if this is being addressed as part of the .net 4.6 upgrade?

**Comment by cmcpasserby** [comment]
Yes same issue as https://github.com/JetBrains/resharper-unity/issues/35 you can get more info as to why here https://blogs.unity3d.com/2014/05/16/custom-operator-should-we-keep-it/

**Comment by van800** [comment]
I have got a request about C# 6 
https://github.com/JetBrains/Unity3dRider/issues/9
It says that even prior to Unity 5.5 people may want C# 6, if they use a plugin https://bitbucket.org/alexzzzz/unity-c-5.0-and-6.0-integration/src

**Comment by citizenmatt** [comment]
What would be the best way to do this? Is there a way of automatically checking to know that we should allow C#6 support? We can check for Unity 5.5, but is it also worth looking for the `CSharp60Support` folder? Or just add an options page?

**Comment by van800** [comment]
I am going to check presence of reference to AsyncBridge.*.dll

**Comment by alexzzzz** [comment]
Frankly, I'm not very fond of automatic language version restriction. When Visual Studio Tools for Unity introduced one, I think, it caused more problems with my C# 6 for Unity integration than it solved elsewhere. Maybe I'm biased, but, speaking about version restriction, I would prefer just a global switch a user can turn on or off.

**Comment by citizenmatt** [comment]
The global switch is already there, it just has the wrong default for Unity projects. The plugin just sets the switch to C# 5 for Unity - you can still switch it back to C# 6.

Normally, ReSharper will use either the default language version for Visual Studio (VS2015 == C#6) or whatever is specified in the `LangVersion` element in the .csproj. Unity doesn't set this (or at least it didn't. I need to check again) So this plugin would set ReSharper's override to default to C#5. It can still be [overridden manually](https://www.jetbrains.com/help/resharper/2016.2/ReSharper_by_Language__CSharp.html).

So really, this feature is about changing ReSharper's defaults so that they make more sense for Unity. Everything is still configurable.

**Comment by van800** [comment]
@alexzzzz At least in Rider there were requests, that Rider suggests to change code to C#6, which made it non-compilable in Unity. So now I check the Unity runtime >=4 or presence of UnitySynchronizationContext to allow C#6.

**Comment by citizenmatt** [comment]
OK. Here's my plan for checking the language version:

- If `LangVersion` is in the project file, then do nothing. It's been explicitly set by VSTU, we should honour it. I think the new VSTU for Unity 5.5 will set the correct value here for either the C#5 or C#6 compiler. I've emailed @jbevain to confirm (although I could have just pinged him here 😄)
- If `LangVersion` is not in the project file, check for a `CSharp60Support` folder in the project root. If it exists, override language version to C#6 (we need to do this so we don't start suggesting C# 7.0 stuff!). The [CSharp60Support](https://bitbucket.org/alexzzzz/unity-c-5.0-and-6.0-integration/src) project removes `LangVersion` if it's set.
- If `LangVersion` is not in the project file, and the `CSharp60Support` folder doesn't exist, override language version to C#5.

I think that covers everything, right?

@van800, I think it would also mean that you should remove the code to add `LangVersion` from the Rider plugin.

**Comment by van800** [comment]
@citizenmatt bullet 1 will not work for Rider (no VSTU), so I would keep the code, which sets LangVersion for Rider.

**Comment by citizenmatt** [comment]
Very good point :)

I also didn't realise Unity had its own .csproj generation process, separate from VSTU's. Perhaps we can persuade Unity to add the chosen LangVersion to the templates.

**Comment by alexzzzz** [comment]
> If `LangVersion` is not in the project file, check for a `CSharp60Support` folder in the project root. If it exists, override language version to C#6 (we need to do this so we don't start suggesting C# 7.0 stuff!). 

Could you also check for `CSharp70Support` folder? I have an experimental version of my plugin that supports C# 7. For now it still uses the old `CSharp60Support` folder, but, I guess, it would be logical if I change the folder name to `CSharp70Support`.

**Comment by citizenmatt** [comment]
Yep! That would be great, thanks! (Also happy to look for other marker file, if you want to keep the old name, or change it to something without a version)

**Comment by citizenmatt** [comment]
@alexzzzz Just to confirm, the CSharp60Support plugin doesn't rewrite the .csproj files [if VSTU is installed](https://bitbucket.org/alexzzzz/unity-c-5.0-and-6.0-integration/src/e56c302fe239cf8818c0c02d23519f224a7bc891/CSharp60%20Support%20Solution/CSharp60Support/CSharpProjectPostprocessor.cs?at=default&fileviewer=file-view-default#CSharpProjectPostprocessor.cs-62), right?

And recent versions of VSTU writes the `LangVersion` to the .csproj file, so ReSharper would see a `LangVersion` of 4 (and I don't know why VSTU sets it to 4 and not 5), but we'd be targeting C# 6, right?

**Comment by SugoiDev** [comment]
Might also be interesting to check for the presence of the [IncrementalCompiler](https://github.com/SaladLab/Unity3D.IncrementalCompiler) with `Compiler\IncrementalCompiler.exe`. 

This uses @alexzzzz's compiler so it is C#6 as well. Though it can be configured to use Mono3 (settings live in `Compiler\UniversalCompiler.xml`).

```
<?xml version="1.0" encoding="utf-8"?>
<Settings>

  <!-- 
    Compiler: Type of compiler will be used.
    - Auto : Automatically choose compiler.
             Order: Incremental6, Microsoft6, Mono6, Mono5, Mono3
    - Mono3 : Mono C# 3 Compiler (Unity Default)
    - Mono5 : Mono C# 5 Compiler
    - Mono6 : Mono C# 6 Compiler
    - Microsoft6 : Microsoft C# 6 Compiler
    - Incremental6 : Incremental C# 6 Compiler
  -->
  <Compiler>Microsoft6</Compiler>
  
</Settings>
```

**Comment by citizenmatt** [comment]
Interesting project, thanks! Do you have any idea how popular it is? It states that the project "is at an early development stage", and to be honest, I'd like to reduce the complexity of this situation rather than add more things to support. What would be the absolute best is if Unity (or the various plugins) wrote the correct `LangVersion` into the .csproj files - this way, Rider and ReSharper would work appropriately, and not have to add special cases.

**Comment by alexzzzz** [comment]
@citizenmatt 
* If VSTU is installed, the CSharp60Support plugin doesn't touch .csproj files directly, but uses VSTU's own API to access .csproj content to remove `LangVersion` restriction.
* If VSTU is not installed, the plugin relies on Unity's undocumented `OnGeneratedCSProjectFiles` event to remove the `LangVersion` restriction if it exists for some reason. It reads the newly generated project files, modifies them and writes back to disk.

CSharp60Support plugin pretty much guarantees that there will be no ´LangVersion´ restriction in the project files regardless of presence of VSTU.

> and I don't know why VSTU sets it to 4 and not 5

The Unity's ancient Mono compiler doesn't support C# 5.0. It completely supports C# 3.0 and partially 4.0.

> to be honest, I'd like to reduce the complexity of this situation rather than add more things to support

I feel your pain. This is exactly why I'm not enthusiastic about the automatic language version detection. To me a manual switch seems to be more than enough.

**Comment by SugoiDev** [comment]
@citizenmatt

>Do you have any idea how popular it is?

Probably not very popular, to be honest.

>I'd like to reduce the complexity of this situation rather than add more things to support

Totally fair point. This reinforces @alexzzzz's idea of ditching automatic detection altogether.

**Comment by citizenmatt** [comment]
Brilliant info, thanks.

> The Unity's ancient Mono compiler doesn't support C# 5.0. It completely supports C# 3.0 and partially 4.0.

I don't know why this was set to 5. I guess I'll change it to 4 (5 only added async/await and caller info attributes, so probably why no-one noticed it was wrong). (#60)

The problem with leaving the language version at the default is that ReSharper and Rider suggest changes that won't compile, and we're going to get support requests for that. I'm just trying to make my future life easier :)

**Comment by alexzzzz** [comment]
Is there a way for Rider/Resharper to figure out the language version from the source code? Like, don't suggest C# version X features unless at least one feature of version X is already used.

**Comment by citizenmatt** [comment]
No, unfortunately not - the language version drives the parsing, rather than the other way round.

To be perfectly honest, the best thing would be if `LangVersion` was _always_ specified in the .csproj file. All of this discussion has been about filling in the gaps when it's not specified - and all the tooling that generates the file already knows what it should be!

But this will work - I'm pretty confident I know what the gaps are now. Basically, if it's not specified, it should be C#4, unless we're in Unity 5.5 and the user is targeting .net 4.6. This is the trigger, so we can just look at `TargetFrameworkVersion` (and of course, the `CSharpXXSupport` folders). I'll be pushing a new version shortly.

**Comment by alexzzzz** [comment]
I'm wondering what C# version should it be if both CSharp60Support and CSharp70Support exist. :)

If I modify my CSharpXXSupport so that future versions will set the correct value to `LangVersion` rather than removing it completely, will it help or mess up everything even more?

**Comment by citizenmatt** [comment]
Yep, explicitly setting `LangVersion` would be a good thing. The code treats this value as authoritative, if it's set, and only tries to fill in the gaps if it's missing. If you add it in the future, we'll pick it up automatically, and won't bother looking for any folders.
