### ISSUE TITLE
Add option to disable auto Unity editor refresh

### ISSUE THREAD

**Issue by JayPavlina** [JetBrains/resharper-unity#502]
In one of the recent updates, the plugin started triggering a refresh in the Unity editor when I save in Rider or add new classes. Refreshing the project in Unity causes Rider to slow down. I would prefer to not have this happen automatically, so please make it an option in the plugin settings.

**Comment by JayPavlina** [comment]
Sorry it looks like someone already requested this. #478

**Comment by van800** [comment]
Yes, and the setting is in the latest nightly.
