### ISSUE TITLE
Incremental Compiler - Failed to stop at breakpoint

### ISSUE THREAD

**Issue by optimisez** [JetBrains/resharper-unity#509]
Rider 2018.1 Nightly Build (181.4379.872)
Unity 2018.1b12

Unity Package Manager:
Entities 0.0.11
Incremental Compiler 0.0.32

After I press Debug "Attach to Unity Editor" button at Rider and press play button at Unity, nothing happen. What I expect is it will go to the breakpoint. 

![image](https://user-images.githubusercontent.com/7009368/38547026-bc33248a-3ce0-11e8-963e-2895a28a40b0.png)
![image](https://user-images.githubusercontent.com/7009368/38547036-c1ca90ae-3ce0-11e8-9420-ffe66345e5e3.png)

**Comment by van800** [comment]
Brakepoint is hit fine if we attach after entering Play mode.
But if we Attach and then enter Play mode - it is not hit.

**Comment by Iliya-usov** [comment]
The problem is solved with Incremental Compiler 0.0.34
