### ISSUE TITLE
Feature request: getting color assistance for UnityEngine.Color/Color32

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#51]
Would it be possible to get a similar feature for Unity color types ?

Here is how the original feature works in Resharper:

https://www.jetbrains.com/help/resharper/2016.1/Coding_Assistance__Color_Assistance.html

![](https://www.jetbrains.com/help/img/dotnet/2016.1/Coding_Assistance__Color_Assistance__Colors.png)

![](https://www.jetbrains.com/help/img/dotnet/2016.1/color_completion.png)

Thank you 👍

**Comment by citizenmatt** [comment]
Great idea! What are the normal usages for `UnityEngine.Color`? Just in the editor?

**Comment by aybe** [comment]
I think that the feature should be available for both editor and non-editor projects in the generated solution for Visual Studio :)

**Comment by jizc** [comment]
I would absolutely love this! @citizenmatt `UnityEngine.Color` and `UnityEngine.Color32` are used everywhere. Anything that can have a color.

**Comment by citizenmatt** [comment]
I'm liking this one :smile:

<img width="425" alt="screen shot 2016-11-15 at 10 22 49 pm" src="https://cloud.githubusercontent.com/assets/222659/20327489/375a99ca-ab85-11e6-97f4-b1d9dc8cd0c9.png">

Also works with the colour palette picker quick fix. Will rewrite to a named colour, to a `Color` constructor, or, if the colour is being used in `HSVToRGB`, update it inplace. And the icons for the named colour properties reflect the colour. This is a fun one :)

**Comment by jizc** [comment]
Love it!! So looking forward to this update ❤️ Would it be possible to get support for `UnityEngine.Color32` as well?

**Comment by citizenmatt** [comment]
Yeah, I forgot about `Color32`. It's there now :)

<img width="345" alt="screen shot 2016-11-16 at 12 47 05 am" src="https://cloud.githubusercontent.com/assets/222659/20330392/6d3464d4-ab96-11e6-8224-5686f70c8343.png">

**Comment by jizc** [comment]
Fantastic!

**Comment by aybe** [comment]
Thank you !! 👍

**Comment by aybe** [comment]
@citizenmatt 

When values are outside it fails to render:

![devenv_2020-04-23_19-58-07](https://user-images.githubusercontent.com/1537591/80132971-c97c9980-859c-11ea-9c4b-2452ce1e38fa.png)

But Unity seems to handle this, second color is still magenta in game.

Maybe render color anyway in IDE and/or issue a warning ?

**Comment by citizenmatt** [comment]
Good call. I've added a new issue to track. Will need to figure out if it's got something to do with HDR (and whatever that would mean), or if the values are just clamped to a maxmium.

**Comment by aybe** [comment]
Great 💯
