### ISSUE TITLE
Rider 2018.1 does not automatically remove Unity3DRider.cs 

### ISSUE THREAD

**Issue by optimisez** [JetBrains/resharper-unity#514]
The Unity3DRider.cs inside Rider plugin still using .Net 4.6 instead of .Net 4.6.1 and make it throw error as the generated project file by Unity is using .Net 4.6.1.

**Comment by van800** [comment]
Are you still using Rider 2017.x?

**Comment by optimisez** [comment]
Nope. Latest 2018.1 Nightly Build.

**Comment by van800** [comment]
There should not be Unity3dRider.cs in 2018.1. There must be JetBrains.Rider.Unity.Editor.Plugin.Repacked.dll instead.

we expect the following workflow
1. Anyhow open your solution in Rider 2018.1
2. It should remove the old Unity3dRider.cs and add new dll plugin instead.
3. Either delete old Rider build or change Unity-Settings-Rider to use new Rider build.
![image](https://user-images.githubusercontent.com/1482681/38598583-4076dfa8-3d5d-11e8-9cbe-d0eae8a96634.png)

Please follow up here why it didn't work automatically as described.
Check that you have "Install or Update Rider plugin automatically" checkbox set in Rider Settings.
![image](https://user-images.githubusercontent.com/1482681/38598731-de6ee598-3d5d-11e8-92a1-526d7bd17b41.png)

**Comment by optimisez** [comment]
I have all the settings u mention. Seems like it does not automatically remove Unity3DRider.cs automatically after using latest 2018.1 version. I will just remove manually.

**Comment by van800** [comment]
on it
