### ISSUE TITLE
unity add class library project then be clear empty

### ISSUE THREAD

**Issue by xfilson** [JetBrains/resharper-unity#517]
unity5.6.4f1
rider-eap 2018.1
step1:  open .cs file by rider
step2: ride add exist project 
step3: switch to unity editor, add one new .cs file or delete one .cs file.
step4: switch to rider. you can see the project added in step2 will be removed

why like this?
who can help? thanks

**Comment by van800** [comment]
It is normal behavior for Unity. Unity generates sln and csproj files
automatically and refreshes them on any change.

https://stackoverflow.com/questions/45354848/adding-external-project-to-unity-solution
