### ISSUE TITLE
Add option to disable Refresh on focusing Unity during Play mode

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#520]
Track Play mode and call EditorApplication.LockReloadAssemblies on entering it
EditorApplication.UnLockReloadAssemblies on exiting it.

Will this be a helpful feature?
Given that it is already supported by https://assetstore.unity.com/packages/tools/utilities/console-enhanced-free-42381
Should we add it too?

**Comment by van800** [comment]
related https://capeguy.co.uk/2015/06/no-more-unity-hot-reload/

**Comment by lifangjie** [comment]
yes, i think it is a good idea.

**Comment by Nezz** [comment]
We are using Console Enhanced at my company and some have experimented with that feature but it was rather unreliable. Unity just stopped compiling at some point no matter what. This was about a year ago though, so things might have improved.

**Comment by van800** [comment]
fixed with https://github.com/JetBrains/resharper-unity/pull/615
