### ISSUE TITLE
The type 'AnalyticsResult' is defined in an assembly that is not referenced. You must add a reference to assembly 'UnityEngine.UnityAnalyticsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by dozd** [JetBrains/resharper-unity#523]
Hello,

Not sure if it's problem in the Rider or in the unity itself, but I've tried using Unity analytics (unity version 2017.4.0f1) in Rider (2017.3 as well as EAP 2018.1):

```
UnityEngine.Analytics.AnalyticsResult r = UnityEngine.Analytics.AnalyticsEvent.LevelStart("level");
```

And getting following error: 
```
The type 'AnalyticsResult' is defined in an assembly that is not referenced. You must add a reference to assembly 'UnityEngine.UnityAnalyticsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

When I try manually add UnityEngine.UnityAnalyticsModule.dll into references I'm getting:
```
The type 'AnalyticsResult' exists in both 'UnityEngine.UnityAnalyticsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
```

**Comment by van800** [comment]
Related to https://issuetracker.unity3d.com/issues/vscode-unityanalyticsmodule-reference-not-added-to-csproj-in-2017-dot-3
We can hardly workaround this in Rider.

**Comment by dozd** [comment]
Yeah, that's issue I visited & voted today. But I'm not sure if it's the solution. Why you need `UnityAnalyticsModule` when it's not needed? Because when I add it manually (workaround for mentioned issue) there is error `AnalyticsResult` is already defined somewhere else.

So first you need reference for definition but then there are two definitions. Build is failing but when I alt+tab to Unity, it builds scripts OK and everything is running. Not CTRL+F9 in Rider.

**Comment by van800** [comment]
I haven't yet looked on it yet. In the meantime you may try to Build the Solution in Rider (or by plain MSBuild) and see if Build errors are similar.

**Comment by dozd** [comment]
I still don't get why it complaints about missing `AnalyticsResult` when it's defined in `UnityEngine.dll` (which is already in the csproj).

**Comment by van800** [comment]
In UnityEngine.dll there is AnalyticsResult, but there is no UnityEngine.Analytics.AnalyticsEvent.
Here is a screenshot from JetBrains dotPeek:
![image](https://user-images.githubusercontent.com/1482681/38868500-7b559aee-4247-11e8-96b6-647670aac517.png)

**Comment by dozd** [comment]
Ok. Thanks for the help. It seems like a problem on the Unity side.

**Comment by dozd** [comment]
@van800 I've tried to build the project in Visual Studio and build is working there fine so I'm not sure (again) if the problem is on the Unity side. Maybe Rider itself? Should I create issue there?

**Comment by dozd** [comment]
Hm, after switching back to Rider, build is working there as well... I'm not experienced in the c# / unity project definition and building process but it's working now, so I'm probably good. Don't know how it could be solved by switching to visual studio for one CTRL+F9 build.

**Comment by van800** [comment]
In Unity 2017.x VS is generating csproj on its own. In 2018.x they are switching back to csproj generated by Unity itself. So you may try to rename csproj-s, use VS as external editor and compare new csproj with renamed one.

**Comment by van800** [comment]
Sorry for delay.
I think we have hot-fixed this at our side.
Fix is available in the recent nightly build.
Here are instructions how to get nightly build https://rider-support.jetbrains.com/hc/en-us/articles/360000009804-How-to-get-Rider-Nightly-build-

Issue is related to https://github.com/JetBrains/resharper-unity/issues/562 and https://youtrack.jetbrains.com/issue/RIDER-15934
