### ISSUE TITLE
Extension not working with Managed dll

### ISSUE THREAD

**Issue by TheDelhiDuck** [JetBrains/resharper-unity#53]
I have Unity Support extension 1.3.0 installed. The extensions seem to work when editing the the main unity project within the solution. I also have a project for a managed dll which sits along side the unity project. The project for the managed dll references the unity engine dlls but doesn't appear to be using the Unity Support extension. eg when viewing the code for my MonoBehaviour in the extension dll project I still get unused method warnings.

**Comment by citizenmatt** [comment]
Yeah. The plugin looks for the unity "project flavour" guid in the .csproj file, and only activates if that's there. Does Unity pick up MonoBehaviour objects in other projects, then? It would be fairly straightforward to change to look at references.

**Comment by TheDelhiDuck** [comment]
Excellent thank you. I just copied the <ProjectTypeGuids> tag from my unity .csproj to the one for my managed dll and the extension now works for that project.

**Comment by TheDelhiDuck** [comment]
Actually that left my project in a strange state, I couldn't edit project properties or add new references, for example. So there's a little more to it I guess.

**Comment by citizenmatt** [comment]
Yep, your edit is correct - this is a "feature" of the unity tools for VS.
