### ISSUE TITLE
Add ability to run unit tests NOT via Unity Test Runner

### ISSUE THREAD

**Issue by Caritas** [JetBrains/resharper-unity#530]
We have pretty big project n Unity with active use of asmdefs and nearly 150 unit tests in it - all of them are running nice and smooth in Rider 2017.3  in just few seconds. Problem is that Unity Test Runner hangs on trying to handle them - Unity freezes for a few minutes, and then running all tests also takes few minutes (up to 10).  And now we are forced to used that mechanism in Rider 2018.1! The only way we found to avoid running Test Runner is to close Unity completely before running tests. For us, it is major problem forcing us to downgrade to Rider 2017.3 to be able to run all tests again.

1) The greatest solution for this problem would be just add one checkbox in settings to avoid running tests from solution via Test Runner

2) May be, there are some workarounds to achieve this without waiting next plugin\Rider release?

**Comment by van800** [comment]
@Caritas Thank you for your feedback. 
We removed the workaround which allowed tests to run in 2017.3 because of such requests
https://youtrack.jetbrains.com/issue/RIDER-14825
We have an idea of a fix for both problems, stay synced.

**Comment by citizenmatt** [comment]
Rider has a drop down to select whether or not to run tests via Unity or via NUnit. I'm going to close this as a workable solution, but we'll be looking to improve testing over the next few releases.

**Comment by van800** [comment]
This is still an issue, because default NUnit strategy doesn't fit to project with reference to Unity custom-made nunit-framework.dll. We need new one with some workaround. Yes, drop-down is there, but tests are inconclusive.

**Comment by van800** [comment]
Temporary workaround (which changes reference in csproj) can be found in zip attached to this request https://youtrack.jetbrains.com/issue/RIDER-18961

**Comment by van800** [comment]
Fixed in Re# unit-test-runner, so this will work in both Re# and Rider starting with version 2018.3

**Comment by van800** [comment]
Works in Rider 2018.3 EAP1, however doesn't work on Mac https://youtrack.jetbrains.com/issue/RIDER-20514

**Comment by van800** [comment]
Fix for Mac will appear in 2018.3 EAP3
