### ISSUE TITLE
Feature request: Add [FormerlySerializedAs($fieldName$)] attribute when using Refactor-Rename on serialized fields

### ISSUE THREAD

**Issue by sindrijo** [JetBrains/resharper-unity#54]
Renaming serialized fields in Unity can result in loss of data/serialized references if they are not marked with a FormerlySerializedAs attribute to denote their previous names. 

Ideally ReSharper should add it when doing a rename refactor, such that renaming both fields below...
![beforerefactor](https://cloud.githubusercontent.com/assets/1384288/19541583/a9dd7a68-9667-11e6-8db2-c34c510baa3e.png)
... would result in something like this:
![afterrefactor](https://cloud.githubusercontent.com/assets/1384288/19541634/09192dba-9668-11e6-9205-0f2657855766.png)

See https://docs.unity3d.com/ScriptReference/SerializeField.html for a list types that are serializable, though it is missing some info: Classes marked with the System.Serializable attribute can also be serialized (provided they contain serializable types)

If renaming a field that already has a FormerlySerializedAs attribute it should append add a new attribute 
FormerlySerializedAs attribute (that is, is should not overwrite the existing one).

**Comment by tac14** [comment]
I need it, I wait

**Comment by CAD97** [comment]
What should be the behavior if I have

```csharp
[FormallySerializedAs("foo")] public string bar;
public string baz;
```

and I refactor `baz` to be called `foo`?

(Additionally, how does Unity handle that case of two conflicting current/former serialize names? Just assume the most recent? If this won't ever cause an issue, the naive solution of just adding `FormerlySerializedAs` will work.)

**Comment by nkAlex** [comment]
I suppose you could try it out and check ;)
Was thinking about it myself, but I am too lazy to test it, so I just keep stuff organized :)

Btw, you can also stack as many `FormallySerializedAs()` attributes on top of a property as you wish, so there is even more opportunities for collisions. Most likely assumption is that Unity just iterates through the field names of a corresponding type until it finds a match. Field order may also play a role.

**Comment by sindrijo** [comment]
Renaming two fields of the same type simultaneously to the others name will "swap" the values
```
    //[SerializeField] private int foo = 100;
    //[SerializeField] private int bar = 50;
    
    // Renaming both fields to each other
    [SerializeField, FormerlySerializedAs("foo")] private int bar;
    [SerializeField, FormerlySerializedAs("bar")] private int foo;
```
Field names take precedence over the `FormerlySerializedAs` attribute, probably because it is faster. The deserializer will only start looking at attributes if it doesn't find a field with a matching name for the value it is deserializing.

@CAD97 the case you describe wouldn't be a problem but I see where you are getting at so did a quick test:

`public class TestFormerlySerialized : MonoBehaviour
{
    //public string foo = "AAA";
    //public string baz = "BBB";

    // Rename foo -> bar
    //[FormerlySerializedAs("foo")]
    //public string bar = "";
    //public string baz = "";

    // Rename baz -> foo
    //[FormerlySerializedAs("foo")] public string bar = "";
    //[FormerlySerializedAs("baz")] public string foo = "";

    // Rename bar -> baz
    //[FormerlySerializedAs("bar"), FormerlySerializedAs("foo")] public string baz = "";
    //[FormerlySerializedAs("baz")] public string foo = "";

    // Rename foo -> bar = Result: Value of baz is deserialized/"copied" into bar, we end up with two fields with the same value
    [FormerlySerializedAs("bar"), FormerlySerializedAs("foo")] public string baz = "";
    [FormerlySerializedAs("foo"), FormerlySerializedAs("baz")] public string bar = "";
}`

Though I think it would be possible to restrict the feature to cases where it won't mess up (it won't mess up if the field is not already marked with the attribute. Though multiple renaming on the same type where the names collide (without going back to unity to serialize between each rename will still be affected by the "swap/copy"-problem.) I don't think it is an issue the plugin should concern itself if it can't do prevent/do anything about it.

**Comment by citizenmatt** [comment]
See also [RIDER-12298](https://youtrack.jetbrains.com/issue/RIDER-12298)

**Comment by citizenmatt** [comment]
What? It's only been open for a little bit more than a year. :)

We'll see if we can look at is as part of the 2018.1 milestone, but to be honest, [it's looking pretty busy already](https://github.com/JetBrains/resharper-unity/milestone/14).

This does look like a feature that is almost exclusively made up of edge cases, though :)

**Comment by Skjalgsm** [comment]
What exactly do you mean by edge cases? There's a lot of comments in this issue that is not actually really related to the feature request. The feature request is really simple though, all you have to do is add the [FormerlySerializedAs("$oldFieldName")] attribute above a field that you have renamed if the field is serializable (meaning that it is a private field with [SerializedField] attribute (or a public field) in a MonoBehaviour.

**Comment by Skjalgsm** [comment]
![rider64_2018-02-15_10-40-08](https://user-images.githubusercontent.com/568589/36256568-ca5219de-1253-11e8-8ea9-d8b79ed1c193.png)
![rider64_2018-02-15_10-40-26](https://user-images.githubusercontent.com/568589/36256569-ca6bbefc-1253-11e8-9374-de1b91f187b8.png)
![rider64_2018-02-15_10-40-36](https://user-images.githubusercontent.com/568589/36256570-ca834eb4-1253-11e8-9661-4f73f69f8217.png)

**Comment by citizenmatt** [comment]
It's a bit of a cheeky comment to be honest, as the mainline case is as you say.

But there are definitely edge cases - e.g. what if you rename the field multiple times in a single code session (between source commits)? If none of the intermediate names made it off your machine, what should we do with them? And there's also the scenario listed above about using the name of a previous field - should we treat a previous name as a conflict and prevent that case? Also, when can we remove these attributes? Does order matter?

It all plays into the question of "are we doing the best thing for the user?" - we want to make sure that we're offering value and not making it quick and easy to shoot yourself in the foot.

**Comment by AngryAnt** [comment]
Just keep appending the attributes - with a quick check to see that your addition would not duplicate an existing one.

The rest of the comments in here are related to understanding the underlying Unity feature.

Making any further assumptions would require inspecting the Unity serialiser of the project you *think* holds all relevant data. In other words a lot of work for something which heavily relies on crossed fingers and a failure state of data loss & hard to debug behaviour.

So, only acting on what you know, all you can do safely is append attributes when you know a rename refactor is happening. And that is plenty.

Everything on the script<->serialiser boundary requires a user aware of what they are doing. Tools here trying too much guesswork are way less than helpful. This requested feature, however, would be.

**Comment by sorencoder** [comment]
Has this feature been added to rider/resharper?

**Comment by van800** [comment]
@sorencoder it is already in Rider 2018.2. And it will get to Re# 2018.2 (https://github.com/JetBrains/resharper-unity/issues/706)
