### ISSUE TITLE
Using the latest nightly with Unity 2018.2.0b2 throws when trying to open a script

### ISSUE THREAD

**Issue by SugoiDev** [JetBrains/resharper-unity#540]
Using the latest nightly (181.4379.1481) with Unity 2018.2.0b2 and trying to open a script will throw:

```
FileNotFoundException: Could not load file or assembly 'JetBrains.Rider.Unity.Editor.Plugin.Repacked, Version=2018.1.0.4661, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
```

I reverted the plugin to the build from 04/21 and it works as expected.
I checked with dependency walker and didn't see anything weird between the three last versions.
I also don't see any commit that could be causing this.

**Comment by van800** [comment]
I can't reproduce on both Win and Mac.
Exception fired in Unity?

**Comment by SugoiDev** [comment]
I got curious and did a full reimport (took a while) and it seems to have fixed the issue.
Maybe something broke on my side during the b1 -> b2 upgrade.
