### ISSUE TITLE
DirectoryNotFoundException: Could not find a part of the path '/home/user/.local/share/JetBrains/Toolbox/apps/Rider'.

### ISSUE THREAD

**Issue by websters-dog** [JetBrains/resharper-unity#544]
I got this error after update Rider to version 2018.1:

> DirectoryNotFoundException: Could not find a part of the path '/home/user/.local/share/JetBrains/Toolbox/apps/Rider'.
System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/io/__error.cs:151)
System.IO.FileSystemEnumerableIterator`1[TSource].HandleError (System.Int32 hr, System.String path) (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/io/filesystemenumerable.cs:564)
System.IO.FileSystemEnumerableIterator`1[TSource].CommonInit () (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/io/filesystemenumerable.cs:296)
System.IO.FileSystemEnumerableIterator`1[TSource]..ctor (System.String path, System.String originalUserPath, System.String searchPattern, System.IO.SearchOption searchOption, System.IO.SearchResultHandler`1[TSource] resultHandler, System.Boolean checkHost) (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/io/filesystemenumerable.cs:264)
System.IO.FileSystemEnumerableFactory.CreateFileNameIterator (System.String path, System.String originalUserPath, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/io/filesystemenumerable.cs:48)
System.IO.Directory.InternalGetFileDirectoryNames (System.String path, System.String userPathOriginal, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/io/directory.cs:836)
System.IO.Directory.InternalGetDirectories (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/io/directory.cs:726)
System.IO.Directory.GetDirectories (System.String path) (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/io/directory.cs:678)
JetBrains.Rider.Unity.Editor.RiderPathLocator.CollectAllRiderPathsLinux () (at <0f48062c15e34c198ff3e3c4b9abe9a9>:0)
JetBrains.Rider.Unity.Editor.RiderPathLocator.GetAllRiderPaths (JetBrains.Rider.Unity.Editor.OperatingSystemFamilyRider operatingSystemFamily) (at <0f48062c15e34c198ff3e3c4b9abe9a9>:0)
JetBrains.Rider.Unity.Editor.RiderPathLocator.GetAllFoundInfos (JetBrains.Rider.Unity.Editor.OperatingSystemFamilyRider operatingSystemFamily) (at <0f48062c15e34c198ff3e3c4b9abe9a9>:0)
JetBrains.Rider.Unity.Editor.RiderPathLocator.GetAllFoundPaths (JetBrains.Rider.Unity.Editor.OperatingSystemFamilyRider operatingSystemFamily) (at <0f48062c15e34c198ff3e3c4b9abe9a9>:0)
JetBrains.Rider.Unity.Editor.PluginEntryPoint..cctor () (at <0f48062c15e34c198ff3e3c4b9abe9a9>:0)
Rethrow as TypeInitializationException: The type initializer for 'JetBrains.Rider.Unity.Editor.PluginEntryPoint' threw an exception.
JetBrains.Rider.Unity.Editor.PluginSettings.ValidateMenuSyncProject () (at <0f48062c15e34c198ff3e3c4b9abe9a9>:0)

I don't use JetBrains Toolbox for Rider installation. And default path for Rider package from distro's repository is "/usr/share/rider/".

**Comment by van800** [comment]
Thanks for the report!
I have fixed the exception. I think it was not affecting functionality though.
Could you please clarify the info about default path from distro. Which Linux do you use?

**Comment by van800** [comment]
In a couple of days fix should appear in nightly builds, which are distributed via https://www.jetbrains.com/toolbox/app/

**Comment by websters-dog** [comment]
Nice, thank you. I use Arch Linux, and installed package from AUR. It's not officially supported repository. Maintainer of Rider package chose path "/usr/share/rider/" and it looks as default approach. If update distributed by toolbox app, is it available for download on Rider web page?

**Comment by z3ntu** [comment]
I see the same error (`DirectoryNotFoundException: Directory '/home/luca/.local/share/JetBrains/Toolbox/apps/Rider' not found.`) and I have Rider installed at `/home/luca/Programs/Binary/JetBrains Rider-2018.1/bin/rider.sh`

**Comment by van800** [comment]
This is already fixed in the nightly builds. Nightly builds are distributed via https://www.jetbrains.com/toolbox/app/

**Comment by van800** [comment]
https://github.com/JetBrains/resharper-unity/issues/561
