### ISSUE TITLE
On namespace change, move file to folder ends up putting the file in Recycle bin.

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#545]
Suppose you have `namespace A`, edit the code to `namespace A.B` then the context menu offers to move the file to that folder it'll create first.

However that fails, the file ends up in Recycle Bin and Visual Studio opens the meta file for obscure reasons.

So basically one has to restore the file from the bin, switch to Unity to pick the changes and switch back to Visual Studio **BUT** the file is still on the old directory.

Plugin 2.1.3.4208
Resharper 2017.3.5
Visual Studio 15.6.5

**Comment by citizenmatt** [comment]
This is actually a bug in ReSharper itself - it happens even if the Unity plugin is not installed. I've raised an issue against ReSharper ([RSRP-471285](https://youtrack.jetbrains.com/issue/RSRP-471285)) so I'm going to close this issue.
