### ISSUE TITLE
Incompatibility with Database plugin

### ISSUE THREAD

**Issue by RDeluxe** [JetBrains/resharper-unity#549]
I have a weird bug since a while. As soon as I enable the Unity plugin, I can't use the native database plugin anymore.

This manifests in several ways : 

* Can't find the database window under `View -> Windows -> Database` anymore
* Using the command palette to launch the database tools results in "Nothing here"
* The keyboard shortcut mapped to the database tool is doing nothing

If I disable the Unity plugin everything works fine. As soon as I enable it and restart, the database windows is going to disappear soon after launch (I'm guessing when the Unity plugin enables).

Rider version 2018.1
Unity 2018.1

To be clear, the tool is still working, but I can't access it easily => 

A quick  and dirty video : https://bit.ly/2HOFOMl

**Comment by citizenmatt** [comment]
We hide some tool windows when we open a Unity project, by design. We want to simplify the interface for Unity developers, and we've made a start with some tool windows - NuGet is one, the Database window is another. If you open a non-Unity project, the Database tooling should be still available. Do you need to use the Database tooling from a Unity project? /cc @kskrygan

**Comment by RDeluxe** [comment]
Hello.

Yes, I do. I'm developing a multiplayer game and being able to have a quick look on my data is paramount.

It makes sense for this to be a default behaviour, however imvho : 

* It should be clearly documented somewhere
* It should be reversible easily

**Comment by RAACosta** [comment]
👍 To this issue. I don't believe it's a good idea to hide/remove IDE functionalities just because it's a Unity project unless it's completely incompatible with the Unity solution.

Please bring it back.

**Comment by marcelschmidt1337** [comment]
I am also using it with a Unity project to look up player data. I thought it got secretly removed, glad I found this ticket here.

**Comment by RDeluxe** [comment]
Same as you @marcelschmidt1337 , it took me some time to debug this. 
As @RAACosta it's definitely not advised to hide such a basic feature.

I would be glad to have a temporary solution, because it seems I can access the tool only after the first reboot after activating the unity plugin.

**Comment by marcelschmidt1337** [comment]
@RDeluxe I've created a new project with an empty solution and there I use the database tool for now. Hope this is fixed soon.

**Comment by RDeluxe** [comment]
I'm actually using DataGrip myself

**Comment by van800** [comment]
Database functionality was fully restored in the last nightly build.
Distributed via https://www.jetbrains.com/toolbox/app/
