### ISSUE TITLE
(Rider) Plugin hides configuration selector

### ISSUE THREAD

**Issue by Chippit** [JetBrains/resharper-unity#554]
Having this plugin hides the default debug/release platform configuration selector from the toolbar.

I understand that this is not useful to most Unity users, but in our projects we have updated the solution files to change symbol defines and referenced assemblies based on various configuration settings, and now it is not (trivially) possible to switch between them.

Is it possible to make the disabling of this configuration selector an option in the plugin's settings?

**Comment by van800** [comment]
relates to https://github.com/JetBrains/resharper-unity/issues/549

**Comment by van800** [comment]
Option for this was added in the last nightly build
Distributed via https://www.jetbrains.com/toolbox/app/

**Comment by tbg10101** [comment]
Sorry to resurrect an old ticket but the platform confutation option is again missing here in 2019. I want to switch to Debug so that Rider uses the DefineConstants in the csproj.

The Release target has no defines so it is hard to use platform-conditional compilation with Rider.

**Comment by van800** [comment]
@tbg10101 
There is a way to restore "Full UI".
![image](https://user-images.githubusercontent.com/1482681/69491664-60cbac80-0e98-11ea-8224-0027f04d5aaf.png)
Let me know, if it worked for you.

**Comment by tbg10101** [comment]
I don't have that option:

![image](https://user-images.githubusercontent.com/1455209/69504483-26422e00-0ef1-11ea-8e4a-3ff3a4b8142b.png)

**Comment by van800** [comment]
Please attach logs from Help-Compress logs and show in Explorer.

**Comment by Chippit** [comment]
I see the confusion, @tbg10101. You're pressing the wrong button. You want the Unity icon to the left of the Refresh Unity Assets.

![Annotation 2019-11-25 102152](https://user-images.githubusercontent.com/870779/69523839-824a9800-0f6d-11ea-8dfe-f1c9f0aaf2d7.jpg)

**Comment by van800** [comment]
Oh man, you are right! Thanks @Chippit
