### ISSUE TITLE
Viewing logs is not available

### ISSUE THREAD

**Issue by Humberd** [JetBrains/resharper-unity#557]
When I clean start Unity with Rider my Debug Configuration seems to be ok
![image](https://user-images.githubusercontent.com/10242142/39933356-08035fc2-5543-11e8-918f-89c7a021b4e5.png)

```c#
public class Player : MonoBehaviour {

    void Update() {
        print("hello");
    }
}
```
Then I play the app.
After that the problem is that I can see only the first Unity log in Rider. The next logs are simply not showing. Also my debug configuration shows error

![image](https://user-images.githubusercontent.com/10242142/39933518-7c5ec56e-5543-11e8-8777-f037565dbfa9.png)

I can detach debug, or stop/play again and the logs are empty.

**Comment by van800** [comment]
Could you please try the most recent nightly build of Rider?
Nightly builds are distributed via https://www.jetbrains.com/toolbox/app/
Thank you!

**Comment by Humberd** [comment]
I don't know why or how, but it somehow started working. It's always like that. I try to fix that for an hour and 2 minutes after complaining about it it fixes itself. Unbelievale
