### ISSUE TITLE
Feature request: Support for source-control when renaming classes

### ISSUE THREAD

**Issue by sindrijo** [JetBrains/resharper-unity#56]
- Unity uses special .meta files for all assets when it used with source control.
- MonoBehaviours and other script types in Unity require the file name to match the class name.
- ReSharper is helpful: 'Refactor-Rename class' has option to rename files

**Not so helpful:** It doesn't know about .meta files. So when a file is renamed outside of the Unity Editor it will detect the change as a delete/add and not a rename/move. (I'm guessing this is more of a Unity Tools for VS/VS issue rather than a ReSharper issue.)

A partial fix for this, which I think will be good enough is to **make sure to also rename the .meta files** as otherwise Unity will generate a new meta file for the "new" script file (with a new GUID).

When that happens all script references to the renamed script file in scenes and on prefabs will become invalid because they still reference the old meta file (GUID) but no script file exists for it anymore...

P.S:
A "total" fix _might be possible_ because Unity exposes an API for interacting with source control but it is probably too much of a hassle to get it to work correctly, maintain it and for it to still be user friendly. Because it would require the plugin to call into the Unity process and wait on a async task to finish which may or may not complete successfully depending on connectivity to source control or the source control state of the file ("added but not pushed", "not checked out" etc.) i.e. a can of worms...

**Comment by citizenmatt** [comment]
Nice feature! Renaming meta files might be possible, I'll need to check. The Unity API sounds like it would be too complex, but do you have any links so I can look it up?

**Comment by sindrijo** [comment]
Here are some links and a short summary:

The **Provider** class in the UnityEditor.VersionControl namespace exposes static methods for doing most of the version control actions, the **Asset** class provides state information about asset files.

- [UnityEditor.VersionControl.Provider](https://docs.unity3d.com/ScriptReference/VersionControl.Provider.html)

- [UnityEditor.VersionControl.Asset](https://docs.unity3d.com/ScriptReference/VersionControl.Asset.html)

- **Provider.enabled**	_Returns true if the version control provider is enabled and a valid Unity Pro License was found._ (Note: I
- **Provider.isActive**	_Returns true if a version control plugin has been selected and configured correctly._

By using  _Provider.GetAssetByPath_ we can check for the existence of a metafile with something like:

```
var potentialMetaAsset = Provider.GetAssetByPath(scriptFilePath + ".meta");
var scriptFileHasMeta = potentialMetaAsset != null && potentialMetaAsset.isMeta;
```

If I remember correctly there is a caveat that the .meta file is not required to be located next to the script file but the cases where it is not is either user error or a bug in Unity-itself.
Then [_Provider.Move_ ](https://docs.unity3d.com/ScriptReference/VersionControl.Provider.Move.html) could be used to do the actual "moving" that is renaming of the file in source control. 

Also do note that while the version control integration in Unity requires a Pro license, Personal Edition (free) users can still use .meta files with external version control.

**Comment by sepharg** [comment]
I´d love to have this as a feature.
A very common thing like renaming / moving scripts around in the folder structure gets so annoying when all references in prefabs and whatnot get lost

**Comment by citizenmatt** [comment]
For the most part, `.meta` files are now renamed/created/deleted. There are a couple of edge cases:

* This only happens if the files live in the `Assets` folder or a sub-folder. Moving an item out of the folder will delete the `.meta` file, but not create a new one.
* The `.meta` file is not renamed if you use the Move To File refactoring to rename the file. This refactoring is really Move Type To File, and it will create a new file, move the type and delete the old file if it's empty. In other words, it's NOT a rename operation - if there is more than one type in the file, it won't be deleted. More practically, it means ReSharper doesn't send "rename" notifications, so it's not possible to accurately treat it as a rename. So, you get a new `.meta` file, and the old `.meta` file is potentially deleted.

**Comment by citizenmatt** [comment]
1.6 has just been released, go get it!
