### ISSUE TITLE
Improve RiderPathLocator on Linux

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#561]
Search  .desktop files in ~/.local/share/applications
These are created by Action create desktop launcher in IDEA products including Rider.

**Comment by van800** [comment]
What is your Unity version?

**Comment by Steverman** [comment]
Unity 2018.1.0f2 
Rider 2018.1 (#RD 181.4379.1191)

**Comment by van800** [comment]
@Steverman 
I don't know the Unity team reasoning, but Unity has concept of "known editor". Known editors can handle sln. And Unity generates/regenerates solution only for that editors.
For Rider the match is something like rider.sh/*Rider*.exe/*Rider*.app
So /usr/bin/rider is not be matched.

**Comment by Steverman** [comment]
@van800 Yes, this is what happens. I have only tested `/usr/bin/rider.exe` and it seems to be working fine.

`/usr/bin/rider` will not generate anything.

**Comment by van800** [comment]
https://github.com/Unity-Technologies/UnityCsReference/blob/master/Editor/Mono/ScriptEditorUtility.cs#L45
