### ISSUE TITLE
Missing CoreModule in 3rd Party DLL

### ISSUE THREAD

**Issue by Jack31081988** [JetBrains/resharper-unity#562]
Hello i have a Issue with the Unity-Plugin.

I have developed my own DLL which is basically a code-base for my various Unity-Projekt.
But with the Update to Rider 2018.1 they wont work anymore.

`public class SomeView : BaseView { ... }`

BaseView is part of my DLL which inherits MonoBehaviour

I'll get a error in Rider 
   **Module 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' should be referenced**

Unity compiles the script just fine.
Also other IDE like VS for mac or monodevelop don't seem to have a problem with the project

I dont't understand whats wrong anymore
UnityEngine.CoreModule is part of the UnityEngine.dll isn't it?
so why is rider having a problem with my DLL?

**Comment by citizenmatt** [comment]
What happens if you try to build in Rider?

**Comment by Jack31081988** [comment]
I cannot build the project with rider anymore due to this..
It says   

**  SomeView.cs(5, 26): [CS0012] The type 'MonoBehaviour' is defined in an assembly that is not referenced. You must add a reference to assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.**

other IDEs and Unity-Editor compile without error

**Comment by van800** [comment]
I guess you have updated Unity? As far as I understand they changed the list of references in csproj.
Instead of referencing Editor/Data/Managed/UnityEngine.dll as it was before
You should reference everything in Editor/Data/Managed/UnityEngine folder including 
UnityEngine/UnityEngine.dll
and UnityEngine/UnityEngine.CoreModule.dll

Let us know how it help.

**Comment by citizenmatt** [comment]
Can you also confirm that it compiles correctly with MonoDevelop, please? And what version of Unity you're using?

Visual Studio's .csproj generation is custom, and will add these references, but we use Unity's own generation with only minor changes, so I would expect to see Rider and MonoDevelop report the same error. If they don't, we'll need to speak to Unity to get guidance on how to best solve this - we can change our generation to also include the module assemblies, but if Unity themselves don't do this, we need to find out why.

**Comment by van800** [comment]
Please discard my previous comment.
Do I understand correct that you can't use your dll in a unity-generated solution? And you use Unity 2018.1.x?
I have made a fix for that yesterday https://youtrack.jetbrains.com/issue/RIDER-15934
But Rider nightly build with fix is not yet ready. Expect it in a couple of days.

Other workaround is to switch back to Unity 2017.x or forward to 2018.2.x
I expect both of them handle this problem just fine.

**Comment by Jack31081988** [comment]
I still use 2017.4.2f installed via UnityHub
 (We don't update our Unity-Version within a project to avoid complication during the development)

for some reason Unity-Hub don't let me add Mono-Develop
I'll get back to you after reninstalling unity with MonoDevelop

**Comment by van800** [comment]
Please try newest Rider build via Toolbox RD-181.4952.153.
Here are instructions how to get nightly build https://rider-support.jetbrains.com/hc/en-us/articles/360000009804-How-to-get-Rider-Nightly-build-
I checked it contains the fix RIDER-15934, which I mentioned.

**Comment by Jack31081988** [comment]
Okay Mono-Develop also does not Build 
But Visual Studio for mac does..

Since this is not a Rider issue, im sorry for wasting your time!
I'll try out the Nightly build! 
Thanks!

**Comment by Jack31081988** [comment]
The Nightly build works!! 
Thank you soo much!!

**Comment by citizenmatt** [comment]
Thanks for checking MonoDevelop + VS Mac. It's reassuring that MD has the same problem, it means we're not breaking anything. I don't know why VS Mac works, though - I didn't think VS Mac modified generated files.

**Comment by citizenmatt** [comment]
Fixed by c1a01c67e67496d24c9d192147d4aad36ccc8686, see also [RIDER-15934](https://youtrack.jetbrains.com/issue/RIDER-15934)

**Comment by citizenmatt** [comment]
We're just trying to get to the bottom of this, and understand it all correctly, so can I ask a few more questions?

* What's the current platform for the Unity project? PC/Mac standalone?
* When you built your own .dll, what Unity assemblies did you reference? Can you give paths, please?

**Comment by Jack31081988** [comment]
Of Course!

Build Target ist Pc/Mac standalone with Traget Platform Linux 

We use and update the assamblies, with each Unity update (currently 2017.4.2f)
Wie put them in a "Lib" folder

Framework/Lib/System.Core.dll
Framework/Lib/UnityEditor.dll
Framework/Lib/UnityEditor.dll.mdb
Framework/Lib/UnityEditor.xml
Framework/Lib/UnityEngine.AnimationModule.dll
Framework/Lib/UnityEngine.AnimationModule.dll.mdb
Framework/Lib/UnityEngine.CoreModule.dll
Framework/Lib/UnityEngine.CoreModule.dll.mdb
Framework/Lib/UnityEngine.dll
Framework/Lib/UnityEngine.dll.mdb
Framework/Lib/UnityEngine.ImageConversionModule.dll
Framework/Lib/UnityEngine.ImageConversionModule.dll.mdb
Framework/Lib/UnityEngine.IMGUIModule.dll
Framework/Lib/UnityEngine.IMGUIModule.dll.mdb
Framework/Lib/UnityEngine.Physics2DModule.dll
Framework/Lib/UnityEngine.Physics2DModule.dll.mdb
Framework/Lib/UnityEngine.PhysicsModule.dll
Framework/Lib/UnityEngine.PhysicsModule.dll.mdb
Framework/Lib/UnityEngine.TextRenderingModule.dll
Framework/Lib/UnityEngine.TextRenderingModule.dll.mdb
Framework/Lib/UnityEngine.UI.dll
Framework/Lib/UnityEngine.UI.dll.mdb
Framework/Lib/UnityEngine.UI.xml
Framework/Lib/UnityEngine.UIModule.dll
Framework/Lib/UnityEngine.UIModule.dll.mdb
Framework/Lib/UnityEngine.xml

hope this helps
