### ISSUE TITLE
cannot resolve symbol 'void' & unable to add System.dll reference

### ISSUE THREAD

**Issue by Draethorian** [JetBrains/resharper-unity#564]
Hi I got this issue again with my newly set up Unity Project.

deleting the System.dll Reference and adding it again plus reloading doesn't work.

letting Unity compile also doesn't solve the issue.

**Comment by van800** [comment]
OS, Unity version, Rider version?

**Comment by van800** [comment]
Check that in Rider full MSBuild is selected. Not a dotnetcore one.
![image](https://user-images.githubusercontent.com/1482681/40143163-fb4a5e54-595a-11e8-8e61-697610acf7a4.png)

**Comment by van800** [comment]
feel free to reopen, if my previous suggestion didn't help
