### ISSUE TITLE
Can't add as an extension

### ISSUE THREAD

**Issue by ericmuyser** [JetBrains/resharper-unity#57]
> Use ReSharper's Extension Manager (ReSharper → Extension Manager), search for "Unity" and install. Restart, and it'll just start working.

I don't see this option. I see an Add that takes the name and URL. Thoughts?

![.](https://i.imgur.com/EI0saua.png)

**Comment by citizenmatt** [comment]
What ReSharper version is this? If it's 2016.3 EAP, then it's not been updated yet - it currently only supports the RTM versions. 2016.3 support will come later in the release cycle.

**Comment by jizc** [comment]
I think you're looking in the wrong place @ericmuyser. It's not in the Options panel.
`ReSharper → Extension Manager` refers to this menu option:
![image](https://cloud.githubusercontent.com/assets/1404846/20328850/4be1cfac-ab95-11e6-9929-9d008191537c.png)
Which will give you this window:
![image](https://cloud.githubusercontent.com/assets/1404846/20328875/6ce26ffe-ab95-11e6-8055-081804edd3a9.png)

**Comment by citizenmatt** [comment]
Closing this as can't repro. Please feel free to reopen or open a new issue.
