### ISSUE TITLE
Add an option to return Nuget toolwindow back for Unity-generated solution

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#571]
Additionally, when toolwindow is hidden, calling anything from menu "Tools->Nuget" fires an exception.

**Comment by citizenmatt** [comment]
Won’t Unity overwrite any changes from nuget?

**Comment by van800** [comment]
According to http://www.what-could-possibly-go-wrong.com/unity-and-nuget/
If you are lucky, it may work. I guess it will not work for all and every nuget package.
But for some of them it may work.
Unity will not overwrite nuget.config and packages.config. It will rewrite csproj, but if packages are installed inside Assets, it will add references to dlls in packages.

**Comment by citizenmatt** [comment]
I love that the site is called "What could possibly go wrong" :)

**Comment by jay-seismic** [comment]
We're using NuGet with Unity by setting the nuget.config to place the packages in the appropriate location in Assets/.  Removing the NuGet window is frustrating as the Rider window was quite convenient and worked well as long as your nuget config was set up.

**Comment by DWishR** [comment]
While Unity and NuGet are not compatible off-the-shelf (which is a whole separate travesty, if you ask me, which you didn't), we use it successfully in our Unity projects. It would be nice to have the ability to force-enable the NuGet window as an advanced option, as it was working just fine before it got disabled.

I would be happy adding a project configuration file to our source control next to the SLN to enable it for all members of the project (I don't know if that functionality is in Rider yet, but we used to do it with DotSettings files for Resharper).

**Comment by doyouevensunbro** [comment]
Yes we use this daily. It's a weird decision to enforce, TBH.

**Comment by RAACosta** [comment]
My +1 here to bring it back. This is the same situation as the Database tools. Please bring it back since some of us can make it work and need it.

**Comment by van800** [comment]
Thank you the information, a setting is already in the works, it should appear in first EAP of Rider 2018.2

**Comment by van800** [comment]
Fixed in 2018.2
![image](https://user-images.githubusercontent.com/1482681/41967931-2fb9f19a-7a03-11e8-8c93-b63099c2630d.png)
