### ISSUE TITLE
Sort System.Collections.Generic above Boo.Lang

### ISSUE THREAD

**Issue by vertxxyz** [JetBrains/resharper-unity#574]
![image](https://user-images.githubusercontent.com/21963717/40632334-22c744f6-6329-11e8-86c3-be6cd4881f73.png)

Generally I'd imagine Generic.List<> should be prioritised, and in this case it's extremely frustrating to always get references to the former.

**Comment by SugoiDev** [comment]
Oh man, that annoyed me too many times.

I though this integration was removing references to Boo, but just read the code again and it seems it doesn't. Now that Boo and UnityScript are deprecated, it would be nice to strip those references out of the generated projects.

**Comment by van800** [comment]
I guess we can't simply strip them, consider if some project has a dll compiled with Boo.Lang reference. 
It might be a solution to check dependencies of all referenced assemblies and if none of them requires Boo.Lang, UnityScript, UnityScript.Lang it is safe to strip them. At least references from Assets and Packages should be checked. Does it sound good?

**Comment by vertxxyz** [comment]
Any solution ya'll think of that gets rid of this particular instance sounds good to me - stripping would be ideal, but the problem for me at least is purely this UI/UX issue.

**Comment by van800** [comment]
Checking ReferencedAssemblies via reflection takes significant time. Looking into alternatives.

**Comment by citizenmatt** [comment]
We can just lower the priority of all completion items coming from the `Boo` namespace. This is an easy fix - they’re still in the list, but less likely to be picked first. I’ll take this.

**Comment by van800** [comment]
@vertxxyz what is your Unity version?

**Comment by van800** [comment]
@citizenmatt if you are taking it, consider all this 3 assemblies {"UnityScript", "UnityScript.Lang", "Boo.Lang"};

**Comment by vertxxyz** [comment]
@van800 currently using 2018.2.0b4
(with the Incremental Compiler)

**Comment by citizenmatt** [comment]
Just putting this on hold for a couple of days, until a bug in Rider's own sorting of completion items is fixed.

**Comment by Baste-RainGames** [comment]
Any chance this will get prioritized? Since Boo.Lang.List<T> offers a very similar API as System.Collection.Generics.List<T>, I keep introducing references to the Boo version by mistake, and not catching it before way later.

**Comment by SugoiDev** [comment]
Yeah, happens every time with me too. I had to get used to force a mental delay to actually read the choices and select the second one instead of the first (default) one.

**Comment by CeleriedAway** [comment]
I did not find any solutions to this problem in Rider. There is a fancy script that uses SyntaxTree.VisualStudio.Unity.Bridge but that is only for visual studio I guess.
Please help with that

**Comment by BluBb-mADe** [comment]
It probably would fix this particular issue but afaict the autocompletion is at least somewhat dependant on user preference but by always involuntary importing boo you push boo to the top of the list. It would probably more helpful to be able to manually influence this dynamic order.

**Comment by kmoth** [comment]
I've been called out on a few PR's recently because I accidentally used `Boo.Lang.List`. I'm looking forward to this fix too.

**Comment by dimmduh** [comment]
I moved dll from unity fodler and removed references from .csproj files in project root, but getting error
and can not compile code
![image](https://user-images.githubusercontent.com/446814/61288986-e2307580-a7fa-11e9-947e-02053da5771b.png)

But good news - in rider no Boo and unityscript anymore, and List import without selection

I guess to fix the error - need to make empty dll for instead original

**Comment by dimmduh** [comment]
It seems find solution, I created fake dll:
replace Boo.Lang.dll in unity folder
"\Unity\2019.1.10f1\Editor\Data\MonoBleedingEdge\lib\mono\unityscript"
with https://mega.nz/#!hY1hEKbR!BxakZKdkz4rMYhuITqEGLLWF3GexMklSowhZKHHL-ls

**Comment by vertxxyz** [comment]
![image](https://user-images.githubusercontent.com/21963717/66371897-5ccef280-e9f0-11e9-86eb-aa237e226487.png)

This should probably be solved in a way that is more automated for the end user still, but it can be solved now at least

**Comment by citizenmatt** [comment]
Yes, see #1252 - you might also want to add `UnityScript.*`. Unfortunately, Rider 2019.2 doesn't allow _merging_ settings for auto import, so the plugin can't automatically set this. Hopefully this will be addressed in Rider 2019.3

**Comment by SchneiderJonathan** [comment]
I'm coming a bit late to the party but I have excactly this problem with ReSharper. 
My first idea was if you could look into the usage amount in the project ? So if you recommend namespaces, you could order them dependant on how many times the namespace is used inside the project. This way you would always suggest the most propable choice for the developer.
