### ISSUE TITLE
"using Boo.Lang.Runtime" non recognized in Rider 2018.1.2

### ISSUE THREAD

**Issue by Rineko** [JetBrains/resharper-unity#588]
![image](https://user-images.githubusercontent.com/23244132/41190013-a12739b4-6bdf-11e8-9f8c-661162e9fbc5.png)

"Cannot resolve symbol "Boo"" after upgrading to 2018.1.2.
This is used in AssetBundleBrowser plugin. Unity 5.6.5p4.

**Comment by van800** [comment]
I think it is something, that Unity generates for us.
What Unity version is used?
Please check the csproj file, if there is a reference to Boo.Lang.

**Comment by Rineko** [comment]
No one "Boo.Lang" in Assembly-CSharp.csproj & Assembly-CSharp-Editor.csproj, but it is present in <projectname>.csproj (generated by Visual Studio).
Also: https://gyazo.com/f892c9caa411309dae18ae823e76067c

**Comment by van800** [comment]
A warning sign indicates the there is something in the csproj, but maybe there is no hint path or the hint path is not correct.
You may 
1. backup csproj with different name
2. Close Unity
3. In Rider manually add reference to Boo.Lang from Unity installation folder (maybe "Editor\Data\Mono\lib\mono\2.0\Boo.Lang.dll")
4. Compare edited csproj with backup with WinMerge or other tool.
Let me know, what you will find out.

Just to clear up a bit.
VS tools for Unity have their own project generation at least for all Unity versions before Unity 2018.2. 
Rider mainly uses Unity generated project with some minor tweaks.

**Comment by van800** [comment]
Sorry to say, it is not that easy. Unity regenerates csproj contents very frequent.

**Comment by Rineko** [comment]
> Unity regenerates csproj contents very frequent.

Yes, same problem after 1 hour

**Comment by van800** [comment]
What do you think about contributing to this plugin?
If I understand correctly, reference is added, but HintPath is missing or wrong.
Check this example and do nearly the same.
https://github.com/JetBrains/resharper-unity/blob/182/unity/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs#L295-L309
If reference is present, add correct HintPath. Use Boo.Lang.dll from Unity installation, instead of `"C:/Program Files (x86)..."`

**Comment by Rineko** [comment]
> If I understand correctly, reference is added, but HintPath is missing or wrong.
No, after csproj regenerate, all Boo.Lang reference was completely erased.
Now I'm trying to use Boo.Lang.dll from Unity installation.

**Comment by Rineko** [comment]
> You may
> 1...

Difference is:
`    <Reference Include="Boo.Lang, Version=2.0.9.5, Culture=neutral, PublicKeyToken=32c39770e9a21a67">
      <HintPath>..\..\..\Program Files\Unity5.6.5p4\Editor\Data\Mono\lib\mono\2.0\Boo.Lang.dll</HintPath>
    </Reference>`

**Comment by van800** [comment]
If reference is not added at all, then something similar to https://github.com/JetBrains/resharper-unity/blob/182/unity/EditorPlugin/AssetPostprocessors/CsprojAssetPostprocessor.cs#L192 should help. I don't think all users would want a reference to Boo.Lang.dll in their projects, so just make your own csprojpostprocessor copy-paste needed code from our CsprojAssetPostprocessor and that would be the solution.

**Comment by Rineko** [comment]
Okay, but how do I use my own csprojpostprocessor instead of your own, which is inside JetBrains.Rider.Unity.Editor.Plugin.Repacked.dll?

**Comment by van800** [comment]
You can have both. In yours change the namespace and put the cs file into Assets/Editor folder.
Unity calls OnGeneratedCSProjectFiles() by reflection.

**Comment by van800** [comment]
Here is an example of separate CsprojAssetPostprocessor.cs
https://gist.github.com/van800/8e0240a4dc67debbc8544d5755c4d406

**Comment by Rineko** [comment]
Sorry for long answer, I create my own csprojpostprocessor and all errors gone.
Thank you!

https://gist.github.com/Rineko/820ae7d46b1db94fbbd5cb5b5f018411

**Comment by van800** [comment]
Great to hear!
