### ISSUE TITLE
Support undocumented OnGeneratedCSProjFiles

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#59]
Any `AssetProcessor.OnGeneratedCSProjFiles` is called after Unity generates files. But it's not documented, and our list of known Unity messages comes from the documentation. This should get included in the list so that we don't mark `OnGeneratedCSProjFiles` as unused.

https://gist.github.com/prime31/35a83fb8ad4eb385ab22

**Comment by van800** [comment]
there are plenty of such methods invoked via reflection in UnityEditor.dll (at least in AssetPostprocessingInternal)

**Comment by citizenmatt** [comment]
Time for a whitelist...
