### ISSUE TITLE
Searching in Solution for name  doesn't look in scene

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#601]
You need to switch to Directory as a workaround. Here is a screenshot of results in Directory. When you search in Solution - occurrences in .scene files are not shown.

![image](https://user-images.githubusercontent.com/1482681/41673319-e457b87c-74bc-11e8-8899-8c32ac6b0e44.png)

**Comment by citizenmatt** [comment]
There's also an "Include non-solution items" checkbox when you have Solution or Project selected.

<img width="716" alt="screen shot 2018-07-03 at 12 14 11 pm" src="https://user-images.githubusercontent.com/222659/42216767-d4f6d266-7eba-11e8-9491-e576a8f88e47.png">
