### ISSUE TITLE
Please make sync moving files in the rider with the unity metafiles

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#61]
This feature is present in the MonoDevelop as separated plugin and in the VS by default.

Scripts linking drops from prefabs after moving files inside rider.

issue moved from https://github.com/JetBrains/Unity3dRider/issues/17

**Comment by citizenmatt** [comment]
Hi @Dukobpa3. Could you provide some more details, please? Is this the same as #56, renaming/moving linked `.meta` files?

**Comment by Dukobpa3** [comment]
I think yes.
The magic is in the guid inside metafile. Linking to gameObject provided by this guid.

You should:
1. Rename both metafile and class to the same name (and move it to the same path if needed)
2. Keep guid and don't change it after moving|renaming classes|interfaces|other_files
3. Maybe something else like fix new path inside metafile, etc. But if you will keep name and guid - then Unity will fix it itself after reimporting this files.

We are using text serialization of metafiles in our projects and it seems like not big deal. But I don't know how it works with binary serialization(which enabled by default).

**Comment by sindrijo** [comment]
_Metafiles_ are always text based (_yaml_),  even when _Asset Serialization_ is set to _Force Binary_

**Comment by citizenmatt** [comment]
See details on #56
