### ISSUE TITLE
Locate in Unity Explorer

### ISSUE THREAD

**Issue by fnuecke** [JetBrains/resharper-unity#614]
A keyboard shortcut analog to "Locate in Solution Explorer" for the Unity Explorer would be great to have.

Alternatively have "Locate in Solution Explorer" work on the currently open explorer instead i.e. actually locate the file in the Unity Explorer if the Unity Explorer is currently the visible one. That might be problematic because this behavior could not be inferred from the keybind's name though, I guess.

**Comment by van800** [comment]
Thanks for the feedback. This is already solved in 2018.2, first public preview builds are expected within a week.

**Comment by fnuecke** [comment]
Sweet, thanks!
