### ISSUE TITLE
Incorrect Comment/Uncomment behavior in CGPROGRAM blocks and .cginc files in Rider

### ISSUE THREAD

**Issue by AmazingThew** [JetBrains/resharper-unity#619]
When editing normal code, Rider's block-comment and line-comment hotkeys (default Ctrl+/ and Ctrl+Shift+/ on Windows) function as toggles, commenting out normal lines and uncommenting lines that are already comments.

However, when editing .shader files, if a line is within a CGPROGRAM block it can only be commented. Pressing Ctrl+/ on a line which is already commented will simply comment the line further, instead of uncommenting it. The block-comment command also exhibits this bug.

(ShaderLab code that is in a .shader file but not inside a CGPROGRAM block behaves as expected)

Additionally, both the line- and block-comment commands cease to have any effect at all when editing a .cginc file.

**Comment by vl4dimir** [comment]
Any news on this? Very annoying bug, I've been working around it for months. I'm doing heavy shader development and have to use VS Code to edit shader files because of this. 😕

**Comment by zeyangl** [comment]
Same here. Please fix. Annoys me to no end. Almost got me switched back to VSCode because of this.

**Comment by CaptainKirby** [comment]
Agreed, this is extremely annoying, compared to VSCode, not great - sadly!

**Comment by DoctorLoop** [comment]
Similar though slight difference on mac - when commenting with cmd-/ causes the whole CGPROGRAM pass is commented out or uncommented rather than just the line.

**Comment by pixelpax** [comment]
This is application breaking, and still an issue in 2021.3.4

Why was it marked closed?
