### ISSUE TITLE
UnityEngine.Debug.Assert is not recognised as an assertion method

### ISSUE THREAD

**Issue by joshuaoconnor** [JetBrains/resharper-unity#62]
The following code raises a warning that `myNewObject` is a `Possible 'System.NullReferenceException'` when attempting to get the Transform component:

`GameObject myNewObject = Instantiate(prefabGO);`
`UnityEngine.Debug.Assert(myNewObject);`
`Transform newTransform = myNewObject.GetComponent<Transform>();`

The suggested quick fix is to assert using `System.Diagnostics.Debug.Assert` even though we're asserting through Unity's assert functions. I think that using the Unity assert methods should count as having checked for `NullReferenceExceptions`.

I think it will just need some extra external annotations for them to be recognised.

**Comment by joshuaoconnor** [comment]
#63 Pull Request added

**Comment by citizenmatt** [comment]
Fixed via #63. Thanks!
