### ISSUE TITLE
Double clicking on Unity console error is not taking to the line or opening Rider at all

### ISSUE THREAD

**Issue by sebas77** [JetBrains/resharper-unity#621]
I zipped all the logs for you, I don't see anything wrong. I am using the unlicensed version of Unity.
[Unity3dRider.zip](https://github.com/JetBrains/resharper-unity/files/2151966/Unity3dRider.zip)

**Comment by van800** [comment]
Hey! Sorry the delayed response. Is it still an issue for you?
Could you please update Rider to either 2018.1.4 release or 2018.2 latest EAP or Nightly build and retry?
Unity license doesn't affect that.
Are you sure that you click message from script within the project, but not some message from dll?
Does double click script in Unity work?

**Comment by sebas77** [comment]
yes this stop to work and fix itself in a totally random fashion. For example, few days ago it suddenly started to work again at home, but yesterday it broke again in office after I updated to the latest EAP

**Comment by van800** [comment]
According to the logs provided Unity callbacks on double click just wasn't fired. It may be interesting to look through UnityEditor.log also. Could you please attach it?

**Comment by van800** [comment]
@sebas77 Please attach UnityEditor.log after reproducing the problem. Thanks!

**Comment by sebas77** [comment]
Sure it's currently working again in office and at home, so I will as soon
as it happens again. You are talking about the unity editor log with
resharper verbose log on right?

**Comment by van800** [comment]
I guess that Unity Editor.log will occasionally give me some idea, why Unity was not firing callbacks on double click. Please reopen this issue if the problem hits you again.
