### ISSUE TITLE
Cannot load Unity project with restricted symbols in project name

### ISSUE THREAD

**Issue by 3DI70R** [JetBrains/resharper-unity#622]
I have unity project, which have apostrophe in its name, because unity doesn't really care about this stuff. But rider do, so if i open this project in rider, project loads incorrectly with MSBuild process error or with infinite "Loading project..." task:
![image](https://user-images.githubusercontent.com/743194/42133304-c4ce2b9c-7d38-11e8-83ec-0f057c3c9d05.png)
Detailed log:
![image](https://user-images.githubusercontent.com/743194/42133480-006f9c14-7d3c-11e8-9457-78b4187c96aa.png)
On the other hand, Visual studio opens this project just fine even with apostrophe.

If i delete apostrophe from project name, and reopen it, it opens correctly.
![image](https://user-images.githubusercontent.com/743194/42133266-47cfc9e8-7d38-11e8-873f-a8f4874167a7.png)

Is there a way to disable restricted symbols in Unity projects, or add notification about them? Because current error message is too unspecific to know exactly what cause for project not loading properly.

I'm using Rider 2018.1.2 and Unity Plugin 2018.1.0.117 by the way.

**Comment by van800** [comment]
I think, this is something to be reported to Unity team.
Btw, for Unity before 2018.2 VSTU has its own project-solution generation.
But they dropped it for newer versions.

**Comment by citizenmatt** [comment]
This does appear to be an issue in Rider, as the project does load correctly in other IDEs. I'm closing this issue in favour of [RIDER-17312](https://youtrack.jetbrains.com/issue/RIDER-17312).
