### ISSUE TITLE
Mark all methods and fields as in use in Unity types

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#625]
The ReSharper engine will now mark any uncalled method (public or private) as unused if it's not used in code. Unity might be using these methods from scenes and whatnot, so avoid false positives by marking all members in a Unity type as being implicitly used.

This is a workaround until we have more details about the scene. See also #32, #263 and #488

**Comment by IvanPashchenko** [comment]
see https://youtrack.jetbrains.com/issue/RIDER-17276
