### ISSUE TITLE
Unity Log is not being formatted in Rider

### ISSUE THREAD

**Issue by SketchWork** [JetBrains/resharper-unity#635]
In Unity you can format your log files which we do.  Rider is ignoring this and displaying the formatting code.  eg:  [13:20:16:951] <color=#7F7F7F><b><i>Some Cool Messasge</i></b></color>

**Comment by van800** [comment]
Side-note about possible implementation:
Should be done with custom ColoredListCellRenderer, with manual parsing tags and building attributes.

**Comment by citizenmatt** [comment]
Do we know the full list of formatting that's available? E.g. is it just `color`? What about bold and italics?

I this a good issue for the `up for grabs` label?

**Comment by IvanPashchenko** [comment]
@citizenmatt 
It's bold, italics, size and color.

Also has sorta-tooltips for material and image rendering, which seem kinda out of reach for us.
https://docs.unity3d.com/Manual/StyledText.html

**Comment by citizenmatt** [comment]
Cool! I vote we also ignore `size`. While a little complicated, is this one that could be `up for grabs`?

**Comment by van800** [comment]
https://youtrack.jetbrains.com/issue/RIDER-26422

**Comment by JurjenBiewenga** [comment]
I'll be willing to give this one a go

**Comment by citizenmatt** [comment]
Go for it! Looks like you'll need to modify [UnityLogPanelEventRenderer](https://github.com/JetBrains/resharper-unity/blob/192/rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelEventRenderer.kt) to parse the text, remove the markup and apply styling to the blocks, using one of:

* `SimpleTextAttributes.REGULAR_ATTRIBUTES`
* `SimpleTextAttributes.REGULAR_BOLD_ATTRIBUTES`
* `SimpleTextAttributes.REGULAR_ITALIC_ATTRIBUTES`

Or create a new instance of `SimpleTextAttributes` with the appropriate style and colours.

**Comment by JurjenBiewenga** [comment]
Yeah I already have something working 😄 
Kotlin is a bit weird though
