### ISSUE TITLE
downloading 4.5 developer pack does not stop asking me to download 4.5 developer pack

### ISSUE THREAD

**Issue by EntranceJew** [JetBrains/resharper-unity#639]
i click this ![](https://i.imgur.com/L6bzLmr.png)

i go here ![](https://i.imgur.com/9l70u77.png)

and downloading and installing and rebooting does not fix the complaints about developer packs and the editor is inoperable because it doesn't understand unity enough by this point to namespace

additionally installing vs2017 doesn't fix it either

![](https://i.imgur.com/SlC7O21.png)

attempting at a later point in time to install the runtime in desperation results in not being able to install the runtime

**Comment by van800** [comment]
Hi! You may either check what target framework version exactly is in the csproj and install it or override target framework version in Unity settings Rider tab.

**Comment by EntranceJew** [comment]
Within Unity I set my target project version to be 4.6 up from 3.5 stable and now Unity will not open as long as Rider is open. Fortunately @citizenmatt has a copy of this cursed project.

Setting it to 4.6 does suppress the warnings, seemingly.

**Comment by EntranceJew** [comment]
As I have noticed, on Rider 2018.1.3 I have not had an issue with the crashing, but on either the EAP or the Nightly the issue with crashing Unity is present.

**Comment by van800** [comment]
Sorry for delayed reply. Is the crash similar to https://github.com/JetBrains/resharper-unity/issues/660?
I am closing this issue, since the initial problem was solved.
Please reopen if the crash is different one. Thanks!
