### ISSUE TITLE
Namespace provider broken?

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#64]
Looks like the namespace provider for `Assets` and `Assets\Scripts` isn't working - code is still being highlighted to be in the `Assets.Scripts` namespace.

**Comment by Squeazer** [comment]
Just a note here, when creating new classes inside of Rider, the correct namespace is set (without `Assets` and `Assets\Scripts`), it seems like only the highlighter is broken.

**Comment by citizenmatt** [comment]
Yeah, the issue is that I identify a Unity project either by project flavour GUIDs in the .csproj, or if that doesn't exist (such as for Rider projects), then by reference. The problem is that the settings are initialised before ReSharper has had a chance to process the references. I just need to reorder things a bit.
