### ISSUE TITLE
Rider 2018.2 : Errors with Assembly Definition Files and Packages folder

### ISSUE THREAD

**Issue by capyvara** [JetBrains/resharper-unity#647]
Rider 2018.2 EAP
Build #RD-182.3458.490

When using any Unity Packages dependencies (such as Unity.Entities) at any .asmdef in your projects, rider shows as "Unknown project reference".

![image](https://user-images.githubusercontent.com/1027847/42718681-80d1b55a-86e1-11e8-9706-635fcb31ef18.png)

May be related to #476 or #629

**Comment by citizenmatt** [comment]
See also [RIDER-17700](https://youtrack.jetbrains.com/issue/RIDER-17700)

**Comment by van800** [comment]
Just mentioning that I see lots of those in https://github.com/Unity-Technologies/ECSJobDemos/tree/master/Samples
