### ISSUE TITLE
Generic Unity event not initialised by Unity

### ISSUE THREAD

**Issue by iBicha** [JetBrains/resharper-unity#648]
Consider:
```
[Serializable]
public class EventEx<T0> : UnityEvent<T0>
{
}
```
And then, a field on a mono behaviour:
```
public EventEx<string> MyEvent;
```

While Raider will tell you `This field is initialised by Unity`, it's actually not, because it's generic (as far as I can tell)

**Comment by citizenmatt** [comment]
Duplicate of #505
