### ISSUE TITLE
Every assembly reload pauses the debugger twice

### ISSUE THREAD

**Issue by SugoiDev** [JetBrains/resharper-unity#664]
If the debugger is attached, any assembly reload will pause it twice.
This is due to the way Unity kills the current domain to load the new one.
It uses the `Environment.FailFast` method that is just a wrapper to throw an exception. This makes the debugger pause twice on every reload.

I tried to set ignores and all but it still pauses.
I have this happening ever since I began using Rider and on all Unity versions since 5.

Recently I found this related bug: [RIDER-16513 FastFail causes exception when debugging Unity](https://youtrack.jetbrains.com/issue/RIDER-16513) so I decided to create this issue.

Is this something you guys can fix on this integration's side?

**Comment by van800** [comment]
I don't think there is something, what can be done from the plugin side.
