### ISSUE TITLE
Opening a script from Unity will open a new Rider window when the debugger is connected and we are in playmode

### ISSUE THREAD

**Issue by SugoiDev** [JetBrains/resharper-unity#667]
Not sure on what version this started happening.
I can confirm it happening on the latest EAP (3944.62).

To reproduce,

* connect the debugger

* enter play mode

* double click a message in the Unity console to open the script in Rider

It will open a new Rider window, instead of using the one already opened.
Also, instead of the new window being opened in the requested file, the current window will, instead, change to that file. The new window opens as if you had just opened Rider (opens with the last session).

**Comment by van800** [comment]
Are both first and second Rider instances of the same version?

**Comment by van800** [comment]
Shorter repro for windows:
1. Start Rider with command-line:
"C:\Users\Ivan.Shakhov\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-1\182.3944.62\bin\rider64.exe" "C:\Work\resharper-unity-main\unity\build\JetBrains.Rider.Unity.Editor.Plugin.Full\JetBrains.Rider.Unity.Editor.Plugin.Full.sln" --line -1 "C:\Work\resharper-unity-main\unity\build\JetBrains.Rider.Unity.Editor.Plugin.Full\Assets\NewBehaviourScript3.cs"
2. Run the same command-line 2nd time.
Expected result: New Rider window should not open. File should be opened in the previously opened solution.

**Comment by van800** [comment]
Duplicates https://youtrack.jetbrains.com/issue/RIDER-17983
