### ISSUE TITLE
Don't mark redundant Unity function if overriding a method in a base class

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#669]
Given a base class that implements a Unity function, e.g. `Update`, and a derived class has an empty method `override void Update()`, do not mark it as redundant - removing this method will cause different run time behaviour.

Consider marking the method name with a warning or even hint - "Empty Unity event function has a performance impact".

**Comment by j-h-a** [comment]
Is there a refactor that could be performed:

Given a base class `Thing : MonoBehaviour` and a derived class `SpecializedThing : Thing`
1. Rename `Thing` to `ThingNoUpdate : MonoBehaviour`
2. Move the `Update` function into a new class `ThingWithUpdate : ThingNoUpdate`
3. If `SpecializedThing` did more than just override `Update` to make it empty, keep it, but without the now-redundant empty `Update`, if not just remove `SpecializedThing` and change references to use `ThingNoUpdate` instead.

Seem viable? Or maybe the hint could suggest a similar approach?

**Comment by citizenmatt** [comment]
See also [RIDER-19894](https://youtrack.jetbrains.com/issue/RIDER-19894). Fixed as part of #794. Released in Rider 2018.3 EAP1
