### ISSUE TITLE
Avoid rewrites sln file

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#671]
Since Unity 2017.4 use OnGeneratedSlnSolution instead.

Changing contents of sln file causes frequent projects reloads
![image 13](https://user-images.githubusercontent.com/1482681/43517204-29dccd60-9588-11e8-8e4f-0b4465fa07b2.png)

**Comment by van800** [comment]
https://youtrack.jetbrains.com/issue/RIDER-18190

**Comment by van800** [comment]
fixed via 68d88f1464e0753bb107c5417df5c5cea48c54e7, already in trunk

**Comment by citizenmatt** [comment]
Was just about to link to that commit :) But I noticed that there was a version check accidentally removed for C# project processing, which means we would have hit the disk more often than we needed to. Fixed in #672
