### ISSUE TITLE
Rider C# Live Template is missing

### ISSUE THREAD

**Issue by IdeoG** [JetBrains/resharper-unity#675]
I'm using latest Rider 2018.1.4, but since 2018.1.3 version i don't have Live Templates for C#.
How to get live templates for C#? 
![image](https://user-images.githubusercontent.com/20797092/43615292-97db1c58-96bf-11e8-85aa-be31abd1ab8f.png)

**Comment by van800** [comment]
Live Templates editor was only added in Rider 2018.2 EAP/Nightly builds.
see https://youtrack.jetbrains.com/issue/RIDER-548

**Comment by IdeoG** [comment]
@van800 
Thanks a lot for information.
I'm waiting for the good feature, that get in PyCharm and Android Studio by default. I suppose, it will be an excellent feature. 
btw, there was a discussion about manual way to add c# template, but i didn't realise where i can download it. 
Could you give me a link for C# custom template?

**Comment by van800** [comment]
This functionality comes with Re# but till 2018.2, there were no UI for it in Rider.
So manual way would probably need to create templates in Re# and then import them in Rider.
I would suggest you to try EAP/Nightly builds of Rider 2018.2.
This would be a lot easier than the manual way.
With https://www.jetbrains.com/toolbox/app/ you may easily have several different versions side-by-side.

**Comment by IdeoG** [comment]
Okay. I'll try it.
