### ISSUE TITLE
OnProjectChange event of Unity's EditorWindow class is recognized as "never used" in last version. It was working fine before.

### ISSUE THREAD

**Issue by XtroTheArctic** [JetBrains/resharper-unity#679]
OnProjectChange event of Unity's EditorWindow class is recognized as "never used" in last version. It was working fine before.

**Comment by citizenmatt** [comment]
I'm not seeing this behaviour - `OnProjectChange` is highlighted as a Unity event function for me in a class that derives from `EditorWindow`. Do you get any Unity based auto-complete for this method? Are other methods such as `OnHierarchyChange` or `Awake` marked as Unity methods, or never used?

**Comment by XtroTheArctic** [comment]
The bug might be about the "static" keyword rule instead of the OnProjectChange event name.

Here is the screenshot. It also warns me about "it can be marked as static" but I can't call the non-static Repaint method if I make the OnProjectChange static.

![adsiz](https://user-images.githubusercontent.com/6631429/43716019-8538c346-9950-11e8-9897-b3c6d9e02698.png)

**Comment by XtroTheArctic** [comment]
This works fine. No warning/error so I guess the static requirement check is bugged. I assume this is related to Resharper; not Unity plugin. Right?

    static void OnProjectChange() => Debug.Log(1);

**Comment by citizenmatt** [comment]
Ugh, yes. Our API list incorrectly lists `OnProjectChange` as static. We parse these details [from the documentation](https://docs.unity3d.com/ScriptReference/EditorWindow.OnProjectChange.html), but the sample code for `EditorApplication.OnProjectChange` is incorrect - it's showing usage of the `EditorApplication.projectWindowChanged` and `EditorApplication.projectChanged` events, and the sample has nothing to do with the `OnProjectChange` message. But it's still picking up that the sample has a `static` modifier.

We can see in the reference source that the [method is invoked](https://github.com/Unity-Technologies/UnityCsReference/blob/8977abdc2e2a797323f537a1b42d0ad50832bebe/Editor/Mono/HostView.cs#L151) via reflection, and it should be an [instance method](https://github.com/Unity-Technologies/UnityCsReference/blob/8977abdc2e2a797323f537a1b42d0ad50832bebe/Editor/Mono/HostView.cs#L191).

**Comment by XtroTheArctic** [comment]
Thank you for confirming. I hope you can release a fixed version soon.

**Comment by IvanPashchenko** [comment]
Fix will be available in the next 2018.2 Nighlty
https://rider-support.jetbrains.com/hc/en-us/articles/360000009804-How-to-get-Rider-Nightly-build-

**Comment by XtroTheArctic** [comment]
I am not using Rider. This fix will be available on Resharper Unity plugin too. Right?

**Comment by citizenmatt** [comment]
Yes, shortly after the release of ReSharper 2018.2. We're developing against Rider and have a CI process set up for it as it is a bundled process, but we're not doing the same with ReSharper, which means we need a bit more time to prepare, test, fix and release for ReSharper.

**Comment by IvanPashchenko** [comment]
Unfortunately, R# Unity plugin only releases after the R# stable gets released (tentatively end of month) because we don't have any infrastructure in place for the coupled R# + unity build.
