### ISSUE TITLE
Unity object lifecycle inspection errors (maybe all resharper unity plugin inspections) aren't detected by solution wide analysis.

### ISSUE THREAD

**Issue by XtroTheArctic** [JetBrains/resharper-unity#680]
Unity object lifecycle inspection errors aren't detected by solution wide analysis.

If I manually open a C# file which contains one of those inspection errors, then it's detected and resharper error count in bottom right corner get updated.

Maybe this is true for all resharper unity plugin inspections. I didn't check all of them.

This bug makes Unity plugin code inspection rules useless so this bug report must be high priority.

Can you please fix this soon?

**Comment by citizenmatt** [comment]
By default, these warnings won't show up in the Solution Wide Error Analysis window - they're configured as warnings, and SWEA only shows errors by default. Have you changed the severity of the warnings to be errors, or have you enabled warnings in the SWEA tool window?

It's possible that changing either of these hasn't re-analysed the files correctly Can you try _File -> Invalidate Caches and Restart_ please? This does mean solution analysis will be run over the entire solution again, but hopefully it means that files will be kept up to date after this.

**Comment by XtroTheArctic** [comment]
I just checked. Other Rehsarper Unity plugin inspections suffer from the same bug too.

See screenshots.

First one: you can see "new MonoBehaviour" error both in code and SWEA.

Second one: As soon as I close the code file, the error is SWEA disappears. Restarting SWEA doesn't bring them back.

![adsiz2](https://user-images.githubusercontent.com/6631429/43716517-5bd50d46-9952-11e8-9864-65bc58254709.png)

![adsiz3](https://user-images.githubusercontent.com/6631429/43716519-5ea72b58-9952-11e8-849e-c326dd78ab41.png)

**Comment by IvanPashchenko** [comment]
@citizenmatt this is because all of our inspections check for `DaemonProcessKind.VISIBLE_DOCUMENT`

**Comment by XtroTheArctic** [comment]
When can I expect a fixed release?

**Comment by XtroTheArctic** [comment]
Any answer about expected release date?

**Comment by IvanPashchenko** [comment]
@XtroTheArctic 2018.2 stable or the next EAP/nightly.

**Comment by XtroTheArctic** [comment]
Ivan. I am asking for an estimated time not a version or build name. If possible. Please.

**Comment by van800** [comment]
Fastest would be Nightly Build tomorrow. Nightly builds are available via https://www.jetbrains.com/toolbox/app/

**Comment by XtroTheArctic** [comment]
Thank you!!

**Comment by IvanPashchenko** [comment]
@XtroTheArctic we're targeting 2018.2 stable for the end of the month, but that's not set in stone.
If you want a fix ASAP, nightly channel would be the fastest, as @van800 said.
