### ISSUE TITLE
Unity object lifecycle inspection errors aren't detected for methods returning Unity object types

### ISSUE THREAD

**Issue by XtroTheArctic** [JetBrains/resharper-unity#681]
Unity object lifecycle inspection errors aren't detected for methods returning Unity object types. They are only detected if you store the returning value to a local variable.

This is NOT detected as Unity object lifecycle inspection error (wrong):

                var Value = transform.GetComponent<RectTransform>()?.rect;

This IS detected as Unity object lifecycle inspection error (correct):

                var RectTransform = Driver.transform.GetComponent<RectTransform>();
                var Value = RectTransform?.rect;

**Comment by citizenmatt** [comment]
Duplicate of #372
