### ISSUE TITLE
Debug Package from Package Manager

### ISSUE THREAD

**Issue by optimisez** [JetBrains/resharper-unity#682]
Currently you are able to see the package at Rider but debugging does not work yet. I hope I can debug package.

**Comment by van800** [comment]
Pllease add some screenshots, steps, which clarifiers the issue, thanks.

**Comment by SugoiDev** [comment]
I debugged a package yesterday, so I think it should be working (at least on the latest nightly).

**Comment by optimisez** [comment]
After more testings, it's working properly now. I'm not sure why it's not working previously. Maybe the problem comes from Unity.
