### ISSUE TITLE
Its not appearing the resharper extension manager

### ISSUE THREAD

**Issue by Woody4618** [JetBrains/resharper-unity#7]
Hey, 
sadly it does not show up the extension manager. 
I am using the newest version of Resharper 9.2 and the bundeled vs Studio version 2015 community. 
I would like to try out the extension. Sounds very helpful. 
Greetings

**Comment by citizenmatt** [comment]
Apologies - the repo was private, and made public to collect ideas for features, so the readme says it's there, but we actually haven't released it yet! I'll get it released ASAP, most likely tomorrow.

**Comment by citizenmatt** [comment]
Fixed! It's there now :)
