### ISSUE TITLE
Release for ReSharper 2018.2

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#706]

**Comment by XtroTheArctic** [comment]
I just updated Resharper and lost the plugin :(

In this kind of business, Resharper is pretty unique. Its version upgrades invalidate all plugins. This is not a common feature of plugin supported software.

I don't wanna downgrade Resharper. :( 
What time can I expect to get the upgraded plugin?

**Comment by XtroTheArctic** [comment]
Please let us know an estimated time.

**Comment by citizenmatt** [comment]
Should be the first half of next week. I’d like to get it finished up ASAP.

**Comment by citizenmatt** [comment]
Apologies for the delay. The 2018.2 release for ReSharper is now available in the Extension Manager.
