### ISSUE TITLE
Review auto-save notification/advice

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#707]
Is the advice still relevant? It's mostly concerned with causing AppDomain reloads while in play mode, and that causing loss of data/state in the running game (stuff is serialised correctly but e.g. static fields aren't correctly reset).

<img width="840" alt="screen shot 2018-08-09 at 3 19 39 pm" src="https://user-images.githubusercontent.com/222659/43904895-bd114696-9be7-11e8-87f4-2a83a9bfed62.png">

<img width="371" alt="screen shot 2018-08-09 at 3 21 00 pm" src="https://user-images.githubusercontent.com/222659/43904944-db5b1afa-9be7-11e8-960e-4dd7a267a8b5.png">

Can we be a bit smarter about this instead? We now have the ability to lock Unity AppDomain reloads when in play mode. Perhaps we should prompt to enable this instead, so our general advice is to have auto-save enabled, without reload, rather than reload, but no auto-save.

And if we do have auto-save disabled, add some advice to use Local History in case of emergencies (perhaps this should be on the System Settings options page - [IDEA-197084](https://youtrack.jetbrains.com/issue/IDEA-197084))

**Comment by julia-vaseva** [comment]
Unfortunately, the local history has only saved content. It is not really helpful when auto-save is disabled.

**Comment by jwvanderbeck** [comment]
Wouldn't auto-save just be bad in general given that even in Editor mode, every autosave would cause Unity to recompile and that may not be desirable.  I've also seen Unity lock up if I make changes, save, make more changes, and save again while Unity is till recompiling from the previous save.  This situation seems more likely to occur with autosaves.

**Comment by van800** [comment]
@jwvanderbeck 
Auto-save in general is a good thing. From the described case I guess you may want to disable Auto-Refresh from Rider.
![image](https://user-images.githubusercontent.com/1482681/44959714-2d97a900-aef3-11e8-929b-c5e44ec83dd1.png)

**Comment by Baste-RainGames** [comment]
Unity 2018.2 introduced a new option in the preferences menu, "Script Changes While Playing". If that is set to either "Recompile after finished playing" or "stop playing and recompile", this warning isn't relevant anymore. If the user has set it to "recompile and continue playing", that means that the user wants that behavior, and Rider shouldn't warn about it.

It seems like new projects defaults to "recompile after finished playing", so Rider's essentially warning about a behavior the user's gone out of their way to get.

**Comment by van800** [comment]
What if we stop suggesting, what we suggest now, and start suggesting "Script Changes While Playing" in Unity for new Unity versions and the same in EditorPlugin for old Unity versions?
https://github.com/JetBrains/resharper-unity/blob/183/unity/EditorPlugin/PluginSettings.cs#L277

**Comment by van800** [comment]
The only technical problem in this case would be reading state of unity setting "Script Changes While Playing". And I would rather show notification in Unity, not Rider, but for now we don't have any notifications there.
