### ISSUE TITLE
Can't debug with android player 

### ISSUE THREAD

**Issue by wangjianpeng** [JetBrains/resharper-unity#71]
When i want to debug android player , i can't find the android player instance in the unity instance list.Even though i set the  android player ip and port , the attach failed.

**Comment by cmcpasserby** [comment]
this is more of  UnityVS issue and not a resharper for unity issue.

**Comment by van800** [comment]
https://youtrack.jetbrains.com/issue/RIDER-2824

**Comment by van800** [comment]
should be fixed in Rider 2018.2 EAP1
