### ISSUE TITLE
Shader highlights for .hlsl files

### ISSUE THREAD

**Issue by candycat1992** [JetBrains/resharper-unity#717]
I'm using Rider 2018.1.4 and there is no highlights for .hlsl files. Any update?

**Comment by van800** [comment]
It is worth to try Rider 2018.2 RC

**Comment by candycat1992** [comment]
Tried the latest Rider 2018.2 EAP and still no highlights for .hlsl files.

**Comment by IvanPashchenko** [comment]
Are there highlights for `.shader` or `.cginc` files? Is Unity plugin enabled? This is very strange behavior.

**Comment by candycat1992** [comment]
Highlights for` .hlsl ` files. We are using Unity 2018 with HRRP and [SRP](https://github.com/Unity-Technologies/ScriptableRenderPipeline) doesn't use `.cginc` files for including shader codes. So, please add support for highlights for `.hlsl` files (the same with shader codes in [Unity PostProcessing Stack](https://github.com/Unity-Technologies/PostProcessing)). Rider is a great tool btw.

**Comment by IvanPashchenko** [comment]
@candycat1992 
Okay, I've found the problem, fix will be available in the 2018.2.2 bugfix release or one of the nightly builds (I'll notify you when it will be available)

**Comment by candycat1992** [comment]
Okay, thanks.
