### ISSUE TITLE
ShaderLab: "Blend factor expected" incorrect/pedantic error

### ISSUE THREAD

**Issue by pvirdone-s8** [JetBrains/resharper-unity#723]
ShaderLab code inspection gives an error when a Blend is set to off in a SubShader. Encountered in code distributed in the Amplify Occlusion plugin.

Here's some code that demonstrates the error when used in Rider 2018.1.4 with Unity 2017.4.1f1. Also reproed with latest Rider EAP.

`
Shader "Unlit/demo"
{
    SubShader {
        Pass {
            Blend 0 Off
        }
    }
}
`

![screen shot 2018-08-20 at 10 49 53 am](https://user-images.githubusercontent.com/26262897/44490897-81151780-a614-11e8-9dca-af81c02816fe.png)

**Comment by IvanPashchenko** [comment]
@citizenmatt NB: this is not a valid syntax according to the Unity docs, you may want to check with Unity people on the updated parser
https://docs.unity3d.com/Manual/SL-Blend.html
