### ISSUE TITLE
UnityEngine.xml not present in Linux Unity distribution causing lack of documentation in Rider

### ISSUE THREAD

**Issue by z3ntu** [JetBrains/resharper-unity#74]
OS is Linux

![spectacle j29071](https://cloud.githubusercontent.com/assets/3768500/20787581/e3c334be-b7ac-11e6-8d02-bc4996f3120d.png)

![spectacle j29135](https://cloud.githubusercontent.com/assets/3768500/20787601/093d268c-b7ad-11e6-957f-c2d7b0d8d309.png)

**Comment by citizenmatt** [comment]
This should come from the standard XML documentation for UnityEngine. Can you verify that your project has UnityEngine.xml sitting next to the UnityEngine.dll that you've got referenced, please?

**Comment by z3ntu** [comment]
Here's the list of files I have installed: https://gist.githubusercontent.com/z3ntu/6caa3d2b12ddfe5ae20d4bee8b271d55/raw/93cdd69fbe272d25f9bd44b15c424f7f964c4383/gistfile1.txt
(pastebin didn't like my huge file)

**Comment by citizenmatt** [comment]
That's a big old list! :)

I don't think project files are generated with a reference into the Unity install folders itself, so could you take a look inside your .csproj file, find where the project is referencing UnityEngine.dll and see if there is a UnityEngine.xml file in the same folder, please?

**Comment by z3ntu** [comment]
Unity is exactly 6,07 GiB :D 

I found that line in several .csproj files (eg Assembly-CSharp.csproj or Assembly-CSharp-firstpass.csproj):
`Assembly-CSharp.csproj:      <HintPath>/opt/Unity/Editor/Data/Managed/UnityEngine.dll</HintPath>`
Contents of that folder:
```
$ ls -al /opt/Unity/Editor/Data/Managed/
total 9424
drwxr-xr-x  2 root root    4096 30. Nov 21:26 ./
drwxr-xr-x 15 root root    4096 30. Nov 21:26 ../
-rw-r--r--  1 root root  528384 25. Nov 17:20 ICSharpCode.NRefactory.dll
-rw-r--r--  1 root root   44544 25. Nov 17:20 Mono.Cecil.Mdb.dll
-rw-r--r--  1 root root   81920 25. Nov 17:20 Mono.Cecil.Pdb.dll
-rw-r--r--  1 root root  302592 25. Nov 17:20 Mono.Cecil.dll
-rwxr-xr-x  1 root root   11264 25. Nov 17:20 Unity.CecilTools.dll*
-rwxr-xr-x  1 root root   11776 25. Nov 17:20 Unity.DataContract.dll*
-rwxr-xr-x  1 root root   29696 25. Nov 17:20 Unity.IvyParser.dll*
-rw-r--r--  1 root root    9843 25. Nov 17:20 Unity.IvyParser.dll.mdb
-rwxr-xr-x  1 root root    9216 25. Nov 17:20 Unity.Locator.dll*
-rw-r--r--  1 root root    1859 25. Nov 17:20 Unity.Locator.dll.mdb
-rwxr-xr-x  1 root root   18432 25. Nov 17:20 Unity.SerializationLogic.dll*
-rwxr-xr-x  1 root root   88064 25. Nov 17:20 Unity.UNetWeaver.dll*
-rw-r--r--  1 root root   28573 25. Nov 17:20 Unity.UNetWeaver.dll.mdb
-rwxr-xr-x  1 root root  228352 25. Nov 17:20 UnityEditor.Graphs.dll*
-rw-r--r--  1 root root   97873 25. Nov 17:20 UnityEditor.Graphs.dll.mdb
-rw-r--r--  1 root root 4412928 25. Nov 17:20 UnityEditor.dll
-rw-r--r--  1 root root 1574692 25. Nov 17:20 UnityEditor.dll.mdb
-rw-r--r--  1 root root 1341952 25. Nov 17:20 UnityEngine.dll
-rw-r--r--  1 root root  456102 25. Nov 17:20 UnityEngine.dll.mdb
-rw-r--r--  1 root root  139264 25. Nov 17:20 nunit.core.dll
-rw-r--r--  1 root root   57344 25. Nov 17:20 nunit.core.interfaces.dll
-rw-r--r--  1 root root  139264 25. Nov 17:20 nunit.framework.dll
```

**Comment by citizenmatt** [comment]
Hmm. There's no .xml file, hence no docs. The odd thing is, I had a project file generated that pointed to a copy of the dll that was local to my project, and it had the .xml file, too. I'll dig in and have a look. Thanks for the extra info!

**Comment by citizenmatt** [comment]
What version of Unity are you using? I'm looking at 5.4 and 5.5, and at least on Windows and Mac, the .xml files are there in those folders.

**Comment by z3ntu** [comment]
**5.5.0f3** from https://forum.unity3d.com/threads/unity-on-linux-release-notes-and-known-issues.350256/#post-2869256

**Comment by citizenmatt** [comment]
Yeah, it's missing in the Linux release, annoyingly. I have to admit that I'm reluctant to do anything about this - it seems like a lot of effort to build new .xml files (which I'm not sure I'd have write permissions to create properly) when the files already exist, but aren't being distributed. Perhaps this should be reported back to Unity?

I'll have a look to see if there's a hook in ReSharper to load the .xml files from another location - if it's really easy, then maybe...

**Comment by citizenmatt** [comment]
Raised an issue with Unity, so hopefully they'll get it fixed in a future release.

https://fogbugz.unity3d.com/default.asp?888267_le4h52kmltuk4a9e

**Comment by citizenmatt** [comment]
Closing this as won't-fix. It's a Unity issue.
