### ISSUE TITLE
Unity 5.5 this plugin doesn't work at least in Rider

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#75]
Maybe the reason is that "The Mono C# compiler has been upgraded to Mono 4.4, and now provides better performance and many bug fixes. Note that it is an upgrade of the C# compiler, not the full Mono runtime, but we feel that it represents an important step on the journey towards modernizing and improving Unity’s .NET experience."

**Comment by citizenmatt** [comment]
What's not working? It worked with an earlier build, where Unity 5.5 only used the new compiler if it was targetting .net 4.6. Has this changed?

The Rider plugin is out of date, but the latest Unity3dRider plugin should add the correct `LangVersion` if it's targeting .net 4.6.

I'm having laptop difficulties right now (astonishing amounts of yak shaving), but I'll get the Rider plugin updated tomorrow, hopefully.

**Comment by van800** [comment]
I wrote request on behalf of @slava.tutushkin.
He claims that Update and Start are marked not-used.
Now I tested on my machine - it works fine.
So I am closing the issue for now.
