### ISSUE TITLE
Unity plugin from Rider 2018.2.1 doesn't set LangVersion correctly

### ISSUE THREAD

**Issue by renattou** [JetBrains/resharper-unity#751]
After updating to Rider 2018.2.1 (plugin version 2018.2.0.78), the Unity plugin sets the LangVersion tag as empty. Like this: `<LangVersion></LangVersion>`.
This causes Rider to suggest C#6 features even though we use C#4.
Downgrading to 2018.1.4 (plugin version 2018.1.0.133) fix the problem, setting it as `<LangVersion>4</LangVersion>`.

**Comment by van800** [comment]
@renattou I can't reproduce it.
What is your Unity version and OS?

Make sure you have "Override LangVersion" unchecked
![image](https://user-images.githubusercontent.com/1482681/44881757-08b3f380-acb1-11e8-93f9-d57766d7d3fd.png)

Please set LoggingLevel to Verbose and call Assets->Sync C# Project, logs will appear in %TEMP%\Unity3dRider or $TMDDIR\Unity3dRider depending on the OS. Thanks!

**Comment by renattou** [comment]
@van800 I'm using using Unity 5.6.5p3 on macOS 10.13.6.

Using Rider 2018.1.4: [2018.1.4.log](https://github.com/JetBrains/resharper-unity/files/2338155/2018.1.4.log)
Using Rider 2018.2.1: [2018.2.1.log](https://github.com/JetBrains/resharper-unity/files/2338156/2018.2.1.log)

I checked the override option, but it was already unchecked.

**Comment by renattou** [comment]
I found this comment https://gist.github.com/van800/875ce55eaf88d65b105d010d7b38a8d4#gistcomment-2689159
which could be associated with this issue.

**Comment by van800** [comment]
@renattou Does it work if you check "Override LangVersion" and specifically change it to 4?

**Comment by van800** [comment]
I was able to reproduce the problem. Thank you.

**Comment by van800** [comment]
Until build with fix is out, you may use "Override LangVersion" setting.

**Comment by renattou** [comment]
@van800 glad to hear you could reproduce it! I'm using the override setting for now and it's working. Thanks!

**Comment by van800** [comment]
Fix is available in the nightly builds, which are accessible via https://www.jetbrains.com/toolbox/app/
