### ISSUE TITLE
Missing in ReSharper´s Extension Manager

### ISSUE THREAD

**Issue by spixy** [JetBrains/resharper-unity#754]
> The ReSharper plugin is installed via the ReSharper → Extension Manager. Simply search for "Unity Support".

It is missing there now (Resharper 2018.2.1)

![bug](https://user-images.githubusercontent.com/4542110/44947355-58f39880-ae0c-11e8-8917-1c992570461d.jpg)

**Comment by citizenmatt** [comment]
Duplicate of #706

**Comment by citizenmatt** [comment]
Sorry, the ReSharper 2018.2 release has taken a little longer than expected. It should be available later today.
