### ISSUE TITLE
Highlighting Color/Debug.LogFormat doesn't work in Rider  

### ISSUE THREAD

**Issue by mrcooper** [JetBrains/resharper-unity#76]
In Visual Studio feature 
> Support for UnityEngine.Color and UnityEngine.Color32

works fine but in Rider it doesnt

Also `UnityEngine.Debug.LogFormat/LogErrorFormat/LogWarningFormat` doesnt highlight {}  insertions

**Comment by citizenmatt** [comment]
The Rider plugin is out of date in relation to the readme. I intend to push a new version hopefully tomorrow.

However, it still won't have the colour highlighting - Rider doesn't support this yet. I've already raised an issue: [RIDER-3448](https://youtrack.jetbrains.com/issue/RIDER-3448).

**Comment by mrcooper** [comment]
Thx for the reply!
Wait for a new version

**Comment by mrcooper** [comment]
Question is not related. But I don't know where to ask...

Can I build this plugin(with Rider) on my local machine(mac) and use it in Rider?
Also does Rider support plugins from the ReSharper Gallery?

**Comment by citizenmatt** [comment]
You can't actually build the plugin with Rider on a Mac right now. I think this is Mono's xbuild not liking the Windows path separators in the HintPath references. Rider loads the project just fine, but it can't build - and therefore can't run tests.

Rider doesn't support the ReSharper Gallery, and won't - it uses the IntelliJ plugins repo instead. We're looking at migrating ReSharper plugins there too, at some point.

**Comment by citizenmatt** [comment]
Rider EAP17 now shows colour highlights, although you can't pick a colour from the palette. And it also highlights the parameters in a format message.
