### ISSUE TITLE
 Project 'Assembly-CSharp' load failed: The attribute "Name" in element <Target> is unrecognized

### ISSUE THREAD

**Issue by xiangyuan** [JetBrains/resharper-unity#767]
unity 2018 2.6 project , then use rider 2018.2 open it 
then the rider solution console show this error.

**Comment by van800** [comment]
@xiangyuan could you please post here the Assembly-CSharp.csproj?
Also you may try to update Rider to 2018.2.1.

**Comment by xiangyuan** [comment]
@van800 hi now i use rider is 2018.2.1 , do you mean the only  Assembly-CSharp.csproj? because there have a lot of project source file in the csproj.  i post the failed  file at line 702 , 
<ItemGroup>                                                                                                                                                                                                                                                                             
695     <Reference Include="UnityEditor.iOS.Extensions.Xcode">                                                                                                                                                                                                                                
696       <HintPath>/Applications/Unity/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.Xcode.dll</HintPath>                                                                                                                                                                            
697     </Reference>                                                                                                                                                                                                                                                                          
698   </ItemGroup>                                                                                                                                                                                                                                                                            
699   <ItemGroup>                                                                                                                                                                                                                                                                             
700     <Reference Include="UnityEditor.iOS.Extensions.Common">                                                                                                                                                                                                                               
701       <HintPath>/Applications/Unity/PlaybackEngines/iOSSupport/UnityEditor.iOS.Extensions.Common.dll</HintPath>                                                                                                                                                                           
702       <Target Name="GenerateTargetFrameworkMonikerAttribute" />                                                                                                                                                                                                                           
703     </Reference>                                                                                                                                                                                                                                                                          
704   </ItemGroup>

**Comment by xiangyuan** [comment]
@van800 i use unity create a new proejct  then find the .csproj file don't have then the target info line 
now it's ok. sorry maybe the problem line is create by the old unity version. still thank you very much

**Comment by ZottiGabriele** [comment]
Same issue here, fixed it by switching the default editor to Visual Studio, opening a script, letting it compile, then switch the default editor back to Rider and that restored all the lost references.
Unity version: 2018.2.7f1
Rider version: 2018.2.1

**Comment by van800** [comment]
@ZottiGabriele Do I understand right, that this is a one time issue? Or you can reproduce it?

**Comment by xiangyuan** [comment]
@van800  just as the @ZottiGabriele say  switch to default editor Visual Studio, then ok.

**Comment by xiangyuan** [comment]
@van800  just as the @ZottiGabriele say  switch to default editor Visual Studio, then ok.

**Comment by xiangyuan** [comment]
@van800  i notice that the studio generated csproj file not no UnityEditor.iOS xml node info

**Comment by van800** [comment]
Are you on Mac? It is strange that I can't reproduce the problem.
Does it reproduce with any project or just yours? I would love to see full corrupted csproj file and steps which lead to it. Do you use IncrementalCompiler package? Any other AssetPostprocessor-s in your codebase?
Logs may also help. Please enable them in Unity-Preferences-Rider-Logging Level = Verbose.

**Comment by van800** [comment]
Ok, I have reported the problem to Unity team and here is a temporary workaround:
1. Close Unity
2. In Finder open Applications, find "Visual Studio" and rename it to "_Visual Studio"
3. Open Unity, call Assets->"Sync C# Project"
Enjoy

**Comment by van800** [comment]
I made a workaround from our side https://github.com/JetBrains/resharper-unity/commit/f6609f6578d8a3c4165673fcef23402fdd1ef88e
It will get public in Rider 2018.3 EAP1

**Comment by imnotanderson** [comment]
whats the temporary workaround on windows?

**Comment by van800** [comment]
@imnotanderson I think renaming `devenv.exe` would be enough to make Unity think that VS is not installed.
