### ISSUE TITLE
Generate run-configuration to run Unity from Rider

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#770]
-projectPath <pathname> | Open the project at the given 
https://docs.unity3d.com/Manual/CommandLineArguments.html

Example of generating run-configurations: `rider\src\main\kotlin\com\jetbrains\rider\plugins\unity\run\DefaultRunConfigurationGenerator.kt`
Use UnityInstallationFinder to find installed Unity

**Comment by citizenmatt** [comment]
Is this already covered by the "Start Unity" action?

**Comment by van800** [comment]
Yeah, covered.
