### ISSUE TITLE
Attach to Unity process - preselect first item in the list

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#775]
![image](https://user-images.githubusercontent.com/1482681/45343998-dfde0900-b5a2-11e8-9503-03f38ca249d3.png)
In this dialog preselect first item in the list. Otherwise it is too much clicks.

**Comment by citizenmatt** [comment]
I'm not sure this is a good idea - the order in this list is unspecified, so we don't know what the first item is going to be. If there is more than one editor, they are returned in whatever order the OS lists processes (perhaps by id?), and external players are going to be added to the end of the list asynchronously, as they are discovered.

If we want some way of quickly re-attaching to a previously attached instance, we could look at creating temporary run configurations for the player/alternative editor instance that would try to reconnect based on IP address, name and so on (port will likely be different if the player has been stopped and restarted).

**Comment by van800** [comment]
I just want to avoid click for selecting item in the list, when it is the only one.
Now I need to select item and press OK.
Reattaching is already good - I just press Debug and it reattaches.

**Comment by van800** [comment]
Closing this without fix, I will try to use run-config and see how it works.
