### ISSUE TITLE
"Add [Serializable]" quick fix for redundant [SerializeField] attributes

### ISSUE THREAD

**Issue by sorencoder** [JetBrains/resharper-unity#779]
When you want to serialize a type using `JsonUtility`, you need to mark fields as serializable.
If the type is not inherited from `MonoBehaviour`, Resharper will grey out the attribute above fields and suggests to remove the attribute.
This should not happen since removing `SerializeField` will cause `JsonUtility` to ignore the fields.

Regards.

**Comment by citizenmatt** [comment]
Do you have the `[Serializable]` attribute applied to the class you want to serialise? If so, make sure you're running Rider 2018.2 - there was an update in there that meant fields in `[Serializable]` classes would be treated as serialised fields (and so the `[SerializeField]` attribute won't be marked as redundant).

**Comment by sorencoder** [comment]
Sorry I didn't mention that I was using Visual studio 2017 with Resharper.
This is my class that I serialize with `JsonUtility`.

```
public class PersistentData
{
    private static PersistentData instance;

    [SerializeField]
    private bool isPremium;

    [SerializeField]
    private int currentLevel;

    [SerializeField]
    private int maxUnlockedLevel;

    public PersistentData()
    {
        instance = this;
        currentLevel = 1;
        maxUnlockedLevel = 1;
    }

    public static void Save()
    {
        using (FileStream stream = File.Create(SaveFilePath))
        {
            string json = JsonUtility.ToJson(instance);
            byte[] jsonBytes = Encoding.Unicode.GetBytes(json);
            stream.Write(jsonBytes, 0, jsonBytes.Length);
        }
    }

    public static void Load()
    {
        if (!File.Exists(SaveFilePath))
        {
            var _ = new PersistentData();
            return;
        }

        using (var reader = new StreamReader(SaveFilePath, Encoding.Unicode))
        {
            instance = JsonUtility.FromJson<PersistentData>(reader.ReadToEnd());
        }
    }
}
```
Those 3 attributes are greyed out.

**Comment by citizenmatt** [comment]
This change is in the latest ReSharper plugin, too, version 2018.2. So the quick workaround would be to add `[Serializable]` to the class.

I'd actually thought that the Unity serialiser required the `[Serializable]` attribute, based on [the docs for `ToJson`](https://docs.unity3d.com/ScriptReference/JsonUtility.ToJson.html):

> Internally, this method uses the Unity serializer; therefore the object you pass in must be supported by the serializer: it must be a MonoBehaviour, ScriptableObject, or plain class/struct with the Serializable attribute applied.

but I guess that's not strictly true…

I'll have a think about a better solution, but I'd like to keep the redundant attribute warning in - perhaps add a quick fix to add `[Serializable]` as well as the one to remove the `[SerializeField]`.

**Comment by sorencoder** [comment]
> This change is in the latest ReSharper plugin, too, version 2018.2. So the quick workaround would be to add `[Serializable]` to the class.
> 
> I'd actually thought that the Unity serialiser required the `[Serializable]` attribute, based on [the docs for `ToJson`](https://docs.unity3d.com/ScriptReference/JsonUtility.ToJson.html):
> 
> > Internally, this method uses the Unity serializer; therefore the object you pass in must be supported by the serializer: it must be a MonoBehaviour, ScriptableObject, or plain class/struct with the Serializable attribute applied.
> 
> but I guess that's not strictly true…
> 
> I'll have a think about a better solution, but I'd like to keep the redundant attribute warning in - perhaps add a quick fix to add `[Serializable]` as well as the one to remove the `[SerializeField]`.

Yup. Adding a quick fix to add `[Serializable]` is better solution.  
Since it's not intended result, it can be patched in future and games will suddenly stop working.

**Comment by citizenmatt** [comment]
Just went to add this and realised that it's already there :) Added as part of 2018.2.
