### ISSUE TITLE
Colorpicker not working

### ISSUE THREAD

**Issue by matkoch** [JetBrains/resharper-unity#790]
Reproduces on several systems in hogwarts project in file `HighlightingBase.cs`

![image](https://user-images.githubusercontent.com/5005566/45683350-9d3ca380-bb43-11e8-87ee-a6dfdb535784.png)

**Comment by citizenmatt** [comment]
This is simply showing ReSharper/Rider's colour picker, it doesn't do anything Unity specific. Can you check that it works/fails in another project with `System.Drawing.Color`, e.g. `Color foo = Color.Red;`.
