### ISSUE TITLE
Allow Rider to connect to Unity Editor even if projects do not correspond

### ISSUE THREAD

**Issue by matkoch** [JetBrains/resharper-unity#791]
Assuming you're working on something that is only part of the Unity project (external library), you may want to _not_ recompile the whole Unity solution, but replace the required assemblies yourself. However, it would still be nice to be able to attach to Unity editor, use run configurations, etc..

**Comment by citizenmatt** [comment]
This is already supported if the solution is created in the same folder as the Unity project. What set up do you have? Where is the external library project and how do we know which Unity project to connect up to?

**Comment by van800** [comment]
I assume you have UnityClassLib project. It is ClassLib with reference to UnityEngine.dll.
What Unity features do you expect to work?

**Comment by matkoch** [comment]
No, the external project can be completely independent from Unity.

**Comment by van800** [comment]
AFAIK at least output path from external library should lead inside Assets folder of Unity-generated solution. We need more details on the use-case. What is the relative path between external solution and unity-generated solution? As @citizenmatt mentioned, if they are at the same folder everything should already work.

**Comment by van800** [comment]
Won't fix, I can see valuable use-case
