### ISSUE TITLE
Rider does not recognise anything anymore

### ISSUE THREAD

**Issue by ManuelRauber** [JetBrains/resharper-unity#799]
Hi,

I just started up my little Unity Project where I use Rider and it started to going crazy :)

Rider does not recognise anything anymore:

<img width="258" alt="image" src="https://user-images.githubusercontent.com/740791/45805840-de59c280-bcbf-11e8-8a58-3ae1d7fd77cc.png">

<img width="466" alt="image" src="https://user-images.githubusercontent.com/740791/45805854-eca7de80-bcbf-11e8-9963-f6d80b523b7d.png">

It only happens in this one project, everything else is working. Other Unity projects are working as well.

I've tried so far:

- `git clean -xdf` according to the gitignore.io Unity template (https://github.com/github/gitignore/blob/master/Unity.gitignore), so basically removed anything generated by Unity
- Updated Rider to 2018.2.3
- Updated Unity 2018.2.8f1
- Used Rider Invalidate Cache & Restart

Interesting thing is, that IntelliSense, compiling etc. is all working. I can continue working, if I ignore the strange editor behaviour.

**Comment by ManuelRauber** [comment]
Using JetBrains MSBuild Distribution seems to fix the problem. 
Strange, it worked for days without any problem using the MSBuild from Unity. I'll keep an eye on it. 

Thanks for the fast answer!

**Comment by van800** [comment]
@ManuelRauber New Unity requires new MSBuild, which is not bundled. We have a plan to bundle it in Rider https://youtrack.jetbrains.com/issue/RIDER-18214. Previously Unity bundled xbuild for MD, but stopped after dropping MD.

**Comment by ManuelRauber** [comment]
@van800 Nice to know, thank you! That would be awesome, if Rider bundles it. I'd love to upvote it, but I guess your link is for an internal issue, getting a 404 here :)

**Comment by van800** [comment]
@ManuelRauber good point, I made it public.

**Comment by RealMSHB** [comment]
Hi,
I have the same problem. I'm using Unity 2019.2 and already tried the solution that was suggested here. it fixed my problem once, but I have the same problem again for the new C# files that I make.

**Comment by van800** [comment]
@RealMSHB I am sorry, could you please describe your setup completely? Rider version, Unity, OS.
Steps to reproduce. Thank you!

**Comment by RealMSHB** [comment]
@van800 I found the problem.
when I make a new file the short keys like save doesn't work but I don't know why. saving manually from the top bar menu fixed the problem.

I'm working on Windows 10, Rider 2019.1.3, Unity 2019.2

**Comment by van800** [comment]
@RealMSHB Maybe something with keymap?
![image](https://user-images.githubusercontent.com/1482681/62533553-3ef5dd80-b847-11e9-8ff7-c4f4366001a8.png)

**Comment by RealMSHB** [comment]
@van800 
Saving didn't solve the problem. I have even installed the same unity version and rider on a fresh system but still I have the problem.
it's like it doesn't recognize the new files that I make.

all of the new file have a yellow tab in rider:
![image](https://user-images.githubusercontent.com/8512440/62694754-37fcd580-b9d5-11e9-9a4a-4b8a8307a65c.png)

what does this mean?

**Comment by van800** [comment]
@RealMSHB Please create a separate issue. It seems very different from the original one.
