### ISSUE TITLE
Add inspection for ScriptableObject inheritor

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#809]
ScriptableObject inheritor must be instantiated using the ScriptableObject.CreateInstance method instead of new.

https://forum.unity.com/threads/why-scriptableobject-createinstance-instead-of-constructor.356845/

Example 
```
new Launcher (){}
public class Launcher : ScriptableObject {}
```

**Comment by citizenmatt** [comment]
I think this is already covered: [IncorrectObjectInstantiationProblemAnalyzer.cs](https://github.com/JetBrains/resharper-unity/blob/183/resharper/src/resharper-unity/CSharp/Daemon/Stages/Analysis/IncorrectObjectInstantiationProblemAnalyzer.cs)

**Comment by van800** [comment]
Ah, great, I see it works in 2018.3
