### ISSUE TITLE
API information should be version specific

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#81]
Code completion for event functions, and recognising existing event functions should be version aware, and only match or suggest types and functions that are applicable for the currently referenced Unity version.

**Comment by citizenmatt** [comment]
This is tricky - the UnityEngine.dll and UnityEditor.dll files do not have a version. The `ProjectSettings\ProjectVersion.txt` file lists the version of the editor that last opened/saved/generated the project.

The only way I can see of doing this is to either a) parse the defines, looking for `UNITY_X_X` (e.g. `UNITY_5_5`). The defines are only set for the Debug configuration, and there's no guarantee of accuracy.

Alternatively, b) install a plugin into the Unity Editor that opens a socket which we can talk to from our plugin (I suspect this is how VSTU works). The editor plugin can get all the information we need - but what happens if we open the project without the editor running? Cache last known good data?

Finally, c) look for something unique in each version of UnityEngine.dll, e.g. 5.5 has a parameter for `OnParticleTrigger` and 5.4 doesn't. I don't like this idea.

**Comment by Silentor** [comment]
UNITY_X_X defines sets for both debug and release configurations. I think defines is a best way to get Unity version for Resharper.
