### ISSUE TITLE
Rider uses an older version of tests when running unit tests from the IDE

### ISSUE THREAD

**Issue by j-h-a** [JetBrains/resharper-unity#831]
**Rider Version:** `2018.2.3`
**Plugin Build:** `182.4231.496`
**Unity Version:** `2018.2.8f1`

When doing TDD and running tests regularly after making changes, I noticed that test execution allows Unity to use an older version of the tests and/or code than what is currently saved.

### Expected behaviour:

When running unit tests from Rider, the results reflect the current state of the saved code and tests.

### Actual behaviour:

When running unit tests from Rider, the results can temporarily reflect an older state of the code and tests, or permanently reflect an older state in the case where compilation of code or tests fails.

### To reproduce:

1. Start with a test-suite with some passing tests in it.
2. Run the tests from Rider, all should pass.
3. Introduce a new test:
```
[Test]
public void FakeTest()
{
	Assert.Fail();
}
```
4. Save all, and immediately run the unit tests (⌘S, ⌘;, R)
5. Rider immediately recognises the new test, but Unity doesn't, this presents as an inconclusive/not run test:
![28 Tests with one inconclusive](https://user-images.githubusercontent.com/1160012/46586130-d8aafd80-ca71-11e8-848e-dc79a2744370.png)
6. Wait a few seconds and without making any changes run the unit tests again. Unity has now caught up and runs the failing test:
![28 Tests with one failing](https://user-images.githubusercontent.com/1160012/46586174-7a324f00-ca72-11e8-9c26-0c11945fd63d.png)
7. Make the test pass by removing the `Assert.Fail();` line, save, and immediately run the tests again. The test which should now pass, still fails:
![28 Tests with one failing](https://user-images.githubusercontent.com/1160012/46586174-7a324f00-ca72-11e8-9c26-0c11945fd63d.png)
8. Once again, wait a few seconds and without making any changes run the unit tests again. Unity has now caught up and all tests pass.
9. Introduce a compile error into the tests:
```
[Test]
public void FakeTest()
{
	please fail to compile
}
```
10. Running the tests immediately has the same effect as above, they still all show passing. But now, even waiting a few seconds won't work because Unity never catches up - it continues to use the previous working version of the code/tests because it can't compile the new version.

### Speculation on cause and proposed fix:

Cause: Rider triggers Unity to run unit tests without triggering a re-compile, or waiting for any ongoing re-compile to finish.
Proposed fix: Delay triggering a test run until Unity has compiled any saved changes.

Cause: Rider allows Unity to run old compiled code and tests when the current code/tests don't compile.
Proposed fix: Report back to Rider a total failure to run any tests in the case where Unity can't compile the latest saved changes.

**Comment by van800** [comment]
Fixed with https://github.com/JetBrains/resharper-unity/pull/929
