### ISSUE TITLE
Xcode DLL references are not being added to the project files

### ISSUE THREAD

**Issue by dvazalves** [JetBrains/resharper-unity#841]
Happens to me with _Rider 2018.2.3_ on _macOS 10.14_.

The problem seems to be that **CsprojAssetPostprocessor::SetXcodeDllReference** tries to create the path to the DLL from **EditorApplication.applicationContentsPath** but should instead do it from **EditorApplication.applicationPath** since this is where the **PlaybackEngines** folder for the non-standalone build targets are.

Could you please look into this? Adding the references by hand gets tiresome really fast ^^

**Comment by van800** [comment]
Sure, what is the correct dll path at your machine?

**Comment by van800** [comment]
And dlls are right in iOSSupport folder, right?

**Comment by dvazalves** [comment]
Correct :)

**Comment by van800** [comment]
In the meantime, you may add mcs.rsp or csc.rsp with -r:"full-path-to-dll" as a workaround.

**Comment by van800** [comment]
Latest Nightly Build #183.3647.159 available via `JetBrains Toolbox App` has this fix
