### ISSUE TITLE
ShaderLab attributes' parameters are not parsed correctly when they begin with numbers 

### ISSUE THREAD

**Issue by Ciziu** [JetBrains/resharper-unity#857]
An error is reported whenever a parameter for an attribute starts with a number, but contains any character that is not a number. Examples:

`
[KeywordEnum(6 Frames Layout, Latitude Longitude Layout)] _Mapping("Mapping", Float) = 1
[Enum(360 Degrees, 0, 180 Degrees, 1)] _ImageType("Image Type", Float) = 0`

**Comment by IvanPashchenko** [comment]
Note: you can write almost anything you want inside the attributes, e.g.
```
[AsdfsfsfSD(dasdasdasda]
 _ImageType("Image Type", Float) = 0
```

will not cause any errors.
