### ISSUE TITLE
Using LayerMask instance for bitwise shift shows an error in the IDE, but compiles fine.

### ISSUE THREAD

**Issue by Ciziu** [JetBrains/resharper-unity#858]
`UnityEngine.LayerMask` has an implicit conversion to `int` defined and works fine in bitwise shift operations. Despite that, an error

> Right operand of shift expression should be convertible to 'int'

is reported every time. Obviously, the code compiles just fine.

**Comment by Ciziu** [comment]
Sure thing. Real examples in our code are slightly more convoluted, but it boils down to this:

```
using UnityEngine;

public class LayerMaskBug : MonoBehaviour
{
    [SerializeField] private LayerMask m_mask;

    void Update()
    {
        RaycastHit hit;
        if (!Physics.SphereCast(Vector3.zero, 0.5f, Vector3.forward, out hit, float.MaxValue, 1 << m_mask))
        {
            // Do something
        }
    }
}
```

**Comment by van800** [comment]
Duplicates https://youtrack.jetbrains.com/issue/RSRP-436730, please follow it on YouTrack.
