### ISSUE TITLE
Do not reorder serialized fields

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#88]
If a class contains fields that will be serialized (deriving from e.g. `MonoBehaviour` and public, or private with the `[SerializedField]` attribute), then those fields should not be reordered during e.g. code cleanup.

**Comment by nkAlex** [comment]
I haven't checked it specifically, but I think the order only matters if you're working with an already compiled game (i.e. making a patch, mod, etc.), so it should probably be a configurable option.

Additionally to **MonoBehaviour**, Unity's scripts can also derive from **ScriptableObject** (it's a sort of a serializable code container not requiring a GameObject to be attached to).

Technically, regular C# classes can also be a part of serialization (with some limitations), so, maybe an attribute to be able to mark those as such? **[UnitySerializable]** or something :)

**Comment by CapnRat** [comment]
Just to confirm, Unity's serialization system does not depend on field order. It only depends on field name.

**Comment by nkAlex** [comment]
When working with sources, I believe so.
But I've been modding an already compiled game, and reordering fields leads to serialization layout errors, and sometimes "position out of bounds" errors. I suppose in the final build objects may be serialized linearly or something like that.
Anyways, that's why I was mentioning "optional" :)

**Comment by ikkentim** [comment]
When you have neatly ordered your fields into sections and by a certain order, it's quite important the order doesn't change.

**Comment by CAD97** [comment]
Given that the order of serialized fields has an effect -- the order of fields in the editor -- code cleanup should not change their relative order as that would change behavior. +1
