### ISSUE TITLE
Inspecting an object while debugging results in a very long "Collecting data..."

### ISSUE THREAD

**Issue by aaronhoogstraten** [JetBrains/resharper-unity#899]
Hello,

Rider 2018.2 did indeed fix a previous issue I reported regarding variable inspection(https://github.com/JetBrains/resharper-unity/issues/353), but often times now when inspecting an object Rider will stall trying to evaluate the watch with just a "Collecting data..." message. Googling reveals some reports of this for other JetBrains products, but this is the first time I've encountered it in Rider (maybe issue 353 linked above prevented me from seeing it). Unity and Rider are both unresponsive (can't step or resume) until I stop the debugger.

I checked my DebuggerWorker log and noticed this line:
`09:35:03.261 |V| AsyncOperationManager         | Debugger worker MTA main thread:3 | Invoke MyClass+MyInnerClass.get_IEnumerableofObjects timed out after 1000 ms. Cancelling.`
`09:35:03.264 |T| AsyncOperationManager         | Debugger worker MTA main thread:3 | Waiting for cancel of invoke MyClass+MyInnerClass.get_IEnumerableofObjects`

I increased the timeout to 10000ms and it still fails to evaluate my "IEnumerableofObjects".
I disabled property evaluation in the debugging settings and now the evaluation works as I would expect. Calling refresh manually on the property "IEnumerableofObjects" results in a very long loading bar popup for "Loading Value". Canceling this results in the same unresponsive behavior.
I changed `get` for my IEnumerableofObjects property to just return a hardcoded List<Object> and now the evaluation **works**. This property calls into further properties which I guess could be causing the issue.

Version info:
Rider 2018.2.3, Build #RD-182.4231.496
Unity 5.6.3p3

**Comment by van800** [comment]
It may be worth trying Rider 2018.3 builds. I recommend JetBrains Toolbox App, which helps having several versions simultaneously.

**Comment by aaronhoogstraten** [comment]
@van800 thanks for the response! I just tried 2018.3 EAP 5 (installed with Toolbox, nifty) but unfortunately the same behavior is occurring and I see the same lines in the DebuggerWorker log i.e. ` ...timed out after 1000 ms. Cancelling.` and then `Waiting for cancel of invoke...`.

**Comment by van800** [comment]
Thanks for the info

**Comment by aaronhoogstraten** [comment]
Just wanted to report that this still occurs in 2018.3 for me unfortunately.

**Comment by van800** [comment]
@aaronhoogstraten Is it still there in 2018.3.3?

**Comment by van800** [comment]
Debugging is a core Rider feature, so we can't really address much of its issues in this plugin scope. So I am closing this issue here. However if it still reproduces, please post an issue in https://youtrack.jetbrains.com/issues/RIDER

**Comment by aka3eka** [comment]
Same problem here with Rider 2019.3. Takes ~30 seconds to see variables values ("Collecting data..." and "Evaluating...").

**Comment by citizenmatt** [comment]
Please can you log an issue here: https://youtrack.jetbrains.com/issues/RIDER? That way we can route the request to the correct people - there's no-one in this repo who can fix core debugging functionality.
