### ISSUE TITLE
Not Available in 2016.3

### ISSUE THREAD

**Issue by farzadmf** [JetBrains/resharper-unity#90]
Hi,
I recently updated ReSharper to 2016.3, and I saw that the extension isn't working. I tried to re-install it, but when I search for "unity" in ReSharper's extension manager, the search result is empty!

**Comment by citizenmatt** [comment]
It needs to be updated for 2016.3. I'm in the middle of implementing a feature (#82), and as soon as that's done, I'll push the update ([milestone 1.5](https://github.com/JetBrains/resharper-unity/milestone/4)). This will be by the end of the week, hopefully sooner.

**Comment by farzadmf** [comment]
Good to know, thanks 👍

**Comment by HodgsonSDAS** [comment]
You rock @citizenmatt

**Comment by farzadmf** [comment]
Any news on this? I'm missing this plugin so much :(

**Comment by farzadmf** [comment]
Thank you so much 👍 Life is beautiful again ;)
