### ISSUE TITLE
Not Working in Rider EAP Build 15 (Dec 19)

### ISSUE THREAD

**Issue by pbreault** [JetBrains/resharper-unity#91]
I just upgraded to the new Rider EAP (RS-163.10479) and it seems like the plugin silently stopped working:
- Methods/Fields implicitly used are marked as unused
- The "generate event functions" action is not there anymore in the "generate" menu.

Might be related to #90

**Comment by citizenmatt** [comment]
It's kinda related - #90 is for 2016.3, but the issue with Rider is that EAP15 is built on what will be ReSharper 2017.1, so it's a version further on. I'll get a build out as soon as I can. See also [RIDER-3877](https://youtrack.jetbrains.com/issue/RIDER-3877).

**Comment by citizenmatt** [comment]
Took a wee while, but there's a new version in the plugin repo that works with EAP15.
