### ISSUE TITLE
Add static analysis rule to detect invalid scene loading

### ISSUE THREAD

**Issue by liortal53** [JetBrains/resharper-unity#910]
Unity provides a few different methods for loading scenes using the `SceneManager` class (either by name or by the scene's index in player settings).

It can be useful to add a rule that detects attempts to load invalid scenes. These may be:

- A scene with an invalid index (scene index doesn't exist in build settings, or the scene is not enabled)
- A scene with an invalid name (string) - again, that doesn't exist in build settings or not enabled.

**Comment by liortal53** [comment]
if you think this is a good idea, i would like to implement it of course :)

**Comment by liortal53** [comment]
Unity provides an API to do that. For example, this will get you the list of all (enabled) scene names:
`var enabledScenePaths = EditorBuildSettings.scenes.Where(s => s.enabled).Select(s => System.IO.Path.GetFileNameWithoutExtension(s.path)).ToArray ();`

If i understood what i've read about the architecture, Rider and the Unity editor communicate via a predefined protocol. as such, it is possible to invoke certain methods (in the editor plugin) and receive back information from Unity.

In this case, the information required is the scene information - names and indices (can be 2 separate calls).

Then, the code can be analyzed to see if actually invoked with valid arguments.

**Comment by krasnotsvetov** [comment]
In analyzer, It's very costly to invoke methods through protocol, but it is possible to store valid scenes in protocol model. Unity will push changes to protocol model, analyzer will pool and update his own information about scenes. This should work fast

**Comment by liortal53** [comment]
Why is it costly? does it incur a long (blocking) call to get that data?

Your suggestion can work, but the scene list can get updated, so this protocol model must be kept in-sync when this occurs.

**Comment by krasnotsvetov** [comment]
It is costly for use protocol for this goals, btw I have find a correct way to extract this information.
Each Unity project contains \ProjectSettings\EditorBuildSettings.asset file.

Currently, Rider can parse yaml files, so we have this information for our inspection.
If you want to implement, please let me know.

**Comment by liortal53** [comment]
This file contains this data, regardless of whether you created a build or not.

Are you already parsing YAML files in Rider? i am not sure this is the best option, as i would rather work with the Unity APIs directly instead of relying on their serialization format (even though it's super unlikely to ever change, but who knows).

**Comment by citizenmatt** [comment]
@krasnotsvetov do the changes in Rider 2019.2 cover this?

**Comment by krasnotsvetov** [comment]
Yes
