### ISSUE TITLE
Game build triggers solution-wide analysis

### ISSUE THREAD

**Issue by Ciziu** [JetBrains/resharper-unity#915]
Tested on Rider 2018.2.3 and 2018.3 EAP 5 with "Solution-Wide Analysis" on. 

When making an actual game build through Unity (File -> Build Settings -> Build), while having Rider open, it seems that triggering the build makes Rider reanalyze what seems to be the whole, or at least most of the project's codebase. When the build finishes, analysis seems to be triggered once again.

The project, while fairly large, doesn't execute any custom build pre- or post-processing.

Obviously, the analysis puts some stress on the CPU, which is especially unwelcome during the build process.

Is it advised not to use "Solution-Wide Analysis" with Unity projects and/or close Rider during the build process? Or maybe the issue is specific to my project, in which case, what information should I provide to help identify it?

**Comment by Ciziu** [comment]
No, "Scripting Runtime: .NET 4.x" and "Api Compatibility Level: .NET 4.x", without Incremental Compiler. Problem observed with both Mono and IL2CPP build.

I've looked through Rider's logs and I think I can see what's causing the problem. Still no idea why though.

I'm attaching a snippet from backend.log, from the moment when a build was triggered.
[backend.log](https://github.com/JetBrains/resharper-unity/files/2599173/backend.log)

The assemblies listed here (Cinemachine, Package Manager UI, TextMesh Pro) are added to the project through Unity's Package Manager. Apparently triggering the build process modifies those assemblies in some way. Still, most of the files that are being reanalyzed as a result of this, don't use those assemblies in any capacity.

**Comment by van800** [comment]
Do you mean Rider process is in background (without focus) but still it reacts (starts SWEA) on some file changes?

**Comment by van800** [comment]
I tested it on my machine, it seems that Unity is overwriting csproj files on each Build, so when you put focus to Rider it really does some re-analysis. But if you don't focus Rider - it will not do anything.

**Comment by Ciziu** [comment]
I can confirm that the problem happens only when I switch focus back to Rider, when building. So as long as I don't try to browse through the code while building, there is no problem, though it's more of a workaround than a solution and quite irritating.

As for Unity overwriting csproj files, it doesn't seem to be just that. First of all, not every build seems to regenerate those, at least on my machine, yet the problem happens every time. Secondly, when I do something different in the editor that causes project to be regenerated, like add a new file, Rider seems to analyze just this file. Even if I manually delete all csproj files and use Unity to generate them again from scratch, the results of analysis seem to properly load from cache.

However, when I build and switch focus to Rider, it starts going through ~1600 files, which is more or less the whole codebase of the project. So, whatever happens during the build process, seems to temporarily invalidate the whole cache of the solution-wide analysis and I think it might be worth investigating.

**Comment by van800** [comment]
Does it reproduce on some open-source project or any project, which you can share?
I thied https://github.com/Unity-Technologies/EntityComponentSystemSamples, but no luck.

**Comment by Ciziu** [comment]
I checked with the project you linked and got the very same issue I described. I tried a few versions of Unity, thinking maybe it's tied to that, but the same thing happened with 2018.2.13, 2018.2.16 and 2018.3.0b11.

I might not be describing what's going on perfectly, so to clear it up, I've saved a short screencast of what's going on when I'm building EntityComponentSystemSamples. I had to zip it, because Github doesn't allow attaching video files for some reason. Here it is:
[rider.zip](https://github.com/JetBrains/resharper-unity/files/2609172/rider.zip)

**Comment by van800** [comment]
Thanks a lot for the excellent video, I managed to reproduce it.
Whole folder `Library\ScriptAssemblies` is deleted and all libs are copied again during build. This causes long re-analysis in Rider. I have raised a question in unity-jetbrains slack channel. I will let you know, when I get something.

**Comment by van800** [comment]
Got a response:
```
I think this happens because we build the player assemblies into the `Library/ScriptAssemblies` folder and delete any existing editor assemblies. We never load the player assemblies into the editor. Once we are done with the player assemblies, we rebuild the editor assemblies in the folder again. This should be fixed by building the player assemblies in another folder and thereby avoid deleting the editor assemblies. One quirk/“breaking change” might be that there might be user code using build pipeline callbacks that assumes that the player assemblies are in `Library/ScriptAssemblies`.
```
So would you please file it as a bug report for Unity? Or I can do it.

**Comment by Ciziu** [comment]
I can definitely file a report to Unity. I just wanted to step through the problem first and make sure I fully understand what's going on.

So, as far as I understand, the problem is indeed with Library/ScriptAssemblies, but only with .dlls there, that are used solely as dependencies and not treated as being build within the project. I think I managed to confirm that, because if you take the EntityComponentSystemSamples project, go to Library/ScriptAssemblies and delete .dlls generated by the project, like Assembly-CSharp.dll, Assembly-CSharp-Editor.dll, Assembly-CSharp-firstpass.dll, Dungeon.dll etc., Rider doesn't seem to care. But as soon as you delete a single .dll, that is used only as a dependency, like Unity.Mathematics.dll, Unity.Entities.dll,  Unity.Transforms.dll etc. (in other words, all the .dlls from packages), as soon as you put focus back to Rider, this whole re-analysis occurs.

This actually means, that adding a new package through Package Manager and switching focus back to Rider when it finished triggers similar behavior to what happens when building. But I guess reanalyzing the project when the list of dependencies changes makes sense, so it shouldn't be considered a bug.

I agree that the setup where Unity uses the very same folder for player build dependency dlls and editor dependency dlls and keeps on deleting the whole folder is a weird idea, so I'll file this bug report later on and link it here.

If they won't treat this report with any reasonable priority, is it possible to have the Unity plugin for Rider pause the Solution-wide Analysis for the duration of making a build?

**Comment by Ciziu** [comment]
Here is the ticket https://fogbugz.unity3d.com/default.asp?1103951_b9hcvnbts8fijbh7

**Comment by van800** [comment]
Probable technical workaround might be:
1. Find some API in Unity, which can notify when Player Build is called.
2. Call Rider via protocol to pause Solution Wide Analysis.
3. After Build - unpause Solution Wide Analysis.

**Comment by van800** [comment]
https://unitydevs.slack.com/archives/CD238E69E/p1595338451218400

**Comment by van800** [comment]
close in favor of https://youtrack.jetbrains.com/issue/RIDER-47998

**Comment by RDeluxe** [comment]
That's still an issue, and a pretty big one at that. Unity answered [there](https://fogbugz.unity3d.com/default.asp?1103951_b9hcvnbts8fijbh7) , is there nothing that can be done on resharper side ?

I'm building quite often, and Rider analyzis is extremely heavy on my CPU.

**Comment by van800** [comment]
I have a plan to have another investigation on this problem in 2020.3 timeframe.
Workaround is to either not focus Rider when non-Editor Build is done in Unity or disable Solution Wide Analysis in Rider during that non-Editor Build.
