### ISSUE TITLE
Support the ENABLE_WINMD_SUPPORT define

### ISSUE THREAD

**Issue by edwood-grant** [JetBrains/resharper-unity#933]
If you are using WinRT APIs in Xbox One and UWP apps, you'll need this define to exist to filter the WinRT APIs. Opening a Rider project normally will not detect this define. In Visual Studio they solve this with another project inside the solution that supports it (named <PorjectName>.player). 
You can read more about it here: 
https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-partner/partner-unity-xdk-il2cpp

It would be nice to be able it find a way to support it in a similar way in RiderRider. Thanks!

**Comment by van800** [comment]
What is your Unity version?

**Comment by edwood-grant** [comment]
I tested this in Unity 2018.2.16f1.

**Comment by van800** [comment]
I have contacted MS to get XBox One SDK for Unity. It may take time.

**Comment by van800** [comment]
Thanks for the info, I am sorry that I missed the comment.

**Comment by van800** [comment]
The code, which creates the "Player" projects - `CreatePlayerProject` method resides in SyntaxTree.VisualStudio.Unity.Bridge.dll, so we can't use it directly.

To mimic the project-generation behavior we may need to:
1. Copy generated csproj
2. Add `ENABLE_WINMD_SUPPORT;WINDOWS_UWP` to DefineConstants
3. Add references to some set of libs in `C:\Program Files (x86)\Windows Kits\10\References\10.0.17763.0`, not sure, where to get the `sdk version`
4. Add new Player csproj-es to solution.

**Comment by van800** [comment]
I have got a comment from Unity team that this feature in on their list, so probably we will wait for their generic implementation, instead of making our own.

**Comment by dmbond** [comment]
Waiting for Unity's implementation? Are you serious? Lots of things have been waiting years for Unity to implement, with no results. If you can do it yourself, do it.

**Comment by van800** [comment]
@dmbond Do you still experience this problem with somewhat recent Unity version and recent Rider package?

**Comment by dmbond** [comment]
Then I tried to do it in VS and it didn't work either. So I found the topic [https://forum.unity.com/threads/migrating-from-windows-standalone-to-uwp.1045375/](https://forum.unity.com/threads/migrating-from-windows-standalone-to-uwp.1045375/) and enabling Player Projects worked for Rider as well. Sorry for the inconvenience.
