### ISSUE TITLE
Could decompilation leverage the sources from UnityCsReference repository ?

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#936]
Since Unity sources are available at https://github.com/Unity-Technologies/UnityCsReference, I was wondering if when pressing <kbd>F12</kbd>, Resharper could open the original source file instead of decompiling it ?

I think we're quite close with the following, but since there's no associated PDB telling what was the original location, I couldn't get this function to work:

![2018-11-29_02-17-00](https://user-images.githubusercontent.com/1537591/49192803-e8153b80-f37c-11e8-88d7-1fc19e4c6c96.png)

That would be outstanding ! 😃

**Comment by aybe** [comment]
By fiddling a bit with the files, it appears that files location are available somehow, they can be seen in the associated MDB file when there's any, e.g. `C:\Program Files\Unity\Hub\Editor\2018.2.16f1\Editor\Data\Managed\UnityEditor.dll.mdb`.

In this case it is `C:\buildslave\unity\build\` which I instantly tried but Resharper didn't pick it ... :(

I believe that it's unaware about MDB format, only PDB format; 

Then I've tried to generate a PDB for it but R# tells that the DLL is missing the debug directory section.

The sources of `pdb2mdb.exe` can be decompiled and seen with JustDecompile, it is however far from being trivial to write the opposite converter.

**Comment by aybe** [comment]
Thanks but neither are working,

The first lacks UnityEditor.dll symbols and does not get picked by Resharper anyway,

The second simply does not expose the feature to folder substitution as shown in the screenshot I've posted.

**Comment by van800** [comment]
Closed in favor of https://youtrack.jetbrains.com/issue/RIDER-22439
Debug is Rider Core feature, we can't do much of it in the plugin.

**Comment by Andor233** [comment]
Sorry about that, but I want to know any solution to this?

**Comment by van800** [comment]
Everybody just use debugging decompiled sources, I guess. @Andor233 
It might be worth adding a request to Unity to add managed symbols to their symbol server.
I have just asked them again on our internal slack channel, but having a public issue with votes might also help.

**Comment by Andor233** [comment]
Decompiled sources are too slow, How to create a public votes? Reopen this issue?
Thank you your answer

**Comment by citizenmatt** [comment]
What do you mean by too slow? Generating the decompiled files? That's not going to be any slower than downloading from GitHub, even if we had a way to map from an assembly to a commit hash in GitHub.
