### ISSUE TITLE
Feature Request: Ability to Hide Icon Next to Unity-Initialized Functions/Variables

### ISSUE THREAD

**Issue by sdarkwell** [JetBrains/resharper-unity#94]
Hello,

I would enjoy the ability to hide the icon next to Unity-initialized functions/variables.

My reason is three-fold:
1. The Unity Asset Store asset "uIntelliSense", also adds its own icons, in addition to adding IntelliSense support to Unity types, a Unity-styled project browser, and shortcuts to the Unity scripting reference.
2. I prefer to only have icons next to Unity-provided message functions (eg: Start(), Update(), OnValidate(), OnCollisionEnter())
3. The icons are quite large (about 3 times larger than those used by uIntelliSense, for example)

Thank you in advance for your consideration!
- S.

**Comment by citizenmatt** [comment]
Gah! I like not having any options 😛 

Makes sense, though. I'm not 100% sold on the icons myself. They're useful, but to many and they can get noisy. I'll add an option, and possibly highlight the method/field in another colour, or show them in bold or something.

I wasn't aware of uIntellisense, but looking at the screenshots, the icons should be pretty much the same size. Are they actually 3 times as big? Any chance of a screenshot?

This is what the ReShaprer/Rider plugin looks like - icon similar size to the text itself:

<img src="https://raw.githubusercontent.com/JetBrains/resharper-unity/master/docs/field_not_accessed.png" width="442">

**Comment by sdarkwell** [comment]
I can certainly appreciate the desire for simplicity!

Seemed about three times as large, but perhaps only twice of large, simnply seeming larger due to the inversion of colors.

Here's a screenshot. They actually display side-by-side when both plugins are installed.

![example](https://cloud.githubusercontent.com/assets/17504940/21591170/9bc3b6f2-d0cf-11e6-9949-2f36e346fbe9.png)

**Comment by CAD97** [comment]
Rider has a Settings section for `Editor>General>Gutter Icons` so if/when possible, that would be a good place to put the setting Rider-side.

**Comment by citizenmatt** [comment]
Fixed in #901 for Rider. Rider highlights implicitly used items such as MonoBehaviour based classes, serialised fields, event functions and event handler methods/setters with a Code Vision marker, and by highlighting the element name in a configurable style.

By default, gutter icons are hidden when Code Vision is enabled, and shown when Code Vision is disabled, but there is also a setting to always show or always hide gutter icons.
