### ISSUE TITLE
Unity preferences does not save with JetBrains.Rider.Unity.Editor.Plugin.Repacked.dll

### ISSUE THREAD

**Issue by MorganVoodoo** [JetBrains/resharper-unity#941]
Unity does not save Preferences anymore when JetBrains.Rider.Unity.Editor.Plugin.Repacked.dll is present in the project.
If i remove it, it works like a charm.

Repro:

Let Rider add JetBrains.Rider.Unity.Editor.Plugin.Repacked.dll to the project
Focus Unity
Open Unity Preferences, change state of "Auto Refresh" checkbox and Close Preferences.
Open Preferences again and "Auto Refresh" value is back, it was not saved.

Rider version : 2018.2.3
Unity version : 2018.2.17f1
[JetBrains.Rider.Unity.Editor.Plugin.log](https://github.com/JetBrains/resharper-unity/files/2634188/JetBrains.Rider.Unity.Editor.Plugin.log)
[Editor.log](https://github.com/JetBrains/resharper-unity/files/2634203/Editor.log)

**Comment by van800** [comment]
Duplicates RIDER-22151 Unity preferences does not save with
