### ISSUE TITLE
Cannot debug unity android with rider

### ISSUE THREAD

**Issue by roroco** [JetBrains/resharper-unity#945]
I encounter this bug: https://youtrack.jetbrains.com/issue/RIDER-22365
please tell me how to debug unity android with rider
I see this tutorial: https://docs.unity3d.com/560/Documentation/Manual/AttachingMonoDevelopDebuggerToAnAndroidDevice.html
but it only work in visual studio, rider doesn't find "AndroidPlayer" process

**Comment by van800** [comment]
Close in favor of https://youtrack.jetbrains.com/issue/RIDER-22365
Debugging is Rider core functionality, issues related to it are planned in YT.
