### ISSUE TITLE
Set Unity yamlmergetool as a custom merge tool in Rider

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#948]
https://docs.unity3d.com/Manual/SmartMerge.html

1. Currently it can be setup manually via "external merge tool" setting in Rider, but it should use the merge tool from current detected Unity version.
2. Most of the times **yamlmergetool** does the job, but sometimes it needs to fallback to different mergetool, which can be rider again called as `rider64.exe merge $LOCAL $REMOTE $BASE $MERGED`.

Full discussion on slack https://unitydevs.slack.com/archives/CD238E69E/p1544020282007900

**Comment by van800** [comment]
May be worth doing after https://youtrack.jetbrains.com/issue/IDEA-200628 is fixed.

**Comment by citizenmatt** [comment]
Fixed with #1682
