### ISSUE TITLE
Version selection in Preferences/Rider could be better

### ISSUE THREAD

**Issue by Baste-RainGames** [JetBrains/resharper-unity#955]
I'm talking about this one:

![image](https://user-images.githubusercontent.com/12800067/49746673-f844e900-fca1-11e8-98fe-c1cdfaba099d.png)

Those are EAP 8, some older nightly, and 2018.2.3 respectively. I can understand nightlies having an internal ID-string, but it would be nice if the versions that have real names (like "EAP 8") could be shown as that, so I don't have to go to toolbox->EAP 8->Settings->install location->show in explorer in order to be able to match the numbers to the correct version. 

I can deduct which version is which due to the numbers being increasing, but it took me quite a few version switches before I realized that.

**Comment by citizenmatt** [comment]
This has been fixed in the Rider package, and Rider now uses "release version" such as "2020.2.4" or "2020.3 EAP5". Unfortunately, I'm not sure on which version, so please update the Rider package to a newer version.

**Comment by Baste-RainGames** [comment]
Yup, this has been fixed for a long while! Thanks for that, it's a lot easier to use now.
