### ISSUE TITLE
C# Language Version "latest" not allowing 7.x features

### ISSUE THREAD

**Issue by svendhhh** [JetBrains/resharper-unity#956]
(This might possibly be related to this issue: https://github.com/JetBrains/resharper-unity/issues/528)

When opening Rider from a Unity 2018.3b11 project (like the one attached), ReSharper will complain about 7.x features. For instance:

![C# 7.0 language feature error](https://user-images.githubusercontent.com/5302311/49860583-643a6500-fdfa-11e8-90ce-0b56619b86ba.png)

The ReSharper auto fix is:

![hxey1](https://user-images.githubusercontent.com/5302311/49860652-8633e780-fdfa-11e8-838b-c514a9604b9d.png)

The csproj file specifies LangVersion as latest:

![image](https://user-images.githubusercontent.com/5302311/49860707-a2d01f80-fdfa-11e8-8619-4ba128feb5cf.png)

And in the properties for the assembly it also says "latest":

![joo6x](https://user-images.githubusercontent.com/5302311/49860816-dad76280-fdfa-11e8-8314-91533b937d8f.png)

Changing it to "7.3" and closing and reopening the settings, it will say it's "overriden" (with a typo) by the Rider Settings to 6.0:

![3at7g](https://user-images.githubusercontent.com/5302311/49860885-f8a4c780-fdfa-11e8-9095-eb4d5ee2d654.png)

Clicking "Reset" will fix it. However, if I close and re-open ReSharper it's back to the initial state.

Below is a test project that reproduces with Unity version 2018.3.0b11 and Rider version:

-------------------------
JetBrains Rider 2018.2.3
Build #RD-182.4231.496, built on September 13, 2018
Licensed to Kiloo ApS / Svend Hansen
You have a perpetual fallback license for this version
Subscription is active until November 24, 2019
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
-------------------------

[SeeSharpVersionTest.zip](https://github.com/JetBrains/resharper-unity/files/2671308/SeeSharpVersionTest.zip)

**Comment by van800** [comment]
This was fixed in Rider 2018.3 https://github.com/JetBrains/resharper-unity/pull/871
Please try on of the latest EAPs/Nightly builds.
If you want to continue using Rider 2018.2.3, there might be a workaround to override LangLevel via Rider settings in Unity Preferences.
![image](https://user-images.githubusercontent.com/1482681/49869498-97dcb580-fe21-11e8-8b32-d2a3a0db8868.png)
