### ISSUE TITLE
Support for USS

### ISSUE THREAD

**Issue by vertxxyz** [JetBrains/resharper-unity#957]
USS is a new UIElements stylesheet file, similar to CSS.
https://docs.unity3d.com/2018.3/Documentation/Manual/UIE-USS.html
Currently there is no highlighting or autocomplete of any kind, so I'm using Sublime Text to manage them (under CSS formatting)

I'm sure it'd be good to also support the UXML format
https://docs.unity3d.com/2018.3/Documentation/Manual/UIE-UXML.html
But I am not really intending to use it any time soon so 🤷‍♀️ 

Obviously these are new and evolving APIs, but it'd be extremely helpful for Rider to interpret a USS file as a CSS file for formatting rules if possible.

**Comment by JurjenBiewenga** [comment]
Some extra info:

UXML Schema files are available in the project folder under UIElementsSchema after you've updated the UIElements schema in Unity. You can do this by right clicking in your Unity project view and doing "Update UIElements Schema"
