### ISSUE TITLE
"Could not evaluate the value" when debugging asp.net core

### ISSUE THREAD

**Issue by carkov1990** [JetBrains/resharper-unity#969]
I updated Rider 2018.2 to 2018.3 and got next bug. 
When I debuging my application(asp.net core) I do not see values  (see screenshot below)
http://joxi.ru/MAjxPDDH4y8vYm

May be I use old configuration file from 2018.2 and that my mistake.
[log.zip](https://github.com/JetBrains/resharper-unity/files/2694722/log.zip)

**Comment by van800** [comment]
Please file an issue to https://youtrack.jetbrains.com/issues/RIDER
Here we are dealing only with Unity plugin problems.
Thank you!
