### ISSUE TITLE
No performance indicators for MonoBehaviour.SendMessage or MonoBehaviour.BroadcastMessage

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#970]
Given a class that derives from `MonoBehaviour`, there are no performance indicators for calls to `this.SendMessage` or `this.BroadcastMessage` when inside a performance critical context.

**Comment by citizenmatt** [comment]
Also `Component.SendMessage`/`Component.BroadcastMessage`

**Comment by citizenmatt** [comment]
And also `Debug.Log` and similar methods. This [forum thread](https://answers.unity.com/questions/126315/debuglog-in-build.html) is useful here (perhaps useful for a quick fix/context action to check for `Debug.isDebugBuild`?)

**Comment by krasnotsvetov** [comment]
#1000
