### ISSUE TITLE
Open File In Rider Support for Assets Targeted by ScriptedImporters

### ISSUE THREAD

**Issue by creativitRy** [JetBrains/resharper-unity#981]
https://docs.unity3d.com/Manual/ScriptedImporters.html

Although Scripted Importers are currently an experimental feature in Unity (2018.3 and below), I would love some support for them.
One of the largest limitations is that they import a file as a Unity asset. This means that when I double click on such file to open it in the Unity project browser, it would not open in Rider regardless of it being a plaintext file.

I tried putting my custom extension on Unity's Editor Settings -> C# Project Generation -> Additional extensions to include. However, Rider would not open because the scriptedimporter converted the text file into a scriptable object.

I suggest that the check whether the asset being opened is a TextAsset be removed on this line:
https://github.com/JetBrains/resharper-unity/blob/9c7528968a964b80662311d515ab055b4afa8085/unity/EditorPlugin/OnOpenAssetHandler.cs#L44
If the extension of a file is being checked anyways, wouldn't it be reasonable to assume that the user knows what they're doing?

Here is an example ScriptedImporter that converts a json file into a different format (partially from the Unity docs). Now in any project with this script active, double clicking on a json file will not open up Rider.
```c#
using UnityEngine;
using UnityEditor.Experimental.AssetImporters;
using System.IO;

[ScriptedImporter(1, "json")]
public class JsonImporter : ScriptedImporter
{
    public override void OnImportAsset(AssetImportContext ctx)
    {
        var cube = GameObject.CreatePrimitive(PrimitiveType.Cube);

        var position = JsonUtility.FromJson<Vector3>(File.ReadAllText(ctx.assetPath));
        cube.transform.position = position;

        // the json file is now a prefab
        ctx.AddObjectToAsset("main obj", cube);
        ctx.SetMainObject(cube);
    }
}
```

**Comment by van800** [comment]
What does selected.GetType().ToString() return for that json?

**Comment by creativitRy** [comment]
Upon further testing, I realized that ScriptedImporters cannot replace Unity default files. I got the following error message when I used the example importer above.
```
A scripted importer attempted to register file type '.json', which is handled by a native Unity importer. Registration rejected.
UnityEditor.Experimental.AssetImporters.ScriptedImporter:RegisterScriptedImporters()
```
When I changed the attribute to `[ScriptedImporter(1, "notjson")]`, all targeted files were imported as prefabs. `GetType().ToString()` returned the following:
```
UnityEngine.GameObject
```
