### ISSUE TITLE
Support hiding the asmdef/project name from the Unity project view, or perhaps only show if it differs from the parent folder

### ISSUE THREAD

**Issue by Tenebrous** [JetBrains/resharper-unity#982]
![image](https://user-images.githubusercontent.com/593662/50786412-6a155000-12ab-11e9-9939-92033469ecc1.png)

**Comment by citizenmatt** [comment]
#989 makes some changes here. Firstly it adds an option so you can hide all names, and secondly, it reduces the noise for the child folders of the project root.

The idea of showing the project names is to show that a folder (recursively) contains files form the named projects, to help visualise the non-intuitive overlapping nature of the Unity file structure and project layout, and also to help navigate from the root of the file structure (`Assets` or `Packages`) down to a project that might be buried several folders down, where it's not easy to find.

So in your example, the `Code` folder would still list 3 projects, but the child folders will be a lot cleaner. `Constants` would still have a name next to it, as it's the project root of `Tenebrous.DroneGame.Constants`, as defined by an `.asmdef` file. And `Addons` would have a name, too, as it looks like there's another project defined under there somewhere.

Hopefully this balances the useful information with reducing the noise.

**Comment by Tenebrous** [comment]
@citizenmatt Perfect, that solves my issue which was the excess clutter.  Thanks!
