### ISSUE TITLE
ShowButton : Method is never used

### ISSUE THREAD

**Issue by AdrienBourgois** [JetBrains/resharper-unity#986]
`void ShowButton(Rect)` is an undocumented method of `EditorWindow` that allow to add content on the top right corner of the window (to make a lock icon for exemple), but this method isn't currently recognized by the extension and marked as never used.

[Exemple of use for this method](http://www.improck.com/2014/11/editorwindow-inspector-lock-icon/)

Could it be possible to add this method to the list of Unity Messages ?

Thx in advance !

**Comment by citizenmatt** [comment]
Looks like there are a few other undocumented messages for `EditorWindow`. These are all instance methods, public or non-public, with no parameters passed and return type not used.

* [`ShowButton`](https://github.com/Unity-Technologies/UnityCsReference/blob/8977abdc2e2a797323f537a1b42d0ad50832bebe/Editor/Mono/HostView.cs#L356)
* [`ModifierKeysChanged`](https://github.com/Unity-Technologies/UnityCsReference/blob/8977abdc2e2a797323f537a1b42d0ad50832bebe/Editor/Mono/HostView.cs#L342) - [see example](http://www.improck.com/2014/11/editorwindow-modifier-keys/)
* [`OnBecameInvisible`](https://github.com/Unity-Technologies/UnityCsReference/blob/8977abdc2e2a797323f537a1b42d0ad50832bebe/Editor/Mono/HostView.cs#L337)
* [`OnBecameVisible`](https://github.com/Unity-Technologies/UnityCsReference/blob/8977abdc2e2a797323f537a1b42d0ad50832bebe/Editor/Mono/HostView.cs#L302)

The `Invoke` method used to send these messages isn't used from C#. Perhaps they're called from native?

* [`OnDidOpenScene`](https://github.com/Unity-Technologies/UnityCsReference/blob/8977abdc2e2a797323f537a1b42d0ad50832bebe/Editor/Mono/HostView.cs#L163)
* [`OnHierarchyChange`](https://github.com/Unity-Technologies/UnityCsReference/blob/8977abdc2e2a797323f537a1b42d0ad50832bebe/Editor/Mono/HostView.cs#L173)
