### ISSUE TITLE
IDE Warning for Invoking Coroutines Directly

### ISSUE THREAD

**Issue by mwegner** [JetBrains/resharper-unity#99]
A huge annoyance in Unity is the total lack of any warnings for invoking coroutines directly.  I prefix coroutines with "cr" to try to remind myself, but even still it stings me every now and then.

An example:

![screenshot 2017-01-31 15 51 37](https://cloud.githubusercontent.com/assets/271924/22488061/48d69800-e7cd-11e6-8545-1d9ab18e7c5a.png)

I have zero comprehension of how difficult it would to be implement in this plugin (I'm using Rider as my IDE), but some kind of warning in-IDE for this would be absolutely amazing...

**Comment by citizenmatt** [comment]
Nice idea! I'm not sure how to implement it though. AIUI, anything that implements `IEnumerable` can be a coroutine, so it would be very hard to accurately identify one. A method on `MonoBehaviour` that returns `IEnumerable` would be one example, but I guess so would any class that implements `IEnumerable`.

One option that might work is to try and mark any method that returns `IEnumerable` to behave as though it has the `[MustUseReturnValue]` [annotation](https://www.jetbrains.com/help/resharper/2016.3/Reference__Code_Annotation_Attributes.html#MustUseReturnValueAttribute) applied. This will give a warning that the return value is never used. If you call it directly, as in your example, this will give you a highlight. It's not foolproof - there's no real way of making you pass it to `StartCoroutine`, but it would be something.

What do you think?

**Comment by mwegner** [comment]
Sounds like a good solution! I can't think of any real reason someone would implement IEnumerable on a MonoBehavior.  Most Unity developers stray away from inheritance or interfaces with MonoBehaviors and go the composition route instead, since serialization and the editor/inspector don't play all that well with more complex setups.

So I think this would work well:

_Any function in a MonoBehavior-descended class that returns an IEnumerator gets an implicit [MustUseReturnValue] annotation applied._

P.S.  I wasn't able to test the behavior of that annotation in Rider 163.12057 with the Unity 1.5.0.1 plugin (unless I'm looking in the wrong place here): 
![screenshot 2017-02-01 11 54 44](https://cloud.githubusercontent.com/assets/271924/22521509/71fd89fc-e875-11e6-851b-b1ea17dd17f7.png)

**Comment by citizenmatt** [comment]
Hmm. Looks like ReSharper already has a warning here if the method is an iterator - that is if the method returns `IEnumerator` and includes a `yield` statement. If you don't do anything with the returned enumerator, ReSharper (and Rider) will mark it with a warning and the message "Return value of iterator is not used".

Since you don't have the warning, what's the body of your `crTryChangeResolution` like

**Comment by citizenmatt** [comment]
However, how's this?

<img width="626" alt="screen shot 2017-02-02 at 12 05 38 am" src="https://cloud.githubusercontent.com/assets/222659/22531822/62c725ae-e8db-11e6-9eb4-e9e9f40c268e.png">

**Comment by mwegner** [comment]
Oh interesting, it looks like Rider is aware of the problem, just not underlining or showing the warning anywhere.  If I mouse hover the function call I do see:

![screenshot 2017-02-01 17 25 00](https://cloud.githubusercontent.com/assets/271924/22532287/925c377e-e8a3-11e6-8786-4c135ea3d54b.png)

For reference, that particular function was doing:

![screenshot 2017-02-01 17 26 53](https://cloud.githubusercontent.com/assets/271924/22532305/a37bdb86-e8a3-11e6-9239-9a2d5bf8c79a.png)

So maybe just a question of Rider's general inspections/warnings not being full plugged in yet.  This seems to be the case with even the latest Rider EAP build (I can't find where a lot of warnings/inspections live in the preferences)...

**Comment by citizenmatt** [comment]
Ah, this is to do with the theme you're using. Darcula will show warnings and errors differently to how ReSharper does. Errors, suggestions and hints gets the usual squiggly underline, but Warnings usually get a green background, no underline.

But you're not seeing a dark background - are you using a custom theme?

**Comment by citizenmatt** [comment]
Also, you're not seeing the `MustUseReturnValue` annotation because those attributes are coming from UnityEngine.dll, and they must be using an older set of annotations.

(Ideally, they should have those attributes set to `internal`. ReSharper/Rider would still see them applied to types and members in UnityEngine.dll, but you wouldn't be able to use them in your own code)

**Comment by mwegner** [comment]
Well now I just feel sheepish!  Turns out I did indeed disable the warnings display in my style and it was there all along.

(After turning it back on, I remember why--I match the incorrect Unity naming of public fields being camelCase, and Rider still has no exposed way to configure/disable the "Inconsistent Naming" inspection.)

Thanks for chiming in!

**Comment by citizenmatt** [comment]
You should be able to use Alt+Enter on the naming inspections, expand "Inspection: Inconsistent Naming" &rarr; "Configure Inspection Severity" and set the severity to suggestion, hint, do not show, etc.

There isn't a dialog for editing naming standard yet, though.

Is this camelCase naming a standard in Unity, or just something that some people do? I might be able to override the default for Unity projects if it would benefit everyone.

**Comment by CapnRat** [comment]
camelCase is standard for all properties in Unity. Don't ask me why.

**Comment by citizenmatt** [comment]
😄 Is this carried over into user code?

**Comment by cmcpasserby** [comment]
it really depends, at my work we do it all using the same style guide as microsoft and how resharper already works.

Also there are many reasons to use IEnumerator aside from Coroutines, and there is already a inspection for when you call a function that returns IEnumerator and not use the return of it. So no need to adding a warning for it.

**Comment by nkAlex** [comment]
I think Unity was initially UnityScript-oriented and was trying to use Java's naming convention (probably wrong), so they left that camelCase for "historical compability" or something when they moved towards C# later. So usually it's a naming mess when you import various 3rd party packages into your code.
